table 'encounters'
    lineageTag: f4243bb9-fdd2-4cb2-8f80-05897cca7549

    column 'Id'
        dataType: string
        lineageTag: 4ee203e9-c8cf-4ab2-bdd5-f30af1e53ed2
        summarizeBy: none
        sourceColumn: Id

    column 'Start'
        dataType: string
        lineageTag: eeb3d3bb-0be2-4f0c-b58f-7e4355398da9
        summarizeBy: none
        sourceColumn: Start

    column 'Stop'
        dataType: string
        lineageTag: a25da1e5-36cb-4efa-9fd9-18adc28f260c
        summarizeBy: none
        sourceColumn: Stop

    column 'Patient'
        dataType: string
        lineageTag: cbb9821c-3c35-4c38-b70c-7617ba9f8b2d
        summarizeBy: none
        sourceColumn: Patient

    column 'Organization'
        dataType: string
        lineageTag: eaf02704-d260-47b1-b3b0-f8d18b20aadf
        summarizeBy: none
        sourceColumn: Organization

    column 'Payer'
        dataType: string
        lineageTag: 2eade98a-3b11-4915-8f2a-03265b63e2d2
        summarizeBy: none
        sourceColumn: Payer

    column 'Encounterclass'
        dataType: string
        lineageTag: b87c28eb-c369-430e-8d0b-7aa37542ac83
        summarizeBy: none
        sourceColumn: Encounterclass

    column 'Code'
        dataType: double
        lineageTag: 8673cb08-6b20-493a-bff7-e25c3fb7e58f
        summarizeBy: none
        sourceColumn: Code

    column 'Description'
        dataType: string
        lineageTag: 6daf2bb5-372d-4db1-80dd-409f659a0910
        summarizeBy: none
        sourceColumn: Description

    column 'Base Encounter Cost'
        dataType: double
        lineageTag: 18beef5d-e182-4f72-be42-12f303d59883
        summarizeBy: none
        sourceColumn: Base Encounter Cost

    column 'Total Claim Cost'
        dataType: double
        lineageTag: 44fc1eaa-4d33-4435-b0f2-e73fe3e0bcb9
        summarizeBy: none
        sourceColumn: Total Claim Cost

    column 'Payer Coverage'
        dataType: double
        lineageTag: 9849b2b9-f281-456f-aa04-0522581f6950
        summarizeBy: none
        sourceColumn: Payer Coverage

    column 'Reasoncode'
        dataType: double
        lineageTag: 245d000b-a2f2-4bf3-9228-eaa37c79acd6
        summarizeBy: none
        sourceColumn: Reasoncode

    column 'Reasondescription'
        dataType: string
        lineageTag: 883df01b-5eda-4ce4-b5a3-b5eac7519636
        summarizeBy: none
        sourceColumn: Reasondescription

    column 'Encounter Start Date' = DATEVALUE(LEFT('encounters'[Start], 10))
        dataType: dateTime
        formatString: Long Date
        lineageTag: 042d5143-0f0b-45b2-a844-1c5d8732e15c
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 627dba26-fc84-4275-ac54-9d7fe584c695
            defaultHierarchy: LocalDateTable_701b193c-b648-4688-9cfe-9875a9c9fe8f.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    measure 'Visits % Contribution (LOD)' =
        DIVIDE(COUNT('encounters'[Id]), CALCULATE([Total Visits (LOD)], ALLSELECTED()), 0)


    measure 'CNT of Id' =
        COUNT('encounters'[Id])


    measure 'Total Visits' =
        COUNT('encounters'[Id])


    measure 'SUM of Visits per Patient' =
        SUM('encounters'[Visits per Patient])


    measure 'SUM of Base Encounter Cost' =
        SUM('encounters'[Base Encounter Cost])


    measure 'Total Procedures (LOD)' =
        CALCULATE(COUNT('encounters'[Code]), REMOVEFILTERS('encounters'))


    measure 'Total Visits (LOD)' =
        CALCULATE(COUNT('encounters'[Id]), REMOVEFILTERS('encounters'))


    measure 'Visits per Patient' =
        CALCULATE(COUNT('encounters'[Id]), REMOVEFILTERS('encounters'), ALLEXCEPT('patients', 'patients'[Id (patients)1]))


    partition 'encounters' = m
        mode: import
        source =
            let
                Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1UFffx5ngb7j1Y2kqRzPCPVA0uvA88GLaftek_fwOjKY/edit"),
                #"Navigation 1" = Source{[name = "encounters", ItemKind = "Table"]}[Data],
                #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
                #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Id", type text}, {"START", type text}, {"STOP", type text}, {"PATIENT", type text}, {"ORGANIZATION", type text}, {"PAYER", type text}, {"ENCOUNTERCLASS", type text}, {"CODE", type number}, {"DESCRIPTION", type text}, {"BASE_ENCOUNTER_COST", type number}, {"TOTAL_CLAIM_COST", type number}, {"PAYER_COVERAGE", type number}, {"REASONCODE", type number}, {"REASONDESCRIPTION", type text}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"START", "Start"}, {"STOP", "Stop"}, {"PATIENT", "Patient"}, {"ORGANIZATION", "Organization"}, {"PAYER", "Payer"}, {"ENCOUNTERCLASS", "Encounterclass"}, {"CODE", "Code"}, {"DESCRIPTION", "Description"}, {"BASE_ENCOUNTER_COST", "Base Encounter Cost"}, {"TOTAL_CLAIM_COST", "Total Claim Cost"}, {"PAYER_COVERAGE", "Payer Coverage"}, {"REASONCODE", "Reasoncode"}, {"REASONDESCRIPTION", "Reasondescription"}})
            in
                #"Renamed Columns"
