table 'patients'
    lineageTag: 9cdfa48c-0019-490b-99bc-2f6e1ecc76b9

    column 'Id (patients)'
        dataType: string
        lineageTag: 3aacefd9-166d-48f2-8c95-f690d2f1498e
        summarizeBy: none
        sourceColumn: Id (patients)

    column 'Birthdate'
        sourceColumn: Birthdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: c092053d-5e6a-45e7-ab87-579ce2c01b63
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 888c8636-fd68-470f-b50f-58990a81d51a
            defaultHierarchy: LocalDateTable_c28519b7-e908-4543-a5f3-7de6d3fcc124.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Deathdate'
        sourceColumn: Deathdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: b642e60c-dc6e-4407-8456-e131a6e62fe0
        summarizeBy: none

        variation Variation
            isDefault
            relationship: e13bf0c3-765a-4084-87fa-a1b99f099e11
            defaultHierarchy: LocalDateTable_7acb4be6-1997-44c2-9478-95e38cc0cf8c.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Prefix'
        dataType: string
        lineageTag: 1b443630-3f05-4843-92eb-f91fe9697af7
        summarizeBy: none
        sourceColumn: Prefix

    column 'First'
        dataType: string
        lineageTag: 113dc245-68a7-4585-b105-cf7ef73d9bf5
        summarizeBy: none
        sourceColumn: First

    column 'Last'
        dataType: string
        lineageTag: 04833f47-c2ae-4701-9c21-0c1f06fd7b5f
        summarizeBy: none
        sourceColumn: Last

    column 'Suffix'
        dataType: string
        lineageTag: 887fc00a-1817-417a-8306-3ab991304688
        summarizeBy: none
        sourceColumn: Suffix

    column 'Maiden'
        dataType: string
        lineageTag: efb57ba5-6229-41c1-b724-ff9294e4742a
        summarizeBy: none
        sourceColumn: Maiden

    column 'Marital'
        dataType: string
        lineageTag: 45f3e760-a935-4c1d-bf0c-65d6a8ba2c91
        summarizeBy: none
        sourceColumn: Marital

    column 'Race'
        dataType: string
        lineageTag: 8cdf3622-c5ed-4c8a-982d-7e1058c9ae7e
        summarizeBy: none
        sourceColumn: Race

    column 'Ethnicity'
        dataType: string
        lineageTag: 2822aaa5-60aa-47e7-8b42-9a4e1cca5a92
        summarizeBy: none
        sourceColumn: Ethnicity

    column 'Gender'
        dataType: string
        lineageTag: 1d27ca0b-4a1a-46c1-8d14-d7c9c4505fde
        summarizeBy: none
        sourceColumn: Gender

    column 'Birthplace'
        dataType: string
        lineageTag: 9f886811-7a3b-4078-ad59-7960d61ab181
        summarizeBy: none
        sourceColumn: Birthplace

    column 'Address'
        dataType: string
        lineageTag: 1a3be04a-3267-4ae4-a355-25438feaeffe
        summarizeBy: none
        sourceColumn: Address

    column 'City'
        dataType: string
        lineageTag: 43907503-5d88-4400-bb1e-7e940fa8b219
        summarizeBy: none
        sourceColumn: City

    column 'State'
        dataType: string
        lineageTag: 6a69a7c2-42e4-45c7-81dd-ff4469cc0b76
        summarizeBy: none
        sourceColumn: State

    column 'County'
        dataType: string
        lineageTag: e7c2f788-3ee3-4b0f-85b5-702ac1c56984
        summarizeBy: none
        sourceColumn: County

    column 'ZIP (organizations)'
        dataType: double
        lineageTag: 8107482d-40d7-427e-b116-50cf9a4cd821
        summarizeBy: none
        sourceColumn: ZIP (organizations)

    column 'LAT (organizations)'
        dataType: double
        lineageTag: a5a6c735-e55c-47f6-a68c-6f8df983fd56
        summarizeBy: none
        sourceColumn: LAT (organizations)

    column 'LON (organizations)'
        dataType: double
        lineageTag: 8010fc86-4cf4-4169-af37-7513656f0645
        summarizeBy: none
        sourceColumn: LON (organizations)

    measure 'Patient Visits Rank (Top N Patients)' =
        RANKX(ALLSELECTED('patients'[Id (patients)1]), SUMX(VALUES('patients'[Id (patients)1]), [Visits per Patient]), , DESC, DENSE)


    measure 'SUM of Avg Visits per Patient (patients)' =
        SUM('patients'[Avg Visits per Patient])


    measure 'Total Patients (LOD)' =
        CALCULATE(DISTINCTCOUNT('patients'[Id (patients)1]), REMOVEFILTERS('patients'))


    measure 'Avg Visits per Patient' =
        CALCULATE(AVERAGEX(VALUES('patients'[Id (patients)1]), [Visits per Patient]), ALLEXCEPT('patients', 'patients'[Gender]))


    partition 'patients' = m
        mode: import
        source =
            let
                Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1Sd4bEK0Fm9q7yTVOwI4GdtixeeY8hPkKqpvnI4WdixA/edit"),
                #"Navigation 1" = Source{[name = "patients", ItemKind = "Table"]}[Data],
                #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
                #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Id", type text}, {"BIRTHDATE", type date}, {"DEATHDATE", type date}, {"PREFIX", type text}, {"FIRST", type text}, {"LAST", type text}, {"SUFFIX", type text}, {"MAIDEN", type text}, {"MARITAL", type text}, {"RACE", type text}, {"ETHNICITY", type text}, {"GENDER", type text}, {"BIRTHPLACE", type text}, {"ADDRESS", type text}, {"CITY", type text}, {"STATE", type text}, {"COUNTY", type text}, {"ZIP", type number}, {"LAT", type number}, {"LON", type number}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"Id", "Id (patients)"}, {"BIRTHDATE", "Birthdate"}, {"DEATHDATE", "Deathdate"}, {"PREFIX", "Prefix"}, {"FIRST", "First"}, {"LAST", "Last"}, {"SUFFIX", "Suffix"}, {"MAIDEN", "Maiden"}, {"MARITAL", "Marital"}, {"RACE", "Race"}, {"ETHNICITY", "Ethnicity"}, {"GENDER", "Gender"}, {"BIRTHPLACE", "Birthplace"}, {"ADDRESS", "Address"}, {"CITY", "City"}, {"STATE", "State"}, {"COUNTY", "County"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}})
            in
                #"Renamed Columns"
