table 'APPOINTMENTS_VISIT_STATUS_FACT'
    lineageTag: e8a55a30-18ff-4657-8449-04510643deb5

    column 'APPOINTMENT_ID (Custom SQL Query1)'
        dataType: string
        lineageTag: 146b25d5-ab4d-4a74-b58b-34c3c3878a51
        summarizeBy: none
        sourceColumn: APPOINTMENT_ID (Custom SQL Query1)

    column 'DEPARTMENT (Custom SQL Query1)'
        dataType: string
        lineageTag: fa35bba7-244c-4217-8ae1-54c105256e3b
        summarizeBy: none
        sourceColumn: DEPARTMENT (Custom SQL Query1)

    column 'VISIT_STATUS (Custom SQL Query1)'
        dataType: string
        lineageTag: 203a046d-80a1-4c47-91f9-5e37d0e7d3da
        summarizeBy: none
        sourceColumn: VISIT_STATUS (Custom SQL Query1)

    column 'VISIT_FLAG'
        dataType: string
        lineageTag: 39521c6f-daaf-46ca-8d3e-2bdb88141253
        summarizeBy: none
        sourceColumn: VISIT_FLAG

    partition 'APPOINTMENTS_VISIT_STATUS_FACT' = m
        mode: import
        source =
            let Source = Snowflake.Databases("mmcuiwz-kl31490.snowflakecomputing.com", "COMPUTE_WH"),
            DB = Source{[Name="CITY_HOSPITAL"]}[Data],
            APPOINTMENTS_VISIT_STATUS_FACT = Value.NativeQuery(DB, "SELECT APPOINTMENT_ID, DEPARTMENT, VISIT_STATUS, CASE WHEN VISIT_STATUS = 'Completed' THEN 'Completed Visit' ELSE 'Not Completed' END AS visit_flag FROM SNOWFLAKE_LEARNING_DB.RAJANMORYA_LOAD_SAMPLE_DATA_FROM_S3.APPOINTMENTS"),
                            #"Renamed Columns" = Table.RenameColumns(APPOINTMENTS_VISIT_STATUS_FACT, {{"APPOINTMENT_ID", "APPOINTMENT_ID (Custom SQL Query1)"}, {"DEPARTMENT", "DEPARTMENT (Custom SQL Query1)"}, {"VISIT_STATUS", "VISIT_STATUS (Custom SQL Query1)"}})
                        in
                            #"Renamed Columns"
