table 'PATIENTS'
    lineageTag: bc21bb3f-ad93-4a82-8b91-14539ff5aa41

    column 'Patient Id (Patients)'
        dataType: string
        lineageTag: 7a11f0f2-7952-42f6-a49a-f44cad85bd5b
        summarizeBy: none
        sourceColumn: Patient Id (Patients)

    column 'First Name'
        dataType: string
        lineageTag: 2823be66-3f48-481d-8d43-dbee2c3fdaae
        summarizeBy: none
        sourceColumn: First Name

    column 'Last Name'
        dataType: string
        lineageTag: 713cf648-c6ed-4ddc-9ab1-6f74b7537e1b
        summarizeBy: none
        sourceColumn: Last Name

    column 'Date Of Birth'
        dataType: string
        lineageTag: 3e065d82-40a3-426d-b817-efca7a73f6fc
        summarizeBy: none
        sourceColumn: Date Of Birth

    column 'Gender'
        dataType: string
        lineageTag: c24cec78-0e25-418a-86d6-345c6242f749
        summarizeBy: none
        sourceColumn: Gender

    column 'Contact Number (Patients)'
        dataType: string
        lineageTag: de086b47-3b87-4a3c-b952-66f3224f7571
        summarizeBy: none
        sourceColumn: Contact Number (Patients)

    column 'Email Address (Patients)'
        dataType: string
        lineageTag: b5211eba-8073-4999-ac85-9e2867500e62
        summarizeBy: none
        sourceColumn: Email Address (Patients)

    column 'Address'
        dataType: string
        lineageTag: 51fdf3e6-d0c9-4549-8efe-3c2b3b9c3c09
        summarizeBy: none
        sourceColumn: Address

    column 'Insurance Provider'
        dataType: string
        lineageTag: 707fcbb2-1873-44b2-ab3f-e69607b96865
        summarizeBy: none
        sourceColumn: Insurance Provider

    column 'Insurance Policy No'
        dataType: string
        lineageTag: f4365ef1-0f9c-47de-b77e-cf0cdf1f5f34
        summarizeBy: none
        sourceColumn: Insurance Policy No

    partition 'PATIENTS' = m
        mode: import
        source =
            let
                Source = Snowflake.Databases("mmcuiwz-kl31490.snowflakecomputing.com", "COMPUTE_WH"),
                DB = Source{[Name="CITY_HOSPITAL"]}[Data],
                Schema = DB{[Name="PUBLIC"]}[Data],
                Table = Schema{[Name="PATIENTS"]}[Data],
                #"Changed Type" = Table.TransformColumnTypes(Table, {{"PATIENT_ID", type text}, {"FIRST_NAME", type text}, {"LAST_NAME", type text}, {"DATE_OF_BIRTH", type text}, {"GENDER", type text}, {"CONTACT_NUMBER", type text}, {"EMAIL_ADDRESS", type text}, {"ADDRESS", type text}, {"INSURANCE_PROVIDER", type text}, {"INSURANCE_POLICY_NO", type text}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"PATIENT_ID", "Patient Id (Patients)"}, {"FIRST_NAME", "First Name"}, {"LAST_NAME", "Last Name"}, {"DATE_OF_BIRTH", "Date Of Birth"}, {"GENDER", "Gender"}, {"CONTACT_NUMBER", "Contact Number (Patients)"}, {"EMAIL_ADDRESS", "Email Address (Patients)"}, {"ADDRESS", "Address"}, {"INSURANCE_PROVIDER", "Insurance Provider"}, {"INSURANCE_POLICY_NO", "Insurance Policy No"}})
            in
                #"Renamed Columns"
