table 'TREATMENTS'
    lineageTag: 6d45131e-4cd5-4379-b67e-2f6658a3e7d0

    column 'Treatment Id (Treatments)'
        dataType: string
        lineageTag: 2aabb3f5-faec-47f3-8fd5-7ef2c2f090d0
        summarizeBy: none
        sourceColumn: Treatment Id (Treatments)

    column 'Appointment Id (Treatments)'
        dataType: string
        lineageTag: 812e9eb9-62f1-4979-bfe6-61795747bb94
        summarizeBy: none
        sourceColumn: Appointment Id (Treatments)

    column 'Treatment Type'
        dataType: string
        lineageTag: 4048f06a-d912-4367-a434-78433c095201
        summarizeBy: none
        sourceColumn: Treatment Type

    column 'Treatment Description'
        dataType: string
        lineageTag: 4b6d5530-4c5c-42d9-97e9-7f3f750eb287
        summarizeBy: none
        sourceColumn: Treatment Description

    column 'Prescribed Medication'
        dataType: string
        lineageTag: 5798a4cc-2508-477a-b70d-533349d2bf1d
        summarizeBy: none
        sourceColumn: Prescribed Medication

    column 'Start Date'
        sourceColumn: Start Date
        dataType: dateTime
        formatString: Long Date
        lineageTag: 02cf0189-89ac-497e-982c-617c00a58230
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 3e4c2bdd-70f0-42e3-99e7-09d4164286a3
            defaultHierarchy: LocalDateTable_2712071b-90d2-4f0d-b3ab-f741d6cd971c.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'End Date'
        sourceColumn: End Date
        dataType: dateTime
        formatString: Long Date
        lineageTag: ddea0349-1055-4020-a2a2-449f7cfb6e27
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 926e4d15-10db-4760-acff-00c64e32650b
            defaultHierarchy: LocalDateTable_a43c4f52-09db-4245-b4c4-a39c2a35b70d.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Outcome Status'
        dataType: string
        lineageTag: d204ab9f-6693-4248-aa48-8079240fdd1b
        summarizeBy: none
        sourceColumn: Outcome Status

    column 'Follow Up Date'
        sourceColumn: Follow Up Date
        dataType: dateTime
        formatString: Long Date
        lineageTag: 36455e1d-2af8-4da5-b9a8-e15fe9e7f4b5
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 27b5541d-23fa-463d-9b0c-460ab34c14f9
            defaultHierarchy: LocalDateTable_70d5ac02-da48-4f74-9645-75b4ba71a06e.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Treatment Cost'
        dataType: double
        lineageTag: 962a3b4a-b985-445a-b650-e33c99cf05e5
        summarizeBy: none
        sourceColumn: Treatment Cost

    measure 'Appointment to Treatment Ratio' =
        DIVIDE(COUNT('TREATMENTS'[Treatment Id (Treatments)]), COUNT('APPOINTMENTS'[Appointment Id]), 0)


    measure 'Avg. Treatment Cost' =
        AVERAGE('TREATMENTS'[Treatment Cost])


    partition 'TREATMENTS' = m
        mode: import
        source =
            let
                Source = Snowflake.Databases("mmcuiwz-kl31490.snowflakecomputing.com", "COMPUTE_WH"),
                DB = Source{[Name="CITY_HOSPITAL"]}[Data],
                Schema = DB{[Name="PUBLIC"]}[Data],
                Table = Schema{[Name="TREATMENTS"]}[Data],
                #"Changed Type" = Table.TransformColumnTypes(Table, {{"TREATMENT_ID", type text}, {"APPOINTMENT_ID", type text}, {"TREATMENT_TYPE", type text}, {"TREATMENT_DESCRIPTION", type text}, {"PRESCRIBED_MEDICATION", type text}, {"START_DATE", type date}, {"END_DATE", type date}, {"OUTCOME_STATUS", type text}, {"FOLLOW_UP_DATE", type date}, {"TREATMENT_COST", type number}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"TREATMENT_ID", "Treatment Id (Treatments)"}, {"APPOINTMENT_ID", "Appointment Id (Treatments)"}, {"TREATMENT_TYPE", "Treatment Type"}, {"TREATMENT_DESCRIPTION", "Treatment Description"}, {"PRESCRIBED_MEDICATION", "Prescribed Medication"}, {"START_DATE", "Start Date"}, {"END_DATE", "End Date"}, {"OUTCOME_STATUS", "Outcome Status"}, {"FOLLOW_UP_DATE", "Follow Up Date"}, {"TREATMENT_COST", "Treatment Cost"}})
            in
                #"Renamed Columns"
