table 'APPOINTMENTS'
    lineageTag: 6fc4a3cf-a1b8-4778-831b-a84db57d3aba

    column 'Appointment Id'
        dataType: string
        lineageTag: dd814ef3-8a72-4afb-843f-3feb77d77027
        summarizeBy: none
        sourceColumn: Appointment Id

    column 'Patient Id'
        dataType: string
        lineageTag: 56864038-d912-49c1-bb60-1dfd9bd98715
        summarizeBy: none
        sourceColumn: Patient Id

    column 'Doctor Id'
        dataType: string
        lineageTag: bdc420a0-646c-478f-80a2-7bdf56f7f3ee
        summarizeBy: none
        sourceColumn: Doctor Id

    column 'Department'
        dataType: string
        lineageTag: 96f5e6f0-a95c-43c9-88e5-cf319cb5d5ab
        summarizeBy: none
        sourceColumn: Department

    column 'Appointment Date'
        sourceColumn: Appointment Date
        dataType: dateTime
        formatString: Long Date
        lineageTag: f3fb2182-bd4f-4175-ac0d-58b33587b1c7
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 4f933dee-27dc-4e06-a194-1081b891e47e
            defaultHierarchy: LocalDateTable_6c24f592-7897-41f2-a7f6-c0128561790d.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Appointment Time'
        sourceColumn: Appointment Time
        dataType: dateTime
        formatString: General Date
        lineageTag: 26883363-b03f-460e-8581-e2c89588d5a6
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 16b2bcc5-fe90-4a9c-841c-535fbe1a5d18
            defaultHierarchy: LocalDateTable_6c291812-0955-458f-a79d-58f59f25b284.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Visit Status'
        dataType: string
        lineageTag: 9dbd1111-dd78-4dbe-846b-b5d5a8781540
        summarizeBy: none
        sourceColumn: Visit Status

    column 'Reason For Visit'
        dataType: string
        lineageTag: 38639491-3640-4cc0-8250-4ddf1486abbd
        summarizeBy: none
        sourceColumn: Reason For Visit

    column 'Diagnosis Code'
        dataType: string
        lineageTag: 531b7e77-be0c-4cac-aad3-ffda1c9da636
        summarizeBy: none
        sourceColumn: Diagnosis Code

    column 'Follow Up Required'
        dataType: boolean
        lineageTag: 0226f33a-1f0e-482b-81e9-dc27d78cd26b
        summarizeBy: none
        sourceColumn: Follow Up Required

    column 'DEPARTMENT__Custom_SQL_Query__Set_Category' = IF('APPOINTMENTS'[Department] IN { }, "In", "Out")
        dataType: string

        summarizeBy: none

    column 'Doctor_Id_Set_Category' = IF('APPOINTMENTS'[Doctor Id] IN { }, "In", "Out")
        dataType: string

        summarizeBy: none

    measure 'Before Migration Count' =
        COUNT('APPOINTMENTS'[Doctor Id])


    measure 'Patients' =
        DISTINCTCOUNT('APPOINTMENTS'[Patient Id])


    measure 'Total Appointments' =
        COUNT('APPOINTMENTS'[Appointment Id])


    measure 'Doctor Contribution %' =
        DIVIDE([Doctor Revenue (LOD)], [Department Revenue (LOD)], 0)


    measure 'SUM of Doctor Contribution %' =
        SUM('APPOINTMENTS'[Doctor Contribution %])


    measure 'CNT of Appointment Id' =
        COUNT('APPOINTMENTS'[Appointment Id])


    measure 'SUM of Appointments per Doctor (LOD' =
        SUM('APPOINTMENTS'[Appointments per Doctor (LOD])


    measure 'Appointments per Patient (fixed)' =
        CALCULATE(COUNT('APPOINTMENTS'[Appointment Id]), ALLEXCEPT('APPOINTMENTS', 'APPOINTMENTS'[Patient Id]))


    measure 'Avg Consultation Fee per Patient(Include)' =
        CALCULATE(AVERAGEX(VALUES('APPOINTMENTS'[Patient Id]), CALCULATE(AVERAGE('DOCTORS'[Consultation Fee]))))


    measure 'Appointments per Doctor (LOD' =
        CALCULATE(COUNTX(VALUES('APPOINTMENTS'[Doctor Id]), CALCULATE(COUNT('APPOINTMENTS'[Appointment Id]))))


    measure 'Avg Doctor Bill Count by Specialization (Nested LOD)' =
        CALCULATE(AVERAGEX(VALUES('APPOINTMENTS'[Doctor Id]), [Doctor Bill Count (LOD)]), ALLEXCEPT('DOCTORS', 'DOCTORS'[Specialization]))


    measure 'Doctor Revenue (LOD)' =
        CALCULATE(SUM([COLLECTED_REVENUE]), ALLEXCEPT('APPOINTMENTS', 'APPOINTMENTS'[Department], 'APPOINTMENTS'[Doctor Id]))


    partition 'APPOINTMENTS' = m
        mode: import
        source =
            let
                Source = Snowflake.Databases("mmcuiwz-kl31490.snowflakecomputing.com", "COMPUTE_WH"),
                DB = Source{[Name="CITY_HOSPITAL"]}[Data],
                Schema = DB{[Name="PUBLIC"]}[Data],
                Table = Schema{[Name="APPOINTMENTS"]}[Data],
                #"Changed Type" = Table.TransformColumnTypes(Table, {{"APPOINTMENT_ID", type text}, {"PATIENT_ID", type text}, {"DOCTOR_ID", type text}, {"DEPARTMENT", type text}, {"APPOINTMENT_DATE", type date}, {"APPOINTMENT_TIME", type datetime}, {"VISIT_STATUS", type text}, {"REASON_FOR_VISIT", type text}, {"DIAGNOSIS_CODE", type text}, {"FOLLOW_UP_REQUIRED", type logical}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"APPOINTMENT_ID", "Appointment Id"}, {"PATIENT_ID", "Patient Id"}, {"DOCTOR_ID", "Doctor Id"}, {"DEPARTMENT", "Department"}, {"APPOINTMENT_DATE", "Appointment Date"}, {"APPOINTMENT_TIME", "Appointment Time"}, {"VISIT_STATUS", "Visit Status"}, {"REASON_FOR_VISIT", "Reason For Visit"}, {"DIAGNOSIS_CODE", "Diagnosis Code"}, {"FOLLOW_UP_REQUIRED", "Follow Up Required"}})
            in
                #"Renamed Columns"
