table 'BILLS'
    lineageTag: 833ba661-18e6-4f0b-8bd5-170dc9e354b2

    column 'Bill Id'
        dataType: string
        lineageTag: 8decef51-8f23-4bf6-98bf-46376bbceea4
        summarizeBy: none
        sourceColumn: Bill Id

    column 'Patient Id (Bills)'
        dataType: string
        lineageTag: bc1e0684-e37a-4d99-b299-5f4dd8c44d9d
        summarizeBy: none
        sourceColumn: Patient Id (Bills)

    column 'Appointment Id (Bills)'
        dataType: string
        lineageTag: 399e062f-8dc1-4291-a8dc-9e9822693f5c
        summarizeBy: none
        sourceColumn: Appointment Id (Bills)

    column 'Treatment Id'
        dataType: string
        lineageTag: 4990fc3c-f16e-4694-958e-71172154a5df
        summarizeBy: none
        sourceColumn: Treatment Id

    column 'Billing Date'
        sourceColumn: Billing Date
        dataType: dateTime
        formatString: Long Date
        lineageTag: 95785820-cb01-4866-9abe-57d2641669f3
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 103a317d-b92d-4f85-afe2-6b24752569d5
            defaultHierarchy: LocalDateTable_4fceb0aa-f3b4-4004-9b72-a73fd9bd8362.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Total Amount'
        dataType: double
        lineageTag: 90fed2b7-39c7-47df-9a5b-acdae38d48ba
        summarizeBy: none
        sourceColumn: Total Amount

    column 'Insurance Covered'
        dataType: double
        lineageTag: 455c9d56-12a3-4eff-9da5-4b8c30a20c1a
        summarizeBy: none
        sourceColumn: Insurance Covered

    column 'Patient Payable'
        dataType: double
        lineageTag: ed0f3468-97a9-413b-adab-d6a0335d70e6
        summarizeBy: none
        sourceColumn: Patient Payable

    column 'Payment Method'
        dataType: string
        lineageTag: 84dc8632-8a1d-45bb-9c1e-8cd55e6eb253
        summarizeBy: none
        sourceColumn: Payment Method

    column 'Payment Status'
        dataType: string
        lineageTag: f91e9efb-1575-4535-b4c6-332c53509f3d
        summarizeBy: none
        sourceColumn: Payment Status

    measure 'Insurance Coverage %' =
        DIVIDE(SUM('BILLS'[Insurance Covered]), SUM('BILLS'[Total Amount]), 0)


    measure 'Total Bill' =
        COUNT('BILLS'[Bill Id])


    measure 'Total billing Amount' =
        SUM('BILLS'[Total Amount])


    measure 'Total Revenue' =
        SUM('BILLS'[Total Amount])


    measure 'Unpaid Balance' =
        SUM('BILLS'[Total Amount]) - SUM('BILLS'[Insurance Covered])


    measure 'COLLECTED_REVENUE' =
        CALCULATE(SUM('BILLS'[Total Amount]), KEEPFILTERS('BILLS'[Payment Status] & "" = "Paid"))


    measure 'SUM of Total Amount (BILLS)' =
        SUM('BILLS'[Total Amount])


    measure 'Unpaid Balance per Specialization (Fixed)' =
        CALCULATE(SUM('BILLS'[Total Amount]) - SUM('BILLS'[Insurance Covered]), ALLEXCEPT('DOCTORS', 'DOCTORS'[Specialization]))


    measure 'Doctor Bill Count (LOD)' =
        CALCULATE(COUNT('BILLS'[Bill Id]), REMOVEFILTERS('BILLS'), ALLEXCEPT('DOCTORS', 'DOCTORS'[Doctor Id (Doctors)]))


    partition 'BILLS' = m
        mode: import
        source =
            let
                Source = Snowflake.Databases("mmcuiwz-kl31490.snowflakecomputing.com", "COMPUTE_WH"),
                DB = Source{[Name="CITY_HOSPITAL"]}[Data],
                Schema = DB{[Name="PUBLIC"]}[Data],
                Table = Schema{[Name="BILLS"]}[Data],
                #"Changed Type" = Table.TransformColumnTypes(Table, {{"BILL_ID", type text}, {"PATIENT_ID", type text}, {"APPOINTMENT_ID", type text}, {"TREATMENT_ID", type text}, {"BILLING_DATE", type date}, {"TOTAL_AMOUNT", type number}, {"INSURANCE_COVERED", type number}, {"PATIENT_PAYABLE", type number}, {"PAYMENT_METHOD", type text}, {"PAYMENT_STATUS", type text}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"BILL_ID", "Bill Id"}, {"PATIENT_ID", "Patient Id (Bills)"}, {"APPOINTMENT_ID", "Appointment Id (Bills)"}, {"TREATMENT_ID", "Treatment Id"}, {"BILLING_DATE", "Billing Date"}, {"TOTAL_AMOUNT", "Total Amount"}, {"INSURANCE_COVERED", "Insurance Covered"}, {"PATIENT_PAYABLE", "Patient Payable"}, {"PAYMENT_METHOD", "Payment Method"}, {"PAYMENT_STATUS", "Payment Status"}})
            in
                #"Renamed Columns"
