table 'DOCTORS'
    lineageTag: 524124dc-b4cb-4540-a12f-206fac2eafef

    column 'Doctor Id (Doctors)'
        dataType: string
        lineageTag: 11709dc9-4129-45c9-801e-d34453ac8512
        summarizeBy: none
        sourceColumn: Doctor Id (Doctors)

    column 'Full Name'
        dataType: string
        lineageTag: e9ac3be0-89fa-4f1a-bc03-e26100fa55e0
        summarizeBy: none
        sourceColumn: Full Name

    column 'Specialization'
        dataType: string
        lineageTag: fa327dee-8e23-4dc3-b0e3-c2ba601eea8a
        summarizeBy: none
        sourceColumn: Specialization

    column 'Department (Doctors)'
        dataType: string
        lineageTag: 6990bc07-a2d1-4a37-858b-c6e7309dd810
        summarizeBy: none
        sourceColumn: Department (Doctors)

    column 'Contact Number'
        dataType: string
        lineageTag: 57ada83a-fb23-4b00-87e9-e83ed77b088a
        summarizeBy: none
        sourceColumn: Contact Number

    column 'Email Address'
        dataType: string
        lineageTag: a207e5da-8407-46d6-8eba-a2e0ab1801b4
        summarizeBy: none
        sourceColumn: Email Address

    column 'Availability Days'
        dataType: string
        lineageTag: 7bdfb7fa-4b49-4ffc-997d-7d60191e4de6
        summarizeBy: none
        sourceColumn: Availability Days

    column 'Consultation Fee'
        dataType: double
        lineageTag: c061ffc4-f65a-4bce-9ce6-35dd5d1ab172
        summarizeBy: none
        sourceColumn: Consultation Fee

    column 'Experience Years'
        dataType: double
        lineageTag: 9886c4ba-1e15-450b-abd2-72cff876638e
        summarizeBy: none
        sourceColumn: Experience Years

    column 'Registration Number'
        dataType: string
        lineageTag: 85900d0f-846e-4059-b41e-b06fed0e245b
        summarizeBy: none
        sourceColumn: Registration Number

    column 'Experience Level_Cal' = SWITCH( TRUE(), 'DOCTORS'[Experience Years] < 5, "Junior", 'DOCTORS'[Experience Years] <= 10, "Mid-Level", "Senior" )
        dataType: string

        summarizeBy: none

    measure 'Average Consultation Fee' =
        AVERAGE('DOCTORS'[Consultation Fee])


    measure 'Average Doctor Experience (Years)1' =
        AVERAGE('DOCTORS'[Experience Years])


    measure 'Average by Specialization (NESTED)' =
        AVERAGEX(
            VALUES('DOCTORS'[Specialization]),
            AVERAGEX(
                VALUES('BILLS'[Appointment Id (Bills)]),
                CALCULATE(
                    SUM('BILLS'[Total Amount]) - SUM('BILLS'[Insurance Covered])
                )
            )
        )


    measure 'Doctor RLS Filter' =
        SELECTEDVALUE('DOCTORS'[Email Address]) = USERNAME()


    partition 'DOCTORS' = m
        mode: import
        source =
            let
                Source = Snowflake.Databases("mmcuiwz-kl31490.snowflakecomputing.com", "COMPUTE_WH"),
                DB = Source{[Name="CITY_HOSPITAL"]}[Data],
                Schema = DB{[Name="PUBLIC"]}[Data],
                Table = Schema{[Name="DOCTORS"]}[Data],
                #"Changed Type" = Table.TransformColumnTypes(Table, {{"DOCTOR_ID", type text}, {"FULL_NAME", type text}, {"SPECIALIZATION", type text}, {"DEPARTMENT", type text}, {"CONTACT_NUMBER", type text}, {"EMAIL_ADDRESS", type text}, {"AVAILABILITY_DAYS", type text}, {"CONSULTATION_FEE", type number}, {"EXPERIENCE_YEARS", type number}, {"REGISTRATION_NUMBER", type text}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"DOCTOR_ID", "Doctor Id (Doctors)"}, {"FULL_NAME", "Full Name"}, {"SPECIALIZATION", "Specialization"}, {"DEPARTMENT", "Department (Doctors)"}, {"CONTACT_NUMBER", "Contact Number"}, {"EMAIL_ADDRESS", "Email Address"}, {"AVAILABILITY_DAYS", "Availability Days"}, {"CONSULTATION_FEE", "Consultation Fee"}, {"EXPERIENCE_YEARS", "Experience Years"}, {"REGISTRATION_NUMBER", "Registration Number"}})
            in
                #"Renamed Columns"
