table 'TREATMENTS'
    lineageTag: 3159c38e-54c6-41b6-aa0e-c21a6e5b2de6

    column 'Treatment Id (Treatments)'
        dataType: string
        lineageTag: e0c213ad-bf9f-4cf6-82ac-688af299875b
        summarizeBy: none
        sourceColumn: Treatment Id (Treatments)

    column 'Appointment Id (Treatments)'
        dataType: string
        lineageTag: 8f498c9e-ff03-46c5-96c2-1c7d43f5c1f5
        summarizeBy: none
        sourceColumn: Appointment Id (Treatments)

    column 'Treatment Type'
        dataType: string
        lineageTag: 6ccac146-22a7-434f-84dc-cf35c7e34359
        summarizeBy: none
        sourceColumn: Treatment Type

    column 'Treatment Description'
        dataType: string
        lineageTag: 324458e8-bc89-4fa2-b185-57f1dbb44243
        summarizeBy: none
        sourceColumn: Treatment Description

    column 'Prescribed Medication'
        dataType: string
        lineageTag: 54aacddd-5914-4da5-85a0-f3d075946899
        summarizeBy: none
        sourceColumn: Prescribed Medication

    column 'Start Date'
        sourceColumn: Start Date
        dataType: dateTime
        formatString: Long Date
        lineageTag: 13094cec-1a09-4dd2-b31a-13425445e51d
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 39881fbb-a5ba-4ea9-8af6-961e5455aaae
            defaultHierarchy: LocalDateTable_918d9546-498d-42e0-8a26-2fdfb7ddb966.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'End Date'
        sourceColumn: End Date
        dataType: dateTime
        formatString: Long Date
        lineageTag: 8fc70249-a8ef-4c1e-be00-b40ffac1f1a8
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 66263a33-f610-46bf-9658-3540f02bc347
            defaultHierarchy: LocalDateTable_cad9915b-df99-4595-8021-b961e9b2bd0d.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Outcome Status'
        dataType: string
        lineageTag: 9e66f1ab-cd2a-422d-9adf-c43a81bf515c
        summarizeBy: none
        sourceColumn: Outcome Status

    column 'Follow Up Date'
        sourceColumn: Follow Up Date
        dataType: dateTime
        formatString: Long Date
        lineageTag: 3029a450-439e-428d-9bd2-5e959b86d2c4
        summarizeBy: none

        variation Variation
            isDefault
            relationship: ab16793d-7652-404c-b162-8319aa6a83d1
            defaultHierarchy: LocalDateTable_5e6ab6e8-dd5f-4bf6-b4a5-178a92a0f5c7.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Treatment Cost'
        dataType: double
        lineageTag: 02c8ebd7-e498-4499-95f5-e74a0c20f8be
        summarizeBy: none
        sourceColumn: Treatment Cost

    measure 'Appointment to Treatment Ratio' =
        DIVIDE(COUNT('TREATMENTS'[Treatment Id (Treatments)]), COUNT('APPOINTMENTS'[Appointment Id]), 0)


    measure 'Avg. Treatment Cost' =
        AVERAGE('TREATMENTS'[Treatment Cost])


    partition 'TREATMENTS' = m
        mode: import
        source =
            let
                Source = Snowflake.Databases("mmcuiwz-kl31490.snowflakecomputing.com", "COMPUTE_WH"),
                DB = Source{[Name="CITY_HOSPITAL"]}[Data],
                Schema = DB{[Name="PUBLIC"]}[Data],
                Table = Schema{[Name="TREATMENTS"]}[Data],
                #"Changed Type" = Table.TransformColumnTypes(Table, {{"TREATMENT_ID", type text}, {"APPOINTMENT_ID", type text}, {"TREATMENT_TYPE", type text}, {"TREATMENT_DESCRIPTION", type text}, {"PRESCRIBED_MEDICATION", type text}, {"START_DATE", type date}, {"END_DATE", type date}, {"OUTCOME_STATUS", type text}, {"FOLLOW_UP_DATE", type date}, {"TREATMENT_COST", type number}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"TREATMENT_ID", "Treatment Id (Treatments)"}, {"APPOINTMENT_ID", "Appointment Id (Treatments)"}, {"TREATMENT_TYPE", "Treatment Type"}, {"TREATMENT_DESCRIPTION", "Treatment Description"}, {"PRESCRIBED_MEDICATION", "Prescribed Medication"}, {"START_DATE", "Start Date"}, {"END_DATE", "End Date"}, {"OUTCOME_STATUS", "Outcome Status"}, {"FOLLOW_UP_DATE", "Follow Up Date"}, {"TREATMENT_COST", "Treatment Cost"}})
            in
                #"Renamed Columns"
