table 'encounters'
    lineageTag: b3d62d53-c9b2-4ccf-b3c3-3d4bae2d8d56

    column 'Id'
        dataType: string
        lineageTag: 7e197faa-9c30-4b9f-91d7-d4475d750a8b
        summarizeBy: none
        sourceColumn: Id

    column 'Start'
        dataType: string
        lineageTag: 935c1215-021d-4ba2-a7dc-9b2152724124
        summarizeBy: none
        sourceColumn: Start

    column 'Stop'
        dataType: string
        lineageTag: 99da1aaf-1974-4f46-809d-966d29792a8b
        summarizeBy: none
        sourceColumn: Stop

    column 'Patient'
        dataType: string
        lineageTag: 16e3f5fe-5a00-4d50-804d-cdd49a372ec7
        summarizeBy: none
        sourceColumn: Patient

    column 'Organization'
        dataType: string
        lineageTag: 8efb098c-3e57-4fd6-838e-c94786420759
        summarizeBy: none
        sourceColumn: Organization

    column 'Payer'
        dataType: string
        lineageTag: ae8f80b0-7110-4c32-9df2-93bc28bf44b9
        summarizeBy: none
        sourceColumn: Payer

    column 'Encounterclass'
        dataType: string
        lineageTag: 7c20a840-b5c7-46dd-b8cb-2abf6fa016d9
        summarizeBy: none
        sourceColumn: Encounterclass

    column 'Code'
        dataType: double
        lineageTag: 2a71a45c-8455-45fc-96fa-bf2bf9ef2277
        summarizeBy: none
        sourceColumn: Code

    column 'Description'
        dataType: string
        lineageTag: 8ce1403d-4f21-4d1a-b0b1-e05be7671d80
        summarizeBy: none
        sourceColumn: Description

    column 'Base Encounter Cost'
        dataType: double
        lineageTag: 35f8dafa-849a-4c2f-92dc-aaf8c478a300
        summarizeBy: none
        sourceColumn: Base Encounter Cost

    column 'Total Claim Cost'
        dataType: double
        lineageTag: df57c411-af64-4aee-8add-2956ba47d64c
        summarizeBy: none
        sourceColumn: Total Claim Cost

    column 'Payer Coverage'
        dataType: double
        lineageTag: e4d8e9e7-da17-4b65-811d-1c0d0f9ac9d7
        summarizeBy: none
        sourceColumn: Payer Coverage

    column 'Reasoncode'
        dataType: double
        lineageTag: 496e7a2c-f31e-4bc9-83e9-b4ce81f2d4e3
        summarizeBy: none
        sourceColumn: Reasoncode

    column 'Reasondescription'
        dataType: string
        lineageTag: 35e0e5a3-e861-4417-bf5e-b60fdae13d7d
        summarizeBy: none
        sourceColumn: Reasondescription

    column 'Encounter Start Date' = DATEVALUE(LEFT('encounters'[Start], 10))
        dataType: dateTime
        formatString: Long Date
        lineageTag: 6ef80433-d192-4836-ab02-a6a67fc206b5
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 64adfdaa-b7af-49fe-b840-d48af44cb9c6
            defaultHierarchy: LocalDateTable_379b189a-23d7-436c-9b7b-e7bfa840a24f.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    measure 'Visits % Contribution (LOD)' =
        DIVIDE(COUNT('encounters'[Id]), CALCULATE([Total Visits (LOD)], ALLSELECTED()), 0)


    measure 'CNT of Id' =
        COUNT('encounters'[Id])


    measure 'Total Visits' =
        COUNT('encounters'[Id])


    measure 'SUM of Visits per Patient' =
        SUM('encounters'[Visits per Patient])


    measure 'SUM of Base Encounter Cost' =
        SUM('encounters'[Base Encounter Cost])


    measure 'Total Procedures (LOD)' =
        CALCULATE(COUNT('encounters'[Code]), REMOVEFILTERS('encounters'))


    measure 'Total Visits (LOD)' =
        CALCULATE(COUNT('encounters'[Id]), REMOVEFILTERS('encounters'))


    measure 'Visits per Patient' =
        CALCULATE(COUNT('encounters'[Id]), REMOVEFILTERS('encounters'), ALLEXCEPT('patients', 'patients'[Id (patients)1]))


    partition 'encounters' = m
        mode: import
        source =
            let
                Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1UFffx5ngb7j1Y2kqRzPCPVA0uvA88GLaftek_fwOjKY/edit"),
                #"Navigation 1" = Source{[name = "encounters", ItemKind = "Table"]}[Data],
                #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
                #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Id", type text}, {"START", type text}, {"STOP", type text}, {"PATIENT", type text}, {"ORGANIZATION", type text}, {"PAYER", type text}, {"ENCOUNTERCLASS", type text}, {"CODE", type number}, {"DESCRIPTION", type text}, {"BASE_ENCOUNTER_COST", type number}, {"TOTAL_CLAIM_COST", type number}, {"PAYER_COVERAGE", type number}, {"REASONCODE", type number}, {"REASONDESCRIPTION", type text}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"START", "Start"}, {"STOP", "Stop"}, {"PATIENT", "Patient"}, {"ORGANIZATION", "Organization"}, {"PAYER", "Payer"}, {"ENCOUNTERCLASS", "Encounterclass"}, {"CODE", "Code"}, {"DESCRIPTION", "Description"}, {"BASE_ENCOUNTER_COST", "Base Encounter Cost"}, {"TOTAL_CLAIM_COST", "Total Claim Cost"}, {"PAYER_COVERAGE", "Payer Coverage"}, {"REASONCODE", "Reasoncode"}, {"REASONDESCRIPTION", "Reasondescription"}})
            in
                #"Renamed Columns"
