table 'payers'
    lineageTag: a2b4bc04-0d17-479c-9244-e5b3bb144fed

    column 'Id (payers)'
        dataType: string
        lineageTag: 107f6216-ec26-455c-ac49-f02ee06e1c19
        summarizeBy: none
        sourceColumn: Id (payers)

    column 'NAME (payers)'
        dataType: string
        lineageTag: 64b6b48e-04de-4bfb-8045-3407d5baae3e
        summarizeBy: none
        sourceColumn: NAME (payers)

    column 'ADDRESS (payers)'
        dataType: string
        lineageTag: 55d9c95a-e735-4b7b-93d0-96ce0d5fdcff
        summarizeBy: none
        sourceColumn: ADDRESS (payers)

    column 'CITY (payers)'
        dataType: string
        lineageTag: e106ed2a-8bea-4712-8305-2a945d65c853
        summarizeBy: none
        sourceColumn: CITY (payers)

    column 'State Headquartered'
        dataType: string
        lineageTag: d05db10f-2109-40b0-81d3-968d89b24e38
        summarizeBy: none
        sourceColumn: State Headquartered

    column 'ZIP (payers)'
        dataType: double
        lineageTag: 199bbc4b-c910-47b4-819f-9727a0890eb4
        summarizeBy: none
        sourceColumn: ZIP (payers)

    column 'Phone'
        dataType: string
        lineageTag: 574670bb-5a92-475e-b69b-9e17d1968894
        summarizeBy: none
        sourceColumn: Phone

    partition 'payers' = m
        mode: import
        source =
            let
                Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1NB9uAQnBa6RYGfm5addKbcToYUZJY_5OlBkWxVZRrbU/edit"),
                #"Navigation 1" = Source{[name = "payers", ItemKind = "Table"]}[Data],
                #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
                #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Id", type text}, {"NAME", type text}, {"ADDRESS", type text}, {"CITY", type text}, {"STATE_HEADQUARTERED", type text}, {"ZIP", type number}, {"PHONE", type text}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"Id", "Id (payers)"}, {"NAME", "NAME (payers)"}, {"ADDRESS", "ADDRESS (payers)"}, {"CITY", "CITY (payers)"}, {"STATE_HEADQUARTERED", "State Headquartered"}, {"ZIP", "ZIP (payers)"}, {"PHONE", "Phone"}})
            in
                #"Renamed Columns"
