table 'APPOINTMENTS'
    lineageTag: edebe544-dab4-4413-bfcc-adfec62e6dd3

    column 'Appointment Id'
        dataType: string
        lineageTag: 2aaa417c-54b7-490f-8a1d-b0b2f2460edd
        summarizeBy: none
        sourceColumn: Appointment Id

    column 'Patient Id'
        dataType: string
        lineageTag: f71dde9b-70db-406f-90b1-b57e125a2939
        summarizeBy: none
        sourceColumn: Patient Id

    column 'Doctor Id'
        dataType: string
        lineageTag: b31f70b8-0447-41c6-acb5-6493c6deb8d1
        summarizeBy: none
        sourceColumn: Doctor Id

    column 'Department'
        dataType: string
        lineageTag: 72fe4bea-b911-4697-a886-fdb950149235
        summarizeBy: none
        sourceColumn: Department

    column 'Appointment Date'
        sourceColumn: Appointment Date
        dataType: dateTime
        formatString: Long Date
        lineageTag: 2ef2ee25-6d64-4300-bcb6-e0410052322a
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 6446d7a0-7af8-48f6-a66d-e26a06ef02d0
            defaultHierarchy: LocalDateTable_125fd822-b949-47fa-ac81-2e7c9539c5c9.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Appointment Time'
        sourceColumn: Appointment Time
        dataType: dateTime
        formatString: General Date
        lineageTag: a378da98-a876-4863-9faa-b88d615495c4
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 5f7e97fa-cf2a-4875-b779-56b0eac31f5b
            defaultHierarchy: LocalDateTable_03c23e13-069d-4512-b182-dc571e47b78e.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Visit Status'
        dataType: string
        lineageTag: 52fa75e5-7fcc-4f13-a85b-4a0c8204a652
        summarizeBy: none
        sourceColumn: Visit Status

    column 'Reason For Visit'
        dataType: string
        lineageTag: 0fdda86e-3464-4188-88ea-f530a88715ec
        summarizeBy: none
        sourceColumn: Reason For Visit

    column 'Diagnosis Code'
        dataType: string
        lineageTag: efeb5182-04d9-4bd4-b368-0008ac83fdb6
        summarizeBy: none
        sourceColumn: Diagnosis Code

    column 'Follow Up Required'
        dataType: boolean
        lineageTag: c5a5f4e1-bb65-49ee-9ef8-0eb6262c3e92
        summarizeBy: none
        sourceColumn: Follow Up Required

    column 'DEPARTMENT__Custom_SQL_Query__Set_Category' = IF('APPOINTMENTS'[Department] IN { }, "In", "Out")
        dataType: string

        summarizeBy: none

    column 'Doctor_Id_Set_Category' = IF('APPOINTMENTS'[Doctor Id] IN { }, "In", "Out")
        dataType: string

        summarizeBy: none

    measure 'Before Migration Count' =
        COUNT('APPOINTMENTS'[Doctor Id])


    measure 'Patients' =
        DISTINCTCOUNT('APPOINTMENTS'[Patient Id])


    measure 'Total Appointments' =
        COUNT('APPOINTMENTS'[Appointment Id])


    measure 'Doctor Contribution %' =
        DIVIDE([Doctor Revenue (LOD)], [Department Revenue (LOD)], 0)


    measure 'SUM of Doctor Contribution %' =
        SUM('APPOINTMENTS'[Doctor Contribution %])


    measure 'CNT of Appointment Id' =
        COUNT('APPOINTMENTS'[Appointment Id])


    measure 'SUM of Appointments per Doctor (LOD' =
        SUM('APPOINTMENTS'[Appointments per Doctor (LOD])


    measure 'Appointments per Patient (fixed)' =
        CALCULATE(COUNT('APPOINTMENTS'[Appointment Id]), ALLEXCEPT('APPOINTMENTS', 'APPOINTMENTS'[Patient Id]))


    measure 'Avg Consultation Fee per Patient(Include)' =
        CALCULATE(AVERAGEX(VALUES('APPOINTMENTS'[Patient Id]), CALCULATE(AVERAGE('DOCTORS'[Consultation Fee]))))


    measure 'Appointments per Doctor (LOD' =
        CALCULATE(COUNTX(VALUES('APPOINTMENTS'[Doctor Id]), CALCULATE(COUNT('APPOINTMENTS'[Appointment Id]))))


    measure 'Avg Doctor Bill Count by Specialization (Nested LOD)' =
        CALCULATE(AVERAGEX(VALUES('APPOINTMENTS'[Doctor Id]), [Doctor Bill Count (LOD)]), ALLEXCEPT('DOCTORS', 'DOCTORS'[Specialization]))


    measure 'Doctor Revenue (LOD)' =
        CALCULATE(SUM([COLLECTED_REVENUE]), ALLEXCEPT('APPOINTMENTS', 'APPOINTMENTS'[Department], 'APPOINTMENTS'[Doctor Id]))


    partition 'APPOINTMENTS' = m
        mode: import
        source =
            let
                Source = Snowflake.Databases("mmcuiwz-kl31490.snowflakecomputing.com", "COMPUTE_WH"),
                DB = Source{[Name="CITY_HOSPITAL"]}[Data],
                Schema = DB{[Name="PUBLIC"]}[Data],
                Table = Schema{[Name="APPOINTMENTS"]}[Data],
                #"Changed Type" = Table.TransformColumnTypes(Table, {{"APPOINTMENT_ID", type text}, {"PATIENT_ID", type text}, {"DOCTOR_ID", type text}, {"DEPARTMENT", type text}, {"APPOINTMENT_DATE", type date}, {"APPOINTMENT_TIME", type datetime}, {"VISIT_STATUS", type text}, {"REASON_FOR_VISIT", type text}, {"DIAGNOSIS_CODE", type text}, {"FOLLOW_UP_REQUIRED", type logical}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"APPOINTMENT_ID", "Appointment Id"}, {"PATIENT_ID", "Patient Id"}, {"DOCTOR_ID", "Doctor Id"}, {"DEPARTMENT", "Department"}, {"APPOINTMENT_DATE", "Appointment Date"}, {"APPOINTMENT_TIME", "Appointment Time"}, {"VISIT_STATUS", "Visit Status"}, {"REASON_FOR_VISIT", "Reason For Visit"}, {"DIAGNOSIS_CODE", "Diagnosis Code"}, {"FOLLOW_UP_REQUIRED", "Follow Up Required"}})
            in
                #"Renamed Columns"
