table 'custom table'
    lineageTag: ff72a28a-7368-4774-9c6e-9c9e96295d85

    column 'APPOINTMENT_ID (Custom SQL Query)'
        dataType: string
        lineageTag: d77bf2c7-bfb2-4661-b013-f0a4770645e5
        summarizeBy: none
        sourceColumn: APPOINTMENT_ID (Custom SQL Query)

    column 'PATIENT_ID (Custom SQL Query)'
        dataType: string
        lineageTag: 3a442fc3-d35a-4ea6-8b5a-a0c710065bf5
        summarizeBy: none
        sourceColumn: PATIENT_ID (Custom SQL Query)

    column 'DOCTOR_ID (Custom SQL Query)'
        dataType: string
        lineageTag: f3741da2-bed7-4945-b046-141b7c2f9816
        summarizeBy: none
        sourceColumn: DOCTOR_ID (Custom SQL Query)

    column 'DEPARTMENT (Custom SQL Query)'
        dataType: string
        lineageTag: cd8b4cb6-f234-461b-8d2c-51b123808b10
        summarizeBy: none
        sourceColumn: DEPARTMENT (Custom SQL Query)

    column 'APPOINTMENT_DATE (Custom SQL Query)'
        sourceColumn: APPOINTMENT_DATE (Custom SQL Query)
        dataType: dateTime
        formatString: Long Date
        lineageTag: 7628d0d6-8ee6-48b7-b588-99d3a439274b
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 7d36533d-780d-4e33-b5cd-72c216fab5cc
            defaultHierarchy: LocalDateTable_678c61d4-4e56-433b-9df4-354465412f7e.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'APPOINTMENT_TIME (Custom SQL Query)'
        sourceColumn: APPOINTMENT_TIME (Custom SQL Query)
        dataType: dateTime
        formatString: General Date
        lineageTag: c7cd78b0-5c45-4df3-a0a2-a7d09284ffea
        summarizeBy: none

        variation Variation
            isDefault
            relationship: e28bba35-542c-4b30-ab04-e67b0a559a32
            defaultHierarchy: LocalDateTable_2297df77-8020-4058-8d83-a785b5b52071.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'VISIT_STATUS_CLEAN'
        dataType: string
        lineageTag: 03a9fa3d-bea8-4245-bbbd-76eea96fca2e
        summarizeBy: none
        sourceColumn: VISIT_STATUS_CLEAN

    column 'REASON_FOR_VISIT (Custom SQL Query)'
        dataType: string
        lineageTag: 17903909-7944-4d41-abe2-4a43a7f6db7e
        summarizeBy: none
        sourceColumn: REASON_FOR_VISIT (Custom SQL Query)

    column 'DIAGNOSIS_CODE (Custom SQL Query)'
        dataType: string
        lineageTag: 59d57fb5-37f0-4900-a8b7-8af01b1edd4e
        summarizeBy: none
        sourceColumn: DIAGNOSIS_CODE (Custom SQL Query)

    column 'FOLLOW_UP_REQUIRED (Custom SQL Query)'
        dataType: boolean
        lineageTag: f4dac9c6-55b1-4f28-a3e0-7b70faf158f1
        summarizeBy: none
        sourceColumn: FOLLOW_UP_REQUIRED (Custom SQL Query)

    column 'SPECIALIZATION (Custom SQL Query)'
        dataType: string
        lineageTag: c7ec1e87-8c42-4bb6-aae8-555479cbcdd3
        summarizeBy: none
        sourceColumn: SPECIALIZATION (Custom SQL Query)

    column 'CONSULTATION_FEE (Custom SQL Query)'
        dataType: double
        lineageTag: 41451a25-fd88-499c-abca-f88673567792
        summarizeBy: none
        sourceColumn: CONSULTATION_FEE (Custom SQL Query)

    column 'TREATMENT_TYPE (Custom SQL Query)'
        dataType: string
        lineageTag: 80892aa9-b9c1-4f5f-b2e5-378dbab1f596
        summarizeBy: none
        sourceColumn: TREATMENT_TYPE (Custom SQL Query)

    column 'OUTCOME_STATUS (Custom SQL Query)'
        dataType: string
        lineageTag: 151c1bf3-ec31-4ec4-acb2-84107f854cf7
        summarizeBy: none
        sourceColumn: OUTCOME_STATUS (Custom SQL Query)

    column 'TREATMENT_COST (Custom SQL Query)'
        dataType: double
        lineageTag: 808997cb-dd94-4f53-8109-d2e50e0e8a2f
        summarizeBy: none
        sourceColumn: TREATMENT_COST (Custom SQL Query)

    column 'TOTAL_AMOUNT (Custom SQL Query)'
        dataType: double
        lineageTag: 6216831f-7a48-4101-ab38-eda4cb990deb
        summarizeBy: none
        sourceColumn: TOTAL_AMOUNT (Custom SQL Query)

    column 'PAYMENT_STATUS (Custom SQL Query)'
        dataType: string
        lineageTag: 4aa59d7d-88f1-4df9-8644-c84ef62fe41f
        summarizeBy: none
        sourceColumn: PAYMENT_STATUS (Custom SQL Query)

    column 'COLLECTED_REVENUE'
        dataType: double
        lineageTag: 0182b4a1-531c-4ec4-8ddc-d71029fc9ad9
        summarizeBy: none
        sourceColumn: COLLECTED_REVENUE

    measure 'Revenue Filter' =
        SUMX('custom table', [COLLECTED_REVENUE]) >= SELECTEDVALUE('Revenue Threshold'[Value])


    measure 'SUM of COLLECTED_REVENUE (custom table)' =
        SUM('custom table'[COLLECTED_REVENUE])


    measure 'SUM of Completed Appointments per Department (custom table)' =
        SUM('custom table'[Completed Appointments per Department])


    measure 'Department Total Revenue (LOD)' =
        CALCULATE(SUM([COLLECTED_REVENUE]), ALLEXCEPT('custom table', 'custom table'[DEPARTMENT (Custom SQL Query)]))


    measure 'Completed Appointments per Department' =
        CALCULATE(SUMX('custom table', IF('custom table'[VISIT_STATUS_CLEAN] & "" = "Completed", 1, 0)), ALLEXCEPT('custom table', 'custom table'[DEPARTMENT (Custom SQL Query)]))


    measure 'Department Revenue (LOD)' =
        CALCULATE(SUM([COLLECTED_REVENUE]), ALLEXCEPT('custom table', 'custom table'[DEPARTMENT (Custom SQL Query)]))


    partition 'custom table' = m
        mode: import
        source =
            let Source = Snowflake.Databases("mmcuiwz-kl31490.snowflakecomputing.com", "COMPUTE_WH"),
            DB = Source{[Name="CITY_HOSPITAL"]}[Data],
            custom_table = Value.NativeQuery(DB, "SELECT a.APPOINTMENT_ID, a.PATIENT_ID, a.DOCTOR_ID, a.DEPARTMENT, a.APPOINTMENT_DATE, a.APPOINTMENT_TIME, CASE WHEN a.VISIT_STATUS IN ('No-Show', 'No Show') THEN 'No Show' WHEN a.VISIT_STATUS IN ('Cancelled', 'Canceled') THEN 'Cancelled' WHEN a.VISIT_STATUS = 'Completed' THEN 'Completed' ELSE 'Other' END AS VISIT_STATUS_CLEAN, a.REASON_FOR_VISIT, a.DIAGNOSIS_CODE, a.FOLLOW_UP_REQUIRED, d.SPECIALIZATION, d.CONSULTATION_FEE, t.TREATMENT_TYPE, t.OUTCOME_STATUS, t.TREATMENT_COST, b.TOTAL_AMOUNT, b.PAYMENT_STATUS, CASE WHEN b.PAYMENT_STATUS = 'Paid' THEN b.TOTAL_AMOUNT ELSE 0 END AS COLLECTED_REVENUE FROM SNOWFLAKE_LEARNING_DB.RAJANMORYA_LOAD_SAMPLE_DATA_FROM_S3.APPOINTMENTS a LEFT JOIN SNOWFLAKE_LEARNING_DB.RAJANMORYA_LOAD_SAMPLE_DATA_FROM_S3.DOCTORS d ON a.DOCTOR_ID = d.DOCTOR_ID LEFT JOIN SNOWFLAKE_LEARNING_DB.RAJANMORYA_LOAD_SAMPLE_DATA_FROM_S3.TREATMENTS t ON a.APPOINTMENT_ID = t.APPOINTMENT_ID LEFT JOIN SNOWFLAKE_LEARNING_DB.RAJANMORYA_LOAD_SAMPLE_DATA_FROM_S3.BILLS b ON a.APPOINTMENT_ID = b.APPOINTMENT_ID"),
                            #"Renamed Columns" = Table.RenameColumns(custom_table, {{"APPOINTMENT_ID", "APPOINTMENT_ID (Custom SQL Query)"}, {"PATIENT_ID", "PATIENT_ID (Custom SQL Query)"}, {"DOCTOR_ID", "DOCTOR_ID (Custom SQL Query)"}, {"DEPARTMENT", "DEPARTMENT (Custom SQL Query)"}, {"APPOINTMENT_DATE", "APPOINTMENT_DATE (Custom SQL Query)"}, {"APPOINTMENT_TIME", "APPOINTMENT_TIME (Custom SQL Query)"}, {"REASON_FOR_VISIT", "REASON_FOR_VISIT (Custom SQL Query)"}, {"DIAGNOSIS_CODE", "DIAGNOSIS_CODE (Custom SQL Query)"}, {"FOLLOW_UP_REQUIRED", "FOLLOW_UP_REQUIRED (Custom SQL Query)"}, {"SPECIALIZATION", "SPECIALIZATION (Custom SQL Query)"}, {"CONSULTATION_FEE", "CONSULTATION_FEE (Custom SQL Query)"}, {"TREATMENT_TYPE", "TREATMENT_TYPE (Custom SQL Query)"}, {"OUTCOME_STATUS", "OUTCOME_STATUS (Custom SQL Query)"}, {"TREATMENT_COST", "TREATMENT_COST (Custom SQL Query)"}, {"TOTAL_AMOUNT", "TOTAL_AMOUNT (Custom SQL Query)"}, {"PAYMENT_STATUS", "PAYMENT_STATUS (Custom SQL Query)"}})
                        in
                            #"Renamed Columns"
