table 'PATIENTS'
    lineageTag: 510da771-5460-4bda-9aa1-bbc73985d1d8

    column 'Patient Id (Patients)'
        dataType: string
        lineageTag: 64b41a50-691e-41b1-93a3-65a8ee64a043
        summarizeBy: none
        sourceColumn: Patient Id (Patients)

    column 'First Name'
        dataType: string
        lineageTag: b1aa370a-34a7-431d-9267-a308c6dc86ef
        summarizeBy: none
        sourceColumn: First Name

    column 'Last Name'
        dataType: string
        lineageTag: 20a1d517-28ea-459c-a7d0-8b9354dd373a
        summarizeBy: none
        sourceColumn: Last Name

    column 'Date Of Birth'
        dataType: string
        lineageTag: fff0cb4b-6afe-4023-bb01-3726a6e7ed5a
        summarizeBy: none
        sourceColumn: Date Of Birth

    column 'Gender'
        dataType: string
        lineageTag: d1eb8509-b725-4bae-b96b-cea33fa152a3
        summarizeBy: none
        sourceColumn: Gender

    column 'Contact Number (Patients)'
        dataType: string
        lineageTag: 3e997a70-06eb-4a75-95fe-b7de9aa541e2
        summarizeBy: none
        sourceColumn: Contact Number (Patients)

    column 'Email Address (Patients)'
        dataType: string
        lineageTag: 82ae149b-d22d-4c04-aff5-0dd6702f4332
        summarizeBy: none
        sourceColumn: Email Address (Patients)

    column 'Address'
        dataType: string
        lineageTag: dd5a51dc-b9d4-448b-b90d-00d271e10460
        summarizeBy: none
        sourceColumn: Address

    column 'Insurance Provider'
        dataType: string
        lineageTag: 6e80c40c-da4f-423c-bfc8-0c07ed19bdb4
        summarizeBy: none
        sourceColumn: Insurance Provider

    column 'Insurance Policy No'
        dataType: string
        lineageTag: a15e4e56-96ca-42c5-a90a-0ed0d63cdf6f
        summarizeBy: none
        sourceColumn: Insurance Policy No

    partition 'PATIENTS' = m
        mode: import
        source =
            let
                Source = Snowflake.Databases("mmcuiwz-kl31490.snowflakecomputing.com", "COMPUTE_WH"),
                DB = Source{[Name="CITY_HOSPITAL"]}[Data],
                Schema = DB{[Name="PUBLIC"]}[Data],
                Table = Schema{[Name="PATIENTS"]}[Data],
                #"Changed Type" = Table.TransformColumnTypes(Table, {{"PATIENT_ID", type text}, {"FIRST_NAME", type text}, {"LAST_NAME", type text}, {"DATE_OF_BIRTH", type text}, {"GENDER", type text}, {"CONTACT_NUMBER", type text}, {"EMAIL_ADDRESS", type text}, {"ADDRESS", type text}, {"INSURANCE_PROVIDER", type text}, {"INSURANCE_POLICY_NO", type text}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"PATIENT_ID", "Patient Id (Patients)"}, {"FIRST_NAME", "First Name"}, {"LAST_NAME", "Last Name"}, {"DATE_OF_BIRTH", "Date Of Birth"}, {"GENDER", "Gender"}, {"CONTACT_NUMBER", "Contact Number (Patients)"}, {"EMAIL_ADDRESS", "Email Address (Patients)"}, {"ADDRESS", "Address"}, {"INSURANCE_PROVIDER", "Insurance Provider"}, {"INSURANCE_POLICY_NO", "Insurance Policy No"}})
            in
                #"Renamed Columns"
