table 'payers'
    lineageTag: eb728cbb-33f9-4dda-89ef-e9773ed3aeb9

    column 'Id (payers)'
        dataType: string
        lineageTag: ed34db82-74e6-4cdf-bc58-3855e258b8e2
        summarizeBy: none
        sourceColumn: Id (payers)

    column 'NAME (payers)'
        dataType: string
        lineageTag: e2101e91-aeaa-4edf-9d6b-855e418df4b2
        summarizeBy: none
        sourceColumn: NAME (payers)

    column 'ADDRESS (payers)'
        dataType: string
        lineageTag: c6acf59d-59bf-42cb-aab8-81dcabd88fd5
        summarizeBy: none
        sourceColumn: ADDRESS (payers)

    column 'CITY (payers)'
        dataType: string
        lineageTag: 57e7098e-a574-4666-a2e4-cebcb5a2efa8
        summarizeBy: none
        sourceColumn: CITY (payers)

    column 'State Headquartered'
        dataType: string
        lineageTag: 314f682e-2fdf-438e-bf69-19f936d65df9
        summarizeBy: none
        sourceColumn: State Headquartered

    column 'ZIP (payers)'
        dataType: double
        lineageTag: 9011df1f-ef60-44c3-96e9-b3a76d167aaf
        summarizeBy: none
        sourceColumn: ZIP (payers)

    column 'Phone'
        dataType: string
        lineageTag: e7aca7b2-c478-4c25-9b30-493d1c10e615
        summarizeBy: none
        sourceColumn: Phone

    partition 'payers' = m
        mode: import
        source =
            let Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1NB9uAQnBa6RYGfm5addKbcToYUZJY_5OlBkWxVZRrbU"),
            #"Navigation 1" = Source{[name = "payers", ItemKind = "Table"]}[Data],
                            #"Final Renamed Columns" = Table.RenameColumns(#"Navigation 1", {{"Id", "Id (payers)"}, {"NAME", "NAME (payers)"}, {"ADDRESS", "ADDRESS (payers)"}, {"CITY", "CITY (payers)"}, {"STATE_HEADQUARTERED", "State Headquartered"}, {"ZIP", "ZIP (payers)"}, {"PHONE", "Phone"}})
                        in
                            #"Final Renamed Columns"
