table 'procedures'
    lineageTag: 48868cd2-834d-4bbd-9502-19e2b3f381da

    column 'START (procedures)'
        dataType: string
        lineageTag: 4c0fe888-a9ec-4a9b-954a-6db454b92f60
        summarizeBy: none
        sourceColumn: START (procedures)

    column 'STOP (procedures)'
        dataType: string
        lineageTag: 3caeb4a8-94c2-4e60-85d2-53acbfedb2e9
        summarizeBy: none
        sourceColumn: STOP (procedures)

    column 'PATIENT (procedures)'
        dataType: string
        lineageTag: b5d6a4ac-2c71-4852-89e7-c2b0902ea2e1
        summarizeBy: none
        sourceColumn: PATIENT (procedures)

    column 'Encounter'
        dataType: string
        lineageTag: 6c9afb3e-2d6a-42c7-b82d-a5bfc77f7a85
        summarizeBy: none
        sourceColumn: Encounter

    column 'CODE (procedures)'
        dataType: double
        lineageTag: 9e156f25-1ff0-4438-842c-ac0e846a73fc
        summarizeBy: none
        sourceColumn: CODE (procedures)

    column 'DESCRIPTION (procedures)'
        dataType: string
        lineageTag: ba1d261a-0c3f-47ee-97b9-5a4dee501c4f
        summarizeBy: none
        sourceColumn: DESCRIPTION (procedures)

    column 'Base Cost'
        dataType: double
        lineageTag: 69c46731-14d5-46f5-9a24-4ad934ea31f0
        summarizeBy: none
        sourceColumn: Base Cost

    column 'REASONCODE (procedures)'
        dataType: double
        lineageTag: b5d4f7a7-2190-40fe-be81-03a74229be48
        summarizeBy: none
        sourceColumn: REASONCODE (procedures)

    column 'REASONDESCRIPTION (procedures)'
        dataType: string
        lineageTag: f6667176-041e-4bf0-864f-20bc5b21adf0
        summarizeBy: none
        sourceColumn: REASONDESCRIPTION (procedures)

    column 'DESCRIPTION (procedures) Set' = -- SKIPPED
        dataType: string

        summarizeBy: none

    measure 'Procedure Rank(Top N Procedure Parameter)' =
        -- SKIPPED BY USER


    measure 'Top N Procedures Filter' =
        -- SKIPPED BY USER


    measure 'Selected Metric' =
        -- SKIPPED BY USER


    partition 'procedures' = m
        mode: import
        source =
            let Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/10X1xQHkGidpz_0qYh7o9mxmsRJsOHRB9bNnSKFnUNgo"),
            #"Navigation 1" = Source{[name = "procedures", ItemKind = "Table"]}[Data],
                            #"Final Renamed Columns" = Table.RenameColumns(#"Navigation 1", {{"START", "START (procedures)"}, {"STOP", "STOP (procedures)"}, {"PATIENT", "PATIENT (procedures)"}, {"ENCOUNTER", "Encounter"}, {"CODE", "CODE (procedures)"}, {"DESCRIPTION", "DESCRIPTION (procedures)"}, {"BASE_COST", "Base Cost"}, {"REASONCODE", "REASONCODE (procedures)"}, {"REASONDESCRIPTION", "REASONDESCRIPTION (procedures)"}})
                        in
                            #"Final Renamed Columns"
