table 'patients'
    lineageTag: 4359dadf-c121-44eb-a443-20d044c63d28

    column 'Id (patients)'
        dataType: string
        lineageTag: 78eec19f-4634-415d-9a2f-8147cc68318a
        summarizeBy: none
        sourceColumn: Id (patients)

    column 'Birthdate'
        sourceColumn: Birthdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: bb2a5ab2-1aff-4bcf-949a-5f671537567f
        summarizeBy: none

        variation Variation
            isDefault
            relationship: b4054635-7aac-4530-8660-2ff21018c83c
            defaultHierarchy: LocalDateTable_71767278-4baf-4cbb-8230-b3b4553d363a.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Deathdate'
        sourceColumn: Deathdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: 38e17e3d-24b9-43a3-8878-a439d84e0983
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 53631e9e-35c0-45e4-9c65-7ad2d3eee9fa
            defaultHierarchy: LocalDateTable_4c4106ae-57b2-44df-82e5-cbf776503b34.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Prefix'
        dataType: string
        lineageTag: f4874e66-2301-477e-bcea-22d0e1261b92
        summarizeBy: none
        sourceColumn: Prefix

    column 'First'
        dataType: string
        lineageTag: 6fb5bdfd-1c36-40f5-8c44-79fab16cd6b5
        summarizeBy: none
        sourceColumn: First

    column 'Last'
        dataType: string
        lineageTag: 1cb5e418-4ecc-4f76-9c3e-34c096cc5c4a
        summarizeBy: none
        sourceColumn: Last

    column 'Suffix'
        dataType: string
        lineageTag: ee4dbd02-497d-46de-b24f-ba231c25ce1d
        summarizeBy: none
        sourceColumn: Suffix

    column 'Maiden'
        dataType: string
        lineageTag: 08b5b7cb-0ada-4891-a090-ccc960c29847
        summarizeBy: none
        sourceColumn: Maiden

    column 'Marital'
        dataType: string
        lineageTag: 180ef77d-ef9d-4b8a-9de6-700e8206c40e
        summarizeBy: none
        sourceColumn: Marital

    column 'Race'
        dataType: string
        lineageTag: 56f0ee5b-9058-4455-ae30-fc9ef04c54e1
        summarizeBy: none
        sourceColumn: Race

    column 'Ethnicity'
        dataType: string
        lineageTag: 5dc68929-7e0b-4605-ab08-24303d2d96f6
        summarizeBy: none
        sourceColumn: Ethnicity

    column 'Gender'
        dataType: string
        lineageTag: 72fd3a06-9e2f-4db2-be0c-527ef0dcf9ae
        summarizeBy: none
        sourceColumn: Gender

    column 'Birthplace'
        dataType: string
        lineageTag: f23d655f-ef65-48c4-b3e2-37a36e406166
        summarizeBy: none
        sourceColumn: Birthplace

    column 'Address'
        dataType: string
        lineageTag: 3ccb387f-15f6-4cab-8d25-c020decdbbc7
        summarizeBy: none
        sourceColumn: Address

    column 'City'
        dataType: string
        lineageTag: 93dd82b7-ea5b-4954-99fb-bb9eba068ff0
        summarizeBy: none
        sourceColumn: City

    column 'State'
        dataType: string
        lineageTag: 84e77de0-75a8-4a12-9831-d07a58b62ee0
        summarizeBy: none
        sourceColumn: State

    column 'County'
        dataType: string
        lineageTag: 7bf013ff-2476-4d63-a8e3-3a2b5d42a485
        summarizeBy: none
        sourceColumn: County

    column 'ZIP (organizations)'
        dataType: double
        lineageTag: f3ff59fb-13d1-48e0-9e47-dbb79707b1bd
        summarizeBy: none
        sourceColumn: ZIP (organizations)

    column 'LAT (organizations)'
        dataType: double
        lineageTag: 7037aa50-e8c3-40ad-9766-1fe9e29f0772
        summarizeBy: none
        sourceColumn: LAT (organizations)

    column 'LON (organizations)'
        dataType: double
        lineageTag: 52d4d818-5937-4944-b0e2-c75b558ae80d
        summarizeBy: none
        sourceColumn: LON (organizations)

    measure 'Patient Visits Rank (Top N Patients)' =
        RANKX(ALLSELECTED('patients'[Id (patients)1]), [Visits per Patient], , DESC, DENSE)


    measure 'SUM of Avg Visits per Patient (patients)' =
        SUM('patients'[Avg Visits per Patient])


    measure 'Total Patients (LOD)' =
        CALCULATE(DISTINCTCOUNT('patients'[Id (patients)1]), REMOVEFILTERS('patients'))


    measure 'Avg Visits per Patient' =
        CALCULATE(AVERAGEX(VALUES('patients'[Id (patients)1]), [Visits per Patient]), ALLEXCEPT('patients', 'patients'[Gender]))


    partition 'patients' = m
        mode: import
        source =
            let
                Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1Sd4bEK0Fm9q7yTVOwI4GdtixeeY8hPkKqpvnI4WdixA/edit"),
                #"Navigation 1" = Source{[name = "patients", ItemKind = "Table"]}[Data],
                #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
                #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Id", type text}, {"BIRTHDATE", type date}, {"DEATHDATE", type date}, {"PREFIX", type text}, {"FIRST", type text}, {"LAST", type text}, {"SUFFIX", type text}, {"MAIDEN", type text}, {"MARITAL", type text}, {"RACE", type text}, {"ETHNICITY", type text}, {"GENDER", type text}, {"BIRTHPLACE", type text}, {"ADDRESS", type text}, {"CITY", type text}, {"STATE", type text}, {"COUNTY", type text}, {"ZIP", type number}, {"LAT", type number}, {"LON", type number}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"Id", "Id (patients)"}, {"BIRTHDATE", "Birthdate"}, {"DEATHDATE", "Deathdate"}, {"PREFIX", "Prefix"}, {"FIRST", "First"}, {"LAST", "Last"}, {"SUFFIX", "Suffix"}, {"MAIDEN", "Maiden"}, {"MARITAL", "Marital"}, {"RACE", "Race"}, {"ETHNICITY", "Ethnicity"}, {"GENDER", "Gender"}, {"BIRTHPLACE", "Birthplace"}, {"ADDRESS", "Address"}, {"CITY", "City"}, {"STATE", "State"}, {"COUNTY", "County"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}})
            in
                #"Renamed Columns"
