table 'procedures'
	lineageTag: 744b01d7-bdf0-4318-83be-fea60656a30a

	measure 'Procedure Rank(Top N Procedure Parameter)' = RANKX(ALLSELECTED('procedures'[DESCRIPTION (procedures)]), CALCULATE(COUNT('procedures'[CODE (procedures)])), , DESC, DENSE)
		lineageTag: 1897356b-b6a7-4e79-bb3c-c1f25a689a29

	column 'START (procedures)'
		dataType: string
		lineageTag: 85501acf-4d3e-416e-9cff-4897c73ee5e2
		summarizeBy: none
		sourceColumn: START (procedures)

	column 'STOP (procedures)'
		dataType: string
		lineageTag: 64d77228-7ebe-4775-96ce-0c3f81dbb0c6
		summarizeBy: none
		sourceColumn: STOP (procedures)

	column 'PATIENT (procedures)'
		dataType: string
		lineageTag: 98a4d280-d675-4382-9cb3-2c3b00244a12
		summarizeBy: none
		sourceColumn: PATIENT (procedures)

	column 'Encounter'
		dataType: string
		lineageTag: 5acbaf52-bc23-4ac4-8bf6-98b7fbad8921
		summarizeBy: none
		sourceColumn: Encounter

	column 'CODE (procedures)'
		dataType: double
		lineageTag: 16f349e8-0f39-4152-8578-0522c0665533
		summarizeBy: none
		sourceColumn: CODE (procedures)

	column 'DESCRIPTION (procedures)'
		dataType: string
		lineageTag: c66ca46a-7bf4-41af-8b14-4ffcf685781b
		summarizeBy: none
		sourceColumn: DESCRIPTION (procedures)

	column 'Base Cost'
		dataType: double
		lineageTag: 9fcecb9d-dc8c-4a21-9201-0e27eb10e17b
		summarizeBy: none
		sourceColumn: Base Cost

	column 'REASONCODE (procedures)'
		dataType: double
		lineageTag: f1d17c51-1a42-441e-8ff4-0115a8f015dd
		summarizeBy: none
		sourceColumn: REASONCODE (procedures)

	column 'REASONDESCRIPTION (procedures)'
		dataType: string
		lineageTag: 084d972a-c3e1-40a6-8a68-50e62e6eec20
		summarizeBy: none
		sourceColumn: REASONDESCRIPTION (procedures)

	column 'DESCRIPTION__procedures__Set_Category' = IF('procedures'[DESCRIPTION (procedures)] IN { "Admission to burn unit", "Admission to long stay hospital", "Admission to orthopedic department", "Admission to trauma surgery department", "Ankle X-ray", "Antenatal RhD antibody screening", "Assessment of health and social care needs (procedure)" }, "In", "Out")
		dataType: string
		lineageTag: 5b249a89-3c5f-4b12-8baf-f550e64e05f4
		summarizeBy: none

	partition 'procedures' = m
		mode: import
		source =
				let
				    Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/10X1xQHkGidpz_0qYh7o9mxmsRJsOHRB9bNnSKFnUNgo/edit"),
				    #"Navigation 1" = Source{[name = "procedures", ItemKind = "Table"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"START", type text}, {"STOP", type text}, {"PATIENT", type text}, {"ENCOUNTER", type text}, {"CODE", type number}, {"DESCRIPTION", type text}, {"BASE_COST", type number}, {"REASONCODE", type number}, {"REASONDESCRIPTION", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"START", "START (procedures)"}, {"STOP", "STOP (procedures)"}, {"PATIENT", "PATIENT (procedures)"}, {"ENCOUNTER", "Encounter"}, {"CODE", "CODE (procedures)"}, {"DESCRIPTION", "DESCRIPTION (procedures)"}, {"BASE_COST", "Base Cost"}, {"REASONCODE", "REASONCODE (procedures)"}, {"REASONDESCRIPTION", "REASONDESCRIPTION (procedures)"}})
				in
				    #"Renamed Columns"

