table 'encounters'
    lineageTag: 5d9a8ad0-1de1-4433-825a-5c492c5b1e5c

    column 'Id'
        dataType: string
        lineageTag: 89a046be-5670-432b-9889-3fe294b5a345
        summarizeBy: none
        sourceColumn: Id

    column 'Start'
        dataType: string
        lineageTag: c4186975-48ca-435a-904d-efbc2e753bd7
        summarizeBy: none
        sourceColumn: Start

    column 'Stop'
        dataType: string
        lineageTag: 850e4142-3ea0-4002-b9d9-fa9b1d586504
        summarizeBy: none
        sourceColumn: Stop

    column 'Patient'
        dataType: string
        lineageTag: 6570d610-3f03-4b53-8902-d0168cef78f0
        summarizeBy: none
        sourceColumn: Patient

    column 'Organization'
        dataType: string
        lineageTag: e9249c9d-727b-4817-81ea-68cee2be56f5
        summarizeBy: none
        sourceColumn: Organization

    column 'Payer'
        dataType: string
        lineageTag: 13333b63-344f-47be-ad04-8c788f71f498
        summarizeBy: none
        sourceColumn: Payer

    column 'Encounterclass'
        dataType: string
        lineageTag: dfe92846-85f6-4e4f-a206-128662f5afee
        summarizeBy: none
        sourceColumn: Encounterclass

    column 'Code'
        dataType: double
        lineageTag: 25b9c552-76d1-4f02-ad83-5742ff762e92
        summarizeBy: none
        sourceColumn: Code

    column 'Description'
        dataType: string
        lineageTag: 5a281258-d7ae-4ad3-a7c1-62452eb77295
        summarizeBy: none
        sourceColumn: Description

    column 'Base Encounter Cost'
        dataType: double
        lineageTag: 683819d0-9f1a-4bb3-bbcd-a3b2aee29eb1
        summarizeBy: none
        sourceColumn: Base Encounter Cost

    column 'Total Claim Cost'
        dataType: double
        lineageTag: 0e5ea3c0-c4a4-402a-bd62-222de8bcabbb
        summarizeBy: none
        sourceColumn: Total Claim Cost

    column 'Payer Coverage'
        dataType: double
        lineageTag: 3869c9f8-6200-4c01-9d3f-d9492c96b5cb
        summarizeBy: none
        sourceColumn: Payer Coverage

    column 'Reasoncode'
        dataType: double
        lineageTag: 8483132e-2be5-4a21-af8b-dc69e63d6fbe
        summarizeBy: none
        sourceColumn: Reasoncode

    column 'Reasondescription'
        dataType: string
        lineageTag: 804cfd00-b847-481c-a9f7-d75a7ba025db
        summarizeBy: none
        sourceColumn: Reasondescription

    column 'Encounter Start Date' = -- ERROR: LLM call failed after 6 retries. Last error: 404 Client Error: Not Found for url: https://api.groq.com/openai/v1/chat/completions
        dataType: dateTime
        formatString: Long Date
        lineageTag: 67bdb4b0-2841-4a7d-a367-4539b4dd9439
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 2a2ba0c6-29cf-4a28-a11d-3be207ec2672
            defaultHierarchy: LocalDateTable_4022de2b-b00b-4908-b0e6-69944a0b368b.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    measure 'Patient Visits Rank (Top N Patients)' =
        -- ERROR: LLM call failed after 6 retries. Last error: 404 Client Error: Not Found for url: https://api.groq.com/openai/v1/chat/completions


    measure 'Top N Patients' =
        -- ERROR: LLM call failed after 6 retries. Last error: 404 Client Error: Not Found for url: https://api.groq.com/openai/v1/chat/completions


    measure 'Visits % Contribution (LOD)' =
        -- ERROR: LLM call failed after 6 retries. Last error: 404 Client Error: Not Found for url: https://api.groq.com/openai/v1/chat/completions


    measure 'CNT of Id' =
        COUNT('encounters'[Id])


    measure 'Total Visits' =
        COUNT('encounters'[Id])


    measure 'SUM of Base Encounter Cost' =
        SUM('encounters'[Base Encounter Cost])


    measure 'Total Procedures (LOD)' =
        -- ERROR CONVERTING: LLM call failed after 6 retries. Last error: 404 Client Error: Not Found for url: https://api.groq.com/openai/v1/chat/completions


    measure 'Total Visits (LOD)' =
        -- ERROR CONVERTING: LLM call failed after 6 retries. Last error: 404 Client Error: Not Found for url: https://api.groq.com/openai/v1/chat/completions


    partition 'encounters' = m
        mode: import
        source =
            let
                Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1UFffx5ngb7j1Y2kqRzPCPVA0uvA88GLaftek_fwOjKY/edit"),
                #"Navigation 1" = Source{[name = "encounters", ItemKind = "Table"]}[Data],
                #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
                #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Id", type text}, {"START", type text}, {"STOP", type text}, {"PATIENT", type text}, {"ORGANIZATION", type text}, {"PAYER", type text}, {"ENCOUNTERCLASS", type text}, {"CODE", type number}, {"DESCRIPTION", type text}, {"BASE_ENCOUNTER_COST", type number}, {"TOTAL_CLAIM_COST", type number}, {"PAYER_COVERAGE", type number}, {"REASONCODE", type number}, {"REASONDESCRIPTION", type text}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"START", "Start"}, {"STOP", "Stop"}, {"PATIENT", "Patient"}, {"ORGANIZATION", "Organization"}, {"PAYER", "Payer"}, {"ENCOUNTERCLASS", "Encounterclass"}, {"CODE", "Code"}, {"DESCRIPTION", "Description"}, {"BASE_ENCOUNTER_COST", "Base Encounter Cost"}, {"TOTAL_CLAIM_COST", "Total Claim Cost"}, {"PAYER_COVERAGE", "Payer Coverage"}, {"REASONCODE", "Reasoncode"}, {"REASONDESCRIPTION", "Reasondescription"}})
            in
                #"Renamed Columns"
