table 'patients'
    lineageTag: c523b52a-eaf1-4672-9500-964267324998

    column 'Id (patients)'
        dataType: string
        lineageTag: 695045b5-7782-4a58-b7ff-4a0645c4e36c
        summarizeBy: none
        sourceColumn: Id (patients)

    column 'Birthdate'
        sourceColumn: Birthdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: 227b4c50-4b59-46db-a942-20906798bd38
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 8d0c402f-ff0d-4fb4-a0c5-9ed7bf465fa1
            defaultHierarchy: LocalDateTable_b87ee0a3-1300-446d-8b4d-7607e707ecdf.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Deathdate'
        sourceColumn: Deathdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: b5c44e7b-ebca-4461-b7bc-2fb20fb135e0
        summarizeBy: none

        variation Variation
            isDefault
            relationship: bce40a16-681e-4ec6-98a9-32f693933e0b
            defaultHierarchy: LocalDateTable_90028b7d-fde3-4dc7-ab1c-85c6c16e1688.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Prefix'
        dataType: string
        lineageTag: 5298a846-e62a-4747-8b90-7704b082b308
        summarizeBy: none
        sourceColumn: Prefix

    column 'First'
        dataType: string
        lineageTag: 0709ea0b-fe49-4b42-98d7-8625da09a808
        summarizeBy: none
        sourceColumn: First

    column 'Last'
        dataType: string
        lineageTag: 1c3d0259-a993-45fe-866f-1b0edcc379dd
        summarizeBy: none
        sourceColumn: Last

    column 'Suffix'
        dataType: string
        lineageTag: 28a7e09a-5165-4584-836b-87a899018300
        summarizeBy: none
        sourceColumn: Suffix

    column 'Maiden'
        dataType: string
        lineageTag: 76255f72-8b4f-4d82-b598-0d40c9c411ca
        summarizeBy: none
        sourceColumn: Maiden

    column 'Marital'
        dataType: string
        lineageTag: abd9d8bb-77f3-45f6-9810-f15e5f6f43f8
        summarizeBy: none
        sourceColumn: Marital

    column 'Race'
        dataType: string
        lineageTag: 00d6a7af-7d6e-4acd-8b98-a67a75c53110
        summarizeBy: none
        sourceColumn: Race

    column 'Ethnicity'
        dataType: string
        lineageTag: 6721d903-1b67-4cb3-b18a-7a483ef2ecfb
        summarizeBy: none
        sourceColumn: Ethnicity

    column 'Gender'
        dataType: string
        lineageTag: 2ffeddee-519f-453f-9956-bc8f623e187e
        summarizeBy: none
        sourceColumn: Gender

    column 'Birthplace'
        dataType: string
        lineageTag: 2289c453-281b-44aa-8fa5-cf0fd7984dc6
        summarizeBy: none
        sourceColumn: Birthplace

    column 'Address'
        dataType: string
        lineageTag: 8d646eb0-f791-4f01-92a7-1bac89420290
        summarizeBy: none
        sourceColumn: Address

    column 'City'
        dataType: string
        lineageTag: 9443ff47-9580-43f8-8250-a40391827b6b
        summarizeBy: none
        sourceColumn: City

    column 'State'
        dataType: string
        lineageTag: 642a6c44-f95a-431a-8cd2-3095d0273874
        summarizeBy: none
        sourceColumn: State

    column 'County'
        dataType: string
        lineageTag: 53e7662d-56df-4c64-9a7e-f45cab090078
        summarizeBy: none
        sourceColumn: County

    column 'ZIP (organizations)'
        dataType: double
        lineageTag: 09041e75-11ba-4d59-b0a4-16570b83f33c
        summarizeBy: none
        sourceColumn: ZIP (organizations)

    column 'LAT (organizations)'
        dataType: double
        lineageTag: fe26bd9f-a024-4106-962c-766bcb8298a2
        summarizeBy: none
        sourceColumn: LAT (organizations)

    column 'LON (organizations)'
        dataType: double
        lineageTag: 17e18fd7-9fae-46a4-a567-6709dd33f05d
        summarizeBy: none
        sourceColumn: LON (organizations)

    measure 'SUM of Avg Visits per Patient (patients)' =
        SUM('patients'[Avg Visits per Patient])


    measure 'SUM of Visits per Patient (patients)' =
        SUM('patients'[Visits per Patient])


    measure 'Total Patients (LOD)' =
        -- ERROR CONVERTING: LLM call failed after 6 retries. Last error: 404 Client Error: Not Found for url: https://api.groq.com/openai/v1/chat/completions


    measure 'Visits per Patient' =
        -- ERROR CONVERTING: LLM call failed after 6 retries. Last error: 404 Client Error: Not Found for url: https://api.groq.com/openai/v1/chat/completions


    measure 'Avg Visits per Patient' =
        -- ERROR CONVERTING: LLM call failed after 6 retries. Last error: 404 Client Error: Not Found for url: https://api.groq.com/openai/v1/chat/completions


    partition 'patients' = m
        mode: import
        source =
            let
                Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1Sd4bEK0Fm9q7yTVOwI4GdtixeeY8hPkKqpvnI4WdixA/edit"),
                #"Navigation 1" = Source{[name = "patients", ItemKind = "Table"]}[Data],
                #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
                #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Id", type text}, {"BIRTHDATE", type date}, {"DEATHDATE", type date}, {"PREFIX", type text}, {"FIRST", type text}, {"LAST", type text}, {"SUFFIX", type text}, {"MAIDEN", type text}, {"MARITAL", type text}, {"RACE", type text}, {"ETHNICITY", type text}, {"GENDER", type text}, {"BIRTHPLACE", type text}, {"ADDRESS", type text}, {"CITY", type text}, {"STATE", type text}, {"COUNTY", type text}, {"ZIP", type number}, {"LAT", type number}, {"LON", type number}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"Id", "Id (patients)"}, {"BIRTHDATE", "Birthdate"}, {"DEATHDATE", "Deathdate"}, {"PREFIX", "Prefix"}, {"FIRST", "First"}, {"LAST", "Last"}, {"SUFFIX", "Suffix"}, {"MAIDEN", "Maiden"}, {"MARITAL", "Marital"}, {"RACE", "Race"}, {"ETHNICITY", "Ethnicity"}, {"GENDER", "Gender"}, {"BIRTHPLACE", "Birthplace"}, {"ADDRESS", "Address"}, {"CITY", "City"}, {"STATE", "State"}, {"COUNTY", "County"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}})
            in
                #"Renamed Columns"
