table 'organizations'
    lineageTag: 24423834-0ad3-48e5-b168-55ca62c93478

    column 'Id (organizations)'
        dataType: string
        lineageTag: 9d60b7ea-cb73-434d-9019-84d144aa6865
        summarizeBy: none
        sourceColumn: Id (organizations)

    column 'Name'
        dataType: string
        lineageTag: 00102aa7-1113-45f2-9c68-86da9785733b
        summarizeBy: none
        sourceColumn: Name

    column 'ADDRESS (organizations)'
        dataType: string
        lineageTag: 9517847a-f5ce-4f34-8f3b-2c84ff0ebb9e
        summarizeBy: none
        sourceColumn: ADDRESS (organizations)

    column 'CITY (organizations)'
        dataType: string
        lineageTag: fa56cd75-b32e-4b0b-9fd0-43c421f6e4aa
        summarizeBy: none
        sourceColumn: CITY (organizations)

    column 'STATE (organizations)'
        dataType: string
        lineageTag: e317e6d5-db76-49c1-99ae-d836215c571e
        summarizeBy: none
        sourceColumn: STATE (organizations)

    column 'ZIP (organizations)'
        dataType: double
        lineageTag: 1c778e80-8ae7-4966-bdb2-62c30df2d295
        summarizeBy: none
        sourceColumn: ZIP (organizations)

    column 'LAT (organizations)'
        dataType: double
        lineageTag: 53946b23-c6d2-4483-ba4e-fb0d7f074d7d
        summarizeBy: none
        sourceColumn: LAT (organizations)

    column 'LON (organizations)'
        dataType: double
        lineageTag: 0c3925cd-a7ad-4a87-9054-63085c1f507c
        summarizeBy: none
        sourceColumn: LON (organizations)

    column 'Username' = -- ERROR: LLM call failed after 6 retries. Last error: 401 Client Error: Unauthorized for url: https://api.groq.com/openai/v1/chat/completions
        dataType: string

        summarizeBy: none

    measure 'RLS - Organization Access' =
        -- ERROR: LLM call failed after 6 retries. Last error: 401 Client Error: Unauthorized for url: https://api.groq.com/openai/v1/chat/completions


    partition 'organizations' = m
        mode: import
        source =
            let
                Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1Gfqr930PI28eveUiJrS8ikSsyzDUbPE4pJy7nG9ZIUc/edit"),
                #"Navigation 1" = Source{[name = "organizations", ItemKind = "Table"]}[Data],
                #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
                #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Id", type text}, {"NAME", type text}, {"ADDRESS", type text}, {"CITY", type text}, {"STATE", type text}, {"ZIP", type number}, {"LAT", type number}, {"LON", type number}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"Id", "Id (organizations)"}, {"NAME", "Name"}, {"ADDRESS", "ADDRESS (organizations)"}, {"CITY", "CITY (organizations)"}, {"STATE", "STATE (organizations)"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}})
            in
                #"Renamed Columns"
