table 'patients'
    lineageTag: 9347d8c2-9f0a-4186-b26e-e485ae389dec

    column 'Id (patients)'
        dataType: string
        lineageTag: 58a39b37-ad32-431c-833f-a4ecb7fccc54
        summarizeBy: none
        sourceColumn: Id (patients)

    column 'Birthdate'
        sourceColumn: Birthdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: be81b345-0440-4e79-885d-4c86f757316a
        summarizeBy: none

        variation Variation
            isDefault
            relationship: d98509ef-216d-44e8-9999-9dc790bc7900
            defaultHierarchy: LocalDateTable_c2b67e2e-e44c-4fc7-b1fe-991e072ffdbd.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Deathdate'
        sourceColumn: Deathdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: f26fa231-52bb-44b1-b81e-2c89205711b7
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 84a1eb33-1e87-4fae-81b8-f0c1db021022
            defaultHierarchy: LocalDateTable_b1d7262a-1590-46f4-bb61-7a1b1a7ab03a.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Prefix'
        dataType: string
        lineageTag: e99a42ab-b387-4505-917d-c71d44c34df5
        summarizeBy: none
        sourceColumn: Prefix

    column 'First'
        dataType: string
        lineageTag: 058e017e-a636-4a14-bf86-331aaaed2001
        summarizeBy: none
        sourceColumn: First

    column 'Last'
        dataType: string
        lineageTag: b4059a39-3d1f-479d-bad5-62a52ee27531
        summarizeBy: none
        sourceColumn: Last

    column 'Suffix'
        dataType: string
        lineageTag: 53ccf146-36e9-4102-b6bf-474f4c9f067e
        summarizeBy: none
        sourceColumn: Suffix

    column 'Maiden'
        dataType: string
        lineageTag: 520e2c65-b415-4d61-81f1-3c5f260e3628
        summarizeBy: none
        sourceColumn: Maiden

    column 'Marital'
        dataType: string
        lineageTag: a5682451-c272-4c9e-8f21-db5dac084112
        summarizeBy: none
        sourceColumn: Marital

    column 'Race'
        dataType: string
        lineageTag: 2b07380e-4e72-479c-833e-995627a4c575
        summarizeBy: none
        sourceColumn: Race

    column 'Ethnicity'
        dataType: string
        lineageTag: 824f0417-55a1-4f75-970f-73272c1f0170
        summarizeBy: none
        sourceColumn: Ethnicity

    column 'Gender'
        dataType: string
        lineageTag: 6ae38a39-fdc3-486e-a36d-71c78050d51c
        summarizeBy: none
        sourceColumn: Gender

    column 'Birthplace'
        dataType: string
        lineageTag: 2a2235b7-c9d4-4ba1-817d-ce11fa5ae5d5
        summarizeBy: none
        sourceColumn: Birthplace

    column 'Address'
        dataType: string
        lineageTag: e225a64e-e1aa-41c0-8b2a-1ffe1d871e80
        summarizeBy: none
        sourceColumn: Address

    column 'City'
        dataType: string
        lineageTag: bc6e32ab-dd85-4a2e-ae29-812f3d9390e9
        summarizeBy: none
        sourceColumn: City

    column 'State'
        dataType: string
        lineageTag: 4da9d42e-eed6-4aae-8030-a3bf14dea4b3
        summarizeBy: none
        sourceColumn: State

    column 'County'
        dataType: string
        lineageTag: bc43ed49-e029-463a-8e55-65d2122d12ea
        summarizeBy: none
        sourceColumn: County

    column 'ZIP (organizations)'
        dataType: double
        lineageTag: 47a8a7aa-6130-489e-84c1-4923204952b5
        summarizeBy: none
        sourceColumn: ZIP (organizations)

    column 'LAT (organizations)'
        dataType: double
        lineageTag: 61395b29-6686-4b35-ad4f-edd5cd66b3be
        summarizeBy: none
        sourceColumn: LAT (organizations)

    column 'LON (organizations)'
        dataType: double
        lineageTag: 61ef806c-9fb2-42fc-82b0-b86c3ad36c97
        summarizeBy: none
        sourceColumn: LON (organizations)

    measure 'SUM of Avg Visits per Patient (patients)' =
        SUM('patients'[Avg Visits per Patient])


    measure 'SUM of Visits per Patient (patients)' =
        SUM('patients'[Visits per Patient])


    measure 'Total Patients (LOD)' =
        -- ERROR CONVERTING: LLM call failed after 6 retries. Last error: 401 Client Error: Unauthorized for url: https://api.groq.com/openai/v1/chat/completions


    measure 'Visits per Patient' =
        -- ERROR CONVERTING: LLM call failed after 6 retries. Last error: 401 Client Error: Unauthorized for url: https://api.groq.com/openai/v1/chat/completions


    measure 'Avg Visits per Patient' =
        -- ERROR CONVERTING: LLM call failed after 6 retries. Last error: 401 Client Error: Unauthorized for url: https://api.groq.com/openai/v1/chat/completions


    partition 'patients' = m
        mode: import
        source =
            let
                Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1Sd4bEK0Fm9q7yTVOwI4GdtixeeY8hPkKqpvnI4WdixA/edit"),
                #"Navigation 1" = Source{[name = "patients", ItemKind = "Table"]}[Data],
                #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
                #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Id", type text}, {"BIRTHDATE", type date}, {"DEATHDATE", type date}, {"PREFIX", type text}, {"FIRST", type text}, {"LAST", type text}, {"SUFFIX", type text}, {"MAIDEN", type text}, {"MARITAL", type text}, {"RACE", type text}, {"ETHNICITY", type text}, {"GENDER", type text}, {"BIRTHPLACE", type text}, {"ADDRESS", type text}, {"CITY", type text}, {"STATE", type text}, {"COUNTY", type text}, {"ZIP", type number}, {"LAT", type number}, {"LON", type number}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"Id", "Id (patients)"}, {"BIRTHDATE", "Birthdate"}, {"DEATHDATE", "Deathdate"}, {"PREFIX", "Prefix"}, {"FIRST", "First"}, {"LAST", "Last"}, {"SUFFIX", "Suffix"}, {"MAIDEN", "Maiden"}, {"MARITAL", "Marital"}, {"RACE", "Race"}, {"ETHNICITY", "Ethnicity"}, {"GENDER", "Gender"}, {"BIRTHPLACE", "Birthplace"}, {"ADDRESS", "Address"}, {"CITY", "City"}, {"STATE", "State"}, {"COUNTY", "County"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}})
            in
                #"Renamed Columns"
