table 'patients.csv'
    lineageTag: 2628187b-0dd8-46f1-bdda-8f789a96996c

    column 'Id'
        dataType: string
        lineageTag: 3d197c51-5190-411a-a8f4-90ecc6f9cb02
        summarizeBy: none
        sourceColumn: Id

    column 'Birthdate'
        sourceColumn: Birthdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: 63fd0035-6168-4fa4-b9fc-f623ca1063f5
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 1f770cd0-00c8-4fc7-90cc-bc1dc0a65fc7
            defaultHierarchy: LocalDateTable_d56591c0-7951-4202-bab0-22571f476520.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Deathdate'
        sourceColumn: Deathdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: 4b85fb43-b221-439c-8126-0e0b60b6c0f2
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 5cf56c05-e468-4f55-bf43-25d993048977
            defaultHierarchy: LocalDateTable_1b41a2a7-88ec-4b1b-bdac-f1616367c87e.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Prefix'
        dataType: string
        lineageTag: b6da637f-d52c-4624-8b19-0bfc8f94ce6e
        summarizeBy: none
        sourceColumn: Prefix

    column 'First'
        dataType: string
        lineageTag: ace62565-372d-473c-b6d5-3fcdcdcd5353
        summarizeBy: none
        sourceColumn: First

    column 'Last'
        dataType: string
        lineageTag: eae059bf-58c7-4cab-b50a-64c7211df91d
        summarizeBy: none
        sourceColumn: Last

    column 'Suffix'
        dataType: string
        lineageTag: 2776c384-fd48-4f47-aea5-88419b9cf635
        summarizeBy: none
        sourceColumn: Suffix

    column 'Maiden'
        dataType: string
        lineageTag: c48bc239-ecb7-4146-acf1-2efa7afe77fe
        summarizeBy: none
        sourceColumn: Maiden

    column 'Marital'
        dataType: string
        lineageTag: c3d7572e-805b-4529-83f7-a482798b7c25
        summarizeBy: none
        sourceColumn: Marital

    column 'Race'
        dataType: string
        lineageTag: 6e1977ce-5e0d-490d-922b-bc6034a4df57
        summarizeBy: none
        sourceColumn: Race

    column 'Ethnicity'
        dataType: string
        lineageTag: 67cfa32e-e789-407a-9ea1-f6be2005b20e
        summarizeBy: none
        sourceColumn: Ethnicity

    column 'Gender'
        dataType: string
        lineageTag: 7f21a183-ae42-4538-8dca-6c4fdc406ffe
        summarizeBy: none
        sourceColumn: Gender

    column 'Birthplace'
        dataType: string
        lineageTag: 22614c11-4040-4b86-b805-787307f8afe2
        summarizeBy: none
        sourceColumn: Birthplace

    column 'Address'
        dataType: string
        lineageTag: f1a85250-11dd-4424-8ac6-5b2b9730ae02
        summarizeBy: none
        sourceColumn: Address

    column 'City'
        dataType: string
        lineageTag: a030c221-35b3-415e-8f93-1f7b75d1a8b9
        summarizeBy: none
        sourceColumn: City

    column 'State'
        dataType: string
        lineageTag: 16da7108-933b-4871-ad02-7370b1d8ddc1
        summarizeBy: none
        sourceColumn: State

    column 'County'
        dataType: string
        lineageTag: dea2e217-ddbb-4d9a-a7f6-bc9268a47d1a
        summarizeBy: none
        sourceColumn: County

    column 'ZIP (organizations)'
        dataType: double
        lineageTag: 10cc5c78-dab6-4407-95ea-11edd34b5e14
        summarizeBy: none
        sourceColumn: ZIP (organizations)

    column 'LAT (organizations)'
        dataType: double
        lineageTag: 94a775aa-7730-49a2-aa13-e7e3bf2cd612
        summarizeBy: none
        sourceColumn: LAT (organizations)

    column 'LON (organizations)'
        dataType: double
        lineageTag: 930c8798-7f27-4acb-9f9a-99ae81420d4f
        summarizeBy: none
        sourceColumn: LON (organizations)

    measure 'CNT of Id (patients.csv)' =
        COUNT('patients.csv'[Id])


    measure 'Total Visits' =
        COUNT('patients.csv'[Id])


    measure 'Total Visits (LOD)' =
        -- ERROR CONVERTING: LLM call failed after 6 retries. Last error: 401 Client Error: Unauthorized for url: https://api.groq.com/openai/v1/chat/completions


    partition 'patients.csv' = m
        mode: import
        source =
            let
                Source_Raw = Csv.Document(File.Contents("C:/TableauData/patients.csv"), [Delimiter=",", Encoding=28591, QuoteStyle=QuoteStyle.None]),
                #"Promoted Headers" = Table.PromoteHeaders(Source_Raw, [PromoteAllScalars = true]),
                #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Id", type text}, {"BIRTHDATE", type date}, {"DEATHDATE", type date}, {"PREFIX", type text}, {"FIRST", type text}, {"LAST", type text}, {"SUFFIX", type text}, {"MAIDEN", type text}, {"MARITAL", type text}, {"RACE", type text}, {"ETHNICITY", type text}, {"GENDER", type text}, {"BIRTHPLACE", type text}, {"ADDRESS", type text}, {"CITY", type text}, {"STATE", type text}, {"COUNTY", type text}, {"ZIP", type number}, {"LAT", type number}, {"LON", type number}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"BIRTHDATE", "Birthdate"}, {"DEATHDATE", "Deathdate"}, {"PREFIX", "Prefix"}, {"FIRST", "First"}, {"LAST", "Last"}, {"SUFFIX", "Suffix"}, {"MAIDEN", "Maiden"}, {"MARITAL", "Marital"}, {"RACE", "Race"}, {"ETHNICITY", "Ethnicity"}, {"GENDER", "Gender"}, {"BIRTHPLACE", "Birthplace"}, {"ADDRESS", "Address"}, {"CITY", "City"}, {"STATE", "State"}, {"COUNTY", "County"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}})
            in
                #"Renamed Columns"
