table 'encounters'
    lineageTag: 65dc833d-a473-47b1-8c4c-5f3031aed91d

    column 'Id'
        dataType: string
        lineageTag: 31ab6894-5cfe-430c-b9c3-7382e348b53a
        summarizeBy: none
        sourceColumn: Id

    column 'Start'
        dataType: string
        lineageTag: 09856b91-9608-4f91-bc38-d08fdbc3e37d
        summarizeBy: none
        sourceColumn: Start

    column 'Stop'
        dataType: string
        lineageTag: 711dc601-d67c-4e42-90b7-86433370ee53
        summarizeBy: none
        sourceColumn: Stop

    column 'Patient'
        dataType: string
        lineageTag: 02930f8f-aaa8-4b5c-9c34-4ae3e97ea896
        summarizeBy: none
        sourceColumn: Patient

    column 'Organization'
        dataType: string
        lineageTag: cf71df15-35f3-4a6a-a8a0-aa1f181ec789
        summarizeBy: none
        sourceColumn: Organization

    column 'Payer'
        dataType: string
        lineageTag: 5b48b861-b7d0-4ec3-bb4a-8cc7cec901f9
        summarizeBy: none
        sourceColumn: Payer

    column 'Encounterclass'
        dataType: string
        lineageTag: 3d1e1de7-7bf4-4de3-a65b-be0b7fc2dc7e
        summarizeBy: none
        sourceColumn: Encounterclass

    column 'Code'
        dataType: double
        lineageTag: cfc890c4-541d-4099-a0d9-a4dfbb5068d3
        summarizeBy: none
        sourceColumn: Code

    column 'Description'
        dataType: string
        lineageTag: b1df9d80-10a8-4408-9c06-db29ba79f53c
        summarizeBy: none
        sourceColumn: Description

    column 'Base Encounter Cost'
        dataType: double
        lineageTag: c523f8e2-1f3e-46f4-bb37-a32912a1e487
        summarizeBy: none
        sourceColumn: Base Encounter Cost

    column 'Total Claim Cost'
        dataType: double
        lineageTag: c7970ed1-e560-4ebf-ade9-b308fdeaeaec
        summarizeBy: none
        sourceColumn: Total Claim Cost

    column 'Payer Coverage'
        dataType: double
        lineageTag: 9c34f1fe-37b8-4dce-b2df-4776e3f63514
        summarizeBy: none
        sourceColumn: Payer Coverage

    column 'Reasoncode'
        dataType: double
        lineageTag: 99edf34f-d8f1-49a0-a917-e2f894f503ae
        summarizeBy: none
        sourceColumn: Reasoncode

    column 'Reasondescription'
        dataType: string
        lineageTag: 8d74bc3e-7d71-43e8-8e86-0b94d7ed6329
        summarizeBy: none
        sourceColumn: Reasondescription

    column 'Encounter Start Date' = DATEVALUE(LEFT('encounters'[Start], 10))
        dataType: dateTime
        formatString: Long Date
        lineageTag: 0b25399f-ae61-45f2-aaa6-3dbc93cc39a4
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 5fb756b8-37bf-43e0-a8cf-19483e36250b
            defaultHierarchy: LocalDateTable_fc077599-be55-4421-bc57-7c0426837194.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    measure 'Visits % Contribution (LOD)' =
        DIVIDE(COUNT('encounters'[Id]), CALCULATE([Total Visits (LOD)], ALLSELECTED()), 0)


    measure 'CNT of Id' =
        COUNT('encounters'[Id])


    measure 'Total Visits' =
        COUNT('encounters'[Id])


    measure 'SUM of Visits per Patient' =
        SUM('encounters'[Visits per Patient])


    measure 'SUM of Base Encounter Cost' =
        SUM('encounters'[Base Encounter Cost])


    measure 'Total Procedures (LOD)' =
        CALCULATE(COUNT('encounters'[Code]), REMOVEFILTERS('encounters'))


    measure 'Total Visits (LOD)' =
        CALCULATE(COUNT('encounters'[Id]), REMOVEFILTERS('encounters'))


    measure 'Visits per Patient' =
        CALCULATE(COUNT('encounters'[Id]), REMOVEFILTERS('encounters'), ALLEXCEPT('patients', 'patients'[Id (patients)1]))


    partition 'encounters' = m
        mode: import
        source =
            let
                Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1UFffx5ngb7j1Y2kqRzPCPVA0uvA88GLaftek_fwOjKY/edit"),
                #"Navigation 1" = Source{[name = "encounters", ItemKind = "Table"]}[Data],
                #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
                #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Id", type text}, {"START", type text}, {"STOP", type text}, {"PATIENT", type text}, {"ORGANIZATION", type text}, {"PAYER", type text}, {"ENCOUNTERCLASS", type text}, {"CODE", type number}, {"DESCRIPTION", type text}, {"BASE_ENCOUNTER_COST", type number}, {"TOTAL_CLAIM_COST", type number}, {"PAYER_COVERAGE", type number}, {"REASONCODE", type number}, {"REASONDESCRIPTION", type text}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"START", "Start"}, {"STOP", "Stop"}, {"PATIENT", "Patient"}, {"ORGANIZATION", "Organization"}, {"PAYER", "Payer"}, {"ENCOUNTERCLASS", "Encounterclass"}, {"CODE", "Code"}, {"DESCRIPTION", "Description"}, {"BASE_ENCOUNTER_COST", "Base Encounter Cost"}, {"TOTAL_CLAIM_COST", "Total Claim Cost"}, {"PAYER_COVERAGE", "Payer Coverage"}, {"REASONCODE", "Reasoncode"}, {"REASONDESCRIPTION", "Reasondescription"}})
            in
                #"Renamed Columns"
