table 'patients'
    lineageTag: e7738a60-044a-41c5-ae4a-17273c4e2d06

    column 'Id (patients)'
        dataType: string
        lineageTag: 78f49d7a-d2ae-4f41-8a7b-780f80b7c0e6
        summarizeBy: none
        sourceColumn: Id (patients)

    column 'Birthdate'
        sourceColumn: Birthdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: 35dfe785-28e5-4278-a370-83a50046cd7c
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 9cd724ed-5418-409e-8f2b-d277d94802d0
            defaultHierarchy: LocalDateTable_22b3da2b-379a-4306-b2a4-61d9b68db667.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Deathdate'
        sourceColumn: Deathdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: e5d626d9-9a1d-4675-b6e7-efa04c6b449e
        summarizeBy: none

        variation Variation
            isDefault
            relationship: cee54cd1-f186-459f-96f7-798a663361fe
            defaultHierarchy: LocalDateTable_371e6c13-ee6e-4f02-8c00-02e562c00637.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Prefix'
        dataType: string
        lineageTag: 17c93f37-be4d-4029-b482-75d599e38f8d
        summarizeBy: none
        sourceColumn: Prefix

    column 'First'
        dataType: string
        lineageTag: e4617135-6e4a-4e21-96e2-51eec78c1bd0
        summarizeBy: none
        sourceColumn: First

    column 'Last'
        dataType: string
        lineageTag: b268e5a7-e90c-459c-829f-abc82de12245
        summarizeBy: none
        sourceColumn: Last

    column 'Suffix'
        dataType: string
        lineageTag: a7771433-6b44-4670-8579-5b0692802553
        summarizeBy: none
        sourceColumn: Suffix

    column 'Maiden'
        dataType: string
        lineageTag: 80bd753a-0a4b-4b65-835c-0bc4fcfa4e88
        summarizeBy: none
        sourceColumn: Maiden

    column 'Marital'
        dataType: string
        lineageTag: e67d5b3b-f852-4743-bc3f-756eb87b2949
        summarizeBy: none
        sourceColumn: Marital

    column 'Race'
        dataType: string
        lineageTag: e3302c5e-5799-4ab6-9773-16f8b3a851ac
        summarizeBy: none
        sourceColumn: Race

    column 'Ethnicity'
        dataType: string
        lineageTag: 1e714023-61a6-4efb-b7e5-bfd8ced0ea03
        summarizeBy: none
        sourceColumn: Ethnicity

    column 'Gender'
        dataType: string
        lineageTag: ad3bbe49-59e5-457f-83f1-7d7ac721f8e4
        summarizeBy: none
        sourceColumn: Gender

    column 'Birthplace'
        dataType: string
        lineageTag: d1b74cb4-ac6e-4cd4-aa81-e523f66104d2
        summarizeBy: none
        sourceColumn: Birthplace

    column 'Address'
        dataType: string
        lineageTag: 2c90e630-3acd-47b7-b96a-83efe91498e1
        summarizeBy: none
        sourceColumn: Address

    column 'City'
        dataType: string
        lineageTag: b5a57730-bbcd-4873-a5f3-fbb6d65b37aa
        summarizeBy: none
        sourceColumn: City

    column 'State'
        dataType: string
        lineageTag: 07990f5b-1202-41d6-9aea-16d97a3bb0e1
        summarizeBy: none
        sourceColumn: State

    column 'County'
        dataType: string
        lineageTag: 5a93588f-c3f1-49e9-9804-3363a97532df
        summarizeBy: none
        sourceColumn: County

    column 'ZIP (organizations)'
        dataType: double
        lineageTag: ae100c36-1b66-4fc6-adc3-ab0b55cbaa46
        summarizeBy: none
        sourceColumn: ZIP (organizations)

    column 'LAT (organizations)'
        dataType: double
        lineageTag: 47d7b6c0-f771-4d0a-8ed9-76234bed2fb7
        summarizeBy: none
        sourceColumn: LAT (organizations)

    column 'LON (organizations)'
        dataType: double
        lineageTag: 09838609-dfc6-4470-add3-a8678a5a0488
        summarizeBy: none
        sourceColumn: LON (organizations)

    measure 'Patient Visits Rank (Top N Patients)' =
        RANKX(ALLSELECTED('patients'[Id (patients)1]), [Visits per Patient], , DESC, DENSE)


    measure 'SUM of Avg Visits per Patient (patients)' =
        SUM('patients'[Avg Visits per Patient])


    measure 'Total Patients (LOD)' =
        CALCULATE(DISTINCTCOUNT('patients'[Id (patients)1]), REMOVEFILTERS('patients'))


    measure 'Avg Visits per Patient' =
        CALCULATE(AVERAGEX(VALUES('patients'[Id (patients)1]), [Visits per Patient]), ALLEXCEPT('patients', 'patients'[Gender]))


    partition 'patients' = m
        mode: import
        source =
            let
                Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1Sd4bEK0Fm9q7yTVOwI4GdtixeeY8hPkKqpvnI4WdixA/edit"),
                #"Navigation 1" = Source{[name = "patients", ItemKind = "Table"]}[Data],
                #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
                #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Id", type text}, {"BIRTHDATE", type date}, {"DEATHDATE", type date}, {"PREFIX", type text}, {"FIRST", type text}, {"LAST", type text}, {"SUFFIX", type text}, {"MAIDEN", type text}, {"MARITAL", type text}, {"RACE", type text}, {"ETHNICITY", type text}, {"GENDER", type text}, {"BIRTHPLACE", type text}, {"ADDRESS", type text}, {"CITY", type text}, {"STATE", type text}, {"COUNTY", type text}, {"ZIP", type number}, {"LAT", type number}, {"LON", type number}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"Id", "Id (patients)"}, {"BIRTHDATE", "Birthdate"}, {"DEATHDATE", "Deathdate"}, {"PREFIX", "Prefix"}, {"FIRST", "First"}, {"LAST", "Last"}, {"SUFFIX", "Suffix"}, {"MAIDEN", "Maiden"}, {"MARITAL", "Marital"}, {"RACE", "Race"}, {"ETHNICITY", "Ethnicity"}, {"GENDER", "Gender"}, {"BIRTHPLACE", "Birthplace"}, {"ADDRESS", "Address"}, {"CITY", "City"}, {"STATE", "State"}, {"COUNTY", "County"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}})
            in
                #"Renamed Columns"
