table 'patients'
    lineageTag: b5fd81ea-4e73-4e4b-82d0-a50c8e20f53b

    column 'Id (patients)'
        dataType: string
        lineageTag: 48feebb7-5a1a-4767-aca5-196fe1b678b7
        summarizeBy: none
        sourceColumn: Id (patients)

    column 'Birthdate'
        sourceColumn: Birthdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: 3986dacd-3962-4074-9322-f4ea3ba7ae56
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 1189f2af-546c-4104-bfff-b6b5b013d8ed
            defaultHierarchy: LocalDateTable_b17900fb-096a-407c-ad3a-8d0f3ea293d0.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Deathdate'
        sourceColumn: Deathdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: 383067e4-b0ff-4c9e-b645-d9a2bf6d3955
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 5dac8ce0-0d83-4f7e-af90-cae8e68f3853
            defaultHierarchy: LocalDateTable_5bc9c0f4-3ca7-40dc-991f-fcec3956426b.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Prefix'
        dataType: string
        lineageTag: 12cd7520-8d59-4b40-b8c3-e016c8ea6005
        summarizeBy: none
        sourceColumn: Prefix

    column 'First'
        dataType: string
        lineageTag: 9766cd26-034b-43af-ad04-a3d3ce0f98ed
        summarizeBy: none
        sourceColumn: First

    column 'Last'
        dataType: string
        lineageTag: ddbd37ce-d8aa-4af2-8fcf-79a4f2c4075b
        summarizeBy: none
        sourceColumn: Last

    column 'Suffix'
        dataType: string
        lineageTag: 7fb3b9dc-31aa-449f-abcb-2e105472cc94
        summarizeBy: none
        sourceColumn: Suffix

    column 'Maiden'
        dataType: string
        lineageTag: 188a73ea-758b-4092-959d-5e4b7af4186e
        summarizeBy: none
        sourceColumn: Maiden

    column 'Marital'
        dataType: string
        lineageTag: b9ada9c2-514a-490a-afbb-5ee3222766f2
        summarizeBy: none
        sourceColumn: Marital

    column 'Race'
        dataType: string
        lineageTag: 7faee97b-0a5f-42b7-92e7-abdea3bfc6cf
        summarizeBy: none
        sourceColumn: Race

    column 'Ethnicity'
        dataType: string
        lineageTag: ebb9d2cb-6517-4faa-93d0-19fe67fe7db1
        summarizeBy: none
        sourceColumn: Ethnicity

    column 'Gender'
        dataType: string
        lineageTag: 345166c4-19f9-42ac-9f43-ada5efa29f1a
        summarizeBy: none
        sourceColumn: Gender

    column 'Birthplace'
        dataType: string
        lineageTag: b459bcab-2140-48dd-962d-bff51c269998
        summarizeBy: none
        sourceColumn: Birthplace

    column 'Address'
        dataType: string
        lineageTag: 65064975-4073-4d54-98db-ecf13ee78966
        summarizeBy: none
        sourceColumn: Address

    column 'City'
        dataType: string
        lineageTag: 44b53f47-0d2d-402d-84cb-0289c324889f
        summarizeBy: none
        sourceColumn: City

    column 'State'
        dataType: string
        lineageTag: 0b3f17d2-91c1-494c-b995-8cfd87810a3c
        summarizeBy: none
        sourceColumn: State

    column 'County'
        dataType: string
        lineageTag: beaf691b-bab9-4f92-b611-24653e8de1b2
        summarizeBy: none
        sourceColumn: County

    column 'ZIP (organizations)'
        dataType: double
        lineageTag: d63294f9-c27c-4658-a330-9cea1c6e6db8
        summarizeBy: none
        sourceColumn: ZIP (organizations)

    column 'LAT (organizations)'
        dataType: double
        lineageTag: 6aaa673a-16fa-4393-9ba9-fb3703dbbde1
        summarizeBy: none
        sourceColumn: LAT (organizations)

    column 'LON (organizations)'
        dataType: double
        lineageTag: 5bf40780-f864-400b-a6ff-165fc0598235
        summarizeBy: none
        sourceColumn: LON (organizations)

    measure 'SUM of Avg Visits per Patient (patients)' =
        SUM('patients'[Avg Visits per Patient])


    measure 'SUM of Visits per Patient (patients)' =
        SUM('patients'[Visits per Patient])


    measure 'Total Patients (LOD)' =
        -- SKIPPED BY USER


    measure 'Visits per Patient' =
        -- SKIPPED BY USER


    measure 'Avg Visits per Patient' =
        -- SKIPPED BY USER


    partition 'patients' = m
        mode: import
        source =
            let Source = GoogleSheets.Contents("https://www.googleapis.com/drive/v3/files/1Sd4bEK0Fm9q7yTVOwI4GdtixeeY8hPkKqpvnI4WdixA/export?mimeType=application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
            #"Navigation 1" = Source{[name="patients", ItemKind="Table"]}[Data],
            #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars=true]),
            #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Id", type text}, {"BIRTHDATE", type date}, {"DEATHDATE", type date}, {"PREFIX", type text}, {"FIRST", type text}, {"LAST", type text}, {"SUFFIX", type text}, {"MAIDEN", type text}, {"MARITAL", type text}, {"RACE", type text}, {"ETHNICITY", type text}, {"GENDER", type text}, {"BIRTHPLACE", type text}, {"ADDRESS", type text}, {"CITY", type text}, {"STATE", type text}, {"COUNTY", type text}, {"ZIP", type number}, {"LAT", type number}, {"LON", type number}}),
            #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"Id", "Id (patients)"}, {"BIRTHDATE", "Birthdate"}, {"DEATHDATE", "Deathdate"}, {"PREFIX", "Prefix"}, {"FIRST", "First"}, {"LAST", "Last"}, {"SUFFIX", "Suffix"}, {"MAIDEN", "Maiden"}, {"MARITAL", "Marital"}, {"RACE", "Race"}, {"ETHNICITY", "Ethnicity"}, {"GENDER", "Gender"}, {"BIRTHPLACE", "Birthplace"}, {"ADDRESS", "Address"}, {"CITY", "City"}, {"STATE", "State"}, {"COUNTY", "County"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}}),
                            #"Renamed Columns" = Table.RenameColumns(#"Renamed Columns", {{"Id", "Id (patients)"}, {"BIRTHDATE", "Birthdate"}, {"DEATHDATE", "Deathdate"}, {"PREFIX", "Prefix"}, {"FIRST", "First"}, {"LAST", "Last"}, {"SUFFIX", "Suffix"}, {"MAIDEN", "Maiden"}, {"MARITAL", "Marital"}, {"RACE", "Race"}, {"ETHNICITY", "Ethnicity"}, {"GENDER", "Gender"}, {"BIRTHPLACE", "Birthplace"}, {"ADDRESS", "Address"}, {"CITY", "City"}, {"STATE", "State"}, {"COUNTY", "County"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}})
                        in
                            #"Renamed Columns"
