table 'patients'
    lineageTag: adbfce0e-13a7-4d83-9ff7-2b1eb593d2dc

    column 'Id (patients)'
        dataType: string
        lineageTag: 0ebb42ce-3306-4827-a974-37bead0482ba
        summarizeBy: none
        sourceColumn: Id (patients)

    column 'Birthdate'
        sourceColumn: Birthdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: 5ab297d8-6ab7-43bc-8a65-c33651b40013
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 5ff805b1-c993-499e-81ae-f361b1b6756b
            defaultHierarchy: LocalDateTable_0f603c49-9a1a-406a-9671-93aa0b0d177a.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Deathdate'
        sourceColumn: Deathdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: 061b995c-362b-459e-90bc-518547160743
        summarizeBy: none

        variation Variation
            isDefault
            relationship: d345aa5d-7d62-45c0-b8ca-172d96261fa0
            defaultHierarchy: LocalDateTable_61bb2b57-0e5a-4ee9-9d8c-3c49d1ab1b85.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Prefix'
        dataType: string
        lineageTag: b025c695-8cf5-40d2-ba01-2dac69466759
        summarizeBy: none
        sourceColumn: Prefix

    column 'First'
        dataType: string
        lineageTag: a52bbfc9-5991-4b2a-9872-40560504a1e4
        summarizeBy: none
        sourceColumn: First

    column 'Last'
        dataType: string
        lineageTag: 4cc3d441-8e1d-42a9-a552-9211f951abd7
        summarizeBy: none
        sourceColumn: Last

    column 'Suffix'
        dataType: string
        lineageTag: 1f70237e-4049-4ebe-942a-d43a02eba137
        summarizeBy: none
        sourceColumn: Suffix

    column 'Maiden'
        dataType: string
        lineageTag: ec0777b8-35b9-477e-9012-69fffd9f1c2a
        summarizeBy: none
        sourceColumn: Maiden

    column 'Marital'
        dataType: string
        lineageTag: 9aae1f32-fe8b-40c3-8707-4447755c6ecf
        summarizeBy: none
        sourceColumn: Marital

    column 'Race'
        dataType: string
        lineageTag: 4c863e19-ea9a-4169-b7b8-9b5d8bdf45bb
        summarizeBy: none
        sourceColumn: Race

    column 'Ethnicity'
        dataType: string
        lineageTag: 0f26d76b-03d1-4a08-803f-45c85c01ba7d
        summarizeBy: none
        sourceColumn: Ethnicity

    column 'Gender'
        dataType: string
        lineageTag: 20e63956-425a-4e0e-bda1-0d70f6b8fff8
        summarizeBy: none
        sourceColumn: Gender

    column 'Birthplace'
        dataType: string
        lineageTag: eefea621-7f78-4d29-a2aa-78dff397081f
        summarizeBy: none
        sourceColumn: Birthplace

    column 'Address'
        dataType: string
        lineageTag: cbc29c67-5570-4748-a10d-c82aa0034a2a
        summarizeBy: none
        sourceColumn: Address

    column 'City'
        dataType: string
        lineageTag: 9c113a4a-416c-4f54-bdbe-7d76841498b6
        summarizeBy: none
        sourceColumn: City

    column 'State'
        dataType: string
        lineageTag: 409fac5e-d45b-41fc-9e9d-52cb7e935d60
        summarizeBy: none
        sourceColumn: State

    column 'County'
        dataType: string
        lineageTag: 71fab98c-3d5d-41a2-b871-e274cf264f9b
        summarizeBy: none
        sourceColumn: County

    column 'ZIP (organizations)'
        dataType: double
        lineageTag: ad94485e-62c6-403f-a45e-dbdc480b9cfa
        summarizeBy: none
        sourceColumn: ZIP (organizations)

    column 'LAT (organizations)'
        dataType: double
        lineageTag: cde2e280-324b-402d-8133-26acfe9fd93f
        summarizeBy: none
        sourceColumn: LAT (organizations)

    column 'LON (organizations)'
        dataType: double
        lineageTag: adefa585-f501-42a5-8ee6-7b7f894ed235
        summarizeBy: none
        sourceColumn: LON (organizations)

    measure 'SUM of Avg Visits per Patient (patients)' =
        SUM('patients'[Avg Visits per Patient])


    measure 'SUM of Visits per Patient (patients)' =
        SUM('patients'[Visits per Patient])


    measure 'Total Patients (LOD)' =
        -- SKIPPED BY USER


    measure 'Visits per Patient' =
        -- SKIPPED BY USER


    measure 'Avg Visits per Patient' =
        -- SKIPPED BY USER


    partition 'patients' = m
        mode: import
        source =
            let Source = GoogleSheets.Contents("https://www.googleapis.com/drive/v3/files/1Sd4bEK0Fm9q7yTVOwI4GdtixeeY8hPkKqpvnI4WdixA/export?mimeType=application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
            #"Navigation 1" = Source{[name="patients", ItemKind="Table"]}[Data],
            #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars=true]),
            #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Id", type text}, {"BIRTHDATE", type date}, {"DEATHDATE", type date}, {"PREFIX", type text}, {"FIRST", type text}, {"LAST", type text}, {"SUFFIX", type text}, {"MAIDEN", type text}, {"MARITAL", type text}, {"RACE", type text}, {"ETHNICITY", type text}, {"GENDER", type text}, {"BIRTHPLACE", type text}, {"ADDRESS", type text}, {"CITY", type text}, {"STATE", type text}, {"COUNTY", type text}, {"ZIP", type number}, {"LAT", type number}, {"LON", type number}}),
            #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"Id", "Id (patients)"}, {"BIRTHDATE", "Birthdate"}, {"DEATHDATE", "Deathdate"}, {"PREFIX", "Prefix"}, {"FIRST", "First"}, {"LAST", "Last"}, {"SUFFIX", "Suffix"}, {"MAIDEN", "Maiden"}, {"MARITAL", "Marital"}, {"RACE", "Race"}, {"ETHNICITY", "Ethnicity"}, {"GENDER", "Gender"}, {"BIRTHPLACE", "Birthplace"}, {"ADDRESS", "Address"}, {"CITY", "City"}, {"STATE", "State"}, {"COUNTY", "County"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}}),
                            #"Renamed Columns" = Table.RenameColumns(#"Renamed Columns", {{"Id", "Id (patients)"}, {"BIRTHDATE", "Birthdate"}, {"DEATHDATE", "Deathdate"}, {"PREFIX", "Prefix"}, {"FIRST", "First"}, {"LAST", "Last"}, {"SUFFIX", "Suffix"}, {"MAIDEN", "Maiden"}, {"MARITAL", "Marital"}, {"RACE", "Race"}, {"ETHNICITY", "Ethnicity"}, {"GENDER", "Gender"}, {"BIRTHPLACE", "Birthplace"}, {"ADDRESS", "Address"}, {"CITY", "City"}, {"STATE", "State"}, {"COUNTY", "County"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}})
                        in
                            #"Renamed Columns"
