table 'patients'
    lineageTag: 3ade8443-d94f-4b42-991e-01c126f94a6e

    column 'Id (patients)'
        dataType: string
        lineageTag: 70f4b02b-6105-4f29-b6bd-0d839bc1f442
        summarizeBy: none
        sourceColumn: Id (patients)

    column 'Birthdate'
        sourceColumn: Birthdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: 1341a25b-b005-4c1d-a3ca-4098059734c4
        summarizeBy: none

        variation Variation
            isDefault
            relationship: c213257f-a6ca-4f8b-a929-5fb1774921a6
            defaultHierarchy: LocalDateTable_cff59237-764e-477c-a885-d78f1450df06.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Deathdate'
        sourceColumn: Deathdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: 5d5518b3-abff-4ab9-9363-335c064fd4fa
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 60c5ad6c-6ef8-45ba-bb8f-2ad2fc244c7b
            defaultHierarchy: LocalDateTable_db51ed16-c31f-4a52-aa45-ae5b1aa6664d.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Prefix'
        dataType: string
        lineageTag: f7f6b22b-c050-4e26-b77d-a8701a2d9bb4
        summarizeBy: none
        sourceColumn: Prefix

    column 'First'
        dataType: string
        lineageTag: 9f56b790-11aa-436a-bd9d-7825d61a1fb3
        summarizeBy: none
        sourceColumn: First

    column 'Last'
        dataType: string
        lineageTag: 038f1b59-278d-4c6c-af15-697e70a6f2de
        summarizeBy: none
        sourceColumn: Last

    column 'Suffix'
        dataType: string
        lineageTag: d0b699eb-bac6-4322-8a1e-2eeb308a4c0b
        summarizeBy: none
        sourceColumn: Suffix

    column 'Maiden'
        dataType: string
        lineageTag: 4f4364d4-9a30-46a9-800d-d001493be949
        summarizeBy: none
        sourceColumn: Maiden

    column 'Marital'
        dataType: string
        lineageTag: 400b99cb-f4dd-45b5-988c-847e44af8cca
        summarizeBy: none
        sourceColumn: Marital

    column 'Race'
        dataType: string
        lineageTag: 934fdd59-eb10-44d0-8fa6-a30e4ff6335a
        summarizeBy: none
        sourceColumn: Race

    column 'Ethnicity'
        dataType: string
        lineageTag: d9dd5735-ecdc-43ca-85bd-eb5e37661db0
        summarizeBy: none
        sourceColumn: Ethnicity

    column 'Gender'
        dataType: string
        lineageTag: 96923187-d118-490c-8a1e-8baccb24404e
        summarizeBy: none
        sourceColumn: Gender

    column 'Birthplace'
        dataType: string
        lineageTag: b07cdecd-898e-4688-8da7-212acd48c612
        summarizeBy: none
        sourceColumn: Birthplace

    column 'Address'
        dataType: string
        lineageTag: 02d66800-1b2c-4d54-94bd-05fa359b0fe1
        summarizeBy: none
        sourceColumn: Address

    column 'City'
        dataType: string
        lineageTag: 3dddd9a8-6a41-466b-9af4-f2180206172f
        summarizeBy: none
        sourceColumn: City

    column 'State'
        dataType: string
        lineageTag: 408862e9-20a1-497c-a157-a7c2d57dd159
        summarizeBy: none
        sourceColumn: State

    column 'County'
        dataType: string
        lineageTag: 4751aa18-67f3-4d4a-b33a-e95f215168f4
        summarizeBy: none
        sourceColumn: County

    column 'ZIP (organizations)'
        dataType: double
        lineageTag: 00208149-b58d-45a8-b13c-bd8538fd56b8
        summarizeBy: none
        sourceColumn: ZIP (organizations)

    column 'LAT (organizations)'
        dataType: double
        lineageTag: 0902e722-fd54-4276-aa1c-6d633ee09273
        summarizeBy: none
        sourceColumn: LAT (organizations)

    column 'LON (organizations)'
        dataType: double
        lineageTag: 98c6e070-3a11-4162-a44a-7013c9881893
        summarizeBy: none
        sourceColumn: LON (organizations)

    measure 'SUM of Avg Visits per Patient (patients)' =
        SUM('patients'[Avg Visits per Patient])


    measure 'SUM of Visits per Patient (patients)' =
        SUM('patients'[Visits per Patient])


    measure 'Total Patients (LOD)' =
        -- SKIPPED BY USER


    measure 'Visits per Patient' =
        -- SKIPPED BY USER


    measure 'Avg Visits per Patient' =
        -- SKIPPED BY USER


    partition 'patients' = m
        mode: import
        source =
            let Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1Sd4bEK0Fm9q7yTVOwI4GdtixeeY8hPkKqpvnI4WdixA"),
            #"Navigation 1" = Source{[name = "patients", ItemKind = "Table"]}[Data],
                            #"Final Renamed Columns" = Table.RenameColumns(#"Navigation 1", {{"Id", "Id (patients)"}, {"BIRTHDATE", "Birthdate"}, {"DEATHDATE", "Deathdate"}, {"PREFIX", "Prefix"}, {"FIRST", "First"}, {"LAST", "Last"}, {"SUFFIX", "Suffix"}, {"MAIDEN", "Maiden"}, {"MARITAL", "Marital"}, {"RACE", "Race"}, {"ETHNICITY", "Ethnicity"}, {"GENDER", "Gender"}, {"BIRTHPLACE", "Birthplace"}, {"ADDRESS", "Address"}, {"CITY", "City"}, {"STATE", "State"}, {"COUNTY", "County"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}})
                        in
                            #"Final Renamed Columns"
