table 'payers'
    lineageTag: 6c5e26e9-7f76-4b10-92c4-38308e40d240

    column 'Id (payers)'
        dataType: string
        lineageTag: 01283fff-cf7f-47d4-beee-1e63932feb7c
        summarizeBy: none
        sourceColumn: Id (payers)

    column 'NAME (payers)'
        dataType: string
        lineageTag: 4f9921de-9fec-4550-a0cc-923071907ec4
        summarizeBy: none
        sourceColumn: NAME (payers)

    column 'ADDRESS (payers)'
        dataType: string
        lineageTag: 95111466-46cb-4a19-900f-90755a72af82
        summarizeBy: none
        sourceColumn: ADDRESS (payers)

    column 'CITY (payers)'
        dataType: string
        lineageTag: 8d9657da-fed8-48d8-98e7-90e9754e1734
        summarizeBy: none
        sourceColumn: CITY (payers)

    column 'State Headquartered'
        dataType: string
        lineageTag: 1fe1a7fa-d40c-488e-b45a-26eab6170b17
        summarizeBy: none
        sourceColumn: State Headquartered

    column 'ZIP (payers)'
        dataType: double
        lineageTag: 0704f46b-dd04-4db2-ac84-d2c07d5f0644
        summarizeBy: none
        sourceColumn: ZIP (payers)

    column 'Phone'
        dataType: string
        lineageTag: d84bc173-b15e-4661-831d-9f4b0da07e4b
        summarizeBy: none
        sourceColumn: Phone

    partition 'payers' = m
        mode: import
        source =
            let Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1NB9uAQnBa6RYGfm5addKbcToYUZJY_5OlBkWxVZRrbU"),
            #"Navigation 1" = Source{[name = "payers", ItemKind = "Table"]}[Data],
                            #"Final Renamed Columns" = Table.RenameColumns(#"Navigation 1", {{"Id", "Id (payers)"}, {"NAME", "NAME (payers)"}, {"ADDRESS", "ADDRESS (payers)"}, {"CITY", "CITY (payers)"}, {"STATE_HEADQUARTERED", "State Headquartered"}, {"ZIP", "ZIP (payers)"}, {"PHONE", "Phone"}})
                        in
                            #"Final Renamed Columns"
