table 'procedures'
    lineageTag: bee85bfb-8dce-4b14-aefd-4fcd6e3998e7

    column 'START (procedures)'
        dataType: string
        lineageTag: de3bbb2e-9653-40ca-8a57-bc57130f3d15
        summarizeBy: none
        sourceColumn: START (procedures)

    column 'STOP (procedures)'
        dataType: string
        lineageTag: e6ef8ae9-3a15-44fd-8db5-2ef1cf570f10
        summarizeBy: none
        sourceColumn: STOP (procedures)

    column 'PATIENT (procedures)'
        dataType: string
        lineageTag: 4152df7e-3a1c-4988-a7d6-660c18d598a1
        summarizeBy: none
        sourceColumn: PATIENT (procedures)

    column 'Encounter'
        dataType: string
        lineageTag: 3d1f77f6-e05a-480c-aa01-dcc4c0757510
        summarizeBy: none
        sourceColumn: Encounter

    column 'CODE (procedures)'
        dataType: double
        lineageTag: e4b5aad0-36bc-4ab2-8cfa-a04eff57fde0
        summarizeBy: none
        sourceColumn: CODE (procedures)

    column 'DESCRIPTION (procedures)'
        dataType: string
        lineageTag: cd6171ac-0ecc-4505-87fd-323fa8dca900
        summarizeBy: none
        sourceColumn: DESCRIPTION (procedures)

    column 'Base Cost'
        dataType: double
        lineageTag: c0f6a290-bfb6-4cba-88f5-fa43cbb41c86
        summarizeBy: none
        sourceColumn: Base Cost

    column 'REASONCODE (procedures)'
        dataType: double
        lineageTag: 89e7589f-3ce7-4faf-aa19-f95933588a46
        summarizeBy: none
        sourceColumn: REASONCODE (procedures)

    column 'REASONDESCRIPTION (procedures)'
        dataType: string
        lineageTag: 7db9c2aa-1add-4880-a28e-b7b145df15c6
        summarizeBy: none
        sourceColumn: REASONDESCRIPTION (procedures)

    column 'DESCRIPTION (procedures) Set' = -- SKIPPED
        dataType: string

        summarizeBy: none

    measure 'Procedure Rank(Top N Procedure Parameter)' =
        -- SKIPPED BY USER


    measure 'Top N Procedures Filter' =
        -- SKIPPED BY USER


    measure 'Selected Metric' =
        -- SKIPPED BY USER


    partition 'procedures' = m
        mode: import
        source =
            let Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/10X1xQHkGidpz_0qYh7o9mxmsRJsOHRB9bNnSKFnUNgo"),
            #"Navigation 1" = Source{[name = "procedures", ItemKind = "Table"]}[Data],
                            #"Final Renamed Columns" = Table.RenameColumns(#"Navigation 1", {{"START", "START (procedures)"}, {"STOP", "STOP (procedures)"}, {"PATIENT", "PATIENT (procedures)"}, {"ENCOUNTER", "Encounter"}, {"CODE", "CODE (procedures)"}, {"DESCRIPTION", "DESCRIPTION (procedures)"}, {"BASE_COST", "Base Cost"}, {"REASONCODE", "REASONCODE (procedures)"}, {"REASONDESCRIPTION", "REASONDESCRIPTION (procedures)"}})
                        in
                            #"Final Renamed Columns"
