table STUDENTS
	lineageTag: d1a3acd2-4342-56b0-b44b-b3185bf3bfbe

	measure 'Total Students' = DISTINCTCOUNT('STUDENTS'[STUDENT_ID])
		formatString: "#,##0.00"
		lineageTag: c19b17d3-ba7e-5a82-ae8a-5c0d746fc86f

	column STUDENT_ID
		dataType: string
		lineageTag: e6072bd5-a33f-5ce6-9f08-8e52fd1a0c8d
		summarizeBy: none
		sourceColumn: STUDENT_ID

		annotation SummarizationSetBy = Automatic

	column FIRST_NAME
		dataType: string
		lineageTag: 1f9f2f13-3375-56a0-b685-039e51b197f5
		summarizeBy: none
		sourceColumn: FIRST_NAME

		annotation SummarizationSetBy = Automatic

	column LAST_NAME
		dataType: string
		lineageTag: 5480308a-6c4d-5d53-86f5-cd0324a816c5
		summarizeBy: none
		sourceColumn: LAST_NAME

		annotation SummarizationSetBy = Automatic

	column GENDER
		dataType: string
		lineageTag: c94a06a9-75f3-5bec-a8b2-b8e5d8c2d87e
		summarizeBy: none
		sourceColumn: GENDER

		annotation SummarizationSetBy = Automatic

	column DOB
		dataType: dateTime
		lineageTag: dfefa085-5358-5930-9edb-6f23d11cf12d
		summarizeBy: none
		sourceColumn: DOB
		formatString: M/D/YYYY

		annotation SummarizationSetBy = Automatic

	column EMAIL
		dataType: string
		lineageTag: ae609570-f4af-5c72-bdc7-14c691ef96ea
		summarizeBy: none
		sourceColumn: EMAIL

		annotation SummarizationSetBy = Automatic

	column Age = FLOOR((Today() - [DOB]) / 365.25, 1)
		dataType: double
		lineageTag: 6f5e3991-b855-559b-b091-7fb1b9e73031
		summarizeBy: sum
		formatString: #,##0.00

		annotation SummarizationSetBy = Automatic

	partition STUDENTS = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("gq37595.ap-southeast-7.aws.snowflakecomputing.com", "COMPUTE_WH"),
				    Db = Source{[Name="LEARNING_ANALYTICS",Kind="Database"]}[Data],
				    Result = Value.NativeQuery(Db, "SELECT ""STUDENT_ID"", ""FIRST_NAME"", ""LAST_NAME"", ""GENDER"", ""DOB"", ""EMAIL"" FROM ""LEARNING_ANALYTICS"".""PUBLIC"".""STUDENTS""", null, [EnableFolding=false]),
				    #"Changed Type" = Table.TransformColumnTypes(Result, {{"STUDENT_ID", type text}, {"FIRST_NAME", type text}, {"LAST_NAME", type text}, {"GENDER", type text}, {"DOB", type date}, {"EMAIL", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table