table COURSES
	lineageTag: aef0d33b-71a4-5d33-acdb-9c8f236a6bb5

	measure 'Average Credits' = AVERAGE('COURSES'[CREDITS])
		formatString: "#,##0.00"
		lineageTag: 6423b155-78fd-5c68-816d-d2a029603e99

	measure 'Total Courses' = DISTINCTCOUNT('COURSES'[COURSE_ID])
		formatString: "#,##0.00"
		lineageTag: c3d88ac9-c95e-50d1-b772-ad5b195a12a3

	measure Avg_CREDITS = AVERAGE('COURSES'[CREDITS])
		formatString: "#,##0.00"
		lineageTag: 7fd6d62a-221d-5895-a5a1-2e92c7343017

	measure Avg_GRADE = AVERAGEX('GRADES', SWITCH('GRADES'[GRADE], "A", 5, "B", 4, "C", 3, "D", 2, "F", 0, BLANK()))
		formatString: "#,##0.00"
		lineageTag: 9008cb4a-00fb-521e-83b5-0ee5299b1113

	measure COUNT_GRADE = COUNT('GRADES'[GRADE])
		formatString: "#,##0"
		lineageTag: d6f3c9e1-04e8-5ae0-8c34-e9543b61527a

	measure 'Count(DISTINCT COURSE_ID)' = DISTINCTCOUNT('COURSES'[COURSE_ID])
		formatString: "#,##0"
		lineageTag: 1608ff6c-5557-5085-b97d-a0f3b7f4c916

	measure Count_ENROLLMENT_ID = COUNT('GRADES'[ENROLLMENT_ID])
		formatString: "#,##0"
		lineageTag: ee1ddc97-eb6c-5d8e-84d5-94333efdb5d7

	measure Count_INSTRUCTOR_ID = COUNT('COURSE_INSTRUCTORS'[INSTRUCTOR_ID])
		formatString: "#,##0"
		lineageTag: 830ee78a-4682-54a7-8508-0057a3ee0a52

	measure Avg_ASSIGNED_DATE = AVERAGE(Today() - [ASSIGNED_DATE])
		formatString: "#,##0.00"
		lineageTag: 38118ab1-f895-56ca-8420-9b4ed5639bfa

	/// TODO (Qlik AGGR() has no direct DAX equivalent): Convert the Qlik expression to DAX manually.
	/// Original Qlik: // Decayed GPA Quality Index, 0–100 // - Uses last 180 days anchored to max grade date // - Falls back to all-time GPA if the 180d window is empty 25 * (   // -------- helpers computed via AGGR (legal in Qlik) --------   // window row count   If(     SUM(       Aggr(         If(           FLOOR(GRADED_DATE_DATE, 1) >= FLOOR(MAX({1} TOTAL GRADED_DATE_DATE), 1) - 179           and FLOOR(GRADED_DATE_DATE, 1) <= FLOOR(MAX({1} TOTAL GRADED_DATE_DATE), 1),           1, 0         ),         'GRADES'[GRADE_ID]       )     ) > 0,     // ---------- WINDOWED, DECAYED GPA (when window has rows) ----------     // numerator     SUM(       Aggr(         If(           FLOOR(GRADED_DATE_DATE, 1) >= FLOOR(MAX({1} TOTAL GRADED_DATE_DATE), 1) - 179           and FLOOR(GRADED_DATE_DATE, 1) <= FLOOR(MAX({1} TOTAL GRADED_DATE_DATE), 1),           // decay weight (half-life 30 days)           Exp(             -0.6931471805599453 *             ( FLOOR(MAX({1} TOTAL GRADED_DATE_DATE), 1) - FLOOR(GRADED_DATE_DATE, 1) ) / 30           )           *           // GPA mapping: numeric % OR letters           If(             IsNum('GRADES'[GRADE]),               RangeMax(0, RangeMin(4,                 If('GRADES'[GRADE]>=90, 4,                 If('GRADES'[GRADE]>=85, 3.7 + ('GRADES'[GRADE]-85)*0.06,                 If('GRADES'[GRADE]>=75, 3.0 + ('GRADES'[GRADE]-75)*0.07,                 If('GRADES'[GRADE]>=65, 2.0 + ('GRADES'[GRADE]-65)*0.10,                 If('GRADES'[GRADE]>=50, 1.0 + ('GRADES'[GRADE]-50)*0.0667, 0))))))),               SWITCH(Match(Upper(Trim('GRADES'[GRADE])),                   "A+","A","A-","B+","B","B-","C+","C","C-","D+","D","D-","F",                   "HD","DI","CR","P","N","PASS","FAIL"                 ), 1, 4.0, 2, 4.0, 3, 3.7, 4, 3.3, 5, 3.0, 6, 2.7, 7, 2.3, 8, 2.0, 9, 1.7, 10, 1.3, 11, 1.0, 12, 0.7, 13, 0.0, 14, 4.0, 15, 3.7, 16, 2.5, 17, 1.0, 18, 0.0, 19, 1.0, 20, 0.0, BLANK())           ),           0         ),         'GRADES'[GRADE_ID]       )     )     /     // denominator (guarded)     MAX(       1e-9,       SUM(         Aggr(           If(             FLOOR(GRADED_DATE_DATE, 1) >= FLOOR(MAX({1} TOTAL GRADED_DATE_DATE), 1) - 179             and FLOOR(GRADED_DATE_DATE, 1) <= FLOOR(MAX({1} TOTAL GRADED_DATE_DATE), 1),             Exp(               -0.6931471805599453 *               ( FLOOR(MAX({1} TOTAL GRADED_DATE_DATE), 1) - FLOOR(GRADED_DATE_DATE, 1) ) / 30             ),             0           ),           'GRADES'[GRADE_ID]         )       )     ),     // ---------- FALLBACK: ALL-TIME GPA (no window rows) ----------     (       SUM( Aggr(         If(           IsNum('GRADES'[GRADE]),             RangeMax(0, RangeMin(4,               If('GRADES'[GRADE]>=90, 4,               If('GRADES'[GRADE]>=85, 3.7 + ('GRADES'[GRADE]-85)*0.06,               If('GRADES'[GRADE]>=75, 3.0 + ('GRADES'[GRADE]-75)*0.07,               If('GRADES'[GRADE]>=65, 2.0 + ('GRADES'[GRADE]-65)*0.10,               If('GRADES'[GRADE]>=50, 1.0 + ('GRADES'[GRADE]-50)*0.0667, 0))))))),             SWITCH(Match(Upper(Trim('GRADES'[GRADE])),                 "A+","A","A-","B+","B","B-","C+","C","C-","D+","D","D-","F",                 "HD","DI","CR","P","N","PASS","FAIL"               ), 1, 4.0, 2, 4.0, 3, 3.7, 4, 3.3, 5, 3.0, 6, 2.7, 7, 2.3, 8, 2.0, 9, 1.7, 10, 1.3, 11, 1.0, 12, 0.7, 13, 0.0, 14, 4.0, 15, 3.7, 16, 2.5, 17, 1.0, 18, 0.0, 19, 1.0, 20, 0.0, BLANK())         ),         'GRADES'[GRADE_ID]       ))        /       MAX(1, SUM( Aggr(1, 'GRADES'[GRADE_ID]) ))     )   ) )
	measure 'Decayed GPA Quality Index' = BLANK()
		formatString: "#,##0"
		lineageTag: 9ebe8f30-4fc4-500d-9d10-0ea617c3acb3

	/// TODO (Qlik $() dollar expansion has no direct DAX equivalent): Convert the Qlik expression to DAX manually.
	/// Original Qlik: CALCULATE(SUM([1]), [Date] >= $(=AddMonths(MonthStart($(vMaxLoaded)),-11))<=$(=MonthEnd($(vMaxLoaded))), CALCULATE(Date=ASSIGNED_DATE_DATE))
	measure Sum_AddMonths = BLANK()
		formatString: "#,##0"
		lineageTag: 4f4a7d05-1f82-50a5-9452-bb38aa922cbb

	measure Count_STUDENT_ID = COUNT('STUDENT_COURSES'[STUDENT_ID])
		formatString: "#,##0"
		lineageTag: c8f23a9d-9b59-576e-b721-882ec4759c3c

	column 'Course Category' = 'COURSES'[CREDITS]
		dataType: double
		lineageTag: 1c5ce9f4-58e9-5d7c-a1b1-7267dec4e135
		summarizeBy: none

	column COURSE_ID
		dataType: string
		lineageTag: b20ab871-1f63-54a3-968d-512304647cc6
		summarizeBy: none
		sourceColumn: COURSE_ID

		annotation SummarizationSetBy = Automatic

	column COURSE_NAME
		dataType: string
		lineageTag: 2a28884c-6ce7-5d88-bc97-72f8f44c511c
		summarizeBy: none
		sourceColumn: COURSE_NAME

		annotation SummarizationSetBy = Automatic

	column DEPARTMENT
		dataType: string
		lineageTag: fec604b5-389c-551e-9b9f-ad4f184d7d93
		summarizeBy: none
		sourceColumn: DEPARTMENT

		annotation SummarizationSetBy = Automatic

	column CREDITS
		dataType: double
		lineageTag: 55d744ab-d716-55db-bfe5-175c2d70b20c
		summarizeBy: sum
		sourceColumn: CREDITS
		formatString: ##############

		annotation SummarizationSetBy = Automatic

	partition COURSES = m
		mode: import
		source =
				let
				    Source = Sql.Database("Learning_Analytics", "LEARNING_ANALYTICS"),
				    Result = Value.NativeQuery(Source, "SELECT ""COURSE_ID"", ""COURSE_NAME"", ""DEPARTMENT"", ""CREDITS"" FROM ""LEARNING_ANALYTICS"".""PUBLIC"".""COURSES""", null, [EnableFolding=false]),
				    #"Changed Type" = Table.TransformColumnTypes(Result, {{"COURSE_ID", type text}, {"COURSE_NAME", type text}, {"DEPARTMENT", type text}, {"CREDITS", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table