table STUDENT_COURSES
	lineageTag: 96c79548-a8d5-57b1-9195-f39b3f903dd9

	column COURSE_ID
		dataType: string
		lineageTag: 62433727-e85f-5d14-ac8a-25a002689bb0
		summarizeBy: none
		sourceColumn: COURSE_ID

		annotation SummarizationSetBy = Automatic

	column STUDENT_ID
		dataType: string
		lineageTag: 3701eeb4-b6c9-562d-9d47-b586098f492c
		summarizeBy: none
		sourceColumn: STUDENT_ID

		annotation SummarizationSetBy = Automatic

	partition STUDENT_COURSES = m
		mode: import
		source =
				let
				    Source = Sql.Database("Learning_Analytics", "LEARNING_ANALYTICS"),
				    Result = Value.NativeQuery(Source, "SELECT ""STUDENT_ID"", ""COURSE_ID"" FROM ""LEARNING_ANALYTICS"".""PUBLIC"".""STUDENT_COURSES""", null, [EnableFolding=false]),
				    #"Changed Type" = Table.TransformColumnTypes(Result, {{"COURSE_ID", type text}, {"STUDENT_ID", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
