table 'APPOINTMENTS'
    lineageTag: b7a22a47-e886-4600-8db9-f6cd96eee329

    column 'Appointment Id'
        dataType: string
        lineageTag: 60d062db-c14b-4ada-b9b6-ce152458572d
        summarizeBy: none
        sourceColumn: Appointment Id

    column 'Patient Id'
        dataType: string
        lineageTag: f66ef111-710f-4561-9ff4-39a26ed7881a
        summarizeBy: none
        sourceColumn: Patient Id

    column 'Doctor Id'
        dataType: string
        lineageTag: 2790fcde-0fb2-40f1-9464-17b5e2387bb5
        summarizeBy: none
        sourceColumn: Doctor Id

    column 'Department'
        dataType: string
        lineageTag: 5127b331-f643-413b-89fe-8705ec7dab25
        summarizeBy: none
        sourceColumn: Department

    column 'Appointment Date'
        sourceColumn: Appointment Date
        dataType: dateTime
        formatString: Long Date
        lineageTag: 905bd9a8-81f5-4e88-bd5d-2785f8af46db
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 593c808e-802e-44c5-a35f-698a51f3eaca
            defaultHierarchy: LocalDateTable_ed37c0d0-a23a-41a7-8489-c890ada82c8e.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Appointment Time'
        sourceColumn: Appointment Time
        dataType: dateTime
        formatString: General Date
        lineageTag: ee1e57b6-147c-43e1-897d-0f92d4c2a161
        summarizeBy: none

        variation Variation
            isDefault
            relationship: d52f4faf-7a06-46cd-9d32-864d384a1600
            defaultHierarchy: LocalDateTable_17a64031-be06-4135-9878-6c8932caf392.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Visit Status'
        dataType: string
        lineageTag: d54af0e9-e6fe-4802-9f20-5164a04fcf5a
        summarizeBy: none
        sourceColumn: Visit Status

    column 'Reason For Visit'
        dataType: string
        lineageTag: 2892da67-229b-4b53-a96e-d9085628a10d
        summarizeBy: none
        sourceColumn: Reason For Visit

    column 'Diagnosis Code'
        dataType: string
        lineageTag: 04c0483c-65da-4dcd-a045-54d767696f1a
        summarizeBy: none
        sourceColumn: Diagnosis Code

    column 'Follow Up Required'
        dataType: boolean
        lineageTag: 808bcd57-e2ab-4116-a204-a02ee9d78acf
        summarizeBy: none
        sourceColumn: Follow Up Required

    column 'DEPARTMENT__Custom_SQL_Query__Set_Category' = IF('APPOINTMENTS'[Department] IN { }, "In", "Out")
        dataType: string

        summarizeBy: none

    column 'Doctor_Id_Set_Category' = IF('APPOINTMENTS'[Doctor Id] IN { }, "In", "Out")
        dataType: string

        summarizeBy: none

    measure 'Before Migration Count' =
        COUNT('APPOINTMENTS'[Doctor Id])


    measure 'Patients' =
        DISTINCTCOUNT('APPOINTMENTS'[Patient Id])


    measure 'Total Appointments' =
        COUNT('APPOINTMENTS'[Appointment Id])


    measure 'Doctor Contribution %' =
        DIVIDE([Doctor Revenue (LOD)], [Department Revenue (LOD)], 0)


    measure 'SUM of Doctor Contribution %' =
        SUM('APPOINTMENTS'[Doctor Contribution %])


    measure 'CNT of Appointment Id' =
        COUNT('APPOINTMENTS'[Appointment Id])


    measure 'SUM of Appointments per Doctor (LOD' =
        SUM('APPOINTMENTS'[Appointments per Doctor (LOD])


    measure 'Appointments per Patient (fixed)' =
        CALCULATE(COUNT('APPOINTMENTS'[Appointment Id]), ALLEXCEPT('APPOINTMENTS', 'APPOINTMENTS'[Patient Id]))


    measure 'Avg Consultation Fee per Patient(Include)' =
        CALCULATE(AVERAGEX(VALUES('APPOINTMENTS'[Patient Id]), CALCULATE(AVERAGE('DOCTORS'[Consultation Fee]))))


    measure 'Appointments per Doctor (LOD' =
        CALCULATE(COUNTX(VALUES('APPOINTMENTS'[Doctor Id]), CALCULATE(COUNT('APPOINTMENTS'[Appointment Id]))))


    measure 'Avg Doctor Bill Count by Specialization (Nested LOD)' =
        CALCULATE(AVERAGEX(VALUES('APPOINTMENTS'[Doctor Id]), [Doctor Bill Count (LOD)]), ALLEXCEPT('DOCTORS', 'DOCTORS'[Specialization]))


    measure 'Doctor Revenue (LOD)' =
        CALCULATE(SUM([COLLECTED_REVENUE]), ALLEXCEPT('APPOINTMENTS', 'APPOINTMENTS'[Department], 'APPOINTMENTS'[Doctor Id]))


    partition 'APPOINTMENTS' = m
        mode: import
        source =
            let
                Source = Snowflake.Databases("mmcuiwz-kl31490.snowflakecomputing.com", "COMPUTE_WH"),
                DB = Source{[Name="CITY_HOSPITAL"]}[Data],
                Schema = DB{[Name="PUBLIC"]}[Data],
                Table = Schema{[Name="APPOINTMENTS"]}[Data],
                #"Changed Type" = Table.TransformColumnTypes(Table, {{"APPOINTMENT_ID", type text}, {"PATIENT_ID", type text}, {"DOCTOR_ID", type text}, {"DEPARTMENT", type text}, {"APPOINTMENT_DATE", type date}, {"APPOINTMENT_TIME", type datetime}, {"VISIT_STATUS", type text}, {"REASON_FOR_VISIT", type text}, {"DIAGNOSIS_CODE", type text}, {"FOLLOW_UP_REQUIRED", type logical}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"APPOINTMENT_ID", "Appointment Id"}, {"PATIENT_ID", "Patient Id"}, {"DOCTOR_ID", "Doctor Id"}, {"DEPARTMENT", "Department"}, {"APPOINTMENT_DATE", "Appointment Date"}, {"APPOINTMENT_TIME", "Appointment Time"}, {"VISIT_STATUS", "Visit Status"}, {"REASON_FOR_VISIT", "Reason For Visit"}, {"DIAGNOSIS_CODE", "Diagnosis Code"}, {"FOLLOW_UP_REQUIRED", "Follow Up Required"}})
            in
                #"Renamed Columns"
