table 'APPOINTMENTS_VISIT_STATUS_FACT'
    lineageTag: 6c3a0549-661d-4946-8348-2d046903de52

    column 'APPOINTMENT_ID (Custom SQL Query1)'
        dataType: string
        lineageTag: f3990f23-1005-4bd6-850f-228168501177
        summarizeBy: none
        sourceColumn: APPOINTMENT_ID (Custom SQL Query1)

    column 'DEPARTMENT (Custom SQL Query1)'
        dataType: string
        lineageTag: dac1abbc-1dae-4cda-94d7-b40c482b74cd
        summarizeBy: none
        sourceColumn: DEPARTMENT (Custom SQL Query1)

    column 'VISIT_STATUS (Custom SQL Query1)'
        dataType: string
        lineageTag: 2680d80a-2b51-4782-a572-88d2b71e4ecd
        summarizeBy: none
        sourceColumn: VISIT_STATUS (Custom SQL Query1)

    column 'VISIT_FLAG'
        dataType: string
        lineageTag: 0141a6bc-0e89-4922-b9b7-8522b49da1a0
        summarizeBy: none
        sourceColumn: VISIT_FLAG

    partition 'APPOINTMENTS_VISIT_STATUS_FACT' = m
        mode: import
        source =
            let Source = Snowflake.Databases("mmcuiwz-kl31490.snowflakecomputing.com", "COMPUTE_WH"),
            DB = Source{[Name="CITY_HOSPITAL"]}[Data],
            APPOINTMENTS_VISIT_STATUS_FACT = Value.NativeQuery(DB, "SELECT APPOINTMENT_ID, DEPARTMENT, VISIT_STATUS, CASE WHEN VISIT_STATUS = 'Completed' THEN 'Completed Visit' ELSE 'Not Completed' END AS visit_flag FROM SNOWFLAKE_LEARNING_DB.RAJANMORYA_LOAD_SAMPLE_DATA_FROM_S3.APPOINTMENTS"),
                            #"Renamed Columns" = Table.RenameColumns(APPOINTMENTS_VISIT_STATUS_FACT, {{"APPOINTMENT_ID", "APPOINTMENT_ID (Custom SQL Query1)"}, {"DEPARTMENT", "DEPARTMENT (Custom SQL Query1)"}, {"VISIT_STATUS", "VISIT_STATUS (Custom SQL Query1)"}})
                        in
                            #"Renamed Columns"
