table 'DOCTORS'
    lineageTag: 86a116a7-6a76-465d-9392-18b38feebb98

    column 'Doctor Id (Doctors)'
        dataType: string
        lineageTag: 85551bcb-ef9a-452d-871b-9efcb0238ce3
        summarizeBy: none
        sourceColumn: Doctor Id (Doctors)

    column 'Full Name'
        dataType: string
        lineageTag: 4b658032-a238-4e8b-bd30-796f2a7a0b61
        summarizeBy: none
        sourceColumn: Full Name

    column 'Specialization'
        dataType: string
        lineageTag: 76c919ed-c043-4c65-9490-4a00ad779bff
        summarizeBy: none
        sourceColumn: Specialization

    column 'Department (Doctors)'
        dataType: string
        lineageTag: 0075f9a4-5200-4c2c-b8b9-5ab0a8a677bf
        summarizeBy: none
        sourceColumn: Department (Doctors)

    column 'Contact Number'
        dataType: string
        lineageTag: be26cdcd-7ea6-4ae1-b48a-0f495c69df9e
        summarizeBy: none
        sourceColumn: Contact Number

    column 'Email Address'
        dataType: string
        lineageTag: da2f34f4-6231-4c75-91df-f8fd6aff4fda
        summarizeBy: none
        sourceColumn: Email Address

    column 'Availability Days'
        dataType: string
        lineageTag: 9e14d176-4d38-46eb-a406-15ba603d59cd
        summarizeBy: none
        sourceColumn: Availability Days

    column 'Consultation Fee'
        dataType: double
        lineageTag: 38fb0255-b2c7-4fac-94cb-f8f97b1c5659
        summarizeBy: none
        sourceColumn: Consultation Fee

    column 'Experience Years'
        dataType: double
        lineageTag: 22c82a0c-c527-43cc-9977-334481683a81
        summarizeBy: none
        sourceColumn: Experience Years

    column 'Registration Number'
        dataType: string
        lineageTag: 0561449b-c4be-47a5-9b8f-a25c6a6b635f
        summarizeBy: none
        sourceColumn: Registration Number

    column 'Experience Level_Cal' = SWITCH( TRUE(), 'DOCTORS'[Experience Years] < 5, "Junior", 'DOCTORS'[Experience Years] <= 10, "Mid-Level", "Senior" )
        dataType: string

        summarizeBy: none

    measure 'Average Consultation Fee' =
        AVERAGE('DOCTORS'[Consultation Fee])


    measure 'Average Doctor Experience (Years)1' =
        AVERAGE('DOCTORS'[Experience Years])


    measure 'Average by Specialization (NESTED)' =
        AVERAGEX(
            VALUES('DOCTORS'[Specialization]),
            AVERAGEX(
                VALUES('BILLS'[Appointment Id (Bills)]),
                CALCULATE(
                    SUM('BILLS'[Total Amount]) - SUM('BILLS'[Insurance Covered])
                )
            )
        )


    measure 'Doctor RLS Filter' =
        SELECTEDVALUE('DOCTORS'[Email Address]) = USERNAME()


    partition 'DOCTORS' = m
        mode: import
        source =
            let
                Source = Snowflake.Databases("mmcuiwz-kl31490.snowflakecomputing.com", "COMPUTE_WH"),
                DB = Source{[Name="CITY_HOSPITAL"]}[Data],
                Schema = DB{[Name="PUBLIC"]}[Data],
                Table = Schema{[Name="DOCTORS"]}[Data],
                #"Changed Type" = Table.TransformColumnTypes(Table, {{"DOCTOR_ID", type text}, {"FULL_NAME", type text}, {"SPECIALIZATION", type text}, {"DEPARTMENT", type text}, {"CONTACT_NUMBER", type text}, {"EMAIL_ADDRESS", type text}, {"AVAILABILITY_DAYS", type text}, {"CONSULTATION_FEE", type number}, {"EXPERIENCE_YEARS", type number}, {"REGISTRATION_NUMBER", type text}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"DOCTOR_ID", "Doctor Id (Doctors)"}, {"FULL_NAME", "Full Name"}, {"SPECIALIZATION", "Specialization"}, {"DEPARTMENT", "Department (Doctors)"}, {"CONTACT_NUMBER", "Contact Number"}, {"EMAIL_ADDRESS", "Email Address"}, {"AVAILABILITY_DAYS", "Availability Days"}, {"CONSULTATION_FEE", "Consultation Fee"}, {"EXPERIENCE_YEARS", "Experience Years"}, {"REGISTRATION_NUMBER", "Registration Number"}})
            in
                #"Renamed Columns"
