table 'encounters'
    lineageTag: 968dcb64-943a-4fb4-a88e-819b62f86274

    column 'Id'
        dataType: string
        lineageTag: 4ee81368-6fd3-4bd2-ade6-3fd96b517bc5
        summarizeBy: none
        sourceColumn: Id

    column 'Start'
        dataType: string
        lineageTag: eb771608-eef4-403a-8382-2cd39cae3b8b
        summarizeBy: none
        sourceColumn: Start

    column 'Stop'
        dataType: string
        lineageTag: e104441d-ce85-4bb4-98c9-c80e25bf2454
        summarizeBy: none
        sourceColumn: Stop

    column 'Patient'
        dataType: string
        lineageTag: 600bfa8b-2e88-4077-831c-3d8979a30c0c
        summarizeBy: none
        sourceColumn: Patient

    column 'Organization'
        dataType: string
        lineageTag: 3b45a2b3-1458-40c6-bbc7-00c1bd9551ec
        summarizeBy: none
        sourceColumn: Organization

    column 'Payer'
        dataType: string
        lineageTag: 4030518a-4be9-4eaf-97a0-91427ba9ad98
        summarizeBy: none
        sourceColumn: Payer

    column 'Encounterclass'
        dataType: string
        lineageTag: cf054aa9-1c21-4f9a-8b3b-d805d9701d03
        summarizeBy: none
        sourceColumn: Encounterclass

    column 'Code'
        dataType: double
        lineageTag: 510f93ff-41e7-45ed-9d93-c03705f41636
        summarizeBy: none
        sourceColumn: Code

    column 'Description'
        dataType: string
        lineageTag: 58971fb3-628f-4dbf-a480-2147d902b474
        summarizeBy: none
        sourceColumn: Description

    column 'Base Encounter Cost'
        dataType: double
        lineageTag: 29ab656a-01d1-452a-8f3d-29607e3e3fbb
        summarizeBy: none
        sourceColumn: Base Encounter Cost

    column 'Total Claim Cost'
        dataType: double
        lineageTag: f13f39f2-531a-4c75-a258-8365bd9fda8b
        summarizeBy: none
        sourceColumn: Total Claim Cost

    column 'Payer Coverage'
        dataType: double
        lineageTag: c6f39f1f-609e-4776-bec2-3237eb288ee6
        summarizeBy: none
        sourceColumn: Payer Coverage

    column 'Reasoncode'
        dataType: double
        lineageTag: c3f33122-5d15-4dd0-a1ca-cd416c1d0781
        summarizeBy: none
        sourceColumn: Reasoncode

    column 'Reasondescription'
        dataType: string
        lineageTag: 6f2dadcf-4459-4402-824f-347f4368a2b9
        summarizeBy: none
        sourceColumn: Reasondescription

    column 'Encounter Start Date' = -- SKIPPED BY USER
        dataType: string

        summarizeBy: none

    measure 'Patient Visits Rank (Top N Patients)' =
        -- SKIPPED BY USER


    measure 'Top N Patients Measure' =
        -- SKIPPED BY USER


    measure 'Visits % Contribution (LOD)' =
        -- SKIPPED BY USER


    measure 'CNT of Id' =
        COUNT('encounters'[Id])


    measure 'Total Visits' =
        COUNT('encounters'[Id])


    measure 'SUM of Base Encounter Cost' =
        SUM('encounters'[Base Encounter Cost])


    measure 'Total Procedures (LOD)' =
        -- SKIPPED BY USER


    measure 'Total Visits (LOD)' =
        -- SKIPPED BY USER


    partition 'encounters' = m
        mode: import
        source =
            let Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1Sd4bEK0Fm9q7yTVOwI4GdtixeeY8hPkKqpvnI4WdixA"),
            #"Navigation 1" = Source{[name="encounters", ItemKind="Table"]}[Data],
            #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars=true]),
            #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Id", type text}, {"START", type text}, {"STOP", type text}, {"PATIENT", type text}, {"ORGANIZATION", type text}, {"PAYER", type text}, {"ENCOUNTERCLASS", type text}, {"CODE", type number}, {"DESCRIPTION", type text}, {"BASE_ENCOUNTER_COST", type number}, {"TOTAL_CLAIM_COST", type number}, {"PAYER_COVERAGE", type number}, {"REASONCODE", type number}, {"REASONDESCRIPTION", type text}}),
            #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"START", "Start"}, {"STOP", "Stop"}, {"PATIENT", "Patient"}, {"ORGANIZATION", "Organization"}, {"PAYER", "Payer"}, {"ENCOUNTERCLASS", "Encounterclass"}, {"CODE", "Code"}, {"DESCRIPTION", "Description"}, {"BASE_ENCOUNTER_COST", "Base Encounter Cost"}, {"TOTAL_CLAIM_COST", "Total Claim Cost"}, {"PAYER_COVERAGE", "Payer Coverage"}, {"REASONCODE", "Reasoncode"}, {"REASONDESCRIPTION", "Reasondescription"}}),
                            #"Final Renamed Columns" = Table.RenameColumns(#"Renamed Columns", {{"START", "Start"}, {"STOP", "Stop"}, {"PATIENT", "Patient"}, {"ORGANIZATION", "Organization"}, {"PAYER", "Payer"}, {"ENCOUNTERCLASS", "Encounterclass"}, {"CODE", "Code"}, {"DESCRIPTION", "Description"}, {"BASE_ENCOUNTER_COST", "Base Encounter Cost"}, {"TOTAL_CLAIM_COST", "Total Claim Cost"}, {"PAYER_COVERAGE", "Payer Coverage"}, {"REASONCODE", "Reasoncode"}, {"REASONDESCRIPTION", "Reasondescription"}})
                        in
                            #"Final Renamed Columns"
