table 'patients'
    lineageTag: be3da846-6e93-4211-b74f-97f63d9e9cd2

    column 'Id (patients)'
        dataType: string
        lineageTag: c9e7a0bd-6cfc-4040-a0d8-a0decd0a7cb0
        summarizeBy: none
        sourceColumn: Id (patients)

    column 'Birthdate'
        sourceColumn: Birthdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: 4ed53901-bcdd-4bee-bf19-892938705913
        summarizeBy: none

        variation Variation
            isDefault
            relationship: c284a198-3936-4a56-8ba4-926513b17639
            defaultHierarchy: LocalDateTable_6f418c9d-43c5-40ef-963b-ec233e5b5d2f.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Deathdate'
        sourceColumn: Deathdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: 573918da-af62-403c-9acf-c479c7ecbdfa
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 6570a6f2-935f-4edc-ab8d-f889db87d3cc
            defaultHierarchy: LocalDateTable_df8bbd1f-d3a3-4241-a1d2-2026a90bfa2f.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Prefix'
        dataType: string
        lineageTag: cf7cab4b-acf4-4a83-b8c6-bc8cfc3d368e
        summarizeBy: none
        sourceColumn: Prefix

    column 'First'
        dataType: string
        lineageTag: a8bd1e27-36f4-4d47-afa3-b06b4f82d2d4
        summarizeBy: none
        sourceColumn: First

    column 'Last'
        dataType: string
        lineageTag: a3c915a7-f57f-467f-9613-3dc843793956
        summarizeBy: none
        sourceColumn: Last

    column 'Suffix'
        dataType: string
        lineageTag: be9df301-bc8d-4332-a697-a7deadda155c
        summarizeBy: none
        sourceColumn: Suffix

    column 'Maiden'
        dataType: string
        lineageTag: 2c0a1a19-f207-4ecb-a7a5-ff5e60ea8a0a
        summarizeBy: none
        sourceColumn: Maiden

    column 'Marital'
        dataType: string
        lineageTag: d8e07e7c-7309-44f1-b8ba-bded50e45385
        summarizeBy: none
        sourceColumn: Marital

    column 'Race'
        dataType: string
        lineageTag: ecde576d-24b9-4f83-9ab5-82225eee9321
        summarizeBy: none
        sourceColumn: Race

    column 'Ethnicity'
        dataType: string
        lineageTag: af7469fe-533d-4987-8deb-829407189f98
        summarizeBy: none
        sourceColumn: Ethnicity

    column 'Gender'
        dataType: string
        lineageTag: 03b24854-2a61-44c2-b727-51d7bed8cbe6
        summarizeBy: none
        sourceColumn: Gender

    column 'Birthplace'
        dataType: string
        lineageTag: 89830d9f-44df-4c03-8ad3-741683e25f0d
        summarizeBy: none
        sourceColumn: Birthplace

    column 'Address'
        dataType: string
        lineageTag: 84101703-b5e0-4b2f-ad45-adef9bbb7bbf
        summarizeBy: none
        sourceColumn: Address

    column 'City'
        dataType: string
        lineageTag: 98c97af9-6e57-47a6-91ca-23b6dace737d
        summarizeBy: none
        sourceColumn: City

    column 'State'
        dataType: string
        lineageTag: 73028aa5-a7f1-449d-bd5a-ec7e7daf7f26
        summarizeBy: none
        sourceColumn: State

    column 'County'
        dataType: string
        lineageTag: 5f6fed7f-a652-489f-8266-bd18081195fc
        summarizeBy: none
        sourceColumn: County

    column 'ZIP (organizations)'
        dataType: double
        lineageTag: 28ebc05c-b987-4d74-ba3c-7288daaceaf8
        summarizeBy: none
        sourceColumn: ZIP (organizations)

    column 'LAT (organizations)'
        dataType: double
        lineageTag: 0b857c92-0626-470e-bfe4-e7c5dcd6f18d
        summarizeBy: none
        sourceColumn: LAT (organizations)

    column 'LON (organizations)'
        dataType: double
        lineageTag: e02372a3-0652-49a4-857f-517dfbae5c73
        summarizeBy: none
        sourceColumn: LON (organizations)

    measure 'SUM of Avg Visits per Patient (patients)' =
        SUM('patients'[Avg Visits per Patient])


    measure 'SUM of Visits per Patient (patients)' =
        SUM('patients'[Visits per Patient])


    measure 'Total Patients (LOD)' =
        -- SKIPPED BY USER


    measure 'Visits per Patient' =
        -- SKIPPED BY USER


    measure 'Avg Visits per Patient' =
        -- SKIPPED BY USER


    partition 'patients' = m
        mode: import
        source =
            let Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1Sd4bEK0Fm9q7yTVOwI4GdtixeeY8hPkKqpvnI4WdixA"),
            #"Navigation 1" = Source{[name="patients", ItemKind="Table"]}[Data],
            #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars=true]),
            #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Id", type text}, {"BIRTHDATE", type date}, {"DEATHDATE", type date}, {"PREFIX", type text}, {"FIRST", type text}, {"LAST", type text}, {"SUFFIX", type text}, {"MAIDEN", type text}, {"MARITAL", type text}, {"RACE", type text}, {"ETHNICITY", type text}, {"GENDER", type text}, {"BIRTHPLACE", type text}, {"ADDRESS", type text}, {"CITY", type text}, {"STATE", type text}, {"COUNTY", type text}, {"ZIP", type number}, {"LAT", type number}, {"LON", type number}}),
            #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"Id", "Id (patients)"}, {"BIRTHDATE", "Birthdate"}, {"DEATHDATE", "Deathdate"}, {"PREFIX", "Prefix"}, {"FIRST", "First"}, {"LAST", "Last"}, {"SUFFIX", "Suffix"}, {"MAIDEN", "Maiden"}, {"MARITAL", "Marital"}, {"RACE", "Race"}, {"ETHNICITY", "Ethnicity"}, {"GENDER", "Gender"}, {"BIRTHPLACE", "Birthplace"}, {"ADDRESS", "Address"}, {"CITY", "City"}, {"STATE", "State"}, {"COUNTY", "County"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}}),
                            #"Final Renamed Columns" = Table.RenameColumns(#"Renamed Columns", {{"Id", "Id (patients)"}, {"BIRTHDATE", "Birthdate"}, {"DEATHDATE", "Deathdate"}, {"PREFIX", "Prefix"}, {"FIRST", "First"}, {"LAST", "Last"}, {"SUFFIX", "Suffix"}, {"MAIDEN", "Maiden"}, {"MARITAL", "Marital"}, {"RACE", "Race"}, {"ETHNICITY", "Ethnicity"}, {"GENDER", "Gender"}, {"BIRTHPLACE", "Birthplace"}, {"ADDRESS", "Address"}, {"CITY", "City"}, {"STATE", "State"}, {"COUNTY", "County"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}})
                        in
                            #"Final Renamed Columns"
