table STUDENTS
	lineageTag: d1a3acd2-4342-56b0-b44b-b3185bf3bfbe

	measure 'Total Students' = COUNT('STUDENT_COURSES'[STUDENT_ID])
		formatString: "#,##0.00"
		lineageTag: c19b17d3-ba7e-5a82-ae8a-5c0d746fc86f

	column Age = DATEDIFF('STUDENTS'[DOB], TODAY(), YEAR)
		dataType: double
		lineageTag: a89ef938-4bc2-583a-a8e3-e461041a0043
		summarizeBy: none

	column STUDENT_ID = BLANK()
		dataType: string
		lineageTag: e6072bd5-a33f-5ce6-9f08-8e52fd1a0c8d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column STUDENTS_FIRST_NAME = BLANK()
		dataType: string
		lineageTag: a15bf7d0-fe61-50c1-93e4-795dd11e4e01
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column STUDENTS_LAST_NAME = BLANK()
		dataType: string
		lineageTag: 802539dd-a4c4-5b6b-97c7-d3a8ccf26442
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column GENDER = BLANK()
		dataType: string
		lineageTag: c94a06a9-75f3-5bec-a8b2-b8e5d8c2d87e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column DOB = BLANK()
		dataType: dateTime
		lineageTag: dfefa085-5358-5930-9edb-6f23d11cf12d
		summarizeBy: none
		formatString: M/D/YYYY

		annotation SummarizationSetBy = Automatic

	column STUDENTS_EMAIL = BLANK()
		dataType: string
		lineageTag: 1a1a35c5-d020-5fbc-b10a-865bf6b81a8a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition STUDENTS = m
		mode: import
		source =
				let
				    Source = Sql.Database("Learning_Analytics", "LEARNING_ANALYTICS"),
				    Result = Value.NativeQuery(Source, "SELECT ""STUDENT_ID"", ""FIRST_NAME"", ""LAST_NAME"", ""GENDER"", ""DOB"", ""EMAIL"" FROM ""LEARNING_ANALYTICS"".""PUBLIC"".""STUDENTS""", null, [EnableFolding=false]),
				    #"Renamed Columns" = Table.RenameColumns(Result, {{"FIRST_NAME", "FIRST_NAME"}, {"LAST_NAME", "LAST_NAME"}, {"EMAIL", "EMAIL"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"STUDENT_ID", type text}, {"STUDENTS_FIRST_NAME", type text}, {"STUDENTS_LAST_NAME", type text}, {"GENDER", type text}, {"DOB", type datetime}, {"STUDENTS_EMAIL", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table