table 'encounters'
    lineageTag: 500e0418-ae5a-4a10-8696-cb4d4b376feb

    column 'Id'
        dataType: string
        lineageTag: 7ca2608b-c04d-45c2-b74b-c21e74d6ba7d
        summarizeBy: none
        sourceColumn: Id

    column 'Start'
        dataType: string
        lineageTag: 320c9c9b-aaf1-4f00-bfa7-40853ead5d38
        summarizeBy: none
        sourceColumn: Start

    column 'Stop'
        dataType: string
        lineageTag: 65d68540-2e86-401c-8f56-fb944e9ebe27
        summarizeBy: none
        sourceColumn: Stop

    column 'Patient'
        dataType: string
        lineageTag: cfb022dc-9b13-4333-a6f2-0227cc286814
        summarizeBy: none
        sourceColumn: Patient

    column 'Organization'
        dataType: string
        lineageTag: 1b11722a-5bb1-4ac4-9b20-e01a1e7774b8
        summarizeBy: none
        sourceColumn: Organization

    column 'Payer'
        dataType: string
        lineageTag: 29d8afb3-1c00-45e5-94ee-04c833c8a07f
        summarizeBy: none
        sourceColumn: Payer

    column 'Encounterclass'
        dataType: string
        lineageTag: 51059eb0-1083-49ad-8ef4-16a4f289f5f9
        summarizeBy: none
        sourceColumn: Encounterclass

    column 'Code'
        dataType: double
        lineageTag: 16623f46-063d-4a71-a679-cd5fc647cae8
        summarizeBy: none
        sourceColumn: Code

    column 'Description'
        dataType: string
        lineageTag: 7ab3ba72-ec2c-400f-86ff-9e271b560221
        summarizeBy: none
        sourceColumn: Description

    column 'Base Encounter Cost'
        dataType: double
        lineageTag: a0f20ac2-cff4-4249-9b3e-8a09d56b0557
        summarizeBy: none
        sourceColumn: Base Encounter Cost

    column 'Total Claim Cost'
        dataType: double
        lineageTag: 336fbe42-0595-4003-8e5c-32b8724163f1
        summarizeBy: none
        sourceColumn: Total Claim Cost

    column 'Payer Coverage'
        dataType: double
        lineageTag: b54337b9-7ac4-4eaa-ad77-9a6268964ae5
        summarizeBy: none
        sourceColumn: Payer Coverage

    column 'Reasoncode'
        dataType: double
        lineageTag: d293776b-00e9-4de7-a87f-c55714f02c9f
        summarizeBy: none
        sourceColumn: Reasoncode

    column 'Reasondescription'
        dataType: string
        lineageTag: d3a02121-ea17-4f10-809f-8f659dddf9fe
        summarizeBy: none
        sourceColumn: Reasondescription

    column 'Encounter Start Date' = -- SKIPPED BY USER
        dataType: string

        summarizeBy: none

    measure 'Patient Visits Rank (Top N Patients)' =
        -- SKIPPED BY USER


    measure 'Top N Patients' =
        -- SKIPPED BY USER


    measure 'Visits % Contribution (LOD)' =
        -- SKIPPED BY USER


    measure 'CNT of Id' =
        COUNT('encounters'[Id])


    measure 'Total Visits' =
        COUNT('encounters'[Id])


    measure 'SUM of Base Encounter Cost' =
        SUM('encounters'[Base Encounter Cost])


    measure 'Total Procedures (LOD)' =
        -- SKIPPED BY USER


    measure 'Total Visits (LOD)' =
        -- SKIPPED BY USER


    partition 'encounters' = m
        mode: import
        source =
            let
                Source = GoogleSheets.Contents("None"),
                #"Navigation 1" = Source{[name = "encounters", ItemKind = "Table"]}[Data],
                #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
                #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Id", type text}, {"START", type text}, {"STOP", type text}, {"PATIENT", type text}, {"ORGANIZATION", type text}, {"PAYER", type text}, {"ENCOUNTERCLASS", type text}, {"CODE", type number}, {"DESCRIPTION", type text}, {"BASE_ENCOUNTER_COST", type number}, {"TOTAL_CLAIM_COST", type number}, {"PAYER_COVERAGE", type number}, {"REASONCODE", type number}, {"REASONDESCRIPTION", type text}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"START", "Start"}, {"STOP", "Stop"}, {"PATIENT", "Patient"}, {"ORGANIZATION", "Organization"}, {"PAYER", "Payer"}, {"ENCOUNTERCLASS", "Encounterclass"}, {"CODE", "Code"}, {"DESCRIPTION", "Description"}, {"BASE_ENCOUNTER_COST", "Base Encounter Cost"}, {"TOTAL_CLAIM_COST", "Total Claim Cost"}, {"PAYER_COVERAGE", "Payer Coverage"}, {"REASONCODE", "Reasoncode"}, {"REASONDESCRIPTION", "Reasondescription"}})
            in
                #"Renamed Columns"
