table 'organizations'
    lineageTag: a705f300-c8f0-4089-aad9-361993248935

    column 'Id (organizations)'
        dataType: string
        lineageTag: c220b66b-d3ea-40c9-9272-08d2216b7ff4
        summarizeBy: none
        sourceColumn: Id (organizations)

    column 'Name'
        dataType: string
        lineageTag: 2aff8108-0731-44ad-b196-fa74a25e57b8
        summarizeBy: none
        sourceColumn: Name

    column 'ADDRESS (organizations)'
        dataType: string
        lineageTag: 9cc0f41a-d762-418a-ba93-57c6af92ecee
        summarizeBy: none
        sourceColumn: ADDRESS (organizations)

    column 'CITY (organizations)'
        dataType: string
        lineageTag: 4b1997d6-e611-4aa8-8f5a-c2909adeae15
        summarizeBy: none
        sourceColumn: CITY (organizations)

    column 'STATE (organizations)'
        dataType: string
        lineageTag: 1219ca89-1893-4ea2-b1a5-e5b92f9b706c
        summarizeBy: none
        sourceColumn: STATE (organizations)

    column 'ZIP (organizations)'
        dataType: double
        lineageTag: 81225271-a5fa-4760-9784-fb6fb401d5b6
        summarizeBy: none
        sourceColumn: ZIP (organizations)

    column 'LAT (organizations)'
        dataType: double
        lineageTag: a8a2563f-6f7e-4b12-9ff9-10facd2ada67
        summarizeBy: none
        sourceColumn: LAT (organizations)

    column 'LON (organizations)'
        dataType: double
        lineageTag: e48d11df-334d-4394-b28b-d4795f312776
        summarizeBy: none
        sourceColumn: LON (organizations)

    column 'Username' = -- SKIPPED BY USER
        dataType: string

        summarizeBy: none

    measure 'RLS - Organization Access' =
        -- SKIPPED BY USER


    partition 'organizations' = m
        mode: import
        source =
            let
                Source = GoogleSheets.Contents("None"),
                #"Navigation 1" = Source{[name = "organizations", ItemKind = "Table"]}[Data],
                #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
                #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Id", type text}, {"NAME", type text}, {"ADDRESS", type text}, {"CITY", type text}, {"STATE", type text}, {"ZIP", type number}, {"LAT", type number}, {"LON", type number}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"Id", "Id (organizations)"}, {"NAME", "Name"}, {"ADDRESS", "ADDRESS (organizations)"}, {"CITY", "CITY (organizations)"}, {"STATE", "STATE (organizations)"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}})
            in
                #"Renamed Columns"
