table 'patients'
    lineageTag: 7644b2a1-b4de-4c5b-995d-c466a6bda1d2

    column 'Id (patients)'
        dataType: string
        lineageTag: 38c63de8-d05b-4808-a4dd-72ead481d3f6
        summarizeBy: none
        sourceColumn: Id (patients)

    column 'Birthdate'
        sourceColumn: Birthdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: a98c2787-2123-462d-9f30-50772084c8bb
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 8065c539-ca2c-4326-8850-0eec034ad4c3
            defaultHierarchy: LocalDateTable_fc627e6a-ac22-46e5-ad2d-c6b4ab66b8d9.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Deathdate'
        sourceColumn: Deathdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: fcdffed2-704b-4113-90d1-1297fa4f4f7a
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 054c02dc-bb39-4115-a62f-69e10f6efd8a
            defaultHierarchy: LocalDateTable_f846a56a-ea7d-435c-8d9f-75c5e1723053.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Prefix'
        dataType: string
        lineageTag: 7c3110c1-04d2-4c81-b406-ff4c239ad42d
        summarizeBy: none
        sourceColumn: Prefix

    column 'First'
        dataType: string
        lineageTag: 81557f25-a658-4faf-b4b6-3c060adc27cb
        summarizeBy: none
        sourceColumn: First

    column 'Last'
        dataType: string
        lineageTag: 604336a3-abd8-429a-a8b5-fcad1efc13cd
        summarizeBy: none
        sourceColumn: Last

    column 'Suffix'
        dataType: string
        lineageTag: 34e82464-3849-4bdb-ad39-8952e1975c6f
        summarizeBy: none
        sourceColumn: Suffix

    column 'Maiden'
        dataType: string
        lineageTag: 941f444e-2920-400c-a039-12f159dc1ec9
        summarizeBy: none
        sourceColumn: Maiden

    column 'Marital'
        dataType: string
        lineageTag: 1f4b8651-abd1-4ba2-8957-df0c103f26bd
        summarizeBy: none
        sourceColumn: Marital

    column 'Race'
        dataType: string
        lineageTag: 8f0cfb5d-c5fe-4208-95ba-2991c5b1c135
        summarizeBy: none
        sourceColumn: Race

    column 'Ethnicity'
        dataType: string
        lineageTag: 89d22ad9-0783-48b1-9f14-e77871741edd
        summarizeBy: none
        sourceColumn: Ethnicity

    column 'Gender'
        dataType: string
        lineageTag: 838c7b9f-414a-4947-95ad-4659f7686f27
        summarizeBy: none
        sourceColumn: Gender

    column 'Birthplace'
        dataType: string
        lineageTag: 6ae19f5a-5de7-45ea-b914-7178c2368b5b
        summarizeBy: none
        sourceColumn: Birthplace

    column 'Address'
        dataType: string
        lineageTag: 30213bc6-870a-41fe-be20-daa9b75e2b52
        summarizeBy: none
        sourceColumn: Address

    column 'City'
        dataType: string
        lineageTag: 63d8b9ae-43a6-47b7-b5c5-564d90fd9f5c
        summarizeBy: none
        sourceColumn: City

    column 'State'
        dataType: string
        lineageTag: 1c63048f-76bb-4d3d-8c50-55458cdff5cf
        summarizeBy: none
        sourceColumn: State

    column 'County'
        dataType: string
        lineageTag: 6b408efe-7fdf-4d7d-9646-42fe0e5baf9f
        summarizeBy: none
        sourceColumn: County

    column 'ZIP (organizations)'
        dataType: double
        lineageTag: 1cae54f0-c37f-4361-96b7-bd89e45c5e55
        summarizeBy: none
        sourceColumn: ZIP (organizations)

    column 'LAT (organizations)'
        dataType: double
        lineageTag: 4947c3e9-995b-4251-995d-7a7a0cda1268
        summarizeBy: none
        sourceColumn: LAT (organizations)

    column 'LON (organizations)'
        dataType: double
        lineageTag: cab30f45-05da-47b2-8b55-fc5d9be773be
        summarizeBy: none
        sourceColumn: LON (organizations)

    measure 'SUM of Avg Visits per Patient (patients)' =
        SUM('patients'[Avg Visits per Patient])


    measure 'SUM of Visits per Patient (patients)' =
        SUM('patients'[Visits per Patient])


    measure 'Total Patients (LOD)' =
        -- SKIPPED BY USER


    measure 'Visits per Patient' =
        -- SKIPPED BY USER


    measure 'Avg Visits per Patient' =
        -- SKIPPED BY USER


    partition 'patients' = m
        mode: import
        source =
            let
                Source = GoogleSheets.Contents("None"),
                #"Navigation 1" = Source{[name = "patients", ItemKind = "Table"]}[Data],
                #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
                #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Id", type text}, {"BIRTHDATE", type date}, {"DEATHDATE", type date}, {"PREFIX", type text}, {"FIRST", type text}, {"LAST", type text}, {"SUFFIX", type text}, {"MAIDEN", type text}, {"MARITAL", type text}, {"RACE", type text}, {"ETHNICITY", type text}, {"GENDER", type text}, {"BIRTHPLACE", type text}, {"ADDRESS", type text}, {"CITY", type text}, {"STATE", type text}, {"COUNTY", type text}, {"ZIP", type number}, {"LAT", type number}, {"LON", type number}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"Id", "Id (patients)"}, {"BIRTHDATE", "Birthdate"}, {"DEATHDATE", "Deathdate"}, {"PREFIX", "Prefix"}, {"FIRST", "First"}, {"LAST", "Last"}, {"SUFFIX", "Suffix"}, {"MAIDEN", "Maiden"}, {"MARITAL", "Marital"}, {"RACE", "Race"}, {"ETHNICITY", "Ethnicity"}, {"GENDER", "Gender"}, {"BIRTHPLACE", "Birthplace"}, {"ADDRESS", "Address"}, {"CITY", "City"}, {"STATE", "State"}, {"COUNTY", "County"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}})
            in
                #"Renamed Columns"
