table 'encounters'
    lineageTag: bf248b34-3096-4b4b-8ae2-65ec59090ad4

    column 'Id'
        dataType: string
        lineageTag: 79d422b7-03bd-48f0-9546-2df214fa28b1
        summarizeBy: none
        sourceColumn: Id

    column 'Start'
        dataType: string
        lineageTag: 479a7123-801f-42fd-b426-4ca7278f182c
        summarizeBy: none
        sourceColumn: Start

    column 'Stop'
        dataType: string
        lineageTag: 50cd9da2-6dc9-47d3-a0e1-e9395e11b861
        summarizeBy: none
        sourceColumn: Stop

    column 'Patient'
        dataType: string
        lineageTag: fb416461-19d1-49b1-a8a6-8ec384d1f232
        summarizeBy: none
        sourceColumn: Patient

    column 'Organization'
        dataType: string
        lineageTag: 0427bf0d-1bd8-4acf-b2ca-109e334ff413
        summarizeBy: none
        sourceColumn: Organization

    column 'Payer'
        dataType: string
        lineageTag: 75e151c1-8472-456a-ba59-2b7af1c12849
        summarizeBy: none
        sourceColumn: Payer

    column 'Encounterclass'
        dataType: string
        lineageTag: 8b50ff95-bf2e-4779-a9ac-2d5c947ac035
        summarizeBy: none
        sourceColumn: Encounterclass

    column 'Code'
        dataType: double
        lineageTag: 65862adf-6751-4c4e-a0c9-21d6b245bdcb
        summarizeBy: none
        sourceColumn: Code

    column 'Description'
        dataType: string
        lineageTag: 55544453-9598-4304-a554-bab5663f051f
        summarizeBy: none
        sourceColumn: Description

    column 'Base Encounter Cost'
        dataType: double
        lineageTag: d11230fb-ade5-4c85-a018-2ded3749c2ac
        summarizeBy: none
        sourceColumn: Base Encounter Cost

    column 'Total Claim Cost'
        dataType: double
        lineageTag: ffe00da2-538f-4771-8c79-0a6ac8d6dc40
        summarizeBy: none
        sourceColumn: Total Claim Cost

    column 'Payer Coverage'
        dataType: double
        lineageTag: 53ba8246-d503-40d0-be1b-c723c42e91f0
        summarizeBy: none
        sourceColumn: Payer Coverage

    column 'Reasoncode'
        dataType: double
        lineageTag: 0403844b-33c5-405d-b9e5-c3260603cf9c
        summarizeBy: none
        sourceColumn: Reasoncode

    column 'Reasondescription'
        dataType: string
        lineageTag: e3240c18-5a9e-4f7c-a292-3e73d266f0fd
        summarizeBy: none
        sourceColumn: Reasondescription

    column 'Encounter Start Date' = -- SKIPPED BY USER
        dataType: string

        summarizeBy: none

    measure 'Patient Visits Rank (Top N Patients)' =
        -- SKIPPED BY USER


    measure 'Top N Patients Measure' =
        -- SKIPPED BY USER


    measure 'Visits % Contribution (LOD)' =
        -- SKIPPED BY USER


    measure 'CNT of Id' =
        COUNT('encounters'[Id])


    measure 'Total Visits' =
        COUNT('encounters'[Id])


    measure 'SUM of Base Encounter Cost' =
        SUM('encounters'[Base Encounter Cost])


    measure 'Total Procedures (LOD)' =
        -- SKIPPED BY USER


    measure 'Total Visits (LOD)' =
        -- SKIPPED BY USER


    partition 'encounters' = m
        mode: import
        source =
            let Source = GoogleSheets.Contents("https://www.googleapis.com/drive/v3/files/1Sd4bEK0Fm9q7yTVOwI4GdtixeeY8hPkKqpvnI4WdixA/export?mimeType=application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
            #"Navigation 1" = Source{[name="encounters", ItemKind="Table"]}[Data],
            #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars=true]),
            #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Id", type text}, {"START", type text}, {"STOP", type text}, {"PATIENT", type text}, {"ORGANIZATION", type text}, {"PAYER", type text}, {"ENCOUNTERCLASS", type text}, {"CODE", type number}, {"DESCRIPTION", type text}, {"BASE_ENCOUNTER_COST", type number}, {"TOTAL_CLAIM_COST", type number}, {"PAYER_COVERAGE", type number}, {"REASONCODE", type number}, {"REASONDESCRIPTION", type text}}),
            #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"START", "Start"}, {"STOP", "Stop"}, {"PATIENT", "Patient"}, {"ORGANIZATION", "Organization"}, {"PAYER", "Payer"}, {"ENCOUNTERCLASS", "Encounterclass"}, {"CODE", "Code"}, {"DESCRIPTION", "Description"}, {"BASE_ENCOUNTER_COST", "Base Encounter Cost"}, {"TOTAL_CLAIM_COST", "Total Claim Cost"}, {"PAYER_COVERAGE", "Payer Coverage"}, {"REASONCODE", "Reasoncode"}, {"REASONDESCRIPTION", "Reasondescription"}}),
                            #"Renamed Columns" = Table.RenameColumns(#"Renamed Columns", {{"START", "Start"}, {"STOP", "Stop"}, {"PATIENT", "Patient"}, {"ORGANIZATION", "Organization"}, {"PAYER", "Payer"}, {"ENCOUNTERCLASS", "Encounterclass"}, {"CODE", "Code"}, {"DESCRIPTION", "Description"}, {"BASE_ENCOUNTER_COST", "Base Encounter Cost"}, {"TOTAL_CLAIM_COST", "Total Claim Cost"}, {"PAYER_COVERAGE", "Payer Coverage"}, {"REASONCODE", "Reasoncode"}, {"REASONDESCRIPTION", "Reasondescription"}})
                        in
                            #"Renamed Columns"
