table 'organizations'
    lineageTag: bbec2c0f-ba46-4d76-be9a-50663b02e1f6

    column 'Id (organizations)'
        dataType: string
        lineageTag: 6890ae08-b23a-4e2f-a707-94a42fcd91fa
        summarizeBy: none
        sourceColumn: Id (organizations)

    column 'Name'
        dataType: string
        lineageTag: 8862d9c6-f11a-4cb4-9b1a-8ea5db67dc17
        summarizeBy: none
        sourceColumn: Name

    column 'ADDRESS (organizations)'
        dataType: string
        lineageTag: 20e0969e-a3d7-4d1c-b77c-894d944c7608
        summarizeBy: none
        sourceColumn: ADDRESS (organizations)

    column 'CITY (organizations)'
        dataType: string
        lineageTag: 0079462d-11d5-4506-adca-6949f18e53fd
        summarizeBy: none
        sourceColumn: CITY (organizations)

    column 'STATE (organizations)'
        dataType: string
        lineageTag: e48d6112-49e5-436e-9cb1-08d38db0406c
        summarizeBy: none
        sourceColumn: STATE (organizations)

    column 'ZIP (organizations)'
        dataType: double
        lineageTag: 18d8f984-a6ae-42a8-8112-c7a9ed6e29e9
        summarizeBy: none
        sourceColumn: ZIP (organizations)

    column 'LAT (organizations)'
        dataType: double
        lineageTag: 01589103-9e44-46d4-87f9-05bbe2eb1d1d
        summarizeBy: none
        sourceColumn: LAT (organizations)

    column 'LON (organizations)'
        dataType: double
        lineageTag: 92310492-45e4-4ab8-8064-ac8931b371f8
        summarizeBy: none
        sourceColumn: LON (organizations)

    column 'Username' = -- SKIPPED BY USER
        dataType: string

        summarizeBy: none

    measure 'RLS - Organization Access' =
        -- SKIPPED BY USER


    partition 'organizations' = m
        mode: import
        source =
            let Source = GoogleSheets.Contents("https://www.googleapis.com/drive/v3/files/1Sd4bEK0Fm9q7yTVOwI4GdtixeeY8hPkKqpvnI4WdixA/export?mimeType=application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
            #"Navigation 1" = Source{[name="organizations", ItemKind="Table"]}[Data],
            #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars=true]),
            #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Id", type text}, {"NAME", type text}, {"ADDRESS", type text}, {"CITY", type text}, {"STATE", type text}, {"ZIP", type number}, {"LAT", type number}, {"LON", type number}}),
            #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"Id", "Id (organizations)"}, {"NAME", "Name"}, {"ADDRESS", "ADDRESS (organizations)"}, {"CITY", "CITY (organizations)"}, {"STATE", "STATE (organizations)"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}}),
                            #"Renamed Columns" = Table.RenameColumns(#"Renamed Columns", {{"Id", "Id (organizations)"}, {"NAME", "Name"}, {"ADDRESS", "ADDRESS (organizations)"}, {"CITY", "CITY (organizations)"}, {"STATE", "STATE (organizations)"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}})
                        in
                            #"Renamed Columns"
