table 'procedures'
    lineageTag: 80bfbb17-9901-43b3-88ca-e31d9059639d

    column 'START (procedures)'
        dataType: string
        lineageTag: 9848bb79-221e-488c-b48c-853d3284c809
        summarizeBy: none
        sourceColumn: START (procedures)

    column 'STOP (procedures)'
        dataType: string
        lineageTag: a298db95-35db-465d-bf8d-da26b2c283c9
        summarizeBy: none
        sourceColumn: STOP (procedures)

    column 'PATIENT (procedures)'
        dataType: string
        lineageTag: f6bfe4fd-3ca3-445d-b210-2d11bccd9742
        summarizeBy: none
        sourceColumn: PATIENT (procedures)

    column 'Encounter'
        dataType: string
        lineageTag: c4412c81-5bba-4546-837f-adc742edd1b2
        summarizeBy: none
        sourceColumn: Encounter

    column 'CODE (procedures)'
        dataType: double
        lineageTag: 4fcd4473-5bf8-4666-b8e8-68874153f903
        summarizeBy: none
        sourceColumn: CODE (procedures)

    column 'DESCRIPTION (procedures)'
        dataType: string
        lineageTag: 97b510ad-e54f-4c58-9f67-28b61f55fac1
        summarizeBy: none
        sourceColumn: DESCRIPTION (procedures)

    column 'Base Cost'
        dataType: double
        lineageTag: 3475e04c-4228-4985-9abd-d7769ddec771
        summarizeBy: none
        sourceColumn: Base Cost

    column 'REASONCODE (procedures)'
        dataType: double
        lineageTag: d8ddf8c1-24bf-43c8-aa53-96206c3ad761
        summarizeBy: none
        sourceColumn: REASONCODE (procedures)

    column 'REASONDESCRIPTION (procedures)'
        dataType: string
        lineageTag: 0dbb38c8-3666-4d34-a44f-639858f605e7
        summarizeBy: none
        sourceColumn: REASONDESCRIPTION (procedures)

    column 'DESCRIPTION (procedures) Set' = -- SKIPPED
        dataType: string

        summarizeBy: none

    measure 'Procedure Rank(Top N Procedure Parameter)' =
        -- SKIPPED BY USER


    measure 'Top N Procedures Filter' =
        -- SKIPPED BY USER


    measure 'Selected Metric' =
        -- SKIPPED BY USER


    partition 'procedures' = m
        mode: import
        source =
            let Source = GoogleSheets.Contents("https://www.googleapis.com/drive/v3/files/1Sd4bEK0Fm9q7yTVOwI4GdtixeeY8hPkKqpvnI4WdixA/export?mimeType=application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
            #"Navigation 1" = Source{[name="procedures", ItemKind="Table"]}[Data],
            #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars=true]),
            #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"START", type text}, {"STOP", type text}, {"PATIENT", type text}, {"ENCOUNTER", type text}, {"CODE", type number}, {"DESCRIPTION", type text}, {"BASE_COST", type number}, {"REASONCODE", type number}, {"REASONDESCRIPTION", type text}}),
            #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"START", "START (procedures)"}, {"STOP", "STOP (procedures)"}, {"PATIENT", "PATIENT (procedures)"}, {"ENCOUNTER", "Encounter"}, {"CODE", "CODE (procedures)"}, {"DESCRIPTION", "DESCRIPTION (procedures)"}, {"BASE_COST", "Base Cost"}, {"REASONCODE", "REASONCODE (procedures)"}, {"REASONDESCRIPTION", "REASONDESCRIPTION (procedures)"}}),
                            #"Renamed Columns" = Table.RenameColumns(#"Renamed Columns", {{"START", "START (procedures)"}, {"STOP", "STOP (procedures)"}, {"PATIENT", "PATIENT (procedures)"}, {"ENCOUNTER", "Encounter"}, {"CODE", "CODE (procedures)"}, {"DESCRIPTION", "DESCRIPTION (procedures)"}, {"BASE_COST", "Base Cost"}, {"REASONCODE", "REASONCODE (procedures)"}, {"REASONDESCRIPTION", "REASONDESCRIPTION (procedures)"}})
                        in
                            #"Renamed Columns"
