table 'patients'
    lineageTag: 1dba3672-67c3-41fd-95e8-7b7a42161017

    column 'Id (patients)'
        dataType: string
        lineageTag: 6598588c-4b98-46c3-a60f-3bc33280fcb9
        summarizeBy: none
        sourceColumn: Id (patients)

    column 'Birthdate'
        sourceColumn: Birthdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: 2b7300e9-1d97-4521-bc44-c0b4c10be714
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 043ff8b5-51ff-47df-94ea-fde96b092d3c
            defaultHierarchy: LocalDateTable_94c38fa3-ed5e-4ca0-a16c-ffc782711049.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Deathdate'
        sourceColumn: Deathdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: 7c0c8691-eb87-4973-81f5-986385e9ac39
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 01bac26f-6992-41e5-b528-3fc07be4be79
            defaultHierarchy: LocalDateTable_07d371eb-00a2-4fea-8f3b-4f4bcee052ec.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Prefix'
        dataType: string
        lineageTag: 28f3a94c-1ed5-4eaf-a549-0a0f6baf43f1
        summarizeBy: none
        sourceColumn: Prefix

    column 'First'
        dataType: string
        lineageTag: 0dfef23f-cb84-44e7-bceb-f575b1065701
        summarizeBy: none
        sourceColumn: First

    column 'Last'
        dataType: string
        lineageTag: 37104d40-e004-4f5a-a4a6-9efeea1aeac8
        summarizeBy: none
        sourceColumn: Last

    column 'Suffix'
        dataType: string
        lineageTag: cfc58c81-5e39-4dea-ba6d-9b17da137e6c
        summarizeBy: none
        sourceColumn: Suffix

    column 'Maiden'
        dataType: string
        lineageTag: da03c720-3c7c-4aad-aab4-e6d28902d8b0
        summarizeBy: none
        sourceColumn: Maiden

    column 'Marital'
        dataType: string
        lineageTag: 354b1588-1b4f-4f20-84c0-86d8c9b65271
        summarizeBy: none
        sourceColumn: Marital

    column 'Race'
        dataType: string
        lineageTag: 72c6ec24-48f9-48ca-9949-4a80eec63bbc
        summarizeBy: none
        sourceColumn: Race

    column 'Ethnicity'
        dataType: string
        lineageTag: 2e410be5-bf64-4040-baab-54d3ab90d5d6
        summarizeBy: none
        sourceColumn: Ethnicity

    column 'Gender'
        dataType: string
        lineageTag: a00439bf-b275-49b6-bcd4-281276794cf0
        summarizeBy: none
        sourceColumn: Gender

    column 'Birthplace'
        dataType: string
        lineageTag: c50cc91b-f74f-4c90-b5cd-d1922853280f
        summarizeBy: none
        sourceColumn: Birthplace

    column 'Address'
        dataType: string
        lineageTag: 137fe585-ae0a-4996-93fa-7072717d79f7
        summarizeBy: none
        sourceColumn: Address

    column 'City'
        dataType: string
        lineageTag: 649c7a44-b19d-4e8c-9fe7-2526d4225aa3
        summarizeBy: none
        sourceColumn: City

    column 'State'
        dataType: string
        lineageTag: 32306043-9dd7-4f7e-8a3d-2f024f789b2b
        summarizeBy: none
        sourceColumn: State

    column 'County'
        dataType: string
        lineageTag: 1fdfe0e8-bbeb-4af5-a8c9-3dbf4652a8ca
        summarizeBy: none
        sourceColumn: County

    column 'ZIP (organizations)'
        dataType: double
        lineageTag: aee74ec0-e893-4046-b39f-a0e7e440dd5e
        summarizeBy: none
        sourceColumn: ZIP (organizations)

    column 'LAT (organizations)'
        dataType: double
        lineageTag: 658280f4-921b-4c1a-9b84-60f0eaf53a90
        summarizeBy: none
        sourceColumn: LAT (organizations)

    column 'LON (organizations)'
        dataType: double
        lineageTag: 8a09e9d5-b154-40f8-b94e-64af2a23636d
        summarizeBy: none
        sourceColumn: LON (organizations)

    measure 'SUM of Avg Visits per Patient (patients)' =
        SUM('patients'[Avg Visits per Patient])


    measure 'SUM of Visits per Patient (patients)' =
        SUM('patients'[Visits per Patient])


    measure 'Total Patients (LOD)' =
        -- SKIPPED BY USER


    measure 'Visits per Patient' =
        -- SKIPPED BY USER


    measure 'Avg Visits per Patient' =
        -- SKIPPED BY USER


    partition 'patients' = m
        mode: import
        source =
            let Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1Sd4bEK0Fm9q7yTVOwI4GdtixeeY8hPkKqpvnI4WdixA"),
            #"Navigation 1" = Source{[name="patients", ItemKind="Table"]}[Data],
            #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars=true]),
            #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Id", type text}, {"BIRTHDATE", type date}, {"DEATHDATE", type date}, {"PREFIX", type text}, {"FIRST", type text}, {"LAST", type text}, {"SUFFIX", type text}, {"MAIDEN", type text}, {"MARITAL", type text}, {"RACE", type text}, {"ETHNICITY", type text}, {"GENDER", type text}, {"BIRTHPLACE", type text}, {"ADDRESS", type text}, {"CITY", type text}, {"STATE", type text}, {"COUNTY", type text}, {"ZIP", type number}, {"LAT", type number}, {"LON", type number}}),
            #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"Id", "Id (patients)"}, {"BIRTHDATE", "Birthdate"}, {"DEATHDATE", "Deathdate"}, {"PREFIX", "Prefix"}, {"FIRST", "First"}, {"LAST", "Last"}, {"SUFFIX", "Suffix"}, {"MAIDEN", "Maiden"}, {"MARITAL", "Marital"}, {"RACE", "Race"}, {"ETHNICITY", "Ethnicity"}, {"GENDER", "Gender"}, {"BIRTHPLACE", "Birthplace"}, {"ADDRESS", "Address"}, {"CITY", "City"}, {"STATE", "State"}, {"COUNTY", "County"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}}),
                            #"Final Renamed Columns" = Table.RenameColumns(#"Renamed Columns", {{"Id", "Id (patients)"}, {"BIRTHDATE", "Birthdate"}, {"DEATHDATE", "Deathdate"}, {"PREFIX", "Prefix"}, {"FIRST", "First"}, {"LAST", "Last"}, {"SUFFIX", "Suffix"}, {"MAIDEN", "Maiden"}, {"MARITAL", "Marital"}, {"RACE", "Race"}, {"ETHNICITY", "Ethnicity"}, {"GENDER", "Gender"}, {"BIRTHPLACE", "Birthplace"}, {"ADDRESS", "Address"}, {"CITY", "City"}, {"STATE", "State"}, {"COUNTY", "County"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}})
                        in
                            #"Final Renamed Columns"
