table 'payers'
    lineageTag: b840a24c-51bf-4910-9ada-c5274dd91849

    column 'Id (payers)'
        dataType: string
        lineageTag: 0e9dd5a0-9942-4b94-8581-d59b9f8dcf62
        summarizeBy: none
        sourceColumn: Id (payers)

    column 'NAME (payers)'
        dataType: string
        lineageTag: 5363abfb-d500-4048-b014-5d7f3d98b163
        summarizeBy: none
        sourceColumn: NAME (payers)

    column 'ADDRESS (payers)'
        dataType: string
        lineageTag: b9080b9f-2559-46a6-ab42-1aeb41b7bb91
        summarizeBy: none
        sourceColumn: ADDRESS (payers)

    column 'CITY (payers)'
        dataType: string
        lineageTag: 5095eb0f-cc69-45b3-bd9d-e9292e451b02
        summarizeBy: none
        sourceColumn: CITY (payers)

    column 'State Headquartered'
        dataType: string
        lineageTag: 8f607f90-e237-4885-b852-c29ec64af2b9
        summarizeBy: none
        sourceColumn: State Headquartered

    column 'ZIP (payers)'
        dataType: double
        lineageTag: 2337347c-a31a-4f25-99f4-c4b9a76982f4
        summarizeBy: none
        sourceColumn: ZIP (payers)

    column 'Phone'
        dataType: string
        lineageTag: 3cc2512a-9e68-45dd-bcd8-cc99608c5fc3
        summarizeBy: none
        sourceColumn: Phone

    partition 'payers' = m
        mode: import
        source =
            let Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1Sd4bEK0Fm9q7yTVOwI4GdtixeeY8hPkKqpvnI4WdixA"),
            #"Navigation 1" = Source{[name="payers", ItemKind="Table"]}[Data],
            #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars=true]),
            #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Id", type text}, {"NAME", type text}, {"ADDRESS", type text}, {"CITY", type text}, {"STATE_HEADQUARTERED", type text}, {"ZIP", type number}, {"PHONE", type text}}),
            #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"Id", "Id (payers)"}, {"NAME", "NAME (payers)"}, {"ADDRESS", "ADDRESS (payers)"}, {"CITY", "CITY (payers)"}, {"STATE_HEADQUARTERED", "State Headquartered"}, {"ZIP", "ZIP (payers)"}, {"PHONE", "Phone"}}),
                            #"Final Renamed Columns" = Table.RenameColumns(#"Renamed Columns", {{"Id", "Id (payers)"}, {"NAME", "NAME (payers)"}, {"ADDRESS", "ADDRESS (payers)"}, {"CITY", "CITY (payers)"}, {"STATE_HEADQUARTERED", "State Headquartered"}, {"ZIP", "ZIP (payers)"}, {"PHONE", "Phone"}})
                        in
                            #"Final Renamed Columns"
