table 'APPOINTMENTS'
    lineageTag: fa22ef91-9a2f-4b84-835e-156473efe814

    column 'Appointment Id'
        dataType: string
        lineageTag: c2bdb059-2709-4389-a6f9-dcf1c104eed7
        summarizeBy: none
        sourceColumn: Appointment Id

    column 'Patient Id'
        dataType: string
        lineageTag: 7e01b65d-a65b-4e74-9f12-704304001154
        summarizeBy: none
        sourceColumn: Patient Id

    column 'Doctor Id'
        dataType: string
        lineageTag: e3c6609f-f75b-44a2-9907-4de2832ff9d0
        summarizeBy: none
        sourceColumn: Doctor Id

    column 'Department'
        dataType: string
        lineageTag: 345b6315-2c7c-4bfe-bbcc-ea7c48b3b925
        summarizeBy: none
        sourceColumn: Department

    column 'Appointment Date'
        sourceColumn: Appointment Date
        dataType: dateTime
        formatString: Long Date
        lineageTag: 8b571ed1-84b1-4785-8ac0-1984eab479ba
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 55cab355-b2fd-4551-a304-35b70f3e2dc5
            defaultHierarchy: LocalDateTable_fecb389b-0e3f-4947-bc12-63ab471c9da3.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Appointment Time'
        sourceColumn: Appointment Time
        dataType: dateTime
        formatString: General Date
        lineageTag: 726ab2f0-9e55-4498-8040-fd65460c5195
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 4c0db279-c01d-4c0d-a0af-ddb8c2b04531
            defaultHierarchy: LocalDateTable_35c2adbe-2e70-468e-bce1-fdf2f0a1540f.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Visit Status'
        dataType: string
        lineageTag: 306d4a7b-038e-4bec-92fe-cd5f1dd53b47
        summarizeBy: none
        sourceColumn: Visit Status

    column 'Reason For Visit'
        dataType: string
        lineageTag: b43c4c26-a246-4918-a084-4a3dc4c2cfb9
        summarizeBy: none
        sourceColumn: Reason For Visit

    column 'Diagnosis Code'
        dataType: string
        lineageTag: 95805371-9ab9-4684-aa26-04db7ac3a39c
        summarizeBy: none
        sourceColumn: Diagnosis Code

    column 'Follow Up Required'
        dataType: boolean
        lineageTag: 017ebb10-0a38-462b-b12d-500e22d9d594
        summarizeBy: none
        sourceColumn: Follow Up Required

    column 'DEPARTMENT__Custom_SQL_Query__Set_Category' = IF('APPOINTMENTS'[Department] IN { }, "In", "Out")
        dataType: string

        summarizeBy: none

    column 'Doctor_Id_Set_Category' = IF('APPOINTMENTS'[Doctor Id] IN { }, "In", "Out")
        dataType: string

        summarizeBy: none

    measure 'Before Migration Count' =
        COUNT('APPOINTMENTS'[Doctor Id])


    measure 'Patients' =
        DISTINCTCOUNT('APPOINTMENTS'[Patient Id])


    measure 'Total Appointments' =
        COUNT('APPOINTMENTS'[Appointment Id])


    measure 'Doctor Contribution %' =
        DIVIDE([Doctor Revenue (LOD)], [Department Revenue (LOD)], 0)


    measure 'SUM of Doctor Contribution %' =
        SUM('APPOINTMENTS'[Doctor Contribution %])


    measure 'CNT of Appointment Id' =
        COUNT('APPOINTMENTS'[Appointment Id])


    measure 'SUM of Appointments per Doctor (LOD' =
        SUM('APPOINTMENTS'[Appointments per Doctor (LOD])


    measure 'Appointments per Patient (fixed)' =
        CALCULATE(COUNT('APPOINTMENTS'[Appointment Id]), ALLEXCEPT('APPOINTMENTS', 'APPOINTMENTS'[Patient Id]))


    measure 'Avg Consultation Fee per Patient(Include)' =
        CALCULATE(AVERAGEX(VALUES('APPOINTMENTS'[Patient Id]), CALCULATE(AVERAGE('DOCTORS'[Consultation Fee]))))


    measure 'Appointments per Doctor (LOD' =
        CALCULATE(COUNTX(VALUES('APPOINTMENTS'[Doctor Id]), CALCULATE(COUNT('APPOINTMENTS'[Appointment Id]))))


    measure 'Avg Doctor Bill Count by Specialization (Nested LOD)' =
        CALCULATE(AVERAGEX(VALUES('APPOINTMENTS'[Doctor Id]), [Doctor Bill Count (LOD)]), ALLEXCEPT('DOCTORS', 'DOCTORS'[Specialization]))


    measure 'Doctor Revenue (LOD)' =
        CALCULATE(SUM([COLLECTED_REVENUE]), ALLEXCEPT('APPOINTMENTS', 'APPOINTMENTS'[Department], 'APPOINTMENTS'[Doctor Id]))


    partition 'APPOINTMENTS' = m
        mode: import
        source =
            let
                Source = Snowflake.Databases("mmcuiwz-kl31490.snowflakecomputing.com", "COMPUTE_WH"),
                DB = Source{[Name="CITY_HOSPITAL"]}[Data],
                Schema = DB{[Name="PUBLIC"]}[Data],
                Table = Schema{[Name="APPOINTMENTS"]}[Data],
                #"Changed Type" = Table.TransformColumnTypes(Table, {{"APPOINTMENT_ID", type text}, {"PATIENT_ID", type text}, {"DOCTOR_ID", type text}, {"DEPARTMENT", type text}, {"APPOINTMENT_DATE", type date}, {"APPOINTMENT_TIME", type datetime}, {"VISIT_STATUS", type text}, {"REASON_FOR_VISIT", type text}, {"DIAGNOSIS_CODE", type text}, {"FOLLOW_UP_REQUIRED", type logical}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"APPOINTMENT_ID", "Appointment Id"}, {"PATIENT_ID", "Patient Id"}, {"DOCTOR_ID", "Doctor Id"}, {"DEPARTMENT", "Department"}, {"APPOINTMENT_DATE", "Appointment Date"}, {"APPOINTMENT_TIME", "Appointment Time"}, {"VISIT_STATUS", "Visit Status"}, {"REASON_FOR_VISIT", "Reason For Visit"}, {"DIAGNOSIS_CODE", "Diagnosis Code"}, {"FOLLOW_UP_REQUIRED", "Follow Up Required"}})
            in
                #"Renamed Columns"
