table 'BILLS'
    lineageTag: 7476f71f-e137-4866-9dcf-28a0ccdb19eb

    column 'Bill Id'
        dataType: string
        lineageTag: aac7fbfb-4e40-4479-a809-c6248a14b499
        summarizeBy: none
        sourceColumn: Bill Id

    column 'Patient Id (Bills)'
        dataType: string
        lineageTag: 6bd992a1-c9a2-4c30-bdc0-155e45f4d72d
        summarizeBy: none
        sourceColumn: Patient Id (Bills)

    column 'Appointment Id (Bills)'
        dataType: string
        lineageTag: 4e791447-1082-4552-9381-04e1d9bdc32e
        summarizeBy: none
        sourceColumn: Appointment Id (Bills)

    column 'Treatment Id'
        dataType: string
        lineageTag: 0ed78420-43b8-48d8-b42f-f518f5f20307
        summarizeBy: none
        sourceColumn: Treatment Id

    column 'Billing Date'
        sourceColumn: Billing Date
        dataType: dateTime
        formatString: Long Date
        lineageTag: 3b3039f1-aaea-48b3-b342-fd22b12273d8
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 2870c94c-e9e1-42dd-8518-e7217c42c5ee
            defaultHierarchy: LocalDateTable_6174f0bc-374d-48d7-a43f-0f3f4096cf48.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Total Amount'
        dataType: double
        lineageTag: fe3ced3f-6b2a-4517-b4a3-bf021ed86cce
        summarizeBy: none
        sourceColumn: Total Amount

    column 'Insurance Covered'
        dataType: double
        lineageTag: dce2d0ee-9e4c-4271-9334-56c22008c32d
        summarizeBy: none
        sourceColumn: Insurance Covered

    column 'Patient Payable'
        dataType: double
        lineageTag: bc74941d-e78c-4eeb-9bb1-2a04dc412ede
        summarizeBy: none
        sourceColumn: Patient Payable

    column 'Payment Method'
        dataType: string
        lineageTag: f83b4b38-9e18-41d9-84cf-14baca7ae884
        summarizeBy: none
        sourceColumn: Payment Method

    column 'Payment Status'
        dataType: string
        lineageTag: e889b3a6-80c5-427f-b77f-476dfdca40fd
        summarizeBy: none
        sourceColumn: Payment Status

    measure 'Insurance Coverage %' =
        DIVIDE(SUM('BILLS'[Insurance Covered]), SUM('BILLS'[Total Amount]), 0)


    measure 'Total Bill' =
        COUNT('BILLS'[Bill Id])


    measure 'Total billing Amount' =
        SUM('BILLS'[Total Amount])


    measure 'Total Revenue' =
        SUM('BILLS'[Total Amount])


    measure 'Unpaid Balance' =
        SUM('BILLS'[Total Amount]) - SUM('BILLS'[Insurance Covered])


    measure 'COLLECTED_REVENUE' =
        CALCULATE(SUM('BILLS'[Total Amount]), KEEPFILTERS('BILLS'[Payment Status] & "" = "Paid"))


    measure 'SUM of Total Amount (BILLS)' =
        SUM('BILLS'[Total Amount])


    measure 'Unpaid Balance per Specialization (Fixed)' =
        CALCULATE(SUM('BILLS'[Total Amount]) - SUM('BILLS'[Insurance Covered]), ALLEXCEPT('DOCTORS', 'DOCTORS'[Specialization]))


    measure 'Doctor Bill Count (LOD)' =
        CALCULATE(COUNT('BILLS'[Bill Id]), REMOVEFILTERS('BILLS'), ALLEXCEPT('DOCTORS', 'DOCTORS'[Doctor Id (Doctors)]))


    partition 'BILLS' = m
        mode: import
        source =
            let
                Source = Snowflake.Databases("mmcuiwz-kl31490.snowflakecomputing.com", "COMPUTE_WH"),
                DB = Source{[Name="CITY_HOSPITAL"]}[Data],
                Schema = DB{[Name="PUBLIC"]}[Data],
                Table = Schema{[Name="BILLS"]}[Data],
                #"Changed Type" = Table.TransformColumnTypes(Table, {{"BILL_ID", type text}, {"PATIENT_ID", type text}, {"APPOINTMENT_ID", type text}, {"TREATMENT_ID", type text}, {"BILLING_DATE", type date}, {"TOTAL_AMOUNT", type number}, {"INSURANCE_COVERED", type number}, {"PATIENT_PAYABLE", type number}, {"PAYMENT_METHOD", type text}, {"PAYMENT_STATUS", type text}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"BILL_ID", "Bill Id"}, {"PATIENT_ID", "Patient Id (Bills)"}, {"APPOINTMENT_ID", "Appointment Id (Bills)"}, {"TREATMENT_ID", "Treatment Id"}, {"BILLING_DATE", "Billing Date"}, {"TOTAL_AMOUNT", "Total Amount"}, {"INSURANCE_COVERED", "Insurance Covered"}, {"PATIENT_PAYABLE", "Patient Payable"}, {"PAYMENT_METHOD", "Payment Method"}, {"PAYMENT_STATUS", "Payment Status"}})
            in
                #"Renamed Columns"
