table 'custom table'
    lineageTag: 0ba6b3fd-f7bd-41e3-adbe-a676242afe22

    column 'APPOINTMENT_ID (Custom SQL Query)'
        dataType: string
        lineageTag: d3e123c5-9f86-4ab0-b77b-5a1f3214f2d9
        summarizeBy: none
        sourceColumn: APPOINTMENT_ID (Custom SQL Query)

    column 'PATIENT_ID (Custom SQL Query)'
        dataType: string
        lineageTag: ee9ee768-ca51-4e94-b0f6-512904e123c6
        summarizeBy: none
        sourceColumn: PATIENT_ID (Custom SQL Query)

    column 'DOCTOR_ID (Custom SQL Query)'
        dataType: string
        lineageTag: f4294873-eeef-41ec-bf0b-1cb2f96f8951
        summarizeBy: none
        sourceColumn: DOCTOR_ID (Custom SQL Query)

    column 'DEPARTMENT (Custom SQL Query)'
        dataType: string
        lineageTag: 57f23534-0b6d-49b4-96d0-76af7a63357b
        summarizeBy: none
        sourceColumn: DEPARTMENT (Custom SQL Query)

    column 'APPOINTMENT_DATE (Custom SQL Query)'
        sourceColumn: APPOINTMENT_DATE (Custom SQL Query)
        dataType: dateTime
        formatString: Long Date
        lineageTag: 6eab549a-2ae7-4c56-9c79-2de0b857df38
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 8bbd0a80-4501-4406-806d-76c5d4eb0b9d
            defaultHierarchy: LocalDateTable_68343eab-691f-4fe6-81a6-fdaad442b847.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'APPOINTMENT_TIME (Custom SQL Query)'
        sourceColumn: APPOINTMENT_TIME (Custom SQL Query)
        dataType: dateTime
        formatString: General Date
        lineageTag: dee9d659-7d03-450f-b1bd-1d8abbd627bd
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 9482a1ae-21af-423d-a0d4-3da8813f1b31
            defaultHierarchy: LocalDateTable_6591251c-feb8-4383-a096-5f9cc7c87562.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'VISIT_STATUS_CLEAN'
        dataType: string
        lineageTag: 99c95445-a4a3-47c6-afed-120a935bfeb2
        summarizeBy: none
        sourceColumn: VISIT_STATUS_CLEAN

    column 'REASON_FOR_VISIT (Custom SQL Query)'
        dataType: string
        lineageTag: f14d10c3-bb1c-42d8-95e3-c6bdb8053721
        summarizeBy: none
        sourceColumn: REASON_FOR_VISIT (Custom SQL Query)

    column 'DIAGNOSIS_CODE (Custom SQL Query)'
        dataType: string
        lineageTag: 2c6a579b-31c7-4351-85ce-d477473ca05a
        summarizeBy: none
        sourceColumn: DIAGNOSIS_CODE (Custom SQL Query)

    column 'FOLLOW_UP_REQUIRED (Custom SQL Query)'
        dataType: boolean
        lineageTag: 60e6a8e8-31e0-4d0c-bc5b-8d98b8d4f782
        summarizeBy: none
        sourceColumn: FOLLOW_UP_REQUIRED (Custom SQL Query)

    column 'SPECIALIZATION (Custom SQL Query)'
        dataType: string
        lineageTag: 98bd07a2-d4ab-48fb-b067-12bd5762397e
        summarizeBy: none
        sourceColumn: SPECIALIZATION (Custom SQL Query)

    column 'CONSULTATION_FEE (Custom SQL Query)'
        dataType: double
        lineageTag: eb9a534f-4127-437e-8ee4-34597918b259
        summarizeBy: none
        sourceColumn: CONSULTATION_FEE (Custom SQL Query)

    column 'TREATMENT_TYPE (Custom SQL Query)'
        dataType: string
        lineageTag: fee3a24e-3cd3-432c-9acc-bd4f836ad2e7
        summarizeBy: none
        sourceColumn: TREATMENT_TYPE (Custom SQL Query)

    column 'OUTCOME_STATUS (Custom SQL Query)'
        dataType: string
        lineageTag: 9802efff-a98f-4b2d-9124-b0a1d7324c5c
        summarizeBy: none
        sourceColumn: OUTCOME_STATUS (Custom SQL Query)

    column 'TREATMENT_COST (Custom SQL Query)'
        dataType: double
        lineageTag: a0ebb3b5-b399-4d1c-85e2-74916fafabc7
        summarizeBy: none
        sourceColumn: TREATMENT_COST (Custom SQL Query)

    column 'TOTAL_AMOUNT (Custom SQL Query)'
        dataType: double
        lineageTag: afe58b3f-a74f-49dc-b3fb-3823985b646d
        summarizeBy: none
        sourceColumn: TOTAL_AMOUNT (Custom SQL Query)

    column 'PAYMENT_STATUS (Custom SQL Query)'
        dataType: string
        lineageTag: c61e9e32-ee74-47c3-8bd2-bc119be0e5dc
        summarizeBy: none
        sourceColumn: PAYMENT_STATUS (Custom SQL Query)

    column 'COLLECTED_REVENUE'
        dataType: double
        lineageTag: e931aa68-e925-4841-bbf0-eebe7461c3d8
        summarizeBy: none
        sourceColumn: COLLECTED_REVENUE

    measure 'Revenue Filter' =
        SUMX('custom table', [COLLECTED_REVENUE]) >= SELECTEDVALUE('Revenue Threshold'[Value])


    measure 'SUM of COLLECTED_REVENUE (custom table)' =
        SUM('custom table'[COLLECTED_REVENUE])


    measure 'SUM of Completed Appointments per Department (custom table)' =
        SUM('custom table'[Completed Appointments per Department])


    measure 'Department Total Revenue (LOD)' =
        CALCULATE(SUM([COLLECTED_REVENUE]), ALLEXCEPT('custom table', 'custom table'[DEPARTMENT (Custom SQL Query)]))


    measure 'Completed Appointments per Department' =
        CALCULATE(SUMX('custom table', IF('custom table'[VISIT_STATUS_CLEAN] & "" = "Completed", 1, 0)), ALLEXCEPT('custom table', 'custom table'[DEPARTMENT (Custom SQL Query)]))


    measure 'Department Revenue (LOD)' =
        CALCULATE(SUM([COLLECTED_REVENUE]), ALLEXCEPT('custom table', 'custom table'[DEPARTMENT (Custom SQL Query)]))


    partition 'custom table' = m
        mode: import
        source =
            let Source = Snowflake.Databases("mmcuiwz-kl31490.snowflakecomputing.com", "COMPUTE_WH"),
            DB = Source{[Name="CITY_HOSPITAL"]}[Data],
            custom_table = Value.NativeQuery(DB, "SELECT a.APPOINTMENT_ID, a.PATIENT_ID, a.DOCTOR_ID, a.DEPARTMENT, a.APPOINTMENT_DATE, a.APPOINTMENT_TIME, CASE WHEN a.VISIT_STATUS IN ('No-Show', 'No Show') THEN 'No Show' WHEN a.VISIT_STATUS IN ('Cancelled', 'Canceled') THEN 'Cancelled' WHEN a.VISIT_STATUS = 'Completed' THEN 'Completed' ELSE 'Other' END AS VISIT_STATUS_CLEAN, a.REASON_FOR_VISIT, a.DIAGNOSIS_CODE, a.FOLLOW_UP_REQUIRED, d.SPECIALIZATION, d.CONSULTATION_FEE, t.TREATMENT_TYPE, t.OUTCOME_STATUS, t.TREATMENT_COST, b.TOTAL_AMOUNT, b.PAYMENT_STATUS, CASE WHEN b.PAYMENT_STATUS = 'Paid' THEN b.TOTAL_AMOUNT ELSE 0 END AS COLLECTED_REVENUE FROM SNOWFLAKE_LEARNING_DB.RAJANMORYA_LOAD_SAMPLE_DATA_FROM_S3.APPOINTMENTS a LEFT JOIN SNOWFLAKE_LEARNING_DB.RAJANMORYA_LOAD_SAMPLE_DATA_FROM_S3.DOCTORS d ON a.DOCTOR_ID = d.DOCTOR_ID LEFT JOIN SNOWFLAKE_LEARNING_DB.RAJANMORYA_LOAD_SAMPLE_DATA_FROM_S3.TREATMENTS t ON a.APPOINTMENT_ID = t.APPOINTMENT_ID LEFT JOIN SNOWFLAKE_LEARNING_DB.RAJANMORYA_LOAD_SAMPLE_DATA_FROM_S3.BILLS b ON a.APPOINTMENT_ID = b.APPOINTMENT_ID"),
                            #"Renamed Columns" = Table.RenameColumns(custom_table, {{"APPOINTMENT_ID", "APPOINTMENT_ID (Custom SQL Query)"}, {"PATIENT_ID", "PATIENT_ID (Custom SQL Query)"}, {"DOCTOR_ID", "DOCTOR_ID (Custom SQL Query)"}, {"DEPARTMENT", "DEPARTMENT (Custom SQL Query)"}, {"APPOINTMENT_DATE", "APPOINTMENT_DATE (Custom SQL Query)"}, {"APPOINTMENT_TIME", "APPOINTMENT_TIME (Custom SQL Query)"}, {"REASON_FOR_VISIT", "REASON_FOR_VISIT (Custom SQL Query)"}, {"DIAGNOSIS_CODE", "DIAGNOSIS_CODE (Custom SQL Query)"}, {"FOLLOW_UP_REQUIRED", "FOLLOW_UP_REQUIRED (Custom SQL Query)"}, {"SPECIALIZATION", "SPECIALIZATION (Custom SQL Query)"}, {"CONSULTATION_FEE", "CONSULTATION_FEE (Custom SQL Query)"}, {"TREATMENT_TYPE", "TREATMENT_TYPE (Custom SQL Query)"}, {"OUTCOME_STATUS", "OUTCOME_STATUS (Custom SQL Query)"}, {"TREATMENT_COST", "TREATMENT_COST (Custom SQL Query)"}, {"TOTAL_AMOUNT", "TOTAL_AMOUNT (Custom SQL Query)"}, {"PAYMENT_STATUS", "PAYMENT_STATUS (Custom SQL Query)"}})
                        in
                            #"Renamed Columns"
