table 'DOCTORS'
    lineageTag: 6d9114a0-cad5-4183-a6f1-6490239b627c

    column 'Doctor Id (Doctors)'
        dataType: string
        lineageTag: 92233337-cb91-402a-bcb7-d0ca49a280cb
        summarizeBy: none
        sourceColumn: Doctor Id (Doctors)

    column 'Full Name'
        dataType: string
        lineageTag: 6e069cec-c503-471b-b882-84eed6402692
        summarizeBy: none
        sourceColumn: Full Name

    column 'Specialization'
        dataType: string
        lineageTag: de11b425-eb09-49ca-85a1-55a98a5a8822
        summarizeBy: none
        sourceColumn: Specialization

    column 'Department (Doctors)'
        dataType: string
        lineageTag: 0fa44b68-f04d-42e2-9142-0d40c6e79454
        summarizeBy: none
        sourceColumn: Department (Doctors)

    column 'Contact Number'
        dataType: string
        lineageTag: a081c85e-b80b-4c1a-a249-498d02dea294
        summarizeBy: none
        sourceColumn: Contact Number

    column 'Email Address'
        dataType: string
        lineageTag: fc01826d-a318-4bad-974d-a275c1050d36
        summarizeBy: none
        sourceColumn: Email Address

    column 'Availability Days'
        dataType: string
        lineageTag: ef8e81c0-5034-456e-b1f0-c04c942fc71a
        summarizeBy: none
        sourceColumn: Availability Days

    column 'Consultation Fee'
        dataType: double
        lineageTag: 4e548baf-02fc-4df5-aafe-b7d740acbc42
        summarizeBy: none
        sourceColumn: Consultation Fee

    column 'Experience Years'
        dataType: double
        lineageTag: 3abf02e7-08bc-45a0-bd57-ab98e43e0b15
        summarizeBy: none
        sourceColumn: Experience Years

    column 'Registration Number'
        dataType: string
        lineageTag: b884eef3-d730-4639-bc40-e382c974c7a3
        summarizeBy: none
        sourceColumn: Registration Number

    column 'Experience Level_Cal' = SWITCH( TRUE(), 'DOCTORS'[Experience Years] < 5, "Junior", 'DOCTORS'[Experience Years] <= 10, "Mid-Level", "Senior" )
        dataType: string

        summarizeBy: none

    measure 'Average Consultation Fee' =
        AVERAGE('DOCTORS'[Consultation Fee])


    measure 'Average Doctor Experience (Years)1' =
        AVERAGE('DOCTORS'[Experience Years])


    measure 'Average by Specialization (NESTED)' =
        AVERAGEX(
            VALUES('DOCTORS'[Specialization]),
            AVERAGEX(
                VALUES('BILLS'[Appointment Id (Bills)]),
                CALCULATE(
                    SUM('BILLS'[Total Amount]) - SUM('BILLS'[Insurance Covered])
                )
            )
        )


    measure 'Doctor RLS Filter' =
        SELECTEDVALUE('DOCTORS'[Email Address]) = USERNAME()


    partition 'DOCTORS' = m
        mode: import
        source =
            let
                Source = Snowflake.Databases("mmcuiwz-kl31490.snowflakecomputing.com", "COMPUTE_WH"),
                DB = Source{[Name="CITY_HOSPITAL"]}[Data],
                Schema = DB{[Name="PUBLIC"]}[Data],
                Table = Schema{[Name="DOCTORS"]}[Data],
                #"Changed Type" = Table.TransformColumnTypes(Table, {{"DOCTOR_ID", type text}, {"FULL_NAME", type text}, {"SPECIALIZATION", type text}, {"DEPARTMENT", type text}, {"CONTACT_NUMBER", type text}, {"EMAIL_ADDRESS", type text}, {"AVAILABILITY_DAYS", type text}, {"CONSULTATION_FEE", type number}, {"EXPERIENCE_YEARS", type number}, {"REGISTRATION_NUMBER", type text}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"DOCTOR_ID", "Doctor Id (Doctors)"}, {"FULL_NAME", "Full Name"}, {"SPECIALIZATION", "Specialization"}, {"DEPARTMENT", "Department (Doctors)"}, {"CONTACT_NUMBER", "Contact Number"}, {"EMAIL_ADDRESS", "Email Address"}, {"AVAILABILITY_DAYS", "Availability Days"}, {"CONSULTATION_FEE", "Consultation Fee"}, {"EXPERIENCE_YEARS", "Experience Years"}, {"REGISTRATION_NUMBER", "Registration Number"}})
            in
                #"Renamed Columns"
