table 'TREATMENTS'
    lineageTag: fc75a93d-5401-4854-859a-5facb42e013f

    column 'Treatment Id (Treatments)'
        dataType: string
        lineageTag: 89e3ea39-ea2b-4c02-98a1-bd6e3031a6db
        summarizeBy: none
        sourceColumn: Treatment Id (Treatments)

    column 'Appointment Id (Treatments)'
        dataType: string
        lineageTag: c2035628-4788-4fb7-a5d6-341955c2c41c
        summarizeBy: none
        sourceColumn: Appointment Id (Treatments)

    column 'Treatment Type'
        dataType: string
        lineageTag: 8b688e03-1ca5-482d-b40a-9ebb5721390b
        summarizeBy: none
        sourceColumn: Treatment Type

    column 'Treatment Description'
        dataType: string
        lineageTag: c038dd12-fb5c-46cb-b3bb-6d7ed9cc6462
        summarizeBy: none
        sourceColumn: Treatment Description

    column 'Prescribed Medication'
        dataType: string
        lineageTag: 9cf17b59-fe2d-4069-abd2-ede97f55a0af
        summarizeBy: none
        sourceColumn: Prescribed Medication

    column 'Start Date'
        sourceColumn: Start Date
        dataType: dateTime
        formatString: Long Date
        lineageTag: 779f9085-90b7-4e91-bbad-80be8b227481
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 0648f245-9c13-461b-815c-a50b88239016
            defaultHierarchy: LocalDateTable_948ccd45-33d2-4e02-b320-78120027e887.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'End Date'
        sourceColumn: End Date
        dataType: dateTime
        formatString: Long Date
        lineageTag: bb4053c2-c3cb-454f-9f51-b9e6ea5504d6
        summarizeBy: none

        variation Variation
            isDefault
            relationship: cffd3fcd-cf5d-40f2-8db5-525500b6fdbf
            defaultHierarchy: LocalDateTable_d33bd0eb-6c3b-49a6-98f8-8b5010c4b906.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Outcome Status'
        dataType: string
        lineageTag: d0825c82-8c5c-48a6-87f1-ce9956ff98a7
        summarizeBy: none
        sourceColumn: Outcome Status

    column 'Follow Up Date'
        sourceColumn: Follow Up Date
        dataType: dateTime
        formatString: Long Date
        lineageTag: 20d13c5b-d3ae-452d-96a4-39f36fcbc236
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 41c76b98-1ab9-4115-b109-ef93bb0917ba
            defaultHierarchy: LocalDateTable_9ce45489-7df6-449b-b54c-33173d6c2715.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Treatment Cost'
        dataType: double
        lineageTag: f40b1c42-707f-4c20-a72d-994299239a57
        summarizeBy: none
        sourceColumn: Treatment Cost

    measure 'Appointment to Treatment Ratio' =
        DIVIDE(COUNT('TREATMENTS'[Treatment Id (Treatments)]), COUNT('APPOINTMENTS'[Appointment Id]), 0)


    measure 'Avg. Treatment Cost' =
        AVERAGE('TREATMENTS'[Treatment Cost])


    partition 'TREATMENTS' = m
        mode: import
        source =
            let
                Source = Snowflake.Databases("mmcuiwz-kl31490.snowflakecomputing.com", "COMPUTE_WH"),
                DB = Source{[Name="CITY_HOSPITAL"]}[Data],
                Schema = DB{[Name="PUBLIC"]}[Data],
                Table = Schema{[Name="TREATMENTS"]}[Data],
                #"Changed Type" = Table.TransformColumnTypes(Table, {{"TREATMENT_ID", type text}, {"APPOINTMENT_ID", type text}, {"TREATMENT_TYPE", type text}, {"TREATMENT_DESCRIPTION", type text}, {"PRESCRIBED_MEDICATION", type text}, {"START_DATE", type date}, {"END_DATE", type date}, {"OUTCOME_STATUS", type text}, {"FOLLOW_UP_DATE", type date}, {"TREATMENT_COST", type number}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"TREATMENT_ID", "Treatment Id (Treatments)"}, {"APPOINTMENT_ID", "Appointment Id (Treatments)"}, {"TREATMENT_TYPE", "Treatment Type"}, {"TREATMENT_DESCRIPTION", "Treatment Description"}, {"PRESCRIBED_MEDICATION", "Prescribed Medication"}, {"START_DATE", "Start Date"}, {"END_DATE", "End Date"}, {"OUTCOME_STATUS", "Outcome Status"}, {"FOLLOW_UP_DATE", "Follow Up Date"}, {"TREATMENT_COST", "Treatment Cost"}})
            in
                #"Renamed Columns"
