table APPOINTMENTS
	lineageTag: 072a30c8-c8fd-5d1f-8573-9ec77897d4e3

	measure 'Total Appointments' = COUNT('APPOINTMENTS'[APPOINTMENT_ID])
		formatString: "#,##0.00"
		lineageTag: ec5f005f-676b-51fb-86b6-7a0b7346ed29

	measure 'Appointment to Treatment Ratio' = DIVIDE(COUNT('APPOINTMENTS'[APPOINTMENT_ID]), CALCULATE(COUNT('APPOINTMENTS'[APPOINTMENT_ID]), SEARCH("*", 'APPOINTMENTS'[APPOINTMENT_ID], 1, 0) > 0), 0)
		formatString: "#,##0.00"
		lineageTag: cc966de2-5a28-554c-a578-5be544870613

	measure Patients = COUNT([APPOINTMENTS.PATIENT_ID])
		formatString: "#,##0.00"
		lineageTag: 74e2052c-0615-5741-9144-9944da8b760a

	measure 'COUNT(APPOINTMENT_ID) / COUNT({<APPOINTMENT_ID={"*"}>} APPOINTMENT_ID)' = DIVIDE(COUNT('APPOINTMENTS'[APPOINTMENT_ID]), CALCULATE(COUNT('APPOINTMENTS'[APPOINTMENT_ID]), SEARCH("*", 'APPOINTMENTS'[APPOINTMENT_ID], 1, 0) > 0), 0)
		formatString: "#,##0"
		lineageTag: 019541cb-5be4-55d5-81bf-239dbc3c1d55

	measure 'AVG(CONSULTATION_FEE)' = AVERAGE('DOCTORS'[CONSULTATION_FEE])
		formatString: "#,##0.00"
		lineageTag: 94eef75d-a53c-5c0c-80db-5cf73a2cd75d

	measure 'AVG(EXPERIENCE_YEARS)' = AVERAGE('DOCTORS'[EXPERIENCE_YEARS])
		formatString: "#,##0.00"
		lineageTag: 35b162b5-9cc8-5d50-85a8-4f5528593685

	measure 'AVG(TREATMENT_COST)' = AVERAGE('TREATMENTS'[TREATMENT_COST])
		formatString: "#,##0.00"
		lineageTag: 456ef6a3-ecbb-58c3-b23d-6014c7ffb89d

	measure 'Sum(INSURANCE_COVERED) / Sum(TOTAL_AMOUNT)' = DIVIDE(SUM('BILLS'[INSURANCE_COVERED]), SUM('BILLS'[TOTAL_AMOUNT]), 0)
		formatString: "#,##0.00"
		lineageTag: b1468b6f-3ec0-5f5d-9055-96adc4b88d39

	measure 'Count([APPOINTMENTS.PATIENT_ID])' = COUNT([APPOINTMENTS.PATIENT_ID])
		formatString: "#,##0"
		lineageTag: 14b97b02-5f94-557c-8f42-6a4be0063b01

	measure 'COUNT(APPOINTMENT_ID)' = COUNT('APPOINTMENTS'[APPOINTMENT_ID])
		formatString: "#,##0"
		lineageTag: 44370785-97ea-5601-bee7-ef0bbb8cdbbe

	measure 'Count(BILL_ID)' = COUNT('BILLS'[BILL_ID])
		formatString: "#,##0"
		lineageTag: 03f5da57-5aa0-5898-b1fa-e8d7e52329db

	measure 'Sum(TOTAL_AMOUNT)' = SUM('BILLS'[TOTAL_AMOUNT])
		formatString: "#,##0.00"
		lineageTag: 7ccbea68-c441-57f2-bf29-f46d50eaa18c

	measure 'Sum(CONSULTATION_FEE)' = SUM('DOCTORS'[CONSULTATION_FEE])
		formatString: "#,##0"
		lineageTag: 91764612-20c4-5b25-96fa-4535cb50cf7d

	measure 'Sum(INSURANCE_COVERED)' = SUM('BILLS'[INSURANCE_COVERED])
		formatString: "#,##0"
		lineageTag: 1ac58271-09a6-5585-b474-4984bdded67d

	column APPOINTMENT_ID = BLANK()
		dataType: string
		lineageTag: 883ef188-7697-5874-b3c8-7e32e1b6eebb
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column APPOINTMENTS_PATIENT_ID = BLANK()
		dataType: string
		lineageTag: db64e741-8f4e-5971-ba6c-6644e7409cfb
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column DOCTOR_ID = BLANK()
		dataType: string
		lineageTag: f9e7839b-83ec-5ea1-bd3a-470b83e9c4f6
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column APPOINTMENTS_DEPARTMENT = BLANK()
		dataType: string
		lineageTag: 7e58d0fe-0559-5742-a25a-4fa73cb73b2d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column APPOINTMENT_DATE = BLANK()
		dataType: dateTime
		lineageTag: 3a2bb733-03bf-52a0-825c-3c7ca39cd51e
		summarizeBy: none
		formatString: M/D/YYYY

		annotation SummarizationSetBy = Automatic

	column APPOINTMENT_TIME = BLANK()
		dataType: string
		lineageTag: 2fbf8281-af40-530c-88cb-7dfa26feb4dd
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column VISIT_STATUS = BLANK()
		dataType: string
		lineageTag: ef4ab6b8-2461-54cb-afe1-49d6d6410254
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column REASON_FOR_VISIT = BLANK()
		dataType: string
		lineageTag: 64628fe0-b764-5a14-b80c-b056b8f62483
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column DIAGNOSIS_CODE = BLANK()
		dataType: string
		lineageTag: 1e06a5b8-d567-51c0-971b-f12ad979d514
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column FOLLOW_UP_REQUIRED = BLANK()
		dataType: double
		lineageTag: a42d4048-9031-59e7-ad43-842b16dca47a
		summarizeBy: sum
		formatString: ###0

		annotation SummarizationSetBy = Automatic

	partition APPOINTMENTS = m
		mode: import
		source =
				let
				    Source = Sql.Database("Medisphere", "<DATABASE>"),
				    Result = Value.NativeQuery(Source, "SELECT ""APPOINTMENT_ID"", ""PATIENT_ID"", ""DOCTOR_ID"", ""DEPARTMENT"", ""APPOINTMENT_DATE"", ""APPOINTMENT_TIME"", ""VISIT_STATUS"", ""REASON_FOR_VISIT"", ""DIAGNOSIS_CODE"", ""FOLLOW_UP_REQUIRED"" FROM ""MEDISPHERE"".""PUBLIC"".""APPOINTMENTS""", null, [EnableFolding=false]),
				    #"Renamed Columns" = Table.RenameColumns(Result, {{"PATIENT_ID", "PATIENT_ID"}, {"DEPARTMENT", "DEPARTMENT"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"APPOINTMENT_ID", type text}, {"APPOINTMENTS_PATIENT_ID", type text}, {"DOCTOR_ID", type text}, {"APPOINTMENTS_DEPARTMENT", type text}, {"APPOINTMENT_DATE", type datetime}, {"APPOINTMENT_TIME", type text}, {"VISIT_STATUS", type text}, {"REASON_FOR_VISIT", type text}, {"DIAGNOSIS_CODE", type text}, {"FOLLOW_UP_REQUIRED", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table