table PATIENTS
	lineageTag: 551dc5ee-9930-5af4-9791-199e0584e4e9

	column PATIENTS_PATIENT_ID = BLANK()
		dataType: string
		lineageTag: 7e54d3da-2dad-5e8e-a7b7-ff6900cb49cb
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column FIRST_NAME = BLANK()
		dataType: string
		lineageTag: a2a82c43-b868-5126-8bb1-ce05d7451d2f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column LAST_NAME = BLANK()
		dataType: string
		lineageTag: b2d80cf4-cd09-5bbe-841b-97b231227c2d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column DATE_OF_BIRTH = BLANK()
		dataType: dateTime
		lineageTag: c7647f82-eb68-5240-a6a0-12dfbcb97b0e
		summarizeBy: none
		formatString: M/D/YYYY

		annotation SummarizationSetBy = Automatic

	column GENDER = BLANK()
		dataType: string
		lineageTag: 3fc8fe67-6d7b-5e6e-81e0-8da129b01a42
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column CONTACT_NUMBE = BLANK()
		dataType: string
		lineageTag: 291d6d16-c915-5626-9971-6bf9250a4762
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column PATIENTS_EMAIL_ADDRESS = BLANK()
		dataType: string
		lineageTag: 8310ce72-baa8-5a7a-abe5-d14bec304ed3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column ADDRESS = BLANK()
		dataType: string
		lineageTag: 5f3517f3-3e75-5829-bf6f-de20706af131
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column INURANCE_PROVIDER = BLANK()
		dataType: string
		lineageTag: e35a3a6d-30c6-5ee7-bb0e-55ce9b362def
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column INSURANCE_POLICY = BLANK()
		dataType: string
		lineageTag: 6f736b18-e2af-5de3-a124-5687e52a2ccf
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition PATIENTS = m
		mode: import
		source =
				let
				    Source = Sql.Database("Medisphere", "<DATABASE>"),
				    Result = Value.NativeQuery(Source, "SELECT ""PATIENT_ID"", ""FIRST_NAME"", ""LAST_NAME"", ""DATE_OF_BIRTH"", ""GENDER"", ""CONTACT_NUMBE"", ""EMAIL_ADDRESS"", ""ADDRESS"", ""INURANCE_PROVIDER"", ""INSURANCE_POLICY"" FROM ""MEDISPHERE"".""PUBLIC"".""PATIENTS""", null, [EnableFolding=false]),
				    #"Renamed Columns" = Table.RenameColumns(Result, {{"PATIENT_ID", "PATIENT_ID"}, {"EMAIL_ADDRESS", "EMAIL_ADDRESS"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"PATIENTS_PATIENT_ID", type text}, {"FIRST_NAME", type text}, {"LAST_NAME", type text}, {"DATE_OF_BIRTH", type text}, {"GENDER", type text}, {"CONTACT_NUMBE", type text}, {"PATIENTS_EMAIL_ADDRESS", type text}, {"ADDRESS", type text}, {"INURANCE_PROVIDER", type text}, {"INSURANCE_POLICY", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
