table APPOINTMENTS
	lineageTag: 69609ee4-5f0e-457e-b187-b562b51fd1ae

	measure 'Doctor Rank' =
			RANKX(
			    ALLSELECTED('APPOINTMENTS'[Doctor Id]),
			    CALCULATE(DISTINCTCOUNT('APPOINTMENTS'[Appointment Id])),
			    ,
			    DESC,
			    DENSE
			)

	measure 'RLS Filter' =
			VAR _DoctorId = SELECTEDVALUE('DOCTOR_ACCESS'[Doctor Id (Doctor Access)])
			VAR _Username = SELECTEDVALUE('DOCTOR_ACCESS'[Username])
			RETURN IF(_DoctorId & "" = "ALL", 1, IF(USERNAME() & "" = _Username & "", 1, 0))

	measure RLS_Filter_WB =
			VAR _DoctorAccessId = SELECTEDVALUE('DOCTOR_ACCESS'[Doctor Id (Doctor Access)])
			RETURN
			IF(
			    _DoctorAccessId & "" = "ALL",
			    1,
			    IF(
			        SELECTEDVALUE('APPOINTMENTS'[Doctor Id]) & "" = _DoctorAccessId & "",
			        1,
			        0
			    )
			)

	measure 'Retention Rate' =
			DIVIDE(
			    SUMX(VALUES('APPOINTMENTS'[Patient Id]), [Returning Patient Flag]),
			    DISTINCTCOUNT('APPOINTMENTS'[Patient Id])
			)

	measure 'CNTD of Appointment Id' = DISTINCTCOUNT('APPOINTMENTS'[Appointment Id])

	measure Appointments = DISTINCTCOUNT('APPOINTMENTS'[Appointment Id])

	measure 'MONTH of Appointment Date' = MONTH('APPOINTMENTS'[Appointment Date])

	measure 'CNTD of Patient Id' = DISTINCTCOUNT('APPOINTMENTS'[Patient Id])

	measure Open_Department_Info_WebPage =
			VAR url1 = "https://en.wikipedia.org/wiki/" & SELECTEDVALUE('APPOINTMENTS'[Department])
			RETURN
			"<iframe src='" & url1 & "' width='100%' height='600'></iframe>"

	measure 'Appointments per Department' = CALCULATE(DISTINCTCOUNT('APPOINTMENTS'[Appointment Id]), ALLEXCEPT('APPOINTMENTS', 'APPOINTMENTS'[Department]))

	measure 'Top N Department Filter' =
			CALCULATE(
			    MINX(
			        VALUES('APPOINTMENTS'[Department]),
			        IF(
			            CALCULATE(COUNT('APPOINTMENTS'[Appointment Id])) >= SELECTEDVALUE('Top N Departments'[Value]),
			            CALCULATE(COUNT('APPOINTMENTS'[Appointment Id])),
			            BLANK()
			        )
			    ),
			    REMOVEFILTERS('APPOINTMENTS')
			)

	measure 'Total Appointments (Fixed)' = CALCULATE(DISTINCTCOUNT('APPOINTMENTS'[Appointment Id]))

	measure 'Total Patients (Fixed)' = CALCULATE(DISTINCTCOUNT('APPOINTMENTS'[Patient Id]))

	measure 'Patient Type' =
			VAR _FirstAppointmentDate =
			CALCULATE(
			    MIN('APPOINTMENTS'[Appointment Date]),
			    ALLEXCEPT('APPOINTMENTS', 'APPOINTMENTS'[Patient Id])
			)
			RETURN
			IF(
			    _FirstAppointmentDate = SELECTEDVALUE('APPOINTMENTS'[Appointment Date]),
			    "New Patient",
			    "Returning Patient"
			)

	measure 'Returning Patient Flag' =
			VAR _PatientAppointmentCount = CALCULATE(DISTINCTCOUNT('APPOINTMENTS'[Appointment Id]), ALLEXCEPT('APPOINTMENTS', 'APPOINTMENTS'[Patient Id]))
			RETURN IF(_PatientAppointmentCount > 1, 1, 0)

	column 'Appointment Id'
		dataType: string
		lineageTag: adbc40c6-d01c-442e-8884-b09cc7ef25e1
		summarizeBy: none
		sourceColumn: Appointment Id

	column 'Patient Id'
		dataType: string
		lineageTag: d664e64a-6d56-4dfe-a895-b00abb085ea4
		summarizeBy: none
		sourceColumn: Patient Id

	column 'Doctor Id'
		dataType: string
		lineageTag: 3a660896-52a4-4666-a5c8-ef054f78804b
		summarizeBy: none
		sourceColumn: Doctor Id

	column Department
		dataType: string
		lineageTag: 0e583fa3-dd71-407e-970f-415f5e357e09
		summarizeBy: none
		sourceColumn: Department

	column 'Appointment Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: f3b1d7eb-939d-4962-905f-6fffe67a4c9a
		summarizeBy: none
		sourceColumn: Appointment Date

		variation Variation
			isDefault
			relationship: dd2161af-066e-4304-a9da-5f8e31ea5abf
			defaultHierarchy: LocalDateTable_1ada9aa9-b707-4bb1-93be-cf47de475437.'Date Hierarchy'

		changedProperty = DataType

		annotation UnderlyingDateTimeDataType = Date

	column 'Appointment Time'
		dataType: dateTime
		formatString: General Date
		lineageTag: 45a3713f-9d4c-41fe-bbb8-d2cc9deb5776
		summarizeBy: none
		sourceColumn: Appointment Time

		variation Variation
			isDefault
			relationship: 6c715226-17f4-49c8-8ad2-ab69b1a5df7f
			defaultHierarchy: LocalDateTable_a7a1b85e-6386-4d11-bb7d-c72d32f3939f.'Date Hierarchy'

		changedProperty = DataType

		annotation UnderlyingDateTimeDataType = Date

	column 'Visit Status'
		dataType: string
		lineageTag: 76d0d595-b4a2-4a0a-90d9-bb353a15b1e9
		summarizeBy: none
		sourceColumn: Visit Status

	column 'Reason For Visit'
		dataType: string
		lineageTag: 6da3d26b-f3c6-4ea5-9552-7880688b24ef
		summarizeBy: none
		sourceColumn: Reason For Visit

	column 'Diagnosis Code'
		dataType: string
		lineageTag: 9c8e34cf-4fdb-4c64-baf2-221200390cff
		summarizeBy: none
		sourceColumn: Diagnosis Code

	column 'Follow Up Required'
		dataType: boolean
		lineageTag: 66c4427e-d99a-4554-b52a-1228c0f43c95
		summarizeBy: none
		sourceColumn: Follow Up Required

	column in_out_Department_Set_Category = IF('APPOINTMENTS'[Department] IN { "Inpatient", "Outpatient" }, "In", "Out")
		dataType: string
		summarizeBy: none

	column 'Department Focus' = IF('APPOINTMENTS'[in_out_Department_Set_Category] = "In", "Selected", "Other")
		dataType: string
		summarizeBy: none

	column 'Day of Week' = FORMAT('APPOINTMENTS'[Appointment Date], "dddd")
		dataType: string
		summarizeBy: none

	partition APPOINTMENTS = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("zldagwo-pw94760.snowflakecomputing.com", "COMPUTE_WH"),
				    DB = Source{[Name="CITY_HOSPITAL"]}[Data],
				    Schema = DB{[Name="PUBLIC"]}[Data],
				    Table = Schema{[Name="APPOINTMENTS"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Table, {{"APPOINTMENT_ID", type text}, {"PATIENT_ID", type text}, {"DOCTOR_ID", type text}, {"DEPARTMENT", type text}, {"APPOINTMENT_DATE", type date}, {"APPOINTMENT_TIME", type datetime}, {"VISIT_STATUS", type text}, {"REASON_FOR_VISIT", type text}, {"DIAGNOSIS_CODE", type text}, {"FOLLOW_UP_REQUIRED", type logical}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"APPOINTMENT_ID", "Appointment Id"}, {"PATIENT_ID", "Patient Id"}, {"DOCTOR_ID", "Doctor Id"}, {"DEPARTMENT", "Department"}, {"APPOINTMENT_DATE", "Appointment Date"}, {"APPOINTMENT_TIME", "Appointment Time"}, {"VISIT_STATUS", "Visit Status"}, {"REASON_FOR_VISIT", "Reason For Visit"}, {"DIAGNOSIS_CODE", "Diagnosis Code"}, {"FOLLOW_UP_REQUIRED", "Follow Up Required"}})
				in
				    #"Renamed Columns"

