table BILLS
	lineageTag: 94422e0b-a404-42fd-8749-2e3fdb2563df

	measure 'Total Revenue' = SUM('BILLS'[Total Amount])

	measure 'SUM of Total Amount (BILLS)' = SUM('BILLS'[Total Amount])

	measure 'MONTH of Billing Date (BILLS)' = MONTH('BILLS'[Billing Date])

	measure 'CNT of Bill Id (BILLS)' = CNT('BILLS'[Bill Id])

	column 'Bill Id'
		dataType: string
		lineageTag: dac3b36a-c472-4165-b425-d811613ae9ba
		summarizeBy: none
		sourceColumn: Bill Id

	column 'Patient Id (Bills)'
		dataType: string
		lineageTag: 25c3b123-8388-4390-a06d-baff0259da5e
		summarizeBy: none
		sourceColumn: Patient Id (Bills)

	column 'Appointment Id (Bills)'
		dataType: string
		lineageTag: fcab8543-347c-41c5-ba32-f2f625e16cea
		summarizeBy: none
		sourceColumn: Appointment Id (Bills)

	column 'Treatment Id (Bills)'
		dataType: string
		lineageTag: 9e179253-43e1-4923-8427-4cbf2024d938
		summarizeBy: none
		sourceColumn: Treatment Id (Bills)

	column 'Billing Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6b4573cd-625b-4913-b934-39eb8ae81168
		summarizeBy: none
		sourceColumn: Billing Date

		variation Variation
			isDefault
			relationship: f74a5c71-11e4-4d65-9af9-82eb2316b8c6
			defaultHierarchy: LocalDateTable_98c57e0d-82ef-49b7-8eb5-69bdb771b6e7.'Date Hierarchy'

		changedProperty = DataType

		annotation UnderlyingDateTimeDataType = Date

	column 'Total Amount'
		dataType: double
		lineageTag: b6bb378b-b4b7-407e-bb25-43b1824ebd8a
		summarizeBy: none
		sourceColumn: Total Amount

	column 'Insurance Covered'
		dataType: double
		lineageTag: bafdbd6c-49fa-4813-9e0a-3de9bbe76333
		summarizeBy: none
		sourceColumn: Insurance Covered

	column 'Patient Payable'
		dataType: double
		lineageTag: bc070dd7-8134-4390-b904-e907aab986b5
		summarizeBy: none
		sourceColumn: Patient Payable

	column 'Payment Method'
		dataType: string
		lineageTag: f3258553-83d6-4095-b101-e04a4b9c7aff
		summarizeBy: none
		sourceColumn: Payment Method

	column 'Payment Status'
		dataType: string
		lineageTag: 98606318-3190-46db-a829-4ae7e0f5e412
		summarizeBy: none
		sourceColumn: Payment Status

	partition BILLS = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("zldagwo-pw94760.snowflakecomputing.com", "COMPUTE_WH"),
				    DB = Source{[Name="CITY_HOSPITAL"]}[Data],
				    Schema = DB{[Name="PUBLIC"]}[Data],
				    Table = Schema{[Name="BILLS"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Table, {{"BILL_ID", type text}, {"PATIENT_ID", type text}, {"APPOINTMENT_ID", type text}, {"TREATMENT_ID", type text}, {"BILLING_DATE", type date}, {"TOTAL_AMOUNT", type number}, {"INSURANCE_COVERED", type number}, {"PATIENT_PAYABLE", type number}, {"PAYMENT_METHOD", type text}, {"PAYMENT_STATUS", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"BILL_ID", "Bill Id"}, {"PATIENT_ID", "Patient Id (Bills)"}, {"APPOINTMENT_ID", "Appointment Id (Bills)"}, {"TREATMENT_ID", "Treatment Id (Bills)"}, {"BILLING_DATE", "Billing Date"}, {"TOTAL_AMOUNT", "Total Amount"}, {"INSURANCE_COVERED", "Insurance Covered"}, {"PATIENT_PAYABLE", "Patient Payable"}, {"PAYMENT_METHOD", "Payment Method"}, {"PAYMENT_STATUS", "Payment Status"}})
				in
				    #"Renamed Columns"

