table 'Custom SQL Query'
	lineageTag: dcd22e8d-a401-470e-a9d1-5b74d234aa31

	column 'APPOINTMENT_ID (Custom SQL Query)'
		dataType: string
		lineageTag: d0c4c38d-43d2-4d2b-8b0c-b6afe4f6e211
		summarizeBy: none
		sourceColumn: APPOINTMENT_ID (Custom SQL Query)

	column 'PATIENT_ID (Custom SQL Query)'
		dataType: string
		lineageTag: d8000999-cfd6-4407-a165-8b6bba6906c3
		summarizeBy: none
		sourceColumn: PATIENT_ID (Custom SQL Query)

	column 'DEPARTMENT (Custom SQL Query)'
		dataType: string
		lineageTag: fff6fe16-066c-4c5d-957d-cf136712abbf
		summarizeBy: none
		sourceColumn: DEPARTMENT (Custom SQL Query)

	column 'TOTAL_AMOUNT (Custom SQL Query)'
		dataType: double
		lineageTag: 757e2f28-fd2f-49ff-8b58-43b69a582470
		summarizeBy: none
		sourceColumn: TOTAL_AMOUNT (Custom SQL Query)

	column 'INSURANCE_COVERED (Custom SQL Query)'
		dataType: double
		lineageTag: 41b35dac-6a65-44f2-af96-6e857422bf6d
		summarizeBy: none
		sourceColumn: INSURANCE_COVERED (Custom SQL Query)

	column 'PATIENT_PAYABLE (Custom SQL Query)'
		dataType: double
		lineageTag: 55c32f3e-54f0-41a3-b5e5-6201c1a1ff74
		summarizeBy: none
		sourceColumn: PATIENT_PAYABLE (Custom SQL Query)

	column PAYMENT_CATEGORY
		dataType: string
		lineageTag: 728f62a8-e174-410e-9881-ce8429c8c14f
		summarizeBy: none
		sourceColumn: PAYMENT_CATEGORY

	partition 'Custom SQL Query' = m
		mode: import
		source =
				let Source = Snowflake.Databases("zldagwo-pw94760.snowflakecomputing.com", "COMPUTE_WH"),
				DB = Source{[Name="CITY_HOSPITAL"]}[Data],
				Custom_SQL_Query = Value.NativeQuery(DB, "SELECT a.Appointment_Id, a.Patient_Id, a.Department, b.Total_Amount, b.Insurance_Covered, b.Patient_Payable, CASE WHEN b.Insurance_Covered > 0 THEN 'Insurance' ELSE 'Self Pay' END AS Payment_Category FROM APPOINTMENTS a LEFT JOIN BILLS b ON a.Appointment_Id = b.Appointment_Id"),
				                #"Renamed Columns" = Table.RenameColumns(Custom_SQL_Query, {{"APPOINTMENT_ID", "APPOINTMENT_ID (Custom SQL Query)"}, {"PATIENT_ID", "PATIENT_ID (Custom SQL Query)"}, {"DEPARTMENT", "DEPARTMENT (Custom SQL Query)"}, {"TOTAL_AMOUNT", "TOTAL_AMOUNT (Custom SQL Query)"}, {"INSURANCE_COVERED", "INSURANCE_COVERED (Custom SQL Query)"}, {"PATIENT_PAYABLE", "PATIENT_PAYABLE (Custom SQL Query)"}})
				            in
				                #"Renamed Columns"

