table PATIENTS
	lineageTag: bc1c4894-e504-465d-86c3-b61f0d577c09

	column 'Patient Id (Patients)'
		dataType: string
		lineageTag: 19133bd7-0a42-45fd-8f95-1c18e7e16083
		summarizeBy: none
		sourceColumn: Patient Id (Patients)

	column 'First Name'
		dataType: string
		lineageTag: 58e6eacd-b831-4223-8bd6-dc7a99a338bc
		summarizeBy: none
		sourceColumn: First Name

	column 'Last Name'
		dataType: string
		lineageTag: 506a8981-0584-4694-bf5b-8f57654d77a4
		summarizeBy: none
		sourceColumn: Last Name

	column 'Date Of Birth'
		dataType: string
		lineageTag: f123dd94-d53d-4db3-a913-fd0efaacbb88
		summarizeBy: none
		sourceColumn: Date Of Birth

	column Gender
		dataType: string
		lineageTag: 1cea32b5-a088-4543-ae50-0002e6eec224
		summarizeBy: none
		sourceColumn: Gender

	column 'Contact Number'
		dataType: string
		lineageTag: 6f9c6e65-9810-446b-bf8e-a63033412751
		summarizeBy: none
		sourceColumn: Contact Number

	column 'Email Address'
		dataType: string
		lineageTag: c20cbe0f-4087-4374-a994-cfb4965190b9
		summarizeBy: none
		sourceColumn: Email Address

	column Address
		dataType: string
		lineageTag: a802bf57-d52b-4abc-85ee-5cf5c1d4da46
		summarizeBy: none
		sourceColumn: Address

	column 'Insurance Provider'
		dataType: string
		lineageTag: 8e92e8ce-29e3-4bb4-8913-693e7ceeb368
		summarizeBy: none
		sourceColumn: Insurance Provider

	column 'Insurance Policy No'
		dataType: string
		lineageTag: 8314ebff-aa9f-4f8f-9c1d-6182cd6f5527
		summarizeBy: none
		sourceColumn: Insurance Policy No

	partition PATIENTS = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("zldagwo-pw94760.snowflakecomputing.com", "COMPUTE_WH"),
				    DB = Source{[Name="CITY_HOSPITAL"]}[Data],
				    Schema = DB{[Name="PUBLIC"]}[Data],
				    Table = Schema{[Name="PATIENTS"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Table, {{"PATIENT_ID", type text}, {"FIRST_NAME", type text}, {"LAST_NAME", type text}, {"DATE_OF_BIRTH", type text}, {"GENDER", type text}, {"CONTACT_NUMBER", type text}, {"EMAIL_ADDRESS", type text}, {"ADDRESS", type text}, {"INSURANCE_PROVIDER", type text}, {"INSURANCE_POLICY_NO", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"PATIENT_ID", "Patient Id (Patients)"}, {"FIRST_NAME", "First Name"}, {"LAST_NAME", "Last Name"}, {"DATE_OF_BIRTH", "Date Of Birth"}, {"GENDER", "Gender"}, {"CONTACT_NUMBER", "Contact Number"}, {"EMAIL_ADDRESS", "Email Address"}, {"ADDRESS", "Address"}, {"INSURANCE_PROVIDER", "Insurance Provider"}, {"INSURANCE_POLICY_NO", "Insurance Policy No"}})
				in
				    #"Renamed Columns"

