table STUDENT_COURSES
	lineageTag: 96c79548-a8d5-57b1-9195-f39b3f903dd9

	column COURSE_ID = BLANK()
		dataType: string
		lineageTag: 62433727-e85f-5d14-ac8a-25a002689bb0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column STUDENT_ID = BLANK()
		dataType: string
		lineageTag: 3701eeb4-b6c9-562d-9d47-b586098f492c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition STUDENT_COURSES = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("gq37595.ap-southeast-7.aws.snowflakecomputing.com", "COMPUTE_WH"),
				    Db = Source{[Name="LEARNING_ANALYTICS",Kind="Database"]}[Data],
				    Result = Value.NativeQuery(Db, "SELECT ""STUDENT_ID"", ""COURSE_ID"" FROM ""LEARNING_ANALYTICS"".""PUBLIC"".""STUDENT_COURSES""", null, [EnableFolding=false]),
				    #"Changed Type" = Table.TransformColumnTypes(Result, {{"COURSE_ID", type text}, {"STUDENT_ID", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
