table 'patients'
    lineageTag: d35f3138-8152-4ec0-80df-3091209b0fe9

    column 'Id (patients)'
        dataType: string
        lineageTag: 2067deca-a47f-442a-a2d0-ba4929766c6f
        summarizeBy: none
        sourceColumn: Id (patients)

    column 'Birthdate'
        sourceColumn: Birthdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: 91b31874-b183-4835-8fad-82648b6a3f90
        summarizeBy: none

        variation Variation
            isDefault
            relationship: d2e880a5-18a8-48fb-a449-ffed543903e1
            defaultHierarchy: LocalDateTable_eaa779d0-8a8a-443c-b25a-45e82990a4f1.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Deathdate'
        sourceColumn: Deathdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: 3ec9eaf3-241c-4a43-8b7a-0b3f3134329f
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 16c5785a-adc5-4532-af57-4625249520e7
            defaultHierarchy: LocalDateTable_040fdfa6-de2b-4ce4-aed8-143f57ab0f0f.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Prefix'
        dataType: string
        lineageTag: 5fa90302-7423-4c8f-a5d6-cbe38786bc06
        summarizeBy: none
        sourceColumn: Prefix

    column 'First'
        dataType: string
        lineageTag: aa427161-7d5d-4be5-99d0-6ce51a2d66f0
        summarizeBy: none
        sourceColumn: First

    column 'Last'
        dataType: string
        lineageTag: 05305adc-9509-4ca8-bf2a-0f0742a9c81c
        summarizeBy: none
        sourceColumn: Last

    column 'Suffix'
        dataType: string
        lineageTag: 0fb59e66-a168-46d3-bd18-8eb5eb345a9d
        summarizeBy: none
        sourceColumn: Suffix

    column 'Maiden'
        dataType: string
        lineageTag: 4bf0d0a3-18c0-442f-95f9-19160651feba
        summarizeBy: none
        sourceColumn: Maiden

    column 'Marital'
        dataType: string
        lineageTag: b69eb832-4763-43c6-b8ed-57f5a5b64d32
        summarizeBy: none
        sourceColumn: Marital

    column 'Race'
        dataType: string
        lineageTag: 77c6b8a6-906d-4376-88e7-9c173c3cd45e
        summarizeBy: none
        sourceColumn: Race

    column 'Ethnicity'
        dataType: string
        lineageTag: 76b8b5a7-3109-4d72-9934-362ddbaf7f1e
        summarizeBy: none
        sourceColumn: Ethnicity

    column 'Gender'
        dataType: string
        lineageTag: 060788e5-2a38-407c-bae7-96e68dbb31a4
        summarizeBy: none
        sourceColumn: Gender

    column 'Birthplace'
        dataType: string
        lineageTag: 8280ea8a-b9e7-4d23-ba90-f99d8bbeea2c
        summarizeBy: none
        sourceColumn: Birthplace

    column 'Address'
        dataType: string
        lineageTag: b71a71dd-5d44-455c-8720-85399f30fe63
        summarizeBy: none
        sourceColumn: Address

    column 'City'
        dataType: string
        lineageTag: 48f35e1b-468f-4e10-bd78-3ab56bc35011
        summarizeBy: none
        sourceColumn: City

    column 'State'
        dataType: string
        lineageTag: a3cfaaf2-ab64-4fdf-88e3-3638aaebccbd
        summarizeBy: none
        sourceColumn: State

    column 'County'
        dataType: string
        lineageTag: 4b37a472-6a94-46a0-9841-b16844cf274e
        summarizeBy: none
        sourceColumn: County

    column 'ZIP (organizations)'
        dataType: double
        lineageTag: 27ff571b-1888-41b7-ae69-f3ec4a70289a
        summarizeBy: none
        sourceColumn: ZIP (organizations)

    column 'LAT (organizations)'
        dataType: double
        lineageTag: 93987e9b-dcf4-47ad-810e-045727c8b4fa
        summarizeBy: none
        sourceColumn: LAT (organizations)

    column 'LON (organizations)'
        dataType: double
        lineageTag: cce268a2-a61a-4dac-abf4-c6e4641457b9
        summarizeBy: none
        sourceColumn: LON (organizations)

    measure 'Patient Visits Rank (Top N Patients)' =
        RANKX(ALLSELECTED('patients'[Id (patients)1]), [Visits per Patient], , DESC, DENSE)


    measure 'SUM of Avg Visits per Patient (patients)' =
        SUM('patients'[Avg Visits per Patient])


    measure 'Total Patients (LOD)' =
        CALCULATE(DISTINCTCOUNT('patients'[Id (patients)1]), REMOVEFILTERS('patients'))


    measure 'Avg Visits per Patient' =
        CALCULATE(AVERAGEX(VALUES('patients'[Id (patients)1]), [Visits per Patient]), ALLEXCEPT('patients', 'patients'[Gender]))


    partition 'patients' = m
        mode: import
        source =
            let
                Source = GoogleSheets.Contents("None"),
                #"Navigation 1" = Source{[name = "patients", ItemKind = "Table"]}[Data],
                #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
                #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Id", type text}, {"BIRTHDATE", type date}, {"DEATHDATE", type date}, {"PREFIX", type text}, {"FIRST", type text}, {"LAST", type text}, {"SUFFIX", type text}, {"MAIDEN", type text}, {"MARITAL", type text}, {"RACE", type text}, {"ETHNICITY", type text}, {"GENDER", type text}, {"BIRTHPLACE", type text}, {"ADDRESS", type text}, {"CITY", type text}, {"STATE", type text}, {"COUNTY", type text}, {"ZIP", type number}, {"LAT", type number}, {"LON", type number}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"Id", "Id (patients)"}, {"BIRTHDATE", "Birthdate"}, {"DEATHDATE", "Deathdate"}, {"PREFIX", "Prefix"}, {"FIRST", "First"}, {"LAST", "Last"}, {"SUFFIX", "Suffix"}, {"MAIDEN", "Maiden"}, {"MARITAL", "Marital"}, {"RACE", "Race"}, {"ETHNICITY", "Ethnicity"}, {"GENDER", "Gender"}, {"BIRTHPLACE", "Birthplace"}, {"ADDRESS", "Address"}, {"CITY", "City"}, {"STATE", "State"}, {"COUNTY", "County"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}})
            in
                #"Renamed Columns"
