table 'procedures'
    lineageTag: 492608dc-14c1-46c5-b9ba-a3b403507483

    column 'START (procedures)'
        dataType: string
        lineageTag: 529b6561-b5cc-48dc-bcae-66ab75b0fb51
        summarizeBy: none
        sourceColumn: START (procedures)

    column 'STOP (procedures)'
        dataType: string
        lineageTag: 911fd841-15ee-4322-9263-f5cc3aacdcd6
        summarizeBy: none
        sourceColumn: STOP (procedures)

    column 'PATIENT (procedures)'
        dataType: string
        lineageTag: 0bcdf665-6112-4d1d-9a2b-323cebf0113f
        summarizeBy: none
        sourceColumn: PATIENT (procedures)

    column 'Encounter'
        dataType: string
        lineageTag: 2a727152-6e33-4f6a-9771-93ccbea0ddfb
        summarizeBy: none
        sourceColumn: Encounter

    column 'CODE (procedures)'
        dataType: double
        lineageTag: f68bf4e0-2380-41f4-849b-a76d2ce28624
        summarizeBy: none
        sourceColumn: CODE (procedures)

    column 'DESCRIPTION (procedures)'
        dataType: string
        lineageTag: fb1a2d6f-ebef-4408-bb7b-f3cc9853151d
        summarizeBy: none
        sourceColumn: DESCRIPTION (procedures)

    column 'Base Cost'
        dataType: double
        lineageTag: c806042c-6ea6-492b-b377-d988215e49e2
        summarizeBy: none
        sourceColumn: Base Cost

    column 'REASONCODE (procedures)'
        dataType: double
        lineageTag: ce77e254-4d37-4a28-ae21-77217bf1c7cd
        summarizeBy: none
        sourceColumn: REASONCODE (procedures)

    column 'REASONDESCRIPTION (procedures)'
        dataType: string
        lineageTag: ce81d174-6c13-489c-a2e3-1edc14fc414f
        summarizeBy: none
        sourceColumn: REASONDESCRIPTION (procedures)

    column 'DESCRIPTION__procedures__Set_Category' = IF('procedures'[DESCRIPTION (procedures)] IN { "Admission to burn unit", "Admission to long stay hospital", "Admission to orthopedic department", "Admission to trauma surgery department", "Ankle X-ray", "Antenatal RhD antibody screening", "Assessment of health and social care needs (procedure)" }, "In", "Out")
        dataType: string

        summarizeBy: none

    measure 'Procedure Rank(Top N Procedure Parameter)' =
        RANKX(ALLSELECTED('procedures'[DESCRIPTION (procedures)]), CALCULATE(COUNT('procedures'[CODE (procedures)])), , DESC, DENSE)


    partition 'procedures' = m
        mode: import
        source =
            let
                Source = GoogleSheets.Contents("None"),
                #"Navigation 1" = Source{[name = "procedures", ItemKind = "Table"]}[Data],
                #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
                #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"START", type text}, {"STOP", type text}, {"PATIENT", type text}, {"ENCOUNTER", type text}, {"CODE", type number}, {"DESCRIPTION", type text}, {"BASE_COST", type number}, {"REASONCODE", type number}, {"REASONDESCRIPTION", type text}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"START", "START (procedures)"}, {"STOP", "STOP (procedures)"}, {"PATIENT", "PATIENT (procedures)"}, {"ENCOUNTER", "Encounter"}, {"CODE", "CODE (procedures)"}, {"DESCRIPTION", "DESCRIPTION (procedures)"}, {"BASE_COST", "Base Cost"}, {"REASONCODE", "REASONCODE (procedures)"}, {"REASONDESCRIPTION", "REASONDESCRIPTION (procedures)"}})
            in
                #"Renamed Columns"
