table 'encounters'
    lineageTag: 4b226b61-bd64-4d0e-a38e-b7b8d28ad575

    column 'Id'
        dataType: string
        lineageTag: ebd77216-f0a1-4c9d-af24-ef5a9966778c
        summarizeBy: none
        sourceColumn: Id

    column 'Start'
        dataType: string
        lineageTag: 816166b6-7b9d-42f2-92de-17dd29a3c6e3
        summarizeBy: none
        sourceColumn: Start

    column 'Stop'
        dataType: string
        lineageTag: c1f62e9c-b5ca-4dac-9614-0fbb032a2f37
        summarizeBy: none
        sourceColumn: Stop

    column 'Patient'
        dataType: string
        lineageTag: 00a31bf4-06d3-4b3e-bd16-cc21041d0742
        summarizeBy: none
        sourceColumn: Patient

    column 'Organization'
        dataType: string
        lineageTag: 7aaf9a79-9755-49c5-8b50-5134c415165d
        summarizeBy: none
        sourceColumn: Organization

    column 'Payer'
        dataType: string
        lineageTag: 943bf905-cb42-4d06-b1e9-c932f7f0b162
        summarizeBy: none
        sourceColumn: Payer

    column 'Encounterclass'
        dataType: string
        lineageTag: 2cab9303-007e-4a7d-bc81-50431aa94a26
        summarizeBy: none
        sourceColumn: Encounterclass

    column 'Code'
        dataType: double
        lineageTag: 4af3869a-4714-45b1-96d3-b812277c251c
        summarizeBy: none
        sourceColumn: Code

    column 'Description'
        dataType: string
        lineageTag: 543aaf56-3d75-405b-ad9c-3cd07e23daec
        summarizeBy: none
        sourceColumn: Description

    column 'Base Encounter Cost'
        dataType: double
        lineageTag: 7774410f-4d99-4dd8-abe9-87f9ee387272
        summarizeBy: none
        sourceColumn: Base Encounter Cost

    column 'Total Claim Cost'
        dataType: double
        lineageTag: aa9f29bf-36ee-4d93-a13a-d10bdd25fd4d
        summarizeBy: none
        sourceColumn: Total Claim Cost

    column 'Payer Coverage'
        dataType: double
        lineageTag: 2499eb97-9e3f-412b-b767-9ad5b4047e74
        summarizeBy: none
        sourceColumn: Payer Coverage

    column 'Reasoncode'
        dataType: double
        lineageTag: c205e1f5-e0ad-4c9d-9fb7-b83a9e4ffcfa
        summarizeBy: none
        sourceColumn: Reasoncode

    column 'Reasondescription'
        dataType: string
        lineageTag: 48fb44fe-6415-4bdc-bc91-16dbd9d9aa4f
        summarizeBy: none
        sourceColumn: Reasondescription

    column 'Encounter Start Date' = -- ERROR: LLM call failed after 6 retries. Last error: 404 Client Error: Not Found for url: https://api.groq.com/openai/v1/chat/completions
        dataType: dateTime
        formatString: Long Date
        lineageTag: e8509f7c-a45b-4c5c-9dcc-5c135adef123
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 0050d9fa-99b0-427d-af80-635d25f25d20
            defaultHierarchy: LocalDateTable_a6254f69-a699-4eda-b0f7-f281a22aa387.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    measure 'Patient Visits Rank (Top N Patients)' =
        -- ERROR: LLM call failed after 6 retries. Last error: 404 Client Error: Not Found for url: https://api.groq.com/openai/v1/chat/completions


    measure 'Top N Patients' =
        -- ERROR: LLM call failed after 6 retries. Last error: 404 Client Error: Not Found for url: https://api.groq.com/openai/v1/chat/completions


    measure 'Visits % Contribution (LOD)' =
        -- ERROR: LLM call failed after 6 retries. Last error: 404 Client Error: Not Found for url: https://api.groq.com/openai/v1/chat/completions


    measure 'CNT of Id' =
        COUNT('encounters'[Id])


    measure 'Total Visits' =
        COUNT('encounters'[Id])


    measure 'SUM of Base Encounter Cost' =
        SUM('encounters'[Base Encounter Cost])


    measure 'Total Procedures (LOD)' =
        -- ERROR CONVERTING: LLM call failed after 6 retries. Last error: 404 Client Error: Not Found for url: https://api.groq.com/openai/v1/chat/completions


    measure 'Total Visits (LOD)' =
        -- ERROR CONVERTING: LLM call failed after 6 retries. Last error: 404 Client Error: Not Found for url: https://api.groq.com/openai/v1/chat/completions


    partition 'encounters' = m
        mode: import
        source =
            let Source = Excel.Workbook(Web.Contents("https://www.googleapis.com/drive/v3/files/1Sd4bEK0Fm9q7yTVOwI4GdtixeeY8hPkKqpvnI4WdixA/export?mimeType=application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"), null, true),
            #"Navigation 1" = Source{[Item="encounters",Kind="Sheet"]}[Data],
            #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars=true]),
            #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Id", type text}, {"START", type text}, {"STOP", type text}, {"PATIENT", type text}, {"ORGANIZATION", type text}, {"PAYER", type text}, {"ENCOUNTERCLASS", type text}, {"CODE", type number}, {"DESCRIPTION", type text}, {"BASE_ENCOUNTER_COST", type number}, {"TOTAL_CLAIM_COST", type number}, {"PAYER_COVERAGE", type number}, {"REASONCODE", type number}, {"REASONDESCRIPTION", type text}}),
            #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"START", "Start"}, {"STOP", "Stop"}, {"PATIENT", "Patient"}, {"ORGANIZATION", "Organization"}, {"PAYER", "Payer"}, {"ENCOUNTERCLASS", "Encounterclass"}, {"CODE", "Code"}, {"DESCRIPTION", "Description"}, {"BASE_ENCOUNTER_COST", "Base Encounter Cost"}, {"TOTAL_CLAIM_COST", "Total Claim Cost"}, {"PAYER_COVERAGE", "Payer Coverage"}, {"REASONCODE", "Reasoncode"}, {"REASONDESCRIPTION", "Reasondescription"}}),
                            #"Renamed Columns" = Table.RenameColumns(#"Renamed Columns", {{"START", "Start"}, {"STOP", "Stop"}, {"PATIENT", "Patient"}, {"ORGANIZATION", "Organization"}, {"PAYER", "Payer"}, {"ENCOUNTERCLASS", "Encounterclass"}, {"CODE", "Code"}, {"DESCRIPTION", "Description"}, {"BASE_ENCOUNTER_COST", "Base Encounter Cost"}, {"TOTAL_CLAIM_COST", "Total Claim Cost"}, {"PAYER_COVERAGE", "Payer Coverage"}, {"REASONCODE", "Reasoncode"}, {"REASONDESCRIPTION", "Reasondescription"}})
                        in
                            #"Renamed Columns"
