table 'encounters'
    lineageTag: 4f7c3883-eaa2-41ce-9663-c8ccdb3fd89b

    column 'Id'
        dataType: string
        lineageTag: 26a58582-aea9-4c97-a8b4-c363dffe6d0f
        summarizeBy: none
        sourceColumn: Id

    column 'Start'
        dataType: string
        lineageTag: 9a3682ee-fa90-4f3a-99e6-c5f44faf4b1d
        summarizeBy: none
        sourceColumn: Start

    column 'Stop'
        dataType: string
        lineageTag: 9a9d33dd-1e05-45ab-a10b-d8b765ed0f59
        summarizeBy: none
        sourceColumn: Stop

    column 'Patient'
        dataType: string
        lineageTag: 035120f3-4414-4bc3-a58c-a7656a93ee1c
        summarizeBy: none
        sourceColumn: Patient

    column 'Organization'
        dataType: string
        lineageTag: db65661c-bcc8-457d-911e-b26f61728051
        summarizeBy: none
        sourceColumn: Organization

    column 'Payer'
        dataType: string
        lineageTag: f2ae7205-28e0-45c8-9bad-4ca6d0964625
        summarizeBy: none
        sourceColumn: Payer

    column 'Encounterclass'
        dataType: string
        lineageTag: 4243bfa6-8fd8-4871-9e84-9fb9443033a6
        summarizeBy: none
        sourceColumn: Encounterclass

    column 'Code'
        dataType: double
        lineageTag: a80c4286-f4da-407f-a061-933485ff707e
        summarizeBy: none
        sourceColumn: Code

    column 'Description'
        dataType: string
        lineageTag: 478d1c5d-6cec-4c59-8e06-47483e81b021
        summarizeBy: none
        sourceColumn: Description

    column 'Base Encounter Cost'
        dataType: double
        lineageTag: fcbfe04a-3752-4da8-8581-3397fb7bb042
        summarizeBy: none
        sourceColumn: Base Encounter Cost

    column 'Total Claim Cost'
        dataType: double
        lineageTag: 3019a8ad-a8a6-4422-8c8a-07e242cfca77
        summarizeBy: none
        sourceColumn: Total Claim Cost

    column 'Payer Coverage'
        dataType: double
        lineageTag: 8a155850-ea63-4908-bc05-95038886f077
        summarizeBy: none
        sourceColumn: Payer Coverage

    column 'Reasoncode'
        dataType: double
        lineageTag: 2fdb39f8-9fb4-4fce-bf48-aec175ee96f2
        summarizeBy: none
        sourceColumn: Reasoncode

    column 'Reasondescription'
        dataType: string
        lineageTag: c280d88f-c54e-4a59-80b2-84180cadc941
        summarizeBy: none
        sourceColumn: Reasondescription

    column 'Encounter Start Date' = DATEVALUE(LEFT('encounters'[Start], 10))
        dataType: dateTime
        formatString: Long Date
        lineageTag: 91d49462-9e7e-4935-b1bf-e07f68dc1083
        summarizeBy: none

        variation Variation
            isDefault
            relationship: e9ed738b-9003-4714-8b47-620b9180ea85
            defaultHierarchy: LocalDateTable_0f8f213c-968d-4ad7-a686-e3ecfc4a4dc9.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    measure 'Visits % Contribution (LOD)' =
        DIVIDE(COUNT('encounters'[Id]), CALCULATE([Total Visits (LOD)], ALLSELECTED()), 0)


    measure 'CNT of Id' =
        COUNT('encounters'[Id])


    measure 'Total Visits' =
        COUNT('encounters'[Id])


    measure 'SUM of Visits per Patient' =
        SUM('encounters'[Visits per Patient])


    measure 'SUM of Base Encounter Cost' =
        SUM('encounters'[Base Encounter Cost])


    measure 'Total Procedures (LOD)' =
        CALCULATE(COUNT('encounters'[Code]), REMOVEFILTERS('encounters'))


    measure 'Total Visits (LOD)' =
        CALCULATE(COUNT('encounters'[Id]), REMOVEFILTERS('encounters'))


    measure 'Visits per Patient' =
        CALCULATE(COUNT('encounters'[Id]), REMOVEFILTERS('encounters'), ALLEXCEPT('patients', 'patients'[Id (patients)1]))


    partition 'encounters' = m
        mode: import
        source =
            let
                Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1UFffx5ngb7j1Y2kqRzPCPVA0uvA88GLaftek_fwOjKY/edit"),
                #"Navigation 1" = Source{[name = "encounters", ItemKind = "Table"]}[Data],
                #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
                #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Id", type text}, {"START", type text}, {"STOP", type text}, {"PATIENT", type text}, {"ORGANIZATION", type text}, {"PAYER", type text}, {"ENCOUNTERCLASS", type text}, {"CODE", type number}, {"DESCRIPTION", type text}, {"BASE_ENCOUNTER_COST", type number}, {"TOTAL_CLAIM_COST", type number}, {"PAYER_COVERAGE", type number}, {"REASONCODE", type number}, {"REASONDESCRIPTION", type text}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"START", "Start"}, {"STOP", "Stop"}, {"PATIENT", "Patient"}, {"ORGANIZATION", "Organization"}, {"PAYER", "Payer"}, {"ENCOUNTERCLASS", "Encounterclass"}, {"CODE", "Code"}, {"DESCRIPTION", "Description"}, {"BASE_ENCOUNTER_COST", "Base Encounter Cost"}, {"TOTAL_CLAIM_COST", "Total Claim Cost"}, {"PAYER_COVERAGE", "Payer Coverage"}, {"REASONCODE", "Reasoncode"}, {"REASONDESCRIPTION", "Reasondescription"}})
            in
                #"Renamed Columns"
