table 'organizations'
    lineageTag: ed5e133b-5fe6-45e7-952d-f5ea60c3b473

    column 'Id (organizations)'
        dataType: string
        lineageTag: f8d812f4-34e2-4a7a-825d-1a7eef88fb45
        summarizeBy: none
        sourceColumn: Id (organizations)

    column 'Name'
        dataType: string
        lineageTag: 84590cf1-3c7f-46e2-a8ec-7707ec4d2d37
        summarizeBy: none
        sourceColumn: Name

    column 'ADDRESS (organizations)'
        dataType: string
        lineageTag: bfb23c56-6fc0-4ca9-b13b-165f34dff114
        summarizeBy: none
        sourceColumn: ADDRESS (organizations)

    column 'CITY (organizations)'
        dataType: string
        lineageTag: 4ff58b3b-7e03-4a2b-b9d1-e000ad0b44d5
        summarizeBy: none
        sourceColumn: CITY (organizations)

    column 'STATE (organizations)'
        dataType: string
        lineageTag: 3dbbd6c5-a4c1-4ac7-b881-9f50e96552ad
        summarizeBy: none
        sourceColumn: STATE (organizations)

    column 'ZIP (organizations)'
        dataType: double
        lineageTag: b1c71ff8-7659-45b5-8e5d-f2a4bcaa4198
        summarizeBy: none
        sourceColumn: ZIP (organizations)

    column 'LAT (organizations)'
        dataType: double
        lineageTag: a3f29763-e4ca-4e76-96f2-b77aa5aed2dd
        summarizeBy: none
        sourceColumn: LAT (organizations)

    column 'LON (organizations)'
        dataType: double
        lineageTag: 0fff05a9-e4a9-4f09-96c5-edfaf8d486c9
        summarizeBy: none
        sourceColumn: LON (organizations)

    column 'Username' = 'organizations'[Name]
        dataType: string

        summarizeBy: none

    measure 'RLS - Organization Access' =
        VAR _User = USERNAME()
        RETURN IF(_User = "akash020102@gmail.com", TRUE(), SELECTEDVALUE('organizations'[Name]) = "MASSACHUSETTS GENERAL HOSPITAL")


    partition 'organizations' = m
        mode: import
        source =
            let
                Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1Gfqr930PI28eveUiJrS8ikSsyzDUbPE4pJy7nG9ZIUc/edit"),
                #"Navigation 1" = Source{[name = "organizations", ItemKind = "Table"]}[Data],
                #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
                #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Id", type text}, {"NAME", type text}, {"ADDRESS", type text}, {"CITY", type text}, {"STATE", type text}, {"ZIP", type number}, {"LAT", type number}, {"LON", type number}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"Id", "Id (organizations)"}, {"NAME", "Name"}, {"ADDRESS", "ADDRESS (organizations)"}, {"CITY", "CITY (organizations)"}, {"STATE", "STATE (organizations)"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}})
            in
                #"Renamed Columns"
