table 'patients'
    lineageTag: b5952c66-03f9-46e8-800a-52f9c3df8031

    column 'Id (patients)'
        dataType: string
        lineageTag: 4c81bd63-57bd-41e2-83b3-1874c3b5821c
        summarizeBy: none
        sourceColumn: Id (patients)

    column 'Birthdate'
        sourceColumn: Birthdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: 65c952ac-6202-45c8-af08-884d92210fba
        summarizeBy: none

        variation Variation
            isDefault
            relationship: da63241c-1c38-43c9-91f9-d948492a6fe3
            defaultHierarchy: LocalDateTable_dc590a25-e1bb-41f6-8615-0b8990704d60.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Deathdate'
        sourceColumn: Deathdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: 194abb2f-09af-4cb5-9220-e1b736d153b2
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 532a6291-58db-4193-a029-4b2ffca03a05
            defaultHierarchy: LocalDateTable_4c6bd2c4-91bd-47e5-baac-a07b95329c82.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Prefix'
        dataType: string
        lineageTag: 5f135c98-e854-43cb-90ef-ba0eb63dd290
        summarizeBy: none
        sourceColumn: Prefix

    column 'First'
        dataType: string
        lineageTag: 815e9d44-4346-406c-a8bc-bff9c1a0941e
        summarizeBy: none
        sourceColumn: First

    column 'Last'
        dataType: string
        lineageTag: abadf82d-954c-490b-a965-a4289d101708
        summarizeBy: none
        sourceColumn: Last

    column 'Suffix'
        dataType: string
        lineageTag: 9ee7a168-a727-463a-aacb-09859e95050c
        summarizeBy: none
        sourceColumn: Suffix

    column 'Maiden'
        dataType: string
        lineageTag: 20708311-fae1-4c8f-9461-a9b6e4dba12a
        summarizeBy: none
        sourceColumn: Maiden

    column 'Marital'
        dataType: string
        lineageTag: 60f71b01-5f95-4071-b54c-a6ed52917409
        summarizeBy: none
        sourceColumn: Marital

    column 'Race'
        dataType: string
        lineageTag: 6f3d9818-38d0-4f02-9f9b-09d7d4be18c2
        summarizeBy: none
        sourceColumn: Race

    column 'Ethnicity'
        dataType: string
        lineageTag: 8b58cbff-4905-49a2-98b3-202990a6baf5
        summarizeBy: none
        sourceColumn: Ethnicity

    column 'Gender'
        dataType: string
        lineageTag: 9dd339c9-fb09-4ad7-8545-74fa2d8b42df
        summarizeBy: none
        sourceColumn: Gender

    column 'Birthplace'
        dataType: string
        lineageTag: 5d4e4b7a-8d10-4099-92e6-64e58993babc
        summarizeBy: none
        sourceColumn: Birthplace

    column 'Address'
        dataType: string
        lineageTag: 82f2d082-5922-4b08-b679-5d833e7d6d6e
        summarizeBy: none
        sourceColumn: Address

    column 'City'
        dataType: string
        lineageTag: 73ecb357-8be2-435d-9899-d7c470227a30
        summarizeBy: none
        sourceColumn: City

    column 'State'
        dataType: string
        lineageTag: aa8fa254-d115-4d1d-a11a-edb0c62ad989
        summarizeBy: none
        sourceColumn: State

    column 'County'
        dataType: string
        lineageTag: ec3d9466-3ca6-4cc6-8c30-650d97510564
        summarizeBy: none
        sourceColumn: County

    column 'ZIP (organizations)'
        dataType: double
        lineageTag: d3a07df1-4054-4994-ad47-e8c4852c8a3e
        summarizeBy: none
        sourceColumn: ZIP (organizations)

    column 'LAT (organizations)'
        dataType: double
        lineageTag: 31f3110f-4ee8-413c-a65f-e587025a2917
        summarizeBy: none
        sourceColumn: LAT (organizations)

    column 'LON (organizations)'
        dataType: double
        lineageTag: f100dc6a-8a97-44fd-8086-2861bb1d41f9
        summarizeBy: none
        sourceColumn: LON (organizations)

    measure 'Patient Visits Rank (Top N Patients)' =
        RANKX(ALLSELECTED('patients'[Id (patients)1]), [Visits per Patient], , DESC, DENSE)


    measure 'SUM of Avg Visits per Patient (patients)' =
        SUM('patients'[Avg Visits per Patient])


    measure 'Total Patients (LOD)' =
        CALCULATE(DISTINCTCOUNT('patients'[Id (patients)1]), REMOVEFILTERS('patients'))


    measure 'Avg Visits per Patient' =
        CALCULATE(AVERAGEX(VALUES('patients'[Id (patients)1]), [Visits per Patient]), ALLEXCEPT('patients', 'patients'[Gender]))


    partition 'patients' = m
        mode: import
        source =
            let
                Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1Sd4bEK0Fm9q7yTVOwI4GdtixeeY8hPkKqpvnI4WdixA/edit"),
                #"Navigation 1" = Source{[name = "patients", ItemKind = "Table"]}[Data],
                #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
                #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Id", type text}, {"BIRTHDATE", type date}, {"DEATHDATE", type date}, {"PREFIX", type text}, {"FIRST", type text}, {"LAST", type text}, {"SUFFIX", type text}, {"MAIDEN", type text}, {"MARITAL", type text}, {"RACE", type text}, {"ETHNICITY", type text}, {"GENDER", type text}, {"BIRTHPLACE", type text}, {"ADDRESS", type text}, {"CITY", type text}, {"STATE", type text}, {"COUNTY", type text}, {"ZIP", type number}, {"LAT", type number}, {"LON", type number}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"Id", "Id (patients)"}, {"BIRTHDATE", "Birthdate"}, {"DEATHDATE", "Deathdate"}, {"PREFIX", "Prefix"}, {"FIRST", "First"}, {"LAST", "Last"}, {"SUFFIX", "Suffix"}, {"MAIDEN", "Maiden"}, {"MARITAL", "Marital"}, {"RACE", "Race"}, {"ETHNICITY", "Ethnicity"}, {"GENDER", "Gender"}, {"BIRTHPLACE", "Birthplace"}, {"ADDRESS", "Address"}, {"CITY", "City"}, {"STATE", "State"}, {"COUNTY", "County"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}})
            in
                #"Renamed Columns"
