table 'payers'
    lineageTag: c51a6b15-0d05-40c1-8835-0f1897275f5b

    column 'Id (payers)'
        dataType: string
        lineageTag: dbbde9d6-4e6b-4f42-a25a-afadab63bdd9
        summarizeBy: none
        sourceColumn: Id (payers)

    column 'NAME (payers)'
        dataType: string
        lineageTag: 4a6c6b58-f56a-4d6c-b17e-c79cf08240e2
        summarizeBy: none
        sourceColumn: NAME (payers)

    column 'ADDRESS (payers)'
        dataType: string
        lineageTag: ad756fb4-9581-4fca-866f-5edd0fcbafec
        summarizeBy: none
        sourceColumn: ADDRESS (payers)

    column 'CITY (payers)'
        dataType: string
        lineageTag: 26710a0f-481d-4006-8230-6bae4dea25f4
        summarizeBy: none
        sourceColumn: CITY (payers)

    column 'State Headquartered'
        dataType: string
        lineageTag: 5e30c7b3-1511-4dfd-87c0-fceea1b85cc9
        summarizeBy: none
        sourceColumn: State Headquartered

    column 'ZIP (payers)'
        dataType: double
        lineageTag: c8194490-01a6-43ab-b22b-ba8af26934e5
        summarizeBy: none
        sourceColumn: ZIP (payers)

    column 'Phone'
        dataType: string
        lineageTag: 461eb9a8-14f4-4bb1-9f35-b43c112cd448
        summarizeBy: none
        sourceColumn: Phone

    partition 'payers' = m
        mode: import
        source =
            let
                Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1NB9uAQnBa6RYGfm5addKbcToYUZJY_5OlBkWxVZRrbU/edit"),
                #"Navigation 1" = Source{[name = "payers", ItemKind = "Table"]}[Data],
                #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
                #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Id", type text}, {"NAME", type text}, {"ADDRESS", type text}, {"CITY", type text}, {"STATE_HEADQUARTERED", type text}, {"ZIP", type number}, {"PHONE", type text}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"Id", "Id (payers)"}, {"NAME", "NAME (payers)"}, {"ADDRESS", "ADDRESS (payers)"}, {"CITY", "CITY (payers)"}, {"STATE_HEADQUARTERED", "State Headquartered"}, {"ZIP", "ZIP (payers)"}, {"PHONE", "Phone"}})
            in
                #"Renamed Columns"
