table 'encounters'
    lineageTag: b7fa67f2-5585-423b-8a8b-1731e93cfdc1

    column 'Id'
        dataType: string
        lineageTag: 669dbc10-7ce3-406f-8386-8d3fadf5f6d8
        summarizeBy: none
        sourceColumn: Id

    column 'Start'
        dataType: string
        lineageTag: 35eeb47c-23c9-4bc9-ac21-8a36dd576647
        summarizeBy: none
        sourceColumn: Start

    column 'Stop'
        dataType: string
        lineageTag: 3b81ec2f-3809-4a94-bed1-18232249837a
        summarizeBy: none
        sourceColumn: Stop

    column 'Patient'
        dataType: string
        lineageTag: 4230ad2e-caa9-48fe-84fc-a9ae4dddee48
        summarizeBy: none
        sourceColumn: Patient

    column 'Organization'
        dataType: string
        lineageTag: 0c6b5e6a-6afd-48ec-958e-dee675e62742
        summarizeBy: none
        sourceColumn: Organization

    column 'Payer'
        dataType: string
        lineageTag: d1d689c8-f39c-410c-9fa4-7dca359be2a2
        summarizeBy: none
        sourceColumn: Payer

    column 'Encounterclass'
        dataType: string
        lineageTag: fd9f1c27-f7c1-4d49-ab03-e4a70b0102dd
        summarizeBy: none
        sourceColumn: Encounterclass

    column 'Code'
        dataType: double
        lineageTag: 6c633ca7-ab02-4d4d-8322-f47fd898dd68
        summarizeBy: none
        sourceColumn: Code

    column 'Description'
        dataType: string
        lineageTag: 40e28236-2ebd-47d1-91d5-e01d887f0ce3
        summarizeBy: none
        sourceColumn: Description

    column 'Base Encounter Cost'
        dataType: double
        lineageTag: 15313c99-2582-4890-a073-0ad2a9a4a24d
        summarizeBy: none
        sourceColumn: Base Encounter Cost

    column 'Total Claim Cost'
        dataType: double
        lineageTag: 28b3655b-8108-4c0e-a50f-63d560d8799f
        summarizeBy: none
        sourceColumn: Total Claim Cost

    column 'Payer Coverage'
        dataType: double
        lineageTag: e76d9753-75dd-4364-ab36-aab7c2bb0a46
        summarizeBy: none
        sourceColumn: Payer Coverage

    column 'Reasoncode'
        dataType: double
        lineageTag: 7a457b7a-0c90-426c-a1f0-c50e09a4b0bf
        summarizeBy: none
        sourceColumn: Reasoncode

    column 'Reasondescription'
        dataType: string
        lineageTag: 55e083ad-05c5-43ae-8cfa-c1f46163b80a
        summarizeBy: none
        sourceColumn: Reasondescription

    column 'Encounter Start Date' = -- ERROR: LLM call failed after 6 retries. Last error: 404 Client Error: Not Found for url: https://api.groq.com/openai/v1/chat/completions
        dataType: dateTime
        formatString: Long Date
        lineageTag: cf3ffe84-8aa2-49c6-b52a-b00d66ded870
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 20cc96ce-dbbf-4840-83dd-8bf7d786e25d
            defaultHierarchy: LocalDateTable_1f208541-46f4-47b8-a999-ad1afb47cf29.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    measure 'Patient Visits Rank (Top N Patients)' =
        -- ERROR: LLM call failed after 6 retries. Last error: 404 Client Error: Not Found for url: https://api.groq.com/openai/v1/chat/completions


    measure 'Top N Patients' =
        -- ERROR: LLM call failed after 6 retries. Last error: 404 Client Error: Not Found for url: https://api.groq.com/openai/v1/chat/completions


    measure 'Visits % Contribution (LOD)' =
        -- ERROR: LLM call failed after 6 retries. Last error: 404 Client Error: Not Found for url: https://api.groq.com/openai/v1/chat/completions


    measure 'CNT of Id' =
        COUNT('encounters'[Id])


    measure 'Total Visits' =
        COUNT('encounters'[Id])


    measure 'SUM of Base Encounter Cost' =
        SUM('encounters'[Base Encounter Cost])


    measure 'Total Procedures (LOD)' =
        -- ERROR CONVERTING: LLM call failed after 6 retries. Last error: 404 Client Error: Not Found for url: https://api.groq.com/openai/v1/chat/completions


    measure 'Total Visits (LOD)' =
        -- ERROR CONVERTING: LLM call failed after 6 retries. Last error: 404 Client Error: Not Found for url: https://api.groq.com/openai/v1/chat/completions


    partition 'encounters' = m
        mode: import
        source =
            let Source = Sql.Database("", "Patients.xlsx"),
            #"Navigation 1" = Source{[Schema="[encounters$]",Item="encounters"]}[Data],
                            #"Renamed Columns" = Table.RenameColumns(#"Navigation 1", {{"START", "Start"}, {"STOP", "Stop"}, {"PATIENT", "Patient"}, {"ORGANIZATION", "Organization"}, {"PAYER", "Payer"}, {"ENCOUNTERCLASS", "Encounterclass"}, {"CODE", "Code"}, {"DESCRIPTION", "Description"}, {"BASE_ENCOUNTER_COST", "Base Encounter Cost"}, {"TOTAL_CLAIM_COST", "Total Claim Cost"}, {"PAYER_COVERAGE", "Payer Coverage"}, {"REASONCODE", "Reasoncode"}, {"REASONDESCRIPTION", "Reasondescription"}})
                        in
                            #"Renamed Columns"
