table 'patients'
    lineageTag: edd818a7-e272-4897-b8f5-5be6f3f1ca95

    column 'Id (patients)'
        dataType: string
        lineageTag: d531d4c1-6278-492a-8e27-dce6f253b24d
        summarizeBy: none
        sourceColumn: Id (patients)

    column 'Birthdate'
        sourceColumn: Birthdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: 746d9fd2-a761-4f2d-996b-322cd93c8fb8
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 14bd3174-45ac-4217-abb6-b1f1f4968e6a
            defaultHierarchy: LocalDateTable_bd1bec67-b12e-4eac-968f-e6a07dd4ef84.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Deathdate'
        sourceColumn: Deathdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: 1f6065db-bf1e-4599-9c26-5bee8854d704
        summarizeBy: none

        variation Variation
            isDefault
            relationship: d7c408b3-2e38-466c-aea7-8c3d85dbfe65
            defaultHierarchy: LocalDateTable_2c544ad2-c873-4df7-8baa-1cc11cbcef0c.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Prefix'
        dataType: string
        lineageTag: 8845ac04-9d39-4414-9f4c-0ce7f0d305fe
        summarizeBy: none
        sourceColumn: Prefix

    column 'First'
        dataType: string
        lineageTag: c7ac257f-b184-4eab-86ab-4b73a5300c6d
        summarizeBy: none
        sourceColumn: First

    column 'Last'
        dataType: string
        lineageTag: 100a4869-9710-43a1-b2fb-b1470d662794
        summarizeBy: none
        sourceColumn: Last

    column 'Suffix'
        dataType: string
        lineageTag: 26b72af1-d5d7-4622-89d9-95acf4f48a5e
        summarizeBy: none
        sourceColumn: Suffix

    column 'Maiden'
        dataType: string
        lineageTag: b3dedadc-19ca-437d-99a3-784cb611b4cb
        summarizeBy: none
        sourceColumn: Maiden

    column 'Marital'
        dataType: string
        lineageTag: ec829b18-472c-4d44-8fd4-6161cd121299
        summarizeBy: none
        sourceColumn: Marital

    column 'Race'
        dataType: string
        lineageTag: a5304dc0-3aa9-424d-b53d-0298fa65f1a4
        summarizeBy: none
        sourceColumn: Race

    column 'Ethnicity'
        dataType: string
        lineageTag: 5d7d9c52-afe5-449e-836b-b95e3c31fc16
        summarizeBy: none
        sourceColumn: Ethnicity

    column 'Gender'
        dataType: string
        lineageTag: a3027104-3eee-42f0-a858-676e124b494b
        summarizeBy: none
        sourceColumn: Gender

    column 'Birthplace'
        dataType: string
        lineageTag: 7a326002-0794-435d-83c5-0c824ab63833
        summarizeBy: none
        sourceColumn: Birthplace

    column 'Address'
        dataType: string
        lineageTag: 2d060cc5-9b45-46da-8286-7bbeefd6f4ed
        summarizeBy: none
        sourceColumn: Address

    column 'City'
        dataType: string
        lineageTag: 04f4ae00-546f-46e7-8312-496ab4d9e89f
        summarizeBy: none
        sourceColumn: City

    column 'State'
        dataType: string
        lineageTag: 9f3be39b-92ea-4d84-a909-dc9e1d62d359
        summarizeBy: none
        sourceColumn: State

    column 'County'
        dataType: string
        lineageTag: c94afb1a-b1f9-41dd-baca-c7fd5d203969
        summarizeBy: none
        sourceColumn: County

    column 'ZIP (organizations)'
        dataType: double
        lineageTag: 9e35f7ec-5b10-421a-8f03-0cb1e83fa066
        summarizeBy: none
        sourceColumn: ZIP (organizations)

    column 'LAT (organizations)'
        dataType: double
        lineageTag: dfc08d26-6758-4b4b-bbf9-c77ad2d9b0d7
        summarizeBy: none
        sourceColumn: LAT (organizations)

    column 'LON (organizations)'
        dataType: double
        lineageTag: eaa9d8ac-9ffb-4941-a696-765088f4162c
        summarizeBy: none
        sourceColumn: LON (organizations)

    measure 'SUM of Avg Visits per Patient (patients)' =
        SUM('patients'[Avg Visits per Patient])


    measure 'SUM of Visits per Patient (patients)' =
        SUM('patients'[Visits per Patient])


    measure 'Total Patients (LOD)' =
        -- ERROR CONVERTING: LLM call failed after 6 retries. Last error: 404 Client Error: Not Found for url: https://api.groq.com/openai/v1/chat/completions


    measure 'Visits per Patient' =
        -- ERROR CONVERTING: LLM call failed after 6 retries. Last error: 404 Client Error: Not Found for url: https://api.groq.com/openai/v1/chat/completions


    measure 'Avg Visits per Patient' =
        -- ERROR CONVERTING: LLM call failed after 6 retries. Last error: 404 Client Error: Not Found for url: https://api.groq.com/openai/v1/chat/completions


    partition 'patients' = m
        mode: import
        source =
            let Source = Sql.Database("", "Patients.xlsx"),
            #"Navigation 1" = Source{[Schema="[patients$]",Item="patients"]}[Data],
                            #"Renamed Columns" = Table.RenameColumns(#"Navigation 1", {{"Id", "Id (patients)"}, {"BIRTHDATE", "Birthdate"}, {"DEATHDATE", "Deathdate"}, {"PREFIX", "Prefix"}, {"FIRST", "First"}, {"LAST", "Last"}, {"SUFFIX", "Suffix"}, {"MAIDEN", "Maiden"}, {"MARITAL", "Marital"}, {"RACE", "Race"}, {"ETHNICITY", "Ethnicity"}, {"GENDER", "Gender"}, {"BIRTHPLACE", "Birthplace"}, {"ADDRESS", "Address"}, {"CITY", "City"}, {"STATE", "State"}, {"COUNTY", "County"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}})
                        in
                            #"Renamed Columns"
