table 'patients'
    lineageTag: 2321dfc5-68fc-4bda-a45f-0e14234754d5

    column 'Id (patients)'
        dataType: string
        lineageTag: 38d684ea-7404-4012-b846-a31cf1ee3f5b
        summarizeBy: none
        sourceColumn: Id (patients)

    column 'Birthdate'
        sourceColumn: Birthdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: 34289175-5b9e-48e4-a300-6b6c4d42306a
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 67fb8fa9-a1a2-4e0d-92b8-52cf3a581389
            defaultHierarchy: LocalDateTable_15fd01bf-e440-4ba0-aadd-a19e5b2e9654.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Deathdate'
        sourceColumn: Deathdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: e76a90b0-9a5b-486a-b2c4-9747e9f24cae
        summarizeBy: none

        variation Variation
            isDefault
            relationship: afd15d98-3512-4ed9-bf6b-a4b74f7a8583
            defaultHierarchy: LocalDateTable_5e460816-16c4-4bd6-8e0d-453c0367d2cb.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Prefix'
        dataType: string
        lineageTag: e18c0338-a320-482f-b3d1-29830770113d
        summarizeBy: none
        sourceColumn: Prefix

    column 'First'
        dataType: string
        lineageTag: 64bcb8a6-da21-4814-890d-339d0d46558d
        summarizeBy: none
        sourceColumn: First

    column 'Last'
        dataType: string
        lineageTag: c490d686-4d27-4369-bf29-f0424a377f22
        summarizeBy: none
        sourceColumn: Last

    column 'Suffix'
        dataType: string
        lineageTag: 7ecc5674-bb6d-4a7f-99d7-35e1e566c5f0
        summarizeBy: none
        sourceColumn: Suffix

    column 'Maiden'
        dataType: string
        lineageTag: 6516b072-7656-4947-ab30-d9d46e9ab059
        summarizeBy: none
        sourceColumn: Maiden

    column 'Marital'
        dataType: string
        lineageTag: 54cb0bb7-62f8-416e-9db5-7e4d326a1226
        summarizeBy: none
        sourceColumn: Marital

    column 'Race'
        dataType: string
        lineageTag: a6d3f0e9-f2cf-466a-bc9d-0071b919585d
        summarizeBy: none
        sourceColumn: Race

    column 'Ethnicity'
        dataType: string
        lineageTag: eed49df6-5281-4e75-86d5-3dc397336b0a
        summarizeBy: none
        sourceColumn: Ethnicity

    column 'Gender'
        dataType: string
        lineageTag: ca548aba-182e-4594-b966-e52ec15febb5
        summarizeBy: none
        sourceColumn: Gender

    column 'Birthplace'
        dataType: string
        lineageTag: fc5007c6-e5c9-4459-90c7-2cb082250861
        summarizeBy: none
        sourceColumn: Birthplace

    column 'Address'
        dataType: string
        lineageTag: 1e922728-dc9a-47b0-91b1-e5a1f826f254
        summarizeBy: none
        sourceColumn: Address

    column 'City'
        dataType: string
        lineageTag: b3cf5912-1d68-42a6-a8d5-a92876327f5d
        summarizeBy: none
        sourceColumn: City

    column 'State'
        dataType: string
        lineageTag: ba17615b-30d2-4857-8476-b141a98f929a
        summarizeBy: none
        sourceColumn: State

    column 'County'
        dataType: string
        lineageTag: 8ef2dfb3-cc59-4ffb-9d2e-0d5ab4266c49
        summarizeBy: none
        sourceColumn: County

    column 'ZIP (organizations)'
        dataType: double
        lineageTag: bd96309c-c98a-4b2b-bae0-4adf5e2490b0
        summarizeBy: none
        sourceColumn: ZIP (organizations)

    column 'LAT (organizations)'
        dataType: double
        lineageTag: 57d1b568-fc2e-45d5-8b0a-17b34ee16040
        summarizeBy: none
        sourceColumn: LAT (organizations)

    column 'LON (organizations)'
        dataType: double
        lineageTag: c12614b0-6125-4f7a-b323-10e7fe5cb7ae
        summarizeBy: none
        sourceColumn: LON (organizations)

    measure 'SUM of Avg Visits per Patient (patients)' =
        SUM('patients'[Avg Visits per Patient])


    measure 'SUM of Visits per Patient (patients)' =
        SUM('patients'[Visits per Patient])


    measure 'Total Patients (LOD)' =
        -- SKIPPED BY USER


    measure 'Visits per Patient' =
        -- SKIPPED BY USER


    measure 'Avg Visits per Patient' =
        -- SKIPPED BY USER


    partition 'patients' = m
        mode: import
        source =
            let
                Source = GoogleSheets.Contents("None"),
                #"Navigation 1" = Source{[name = "patients", ItemKind = "Table"]}[Data],
                #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
                #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Id", type text}, {"BIRTHDATE", type date}, {"DEATHDATE", type date}, {"PREFIX", type text}, {"FIRST", type text}, {"LAST", type text}, {"SUFFIX", type text}, {"MAIDEN", type text}, {"MARITAL", type text}, {"RACE", type text}, {"ETHNICITY", type text}, {"GENDER", type text}, {"BIRTHPLACE", type text}, {"ADDRESS", type text}, {"CITY", type text}, {"STATE", type text}, {"COUNTY", type text}, {"ZIP", type number}, {"LAT", type number}, {"LON", type number}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"Id", "Id (patients)"}, {"BIRTHDATE", "Birthdate"}, {"DEATHDATE", "Deathdate"}, {"PREFIX", "Prefix"}, {"FIRST", "First"}, {"LAST", "Last"}, {"SUFFIX", "Suffix"}, {"MAIDEN", "Maiden"}, {"MARITAL", "Marital"}, {"RACE", "Race"}, {"ETHNICITY", "Ethnicity"}, {"GENDER", "Gender"}, {"BIRTHPLACE", "Birthplace"}, {"ADDRESS", "Address"}, {"CITY", "City"}, {"STATE", "State"}, {"COUNTY", "County"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}})
            in
                #"Renamed Columns"
