table 'organizations'
    lineageTag: d3e81a86-abcc-4c4e-8e76-c247aa52643b

    column 'Id (organizations)'
        dataType: string
        lineageTag: 706f858e-96aa-4394-b908-59e408d19830
        summarizeBy: none
        sourceColumn: Id (organizations)

    column 'Name'
        dataType: string
        lineageTag: a92cb5fe-e9a3-4328-8fff-580e1f478e71
        summarizeBy: none
        sourceColumn: Name

    column 'ADDRESS (organizations)'
        dataType: string
        lineageTag: ff52f0e4-7173-4ce1-956c-f1b84466973a
        summarizeBy: none
        sourceColumn: ADDRESS (organizations)

    column 'CITY (organizations)'
        dataType: string
        lineageTag: 6e6bfefc-594b-4444-9e00-7ec231231556
        summarizeBy: none
        sourceColumn: CITY (organizations)

    column 'STATE (organizations)'
        dataType: string
        lineageTag: 0924f4db-58d5-472b-bea5-42614d0ba4d5
        summarizeBy: none
        sourceColumn: STATE (organizations)

    column 'ZIP (organizations)'
        dataType: double
        lineageTag: aa09132d-32e4-4b16-86dd-033ffbbefcc6
        summarizeBy: none
        sourceColumn: ZIP (organizations)

    column 'LAT (organizations)'
        dataType: double
        lineageTag: fc31978a-2366-4337-975c-657296002be0
        summarizeBy: none
        sourceColumn: LAT (organizations)

    column 'LON (organizations)'
        dataType: double
        lineageTag: 66e8dd56-ed96-4b20-9eb1-e8463781d01f
        summarizeBy: none
        sourceColumn: LON (organizations)

    column 'Username' = -- SKIPPED BY USER
        dataType: string

        summarizeBy: none

    measure 'RLS - Organization Access' =
        -- SKIPPED BY USER


    partition 'organizations' = m
        mode: import
        source =
            let Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1Gfqr930PI28eveUiJrS8ikSsyzDUbPE4pJy7nG9ZIUc"),
            #"Navigation 1" = Source{[name = "organizations", ItemKind = "Table"]}[Data],
                            #"Final Renamed Columns" = Table.RenameColumns(#"Navigation 1", {{"Id", "Id (organizations)"}, {"NAME", "Name"}, {"ADDRESS", "ADDRESS (organizations)"}, {"CITY", "CITY (organizations)"}, {"STATE", "STATE (organizations)"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}}, MissingField.Ignore)
                        in
                            #"Final Renamed Columns"
