table 'patients'
    lineageTag: 76a646eb-25b8-4865-bdd4-eab987d585c5

    column 'Id (patients)'
        dataType: string
        lineageTag: 71ddb95f-a3fa-473d-88b2-8a5a517540c4
        summarizeBy: none
        sourceColumn: Id (patients)

    column 'Birthdate'
        sourceColumn: Birthdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: b8675d79-7fd4-4923-bdbd-2679a4ff5ce1
        summarizeBy: none

        variation Variation
            isDefault
            relationship: c7320c76-753a-43a8-9717-1b0163f2b174
            defaultHierarchy: LocalDateTable_236d5c50-91a8-49b6-8bae-10691a06112b.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Deathdate'
        sourceColumn: Deathdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: 755e7de9-4da2-4271-a217-91d9e10a852b
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 84186e9c-29ba-4a45-b170-5f5be916a7f7
            defaultHierarchy: LocalDateTable_7e3da3e8-0556-473b-b1e3-e3c0cb0df176.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Prefix'
        dataType: string
        lineageTag: 42b6cce8-104a-4153-862d-655d699e7339
        summarizeBy: none
        sourceColumn: Prefix

    column 'First'
        dataType: string
        lineageTag: 8a33fcd5-bbe5-4991-894a-45eefa15f382
        summarizeBy: none
        sourceColumn: First

    column 'Last'
        dataType: string
        lineageTag: 199c4277-5c45-42ce-b77b-24f7923b9de0
        summarizeBy: none
        sourceColumn: Last

    column 'Suffix'
        dataType: string
        lineageTag: 94d85290-86c5-4ae6-9437-d1fab0cda099
        summarizeBy: none
        sourceColumn: Suffix

    column 'Maiden'
        dataType: string
        lineageTag: 6322add3-609d-402b-accf-6248121a814b
        summarizeBy: none
        sourceColumn: Maiden

    column 'Marital'
        dataType: string
        lineageTag: ed7ebe92-b578-45d7-8010-4d6ae97a7f11
        summarizeBy: none
        sourceColumn: Marital

    column 'Race'
        dataType: string
        lineageTag: 98899838-7448-485f-a7ba-c43742f51d47
        summarizeBy: none
        sourceColumn: Race

    column 'Ethnicity'
        dataType: string
        lineageTag: 8df1be8c-aa71-4d64-b3bd-9e925337eea0
        summarizeBy: none
        sourceColumn: Ethnicity

    column 'Gender'
        dataType: string
        lineageTag: 3f8f5150-8be4-47ed-a9fa-ef42e2015286
        summarizeBy: none
        sourceColumn: Gender

    column 'Birthplace'
        dataType: string
        lineageTag: c80837cc-0d3b-4f4c-9b2e-8bf7864b1795
        summarizeBy: none
        sourceColumn: Birthplace

    column 'Address'
        dataType: string
        lineageTag: 58e4aea2-5c9f-4368-99ae-06f614fc2357
        summarizeBy: none
        sourceColumn: Address

    column 'City'
        dataType: string
        lineageTag: e4860cdd-ed7a-4e07-ad1f-2c75c3e423b9
        summarizeBy: none
        sourceColumn: City

    column 'State'
        dataType: string
        lineageTag: 82216bf7-d3e1-4270-a8c8-8d2d0a35f1ae
        summarizeBy: none
        sourceColumn: State

    column 'County'
        dataType: string
        lineageTag: e1f1f904-3f03-4ea0-b0a1-589b41d4b0dd
        summarizeBy: none
        sourceColumn: County

    column 'ZIP (organizations)'
        dataType: double
        lineageTag: 68a83262-c6b8-42d8-b251-1cebf4ffb5e0
        summarizeBy: none
        sourceColumn: ZIP (organizations)

    column 'LAT (organizations)'
        dataType: double
        lineageTag: 600789de-39f3-43b3-8e78-0db8272c7b03
        summarizeBy: none
        sourceColumn: LAT (organizations)

    column 'LON (organizations)'
        dataType: double
        lineageTag: 7cb48dd9-64e4-4352-a5cc-1550b5247a81
        summarizeBy: none
        sourceColumn: LON (organizations)

    measure 'SUM of Avg Visits per Patient (patients)' =
        SUM('patients'[Avg Visits per Patient])


    measure 'SUM of Visits per Patient (patients)' =
        SUM('patients'[Visits per Patient])


    measure 'Total Patients (LOD)' =
        -- SKIPPED BY USER


    measure 'Visits per Patient' =
        -- SKIPPED BY USER


    measure 'Avg Visits per Patient' =
        -- SKIPPED BY USER


    partition 'patients' = m
        mode: import
        source =
            let Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1Sd4bEK0Fm9q7yTVOwI4GdtixeeY8hPkKqpvnI4WdixA"),
            #"Navigation 1" = Source{[name = "patients", ItemKind = "Table"]}[Data],
                            #"Final Renamed Columns" = Table.RenameColumns(#"Navigation 1", {{"Id", "Id (patients)"}, {"BIRTHDATE", "Birthdate"}, {"DEATHDATE", "Deathdate"}, {"PREFIX", "Prefix"}, {"FIRST", "First"}, {"LAST", "Last"}, {"SUFFIX", "Suffix"}, {"MAIDEN", "Maiden"}, {"MARITAL", "Marital"}, {"RACE", "Race"}, {"ETHNICITY", "Ethnicity"}, {"GENDER", "Gender"}, {"BIRTHPLACE", "Birthplace"}, {"ADDRESS", "Address"}, {"CITY", "City"}, {"STATE", "State"}, {"COUNTY", "County"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}}, MissingField.Ignore)
                        in
                            #"Final Renamed Columns"
