table 'payers'
    lineageTag: c59afb50-cac8-46e5-8fe8-b1e4983a8800

    column 'Id (payers)'
        dataType: string
        lineageTag: aa94f6e8-a97b-4961-82c4-3c5234a46648
        summarizeBy: none
        sourceColumn: Id (payers)

    column 'NAME (payers)'
        dataType: string
        lineageTag: 267bcc16-779e-456a-bad9-7cc469066bce
        summarizeBy: none
        sourceColumn: NAME (payers)

    column 'ADDRESS (payers)'
        dataType: string
        lineageTag: 14665637-1efd-4715-aa64-edb43294047c
        summarizeBy: none
        sourceColumn: ADDRESS (payers)

    column 'CITY (payers)'
        dataType: string
        lineageTag: 60d41328-463c-4180-8690-c5cd8362be47
        summarizeBy: none
        sourceColumn: CITY (payers)

    column 'State Headquartered'
        dataType: string
        lineageTag: 1ea91f58-e385-44f1-a78d-364ed4ed921f
        summarizeBy: none
        sourceColumn: State Headquartered

    column 'ZIP (payers)'
        dataType: double
        lineageTag: 87e8cba6-808c-40b5-b101-ccea39107a80
        summarizeBy: none
        sourceColumn: ZIP (payers)

    column 'Phone'
        dataType: string
        lineageTag: 7a8cfc9c-a2dd-4602-83ae-1fcc701e58d6
        summarizeBy: none
        sourceColumn: Phone

    partition 'payers' = m
        mode: import
        source =
            let Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1NB9uAQnBa6RYGfm5addKbcToYUZJY_5OlBkWxVZRrbU"),
            #"Navigation 1" = Source{[name = "payers", ItemKind = "Table"]}[Data],
                            #"Final Renamed Columns" = Table.RenameColumns(#"Navigation 1", {{"Id", "Id (payers)"}, {"NAME", "NAME (payers)"}, {"ADDRESS", "ADDRESS (payers)"}, {"CITY", "CITY (payers)"}, {"STATE_HEADQUARTERED", "State Headquartered"}, {"ZIP", "ZIP (payers)"}, {"PHONE", "Phone"}}, MissingField.Ignore)
                        in
                            #"Final Renamed Columns"
