table card
	lineageTag: d47f272a-de9d-4a97-a4cf-7a402ba62aec

	column 'Card Id'
		dataType: double
		lineageTag: c50f0650-b59d-4e17-a66d-b1560837e582
		summarizeBy: none
		sourceColumn: Card Id

	column 'Disp Id (Card)'
		dataType: double
		lineageTag: 3c3d89f7-29ef-44ef-aba3-17ef45b48a5e
		summarizeBy: none
		sourceColumn: Disp Id (Card)

	column 'Type (Card)'
		dataType: string
		lineageTag: d69fa113-04c0-404f-b596-89ae3e6b0dce
		summarizeBy: none
		sourceColumn: Type (Card)

	column Issued
		dataType: string
		lineageTag: db2f9a64-6124-4306-b961-fd0e0b6571e8
		summarizeBy: none
		sourceColumn: Issued

	partition card = m
		mode: import
		source =
				let
				    Source = AmazonRedshift.Database("financial-workgroup.164761934860.ap-southeast-2.redshift-serverless.amazonaws.com:5439", "dev", [ProviderName = null, BatchSize = null]),
				    #"Navigation 1" = Source{[Name = "public"]}[Data],
				    #"Navigation 2" = #"Navigation 1"{[Name = "card"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(#"Navigation 2", {{"card_id", type number}, {"disp_id", type number}, {"type", type text}, {"issued", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"card_id", "Card Id"}, {"disp_id", "Disp Id (Card)"}, {"type", "Type (Card)"}, {"issued", "Issued"}})
				in
				    #"Renamed Columns"

