table district
	lineageTag: ddf5b370-e6bf-4f5d-8fa2-087ea3a208da

	column 'District Id (District)'
		dataType: double
		lineageTag: 1d67e579-ec1f-4043-b1e2-ecb9db53e7be
		summarizeBy: none
		sourceColumn: District Id (District)

	column 'District Name'
		dataType: string
		lineageTag: e29a0a95-a899-4c0f-9b64-85cfd346591f
		summarizeBy: none
		sourceColumn: District Name

	column Region
		dataType: string
		lineageTag: 9878339c-8c1e-436f-9759-3183e1aa5ed9
		summarizeBy: none
		sourceColumn: Region

	column Population
		dataType: double
		lineageTag: 08eaca07-2d44-4a36-b574-5aa5d40f153b
		summarizeBy: none
		sourceColumn: Population

	column 'Number of municipalities (< 499 inhabitants)'
		dataType: double
		lineageTag: 4e7513ee-ef94-48b2-95ec-289ea793c340
		summarizeBy: none
		sourceColumn: Number of municipalities (< 499 inhabitants)

	column 'Number of municipalities (500–1999 inhabitants)'
		dataType: double
		lineageTag: f7e5e31d-d2dd-4274-acbe-3fd4f3610998
		summarizeBy: none
		sourceColumn: Number of municipalities (500–1999 inhabitants)

	column 'Number of municipalities (2000–9999 inhabitants)'
		dataType: double
		lineageTag: 0099836e-62e4-4ef4-90ba-ee6a07b99011
		summarizeBy: none
		sourceColumn: Number of municipalities (2000–9999 inhabitants)

	column 'Number of municipalities (> 10000 inhabitants)'
		dataType: double
		lineageTag: fa59640b-879a-43ac-8f7f-36b808763e17
		summarizeBy: none
		sourceColumn: Number of municipalities (> 10000 inhabitants)

	column 'Number of cities'
		dataType: double
		lineageTag: 9d0a883a-17ab-45e8-b53d-cf638e990b23
		summarizeBy: none
		sourceColumn: Number of cities

	column 'Urban population ratio'
		dataType: double
		lineageTag: 4480a903-2d25-49a9-bdd1-cea5aff4484e
		summarizeBy: none
		sourceColumn: Urban population ratio

	column 'Average Salary'
		dataType: double
		lineageTag: 85b24c32-f7b5-415f-b29d-644b3858060a
		summarizeBy: none
		sourceColumn: Average Salary

	column 'Unemployment rate (1995)'
		dataType: double
		lineageTag: 67b265b1-505a-4d18-8931-34c002d30459
		summarizeBy: none
		sourceColumn: Unemployment rate (1995)

	column 'Unemployment rate (1996)'
		dataType: double
		lineageTag: d1f94718-e5d9-4aa8-b110-e1c59a949564
		summarizeBy: none
		sourceColumn: Unemployment rate (1996)

	column 'Number of entrepreneurs per 1000 inhabitants'
		dataType: double
		lineageTag: e14c7825-f1f4-42e6-8245-b51d56e1cf9d
		summarizeBy: none
		sourceColumn: Number of entrepreneurs per 1000 inhabitants

	column 'Number of committed crimes (1995)'
		dataType: double
		lineageTag: adbcc8ae-4a7e-4134-a5a2-c1223b7b2e7a
		summarizeBy: none
		sourceColumn: Number of committed crimes (1995)

	column 'Number of committed crimes (1996)'
		dataType: double
		lineageTag: c5b30a2c-0ab9-4141-98df-503aed019cf2
		summarizeBy: none
		sourceColumn: Number of committed crimes (1996)

	partition district = m
		mode: import
		source =
				let
				    Source = AmazonRedshift.Database("financial-workgroup.164761934860.ap-southeast-2.redshift-serverless.amazonaws.com:5439", "dev", [ProviderName = null, BatchSize = null]),
				    #"Navigation 1" = Source{[Name = "public"]}[Data],
				    #"Navigation 2" = #"Navigation 1"{[Name = "district"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(#"Navigation 2", {{"district_id", type number}, {"a2", type text}, {"a3", type text}, {"a4", type number}, {"a5", type number}, {"a6", type number}, {"a7", type number}, {"a8", type number}, {"a9", type number}, {"a10", type number}, {"a11", type number}, {"a12", type number}, {"a13", type number}, {"a14", type number}, {"a15", type number}, {"a16", type number}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"district_id", "District Id (District)"}, {"a2", "District Name"}, {"a3", "Region"}, {"a4", "Population"}, {"a5", "Number of municipalities (< 499 inhabitants)"}, {"a6", "Number of municipalities (500–1999 inhabitants)"}, {"a7", "Number of municipalities (2000–9999 inhabitants)"}, {"a8", "Number of municipalities (> 10000 inhabitants)"}, {"a9", "Number of cities"}, {"a10", "Urban population ratio"}, {"a11", "Average Salary"}, {"a12", "Unemployment rate (1995)"}, {"a13", "Unemployment rate (1996)"}, {"a14", "Number of entrepreneurs per 1000 inhabitants"}, {"a15", "Number of committed crimes (1995)"}, {"a16", "Number of committed crimes (1996)"}})
				in
				    #"Renamed Columns"

