table 'patients'
    lineageTag: a5fb8146-a0d3-428f-995c-da24491039d1

    column 'Id (patients)'
        dataType: string
        lineageTag: a7261de3-9526-460e-8dc2-600f6e4feb1d
        summarizeBy: none
        sourceColumn: Id (patients)

    column 'Birthdate'
        sourceColumn: Birthdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: e23a05ab-5e2b-41c6-b4bf-c10e4e5eea02
        summarizeBy: none

        variation Variation
            isDefault
            relationship: ec328fe1-90bb-4ca9-8c28-6d7872aea106
            defaultHierarchy: LocalDateTable_77699972-6a50-4f3c-adad-b6d016226e8a.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Deathdate'
        sourceColumn: Deathdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: 09832292-3f4f-41ce-863b-807dbfc95ac9
        summarizeBy: none

        variation Variation
            isDefault
            relationship: a864ac75-2e03-456a-868c-0c162ae88114
            defaultHierarchy: LocalDateTable_3b662794-5ffe-4f0b-9f02-c446ce7cc5b0.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Prefix'
        dataType: string
        lineageTag: cca3b722-3618-4d0b-b29b-9c3a1627e885
        summarizeBy: none
        sourceColumn: Prefix

    column 'First'
        dataType: string
        lineageTag: 1104f228-82b7-468d-a388-6c5de7c18ac5
        summarizeBy: none
        sourceColumn: First

    column 'Last'
        dataType: string
        lineageTag: 1313cee6-b8ac-49c4-a9c9-6f0539116c96
        summarizeBy: none
        sourceColumn: Last

    column 'Suffix'
        dataType: string
        lineageTag: eef92aa6-1bdf-472a-af44-64f24a07a56e
        summarizeBy: none
        sourceColumn: Suffix

    column 'Maiden'
        dataType: string
        lineageTag: f1fcbbdb-eaf1-42fb-bac1-c15172299a6a
        summarizeBy: none
        sourceColumn: Maiden

    column 'Marital'
        dataType: string
        lineageTag: 889818b1-f4f7-4681-a76a-50e5411900b0
        summarizeBy: none
        sourceColumn: Marital

    column 'Race'
        dataType: string
        lineageTag: eecb0f2d-3a2f-434b-9729-3bddb1d6a132
        summarizeBy: none
        sourceColumn: Race

    column 'Ethnicity'
        dataType: string
        lineageTag: a4c85f91-feed-4a99-bb8a-458221aa3e68
        summarizeBy: none
        sourceColumn: Ethnicity

    column 'Gender'
        dataType: string
        lineageTag: 3eb8d36a-7bee-42df-bc7c-952b4ecb3290
        summarizeBy: none
        sourceColumn: Gender

    column 'Birthplace'
        dataType: string
        lineageTag: 4f507be8-372e-41b6-bf88-d6f11b478cc0
        summarizeBy: none
        sourceColumn: Birthplace

    column 'Address'
        dataType: string
        lineageTag: 1056c00d-db72-4ddf-8e2a-9611f615decd
        summarizeBy: none
        sourceColumn: Address

    column 'City'
        dataType: string
        lineageTag: 8a811b59-da5e-4cbe-ad88-6e81921bb763
        summarizeBy: none
        sourceColumn: City

    column 'State'
        dataType: string
        lineageTag: ab3564eb-faba-4e6e-9043-0244159071ff
        summarizeBy: none
        sourceColumn: State

    column 'County'
        dataType: string
        lineageTag: f8e05690-6108-45b8-b7cc-71805b0fb1a5
        summarizeBy: none
        sourceColumn: County

    column 'ZIP (organizations)'
        dataType: double
        lineageTag: d750bdbc-c7ec-40ed-9d4f-7361b84728c2
        summarizeBy: none
        sourceColumn: ZIP (organizations)

    column 'LAT (organizations)'
        dataType: double
        lineageTag: 04cc6fc1-6c9b-4fe7-929e-0a5534343c5d
        summarizeBy: none
        sourceColumn: LAT (organizations)

    column 'LON (organizations)'
        dataType: double
        lineageTag: e4a57f5b-7805-4027-923c-06b8bc9dd6e5
        summarizeBy: none
        sourceColumn: LON (organizations)

    measure 'SUM of Avg Visits per Patient (patients)' =
        SUM('patients'[Avg Visits per Patient])


    measure 'SUM of Visits per Patient (patients)' =
        SUM('patients'[Visits per Patient])


    measure 'Total Patients (LOD)' =
        -- ERROR CONVERTING: LLM call failed after 6 retries. Last error: 404 Client Error: Not Found for url: https://api.groq.com/openai/v1/chat/completions


    measure 'Visits per Patient' =
        -- ERROR CONVERTING: LLM call failed after 6 retries. Last error: 404 Client Error: Not Found for url: https://api.groq.com/openai/v1/chat/completions


    measure 'Avg Visits per Patient' =
        -- ERROR CONVERTING: LLM call failed after 6 retries. Last error: 404 Client Error: Not Found for url: https://api.groq.com/openai/v1/chat/completions


    partition 'patients' = m
        mode: import
        source =
            let Source = Excel.Workbook(Web.Contents("https://www.googleapis.com/drive/v3/files/1Sd4bEK0Fm9q7yTVOwI4GdtixeeY8hPkKqpvnI4WdixA/export?mimeType=application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"), null, true),
            #"Navigation 1" = Source{[Item="patients",Kind="Sheet"]}[Data],
            #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars=true]),
            #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Id", type text}, {"BIRTHDATE", type date}, {"DEATHDATE", type date}, {"PREFIX", type text}, {"FIRST", type text}, {"LAST", type text}, {"SUFFIX", type text}, {"MAIDEN", type text}, {"MARITAL", type text}, {"RACE", type text}, {"ETHNICITY", type text}, {"GENDER", type text}, {"BIRTHPLACE", type text}, {"ADDRESS", type text}, {"CITY", type text}, {"STATE", type text}, {"COUNTY", type text}, {"ZIP", type number}, {"LAT", type number}, {"LON", type number}}),
            #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"Id", "Id (patients)"}, {"BIRTHDATE", "Birthdate"}, {"DEATHDATE", "Deathdate"}, {"PREFIX", "Prefix"}, {"FIRST", "First"}, {"LAST", "Last"}, {"SUFFIX", "Suffix"}, {"MAIDEN", "Maiden"}, {"MARITAL", "Marital"}, {"RACE", "Race"}, {"ETHNICITY", "Ethnicity"}, {"GENDER", "Gender"}, {"BIRTHPLACE", "Birthplace"}, {"ADDRESS", "Address"}, {"CITY", "City"}, {"STATE", "State"}, {"COUNTY", "County"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}}),
                            #"Renamed Columns" = Table.RenameColumns(#"Renamed Columns", {{"Id", "Id (patients)"}, {"BIRTHDATE", "Birthdate"}, {"DEATHDATE", "Deathdate"}, {"PREFIX", "Prefix"}, {"FIRST", "First"}, {"LAST", "Last"}, {"SUFFIX", "Suffix"}, {"MAIDEN", "Maiden"}, {"MARITAL", "Marital"}, {"RACE", "Race"}, {"ETHNICITY", "Ethnicity"}, {"GENDER", "Gender"}, {"BIRTHPLACE", "Birthplace"}, {"ADDRESS", "Address"}, {"CITY", "City"}, {"STATE", "State"}, {"COUNTY", "County"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}})
                        in
                            #"Renamed Columns"
