table 'patients'
    lineageTag: d5aa56f1-e9a1-4cea-9d8c-129c00de3da9

    column 'Id (patients)'
        dataType: string
        lineageTag: 5ba29efa-bc18-4382-90c1-12067ab750d2
        summarizeBy: none
        sourceColumn: Id (patients)

    column 'Birthdate'
        sourceColumn: Birthdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: 17ca8491-d87a-43c4-988e-ccadbbaf4b52
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 7954dd25-43c6-473a-bdbd-72ce666663e6
            defaultHierarchy: LocalDateTable_b8f5deed-e911-4566-9750-1fd749188bc8.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Deathdate'
        sourceColumn: Deathdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: ffda7253-5b0f-4265-a4c3-74f875414e9e
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 8954f45b-a402-4659-81bf-d421368c03e7
            defaultHierarchy: LocalDateTable_73e06783-5c0f-41c4-925a-9b41711c9b0f.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Prefix'
        dataType: string
        lineageTag: 58f79fc8-187e-488d-bc1d-c8773e599bd6
        summarizeBy: none
        sourceColumn: Prefix

    column 'First'
        dataType: string
        lineageTag: 232eef6a-b1a2-490c-9e69-ffeedeb617cc
        summarizeBy: none
        sourceColumn: First

    column 'Last'
        dataType: string
        lineageTag: f797f6b7-1d97-444b-9a59-98d5be8d1cd6
        summarizeBy: none
        sourceColumn: Last

    column 'Suffix'
        dataType: string
        lineageTag: e4adec97-d0c7-418b-8079-31b255133f7c
        summarizeBy: none
        sourceColumn: Suffix

    column 'Maiden'
        dataType: string
        lineageTag: 2be075aa-2785-4f10-8a86-ae8d6b987679
        summarizeBy: none
        sourceColumn: Maiden

    column 'Marital'
        dataType: string
        lineageTag: 98f2b452-8ae4-4f90-935d-9188a0a27519
        summarizeBy: none
        sourceColumn: Marital

    column 'Race'
        dataType: string
        lineageTag: 7c058412-3ba3-4868-a90d-7abb3cfe64d6
        summarizeBy: none
        sourceColumn: Race

    column 'Ethnicity'
        dataType: string
        lineageTag: ed0f63ac-2aa4-40e0-9da5-936001d1534b
        summarizeBy: none
        sourceColumn: Ethnicity

    column 'Gender'
        dataType: string
        lineageTag: bf6467d7-4894-4e3e-9d7e-b149446b090f
        summarizeBy: none
        sourceColumn: Gender

    column 'Birthplace'
        dataType: string
        lineageTag: ff31c9a9-7a0e-44fa-981d-21f3e9d0836b
        summarizeBy: none
        sourceColumn: Birthplace

    column 'Address'
        dataType: string
        lineageTag: 29367325-2894-442d-bdf4-442bea92a114
        summarizeBy: none
        sourceColumn: Address

    column 'City'
        dataType: string
        lineageTag: 5e8b52f1-fa63-475f-aee9-0e09658cd15b
        summarizeBy: none
        sourceColumn: City

    column 'State'
        dataType: string
        lineageTag: 828d40bf-e296-4a5a-9362-448123e7c539
        summarizeBy: none
        sourceColumn: State

    column 'County'
        dataType: string
        lineageTag: 7a77b0c3-830d-4e62-92dd-7d8df3c4bc7b
        summarizeBy: none
        sourceColumn: County

    column 'ZIP (organizations)'
        dataType: double
        lineageTag: c00667fe-4fcb-4ac5-bf70-b105f5f16921
        summarizeBy: none
        sourceColumn: ZIP (organizations)

    column 'LAT (organizations)'
        dataType: double
        lineageTag: d9d30895-49d5-4d90-83cb-b8d665393296
        summarizeBy: none
        sourceColumn: LAT (organizations)

    column 'LON (organizations)'
        dataType: double
        lineageTag: 0a41beb0-0673-4b9b-89aa-798a3e47ae08
        summarizeBy: none
        sourceColumn: LON (organizations)

    measure 'SUM of Avg Visits per Patient (patients)' =
        SUM('patients'[Avg Visits per Patient])


    measure 'SUM of Visits per Patient (patients)' =
        SUM('patients'[Visits per Patient])


    measure 'Total Patients (LOD)' =
        -- SKIPPED BY USER


    measure 'Visits per Patient' =
        -- SKIPPED BY USER


    measure 'Avg Visits per Patient' =
        -- SKIPPED BY USER


    partition 'patients' = m
        mode: import
        source =
            let Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1Sd4bEK0Fm9q7yTVOwI4GdtixeeY8hPkKqpvnI4WdixA"),
            #"Navigation 1" = Source{[name="patients", ItemKind="Table"]}[Data],
            #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars=true]),
            #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Id", type text}, {"BIRTHDATE", type date}, {"DEATHDATE", type date}, {"PREFIX", type text}, {"FIRST", type text}, {"LAST", type text}, {"SUFFIX", type text}, {"MAIDEN", type text}, {"MARITAL", type text}, {"RACE", type text}, {"ETHNICITY", type text}, {"GENDER", type text}, {"BIRTHPLACE", type text}, {"ADDRESS", type text}, {"CITY", type text}, {"STATE", type text}, {"COUNTY", type text}, {"ZIP", type number}, {"LAT", type number}, {"LON", type number}}),
            #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"Id", "Id (patients)"}, {"BIRTHDATE", "Birthdate"}, {"DEATHDATE", "Deathdate"}, {"PREFIX", "Prefix"}, {"FIRST", "First"}, {"LAST", "Last"}, {"SUFFIX", "Suffix"}, {"MAIDEN", "Maiden"}, {"MARITAL", "Marital"}, {"RACE", "Race"}, {"ETHNICITY", "Ethnicity"}, {"GENDER", "Gender"}, {"BIRTHPLACE", "Birthplace"}, {"ADDRESS", "Address"}, {"CITY", "City"}, {"STATE", "State"}, {"COUNTY", "County"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}}),
                            #"Final Renamed Columns" = Table.RenameColumns(#"Renamed Columns", {{"Id", "Id (patients)"}, {"BIRTHDATE", "Birthdate"}, {"DEATHDATE", "Deathdate"}, {"PREFIX", "Prefix"}, {"FIRST", "First"}, {"LAST", "Last"}, {"SUFFIX", "Suffix"}, {"MAIDEN", "Maiden"}, {"MARITAL", "Marital"}, {"RACE", "Race"}, {"ETHNICITY", "Ethnicity"}, {"GENDER", "Gender"}, {"BIRTHPLACE", "Birthplace"}, {"ADDRESS", "Address"}, {"CITY", "City"}, {"STATE", "State"}, {"COUNTY", "County"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}})
                        in
                            #"Final Renamed Columns"
