table 'patients'
    lineageTag: 03bb681c-2392-438a-9195-7e4495d6bbbb

    column 'Id (patients)'
        dataType: string
        lineageTag: 63a981df-9428-4248-a525-13cf5f837c8b
        summarizeBy: none
        sourceColumn: Id (patients)

    column 'Birthdate'
        sourceColumn: Birthdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: 4892c04d-e7da-4971-a5af-8a505c4b0167
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 571074cc-8739-4acd-9927-e1a39c4eec3d
            defaultHierarchy: LocalDateTable_7fe80b25-8d98-4911-a6a8-b674f05410ad.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Deathdate'
        sourceColumn: Deathdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: 356e5f2a-7e28-4c39-9140-5f69401a6f58
        summarizeBy: none

        variation Variation
            isDefault
            relationship: b1de9605-1225-4d51-a411-ded0d827df58
            defaultHierarchy: LocalDateTable_bed85f8d-0bad-4dc4-bc09-fdfa01c49d15.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Prefix'
        dataType: string
        lineageTag: 3f6bc87f-0116-4773-9ff7-3dbdcee2e6c3
        summarizeBy: none
        sourceColumn: Prefix

    column 'First'
        dataType: string
        lineageTag: 80dac700-3d3c-4e18-9ec9-82125fb4ff18
        summarizeBy: none
        sourceColumn: First

    column 'Last'
        dataType: string
        lineageTag: 6542996f-f296-4180-b4db-93e1bef3d57a
        summarizeBy: none
        sourceColumn: Last

    column 'Suffix'
        dataType: string
        lineageTag: ed1553ad-01c7-4751-a5df-36e3f2f5fc5a
        summarizeBy: none
        sourceColumn: Suffix

    column 'Maiden'
        dataType: string
        lineageTag: a7137fb8-060a-41b1-824e-cad884d62ae3
        summarizeBy: none
        sourceColumn: Maiden

    column 'Marital'
        dataType: string
        lineageTag: 3c97ba5f-236e-456b-a506-0ee3e45cea16
        summarizeBy: none
        sourceColumn: Marital

    column 'Race'
        dataType: string
        lineageTag: 9f09b2e0-495b-4445-9299-e18ac06fc38c
        summarizeBy: none
        sourceColumn: Race

    column 'Ethnicity'
        dataType: string
        lineageTag: d9957157-9884-4343-b05c-0c0f1b301468
        summarizeBy: none
        sourceColumn: Ethnicity

    column 'Gender'
        dataType: string
        lineageTag: 76050dcc-ddb9-43fb-a940-b226d85f0534
        summarizeBy: none
        sourceColumn: Gender

    column 'Birthplace'
        dataType: string
        lineageTag: 44aea78c-dd30-4889-9e38-a9ba77995aad
        summarizeBy: none
        sourceColumn: Birthplace

    column 'Address'
        dataType: string
        lineageTag: 504313c2-9d11-4169-aa80-1731937ba53a
        summarizeBy: none
        sourceColumn: Address

    column 'City'
        dataType: string
        lineageTag: 282d6642-ffcc-46b2-aa16-abdea77dcea3
        summarizeBy: none
        sourceColumn: City

    column 'State'
        dataType: string
        lineageTag: 95ac0247-c2f6-49f4-a233-5bc2a85d01f9
        summarizeBy: none
        sourceColumn: State

    column 'County'
        dataType: string
        lineageTag: 54ae0f76-9d55-4449-9e52-fc7ad8c0afbb
        summarizeBy: none
        sourceColumn: County

    column 'ZIP (organizations)'
        dataType: double
        lineageTag: 15e8fa00-4b87-4315-83de-0132fbade79c
        summarizeBy: none
        sourceColumn: ZIP (organizations)

    column 'LAT (organizations)'
        dataType: double
        lineageTag: 4b0f2c84-e552-44e5-9464-8ef52c4ade66
        summarizeBy: none
        sourceColumn: LAT (organizations)

    column 'LON (organizations)'
        dataType: double
        lineageTag: bc7062f3-81cd-4477-9598-b2fefa3459d9
        summarizeBy: none
        sourceColumn: LON (organizations)

    measure 'SUM of Avg Visits per Patient (patients)' =
        SUM('patients'[Avg Visits per Patient])


    measure 'SUM of Visits per Patient (patients)' =
        SUM('patients'[Visits per Patient])


    measure 'Total Patients (LOD)' =
        -- SKIPPED BY USER


    measure 'Visits per Patient' =
        -- SKIPPED BY USER


    measure 'Avg Visits per Patient' =
        -- SKIPPED BY USER


    partition 'patients' = m
        mode: import
        source =
            let Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1Sd4bEK0Fm9q7yTVOwI4GdtixeeY8hPkKqpvnI4WdixA"),
            #"Navigation 1" = Source{[name = "patients", ItemKind = "Table"]}[Data],
                            #"Final Renamed Columns" = Table.RenameColumns(#"Navigation 1", {{"Id", "Id (patients)"}, {"BIRTHDATE", "Birthdate"}, {"DEATHDATE", "Deathdate"}, {"PREFIX", "Prefix"}, {"FIRST", "First"}, {"LAST", "Last"}, {"SUFFIX", "Suffix"}, {"MAIDEN", "Maiden"}, {"MARITAL", "Marital"}, {"RACE", "Race"}, {"ETHNICITY", "Ethnicity"}, {"GENDER", "Gender"}, {"BIRTHPLACE", "Birthplace"}, {"ADDRESS", "Address"}, {"CITY", "City"}, {"STATE", "State"}, {"COUNTY", "County"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}})
                        in
                            #"Final Renamed Columns"
