table FuelByTrip
	lineageTag: 92a3a65c-e644-527c-9742-7e68c00ed86a

	column trip_id
		dataType: string
		lineageTag: 727e8482-c80b-53b1-8673-26c365074440
		summarizeBy: none
		sourceColumn: trip_id

		annotation SummarizationSetBy = Automatic

	column PurchasedGallons = CALCULATE(SUM('FuelPurchases'[gallons]))
		dataType: double
		lineageTag: 1324fdf1-26e7-5e3c-a8f4-ca515e388028
		summarizeBy: sum
		formatString: #,##0.00

		annotation SummarizationSetBy = Automatic

	column TotalFuelCost = CALCULATE(SUM('FuelPurchases'[fuel_total_cost]))
		dataType: double
		lineageTag: 8125f77c-fd8f-5fd0-b14b-192a0bd182e4
		summarizeBy: sum
		formatString: #,##0.00

		annotation SummarizationSetBy = Automatic

	column AvgFuelPricePerGallon = DIVIDE(CALCULATE(SUM('FuelPurchases'[fuel_total_cost])), CALCULATE(SUM('FuelPurchases'[gallons])), 0)
		dataType: double
		lineageTag: 19375e2e-a18e-5c24-9538-f5e5a73f7c1e
		summarizeBy: sum
		formatString: #,##0.00

		annotation SummarizationSetBy = Automatic

	column FuelTransactions = CALCULATE(DISTINCTCOUNT('FuelPurchases'[fuel_purchase_id]))
		dataType: double
		lineageTag: 67fec475-d41c-5346-8f5a-70764ccfc656
		summarizeBy: sum
		formatString: ###0

		annotation SummarizationSetBy = Automatic

	partition FuelByTrip = m
		mode: import
		source =
				let
				    Source = #"FuelPurchases",
				    #"Selected Columns" = Table.SelectColumns(Source, {"trip_id"}),
				    #"Removed Duplicates" = Table.Distinct(#"Selected Columns")
				in
				    #"Removed Duplicates"

	annotation PBI_ResultType = Table
