table Loads
	lineageTag: 13e30a87-fa1f-5fb1-a4d4-f18fb28b9558

	measure 'Total Revenue' = DIVIDE(SUM('Loads'[revenue]), 1000000, 0)
		formatString: "#,##0.00"
		lineageTag: 91098b09-6315-5012-8cb4-76e719439999

	measure 'Customer Analytics' = MAXX(SUMMARIZE("Loads", 'Customers'[customer_name], "@value", SUM('Loads'[revenue])), [@value])
		formatString: "#,##0.00"
		lineageTag: 5a444008-2977-58aa-8afd-9a301f70d1f2

	measure 'Highest Revenue by Customer' = MAXX(SUMMARIZE("Loads", 'Customers'[customer_name], "@value", SUM('Loads'[revenue])), [@value])
		formatString: "#,##0.00"
		lineageTag: 1b63a406-2922-5cb0-9dcf-d471af1453d0

	measure 'Average Revenue per Load' = AVERAGE('Loads'[revenue])
		formatString: "#,##0.00"
		lineageTag: ec7cf70c-2291-5cbb-9d68-2b9728cb6e1a

	measure 'High Value Revenue' = CALCULATE(SUM('Loads'[revenue]), 'Loads'[RevenueBand] = "High Value")
		formatString: "#,##0.00"
		lineageTag: 9e0aa5db-e86e-5f58-b721-d6dbdd9858ce

	measure 'Average Revenue per Customer' = DIVIDE(SUM('Loads'[revenue]), DISTINCTCOUNT('Customers'[customer_id]), 0)
		formatString: "$#,##0"
		lineageTag: 290c931b-09a5-5f54-b1d3-6d67170e6f7f

	measure 'Driver Analytics' = AVERAGEX(SUMMARIZE("Loads", 'Trips'[driver_id], "@value", SUM('Loads'[revenue])), [@value])
		formatString: "#,##0.00"
		lineageTag: e05a035d-85ce-5856-a036-1afbc7f0beb3

	measure 'High Value Revenue %' = DIVIDE(CALCULATE(SUM('Loads'[revenue]), 'Loads'[RevenueBand] = "High Value"), SUM('Loads'[revenue]), 0)
		formatString: "0.0%"
		lineageTag: d15eab55-18f2-558a-b3d8-3f6bde57dfa6

	measure 'Revenue per Mile' = DIVIDE(SUM('Loads'[revenue]), SUM('Trips'[actual_distance_miles]), 0)
		formatString: "#,##0.00"
		lineageTag: 6a7f8c9d-ae59-5350-b000-d2098e25e5dd

	measure 'Revenue per Trip' = DIVIDE(SUM('Loads'[revenue]), COUNT('Trips'[trip_id]), 0)
		formatString: "#,##0.00"
		lineageTag: be478467-bb36-5135-92b2-1280a432b523

	measure 'Average Revenue per Driver' = AVERAGEX(SUMMARIZE("Loads", 'Trips'[driver_id], "@value", SUM('Loads'[revenue])), [@value])
		formatString: "#,##0.00"
		lineageTag: b48816ec-1244-5c22-ae05-174fd572bc6d

	measure 'High Value Loads' = CALCULATE(DISTINCTCOUNT('Trips'[load_id]), 'Loads'[RevenueBand] = "High Value")
		formatString: "#,##0.00"
		lineageTag: 941ed71d-c9cd-5bf8-9c14-71585bf98f31

	measure 'Revenue %' = DIVIDE(SUM('Loads'[revenue]), CALCULATE(SUM('Loads'[revenue]), ALLSELECTED()), 0)
		formatString: "0.0%"
		lineageTag: f72e061a-527b-5da5-a953-892acb27092f

	measure 'Total Loads' = COUNT('Trips'[load_id])
		formatString: "#,##0.00"
		lineageTag: dc568f16-f764-5701-bf95-6f1a21fe4d5b

	column 'Load Type' = 'Loads'[load_type]
		dataType: string
		lineageTag: 01291e7b-c329-5d57-bb4a-35fb565e71fa
		summarizeBy: none

	column 'Booking Type' = 'Loads'[booking_type]
		dataType: string
		lineageTag: 1d20f7af-cd90-525f-ad73-c326bbd8afde
		summarizeBy: none

	column customer_id
		dataType: string
		lineageTag: f9aee854-a44e-583e-911e-b0a3c8d6d728
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column route_id
		dataType: string
		lineageTag: fac49772-56f1-52a7-8521-e03aecf65481
		summarizeBy: none
		sourceColumn: route_id

		annotation SummarizationSetBy = Automatic

	column load_id
		dataType: string
		lineageTag: d5e9dbe9-70ec-549f-93d4-88c964aeb994
		summarizeBy: none
		sourceColumn: load_id

		annotation SummarizationSetBy = Automatic

	column load_date
		dataType: dateTime
		lineageTag: d015f215-d74d-5b4c-b75a-6f60e9adb897
		summarizeBy: none
		sourceColumn: load_date
		formatString: General Date

		annotation SummarizationSetBy = Automatic

	column load_type
		dataType: string
		lineageTag: cec011a4-0571-5301-8667-00e470144aa6
		summarizeBy: none
		sourceColumn: load_type

		annotation SummarizationSetBy = Automatic

	column weight_lbs
		dataType: double
		lineageTag: d4d0b472-c8a2-5abf-973c-08da760a4765
		summarizeBy: sum
		sourceColumn: weight_lbs
		formatString: ###0

		annotation SummarizationSetBy = Automatic

	column pieces
		dataType: double
		lineageTag: 115c40fc-1695-5395-b1b3-cdcc5666e45a
		summarizeBy: sum
		sourceColumn: pieces
		formatString: ###0

		annotation SummarizationSetBy = Automatic

	column revenue
		dataType: double
		lineageTag: 1a41650e-0a8c-5cf9-af7f-beec7d3c1c04
		summarizeBy: sum
		sourceColumn: revenue
		formatString: ##############

		annotation SummarizationSetBy = Automatic

	column fuel_surcharge
		dataType: double
		lineageTag: e2f4d3bd-bea8-5a0e-a66d-66cd37ffbacc
		summarizeBy: sum
		sourceColumn: fuel_surcharge
		formatString: ##############

		annotation SummarizationSetBy = Automatic

	column accessorial_charges
		dataType: double
		lineageTag: e3933416-af83-51f9-b7e5-298adeabebbe
		summarizeBy: sum
		sourceColumn: accessorial_charges
		formatString: ##############

		annotation SummarizationSetBy = Automatic

	column load_status
		dataType: string
		lineageTag: 53352867-8cc2-5877-a19e-b8709cc9ca7a
		summarizeBy: none
		sourceColumn: load_status

		annotation SummarizationSetBy = Automatic

	column booking_type
		dataType: string
		lineageTag: d9ae0f6b-f9f8-5906-9d00-94110a53d571
		summarizeBy: none
		sourceColumn: booking_type

		annotation SummarizationSetBy = Automatic

	column RevenueBand = SWITCH(TRUE(), 'Loads'[revenue] >= 6000, "High Value", 'Loads'[revenue] >= 3000, "Medium Value", "Low Value")
		dataType: string
		lineageTag: 543f6047-0955-5329-ac40-4210c3bc9133
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Load Month' = Month('Loads'[load_date])
		dataType: double
		lineageTag: 632d891b-e1ca-5596-a7e1-ace5212f8996
		summarizeBy: sum
		formatString: #,##0.00

		annotation SummarizationSetBy = Automatic

	partition Loads = m
		mode: import
		source =
				let
				    Source = AmazonRedshift.Database("fleetvision-wg.881226714470.ap-southeast-2.redshift-serverless.amazonaws.com:5439", "dev"),
				    Result = Value.NativeQuery(Source, "SELECT * FROM fleetvision.loads", null, [EnableFolding=false]),
				    #"Changed Type" = Table.TransformColumnTypes(Result, {{"customer_id", type text}, {"route_id", type text}, {"load_id", type text}, {"load_date", type text}, {"load_type", type text}, {"weight_lbs", type number}, {"pieces", type number}, {"revenue", type number}, {"fuel_surcharge", type number}, {"accessorial_charges", type number}, {"load_status", type text}, {"booking_type", type text}, {"RevenueBand", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table