table Maintenance
	lineageTag: c75bd5d7-e55c-54a1-989f-8feb4433992f

	measure 'Total Maintainane Cost' = SUM('Maintenance'[maintenance_total_cost])
		formatString: "#,##0.00"
		lineageTag: 77f41ac7-0c8c-5611-814a-bcf9899d6369

	column truck_id
		dataType: string
		lineageTag: 32ec1da0-6836-5507-b254-e5039c74718e
		summarizeBy: none
		sourceColumn: truck_id

		annotation SummarizationSetBy = Automatic

	column maintenance_id
		dataType: string
		lineageTag: ce9ec557-f02e-54e9-bfaf-1e2f665df756
		summarizeBy: none
		sourceColumn: maintenance_id

		annotation SummarizationSetBy = Automatic

	column maintenance_date
		dataType: dateTime
		lineageTag: 6a4d1d20-7f1f-5992-a2a9-c9769c0a942a
		summarizeBy: none
		sourceColumn: maintenance_date
		formatString: General Date

		annotation SummarizationSetBy = Automatic

	column maintenance_type
		dataType: string
		lineageTag: 847e0af4-af79-5c6f-9e03-017e18101046
		summarizeBy: none
		sourceColumn: maintenance_type

		annotation SummarizationSetBy = Automatic

	column odometer_reading
		dataType: double
		lineageTag: 038241d8-57a1-5fe4-8963-c17fba582206
		summarizeBy: sum
		sourceColumn: odometer_reading
		formatString: ###0

		annotation SummarizationSetBy = Automatic

	column labor_hours
		dataType: double
		lineageTag: 962b58e9-c61c-5310-ab3f-312ac4120d0d
		summarizeBy: sum
		sourceColumn: labor_hours
		formatString: ##############

		annotation SummarizationSetBy = Automatic

	column labor_cost
		dataType: double
		lineageTag: fc70b322-2558-511b-a173-73a365cdf9c6
		summarizeBy: sum
		sourceColumn: labor_cost
		formatString: ##############

		annotation SummarizationSetBy = Automatic

	column parts_cost
		dataType: double
		lineageTag: b6fdd733-557f-56d7-b740-904ce21870a2
		summarizeBy: sum
		sourceColumn: parts_cost
		formatString: ##############

		annotation SummarizationSetBy = Automatic

	column maintenance_total_cost
		dataType: double
		lineageTag: 924a75f8-0942-59ef-8e8f-782e29a6ab05
		summarizeBy: sum
		sourceColumn: maintenance_total_cost
		formatString: ##############

		annotation SummarizationSetBy = Automatic

	column facility_location
		dataType: string
		lineageTag: 645ee12b-a4ff-5335-bb8d-6e5e0efb828e
		summarizeBy: none
		sourceColumn: facility_location

		annotation SummarizationSetBy = Automatic

	column downtime_hours
		dataType: double
		lineageTag: a62f3bf5-3362-592f-998e-62deeb89abe1
		summarizeBy: sum
		sourceColumn: downtime_hours
		formatString: ##############

		annotation SummarizationSetBy = Automatic

	column service_description
		dataType: string
		lineageTag: 8dd9cbf6-f21f-51c4-a5bf-899956e18384
		summarizeBy: none
		sourceColumn: service_description

		annotation SummarizationSetBy = Automatic

	partition Maintenance = m
		mode: import
		source =
				let
				    Source = AmazonRedshift.Database("fleetvision-wg.881226714470.ap-southeast-2.redshift-serverless.amazonaws.com:5439", "dev"),
				    Result = Value.NativeQuery(Source, "SELECT maintenance_id, truck_id, maintenance_date, maintenance_type, odometer_reading, labor_hours, labor_cost, parts_cost, total_cost AS maintenance_total_cost, facility_location, downtime_hours, service_description FROM fleetvision.maintenance_records", null, [EnableFolding=false]),
				    #"Renamed Columns" = Table.RenameColumns(Result, {{"total_cost", "maintenance_total_cost"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"truck_id", type text}, {"maintenance_id", type text}, {"maintenance_date", type text}, {"maintenance_type", type text}, {"odometer_reading", type number}, {"labor_hours", type number}, {"labor_cost", type number}, {"parts_cost", type number}, {"maintenance_total_cost", type number}, {"facility_location", type text}, {"downtime_hours", type number}, {"service_description", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table