table MaintenanceByTruck
	lineageTag: b25cf30f-944f-5acb-867f-2865adb4cad0

	column truck_id
		dataType: string
		lineageTag: 10c23d76-c733-59e6-8256-977e303922c3
		summarizeBy: none
		sourceColumn: truck_id

		annotation SummarizationSetBy = Automatic

	column MaintenanceEvents = CALCULATE(DISTINCTCOUNT('Maintenance'[maintenance_id]))
		dataType: int64
		lineageTag: 777b6bbb-c10c-5996-bca2-26c6b54ac5a8
		summarizeBy: sum
		formatString: ###0

		annotation SummarizationSetBy = Automatic

	column TotalMaintenanceCost = CALCULATE(SUM('Maintenance'[maintenance_total_cost]))
		dataType: double
		lineageTag: abd1a5e4-802f-5767-8c38-e97a37b62b1c
		summarizeBy: sum
		formatString: #,##0.00

		annotation SummarizationSetBy = Automatic

	column TotalDowntimeHours = CALCULATE(SUM('Maintenance'[downtime_hours]))
		dataType: double
		lineageTag: c5e3d8d6-68a4-55da-896d-bf5411232e9a
		summarizeBy: sum
		formatString: YYYY-MM-DD

		annotation SummarizationSetBy = Automatic

	column AvgDowntimeHours = CALCULATE(AVERAGE('Maintenance'[downtime_hours]))
		dataType: double
		lineageTag: c2847ac1-7ea9-5e8d-bf20-574fac218614
		summarizeBy: sum
		formatString: ########

		annotation SummarizationSetBy = Automatic

	column TotalLaborCost = CALCULATE(SUM('Maintenance'[labor_cost]))
		dataType: double
		lineageTag: c3c4b815-fafb-550f-9320-6d6239736fbe
		summarizeBy: sum
		formatString: #,##0.00

		annotation SummarizationSetBy = Automatic

	column TotalPartsCost = CALCULATE(SUM('Maintenance'[parts_cost]))
		dataType: double
		lineageTag: 11c3f4d4-e75c-5175-8e97-28332ad62a7e
		summarizeBy: sum
		formatString: #,##0.00

		annotation SummarizationSetBy = Automatic

	column AvgLaborHours = CALCULATE(AVERAGE('Maintenance'[labor_hours]))
		dataType: double
		lineageTag: 19e11044-a6f7-51b4-8034-5d6237d7da7d
		summarizeBy: sum
		formatString: ########

		annotation SummarizationSetBy = Automatic

	partition MaintenanceByTruck = m
		mode: import
		source =
				let
				    Source = #"Maintenance",
				    #"Selected Columns" = Table.SelectColumns(Source, {"truck_id"}),
				    #"Removed Duplicates" = Table.Distinct(#"Selected Columns")
				in
				    #"Removed Duplicates"

	annotation PBI_ResultType = Table
