table SafetyByTrip
	lineageTag: aa58eacf-4c38-56da-b2a4-32a0492f9137

	column trip_id
		dataType: string
		lineageTag: e5ef2bce-9187-5407-8570-b00e059eb4e0
		summarizeBy: none
		sourceColumn: trip_id

		annotation SummarizationSetBy = Automatic

	column SafetyIncidents = CALCULATE(DISTINCTCOUNT('SafetyIncidents'[incident_id]))
		dataType: double
		lineageTag: d731dbe6-39d5-555d-8038-75043b044cf6
		summarizeBy: sum
		formatString: ###0

		annotation SummarizationSetBy = Automatic

	column PreventableIncidents = CALCULATE(COUNTROWS('SafetyIncidents'), 'SafetyIncidents'[preventable_flag] = 1)
		dataType: double
		lineageTag: c3fc69af-3b1c-5ac5-880b-89e3b917e39e
		summarizeBy: sum
		formatString: #,##0

		annotation SummarizationSetBy = Automatic

	column InjuryIncidents = CALCULATE(COUNTROWS('SafetyIncidents'), 'SafetyIncidents'[injury_flag] = 1)
		dataType: double
		lineageTag: 4635d220-b341-5fc2-901a-9e8f9bac6e42
		summarizeBy: sum
		formatString: #,##0

		annotation SummarizationSetBy = Automatic

	column AtFaultIncidents = CALCULATE(COUNTROWS('SafetyIncidents'), 'SafetyIncidents'[at_fault_flag] = 1)
		dataType: double
		lineageTag: c02b0008-05aa-556f-996c-5bb0de59ed13
		summarizeBy: sum
		formatString: #,##0

		annotation SummarizationSetBy = Automatic

	column VehicleDamageCost = CALCULATE(SUM('SafetyIncidents'[vehicle_damage_cost]))
		dataType: double
		lineageTag: dceec3bc-c146-5c4e-9ced-aa6bc728f9be
		summarizeBy: sum
		formatString: #,##0.00

		annotation SummarizationSetBy = Automatic

	column CargoDamageCost = CALCULATE(SUM('SafetyIncidents'[cargo_damage_cost]))
		dataType: double
		lineageTag: bf16af75-143b-539f-977e-65d73e977b5a
		summarizeBy: sum
		formatString: #,##0.00

		annotation SummarizationSetBy = Automatic

	column ClaimAmount = CALCULATE(SUM('SafetyIncidents'[claim_amount]))
		dataType: double
		lineageTag: e49b00b3-7f3b-59f0-a985-84df8cc7bcf4
		summarizeBy: sum
		formatString: #,##0.00

		annotation SummarizationSetBy = Automatic

	partition SafetyByTrip = m
		mode: import
		source =
				let
				    Source = #"SafetyIncidents",
				    #"Selected Columns" = Table.SelectColumns(Source, {"trip_id"}),
				    #"Removed Duplicates" = Table.Distinct(#"Selected Columns")
				in
				    #"Removed Duplicates"

	annotation PBI_ResultType = Table
