table TruckPerformance
	lineageTag: 465a4b13-9cea-5d82-a904-b415d908d3d7

	column truck_id
		dataType: string
		lineageTag: 3cf0614d-07a3-5b0e-b752-263e9653ff41
		summarizeBy: none
		sourceColumn: truck_id

		annotation SummarizationSetBy = Automatic

	column TruckTrips = CALCULATE(DISTINCTCOUNT('Trips'[trip_id]))
		dataType: double
		lineageTag: a3c3519c-de0e-5eab-82e4-6aee90391607
		summarizeBy: sum
		formatString: ###0

		annotation SummarizationSetBy = Automatic

	column TruckMiles = CALCULATE(SUM('Trips'[actual_distance_miles]))
		dataType: double
		lineageTag: 61cd7d72-c934-5d24-bcbd-4d4a7aa0a0ba
		summarizeBy: sum
		formatString: #,##0

		annotation SummarizationSetBy = Automatic

	column TruckHours = CALCULATE(SUM('Trips'[actual_duration_hours]))
		dataType: double
		lineageTag: 4d08bd4d-6d19-51ec-a8c0-7e9949ceb3d2
		summarizeBy: sum
		formatString: #,##0.00

		annotation SummarizationSetBy = Automatic

	column TruckFuelGallons = CALCULATE(SUM('Trips'[fuel_gallons_used]))
		dataType: double
		lineageTag: 8f25cb4f-f83a-56d4-a428-d3e85f6742ec
		summarizeBy: sum
		formatString: #,##0.00

		annotation SummarizationSetBy = Automatic

	column TruckMPG = DIVIDE(CALCULATE(SUM('Trips'[actual_distance_miles])), CALCULATE(SUM('Trips'[fuel_gallons_used])), 0)
		dataType: double
		lineageTag: 384ea1ed-afcf-5f6b-8f67-7a55b4596283
		summarizeBy: sum
		formatString: #,##0.00

		annotation SummarizationSetBy = Automatic

	column TruckAvgIdleHours = CALCULATE(AVERAGE('Trips'[idle_time_hours]))
		dataType: double
		lineageTag: a8769a6e-9da8-5d92-8bff-1fa222209c07
		summarizeBy: sum
		formatString: ########

		annotation SummarizationSetBy = Automatic

	column TruckIdleHours = CALCULATE(SUM('Trips'[idle_time_hours]))
		dataType: double
		lineageTag: b5ec3feb-86f2-555c-8530-6f72d2c7a9fa
		summarizeBy: sum
		formatString: #,##0.00

		annotation SummarizationSetBy = Automatic

	partition TruckPerformance = m
		mode: import
		source =
				let
				    Source = #"Trips",
				    #"Selected Columns" = Table.SelectColumns(Source, {"truck_id"}),
				    #"Removed Duplicates" = Table.Distinct(#"Selected Columns")
				in
				    #"Removed Duplicates"

	annotation PBI_ResultType = Table
