table Trucks
	lineageTag: 73040672-c518-5b15-ba0c-643ceb78be53

	measure 'Active Trucks' = CALCULATE(DISTINCTCOUNT('Trips'[truck_id]), 'Trucks'[truck_status] = "Active")
		formatString: "#,##0.00"
		lineageTag: c15447ed-173b-597c-9fbd-28e01a6288cc

	measure 'Diesel Trucks' = CALCULATE(DISTINCTCOUNT('Trips'[truck_id]), 'Trucks'[fuel_type] = "Diesel")
		formatString: "#,##0.00"
		lineageTag: f6f5cf4a-1ce0-556e-8a42-57c0aa05be76

	column truck_id
		dataType: string
		lineageTag: b7013c61-049e-5aa8-ba0f-e722fd6b91a8
		summarizeBy: none
		sourceColumn: truck_id

		annotation SummarizationSetBy = Automatic

	column unit_number
		dataType: int64
		lineageTag: 0e1ef306-99e3-50e5-a961-5ac3429de1ae
		summarizeBy: sum
		sourceColumn: unit_number
		formatString: ###0

		annotation SummarizationSetBy = Automatic

	column make
		dataType: string
		lineageTag: dedc418c-722c-52e7-b7f7-d19d7d951059
		summarizeBy: none
		sourceColumn: make

		annotation SummarizationSetBy = Automatic

	column truck_model_year
		dataType: int64
		lineageTag: 5a007012-c08e-5d30-8d3a-04b12852280b
		summarizeBy: none
		sourceColumn: truck_model_year
		formatString: #,##0

		annotation SummarizationSetBy = Automatic

	column truck_vin
		dataType: string
		lineageTag: bd430b8b-5845-581e-ae1c-55b5040bd471
		summarizeBy: none
		sourceColumn: truck_vin

		annotation SummarizationSetBy = Automatic

	column truck_acquisition_date
		dataType: dateTime
		lineageTag: 2e4c72cd-e481-55b7-867c-42ca2fc6fb24
		summarizeBy: none
		sourceColumn: truck_acquisition_date
		formatString: General Date

		annotation SummarizationSetBy = Automatic

	column acquisition_mileage
		dataType: double
		lineageTag: 250cf308-dbe2-5b4f-8a59-47ce9e99fdf8
		summarizeBy: sum
		sourceColumn: acquisition_mileage
		formatString: ###0

		annotation SummarizationSetBy = Automatic

	column fuel_type
		dataType: string
		lineageTag: 4cb86b0b-807b-5b29-bbd0-5187c33b2d9a
		summarizeBy: none
		sourceColumn: fuel_type

		annotation SummarizationSetBy = Automatic

	column tank_capacity_gallons
		dataType: double
		lineageTag: 3bf65880-7cf0-55d9-a4be-fcb8a908112f
		summarizeBy: sum
		sourceColumn: tank_capacity_gallons
		formatString: ###0

		annotation SummarizationSetBy = Automatic

	column truck_status
		dataType: string
		lineageTag: 3140ac2e-3bdc-58ac-a113-fa169e3d4934
		summarizeBy: none
		sourceColumn: truck_status

		annotation SummarizationSetBy = Automatic

	column truck_home_terminal
		dataType: string
		lineageTag: bb3b2d4c-4c72-5a36-8a99-9af955ca22cf
		summarizeBy: none
		sourceColumn: truck_home_terminal

		annotation SummarizationSetBy = Automatic

	column Truck = 'Trucks'[unit_number]
		dataType: double
		lineageTag: b85298fb-db04-5fac-9a98-62f9c838b31b
		summarizeBy: sum
		formatString: #,##0.00

		annotation SummarizationSetBy = Automatic

	partition Trucks = m
		mode: import
		source =
				let
				    Source = AmazonRedshift.Database("fleetvision-wg.881226714470.ap-southeast-2.redshift-serverless.amazonaws.com:5439", "dev"),
				    Result = Value.NativeQuery(Source, "SELECT truck_id, unit_number, make, model_year AS truck_model_year, vin AS truck_vin, acquisition_date AS truck_acquisition_date, acquisition_mileage, fuel_type, tank_capacity_gallons, status AS truck_status, home_terminal AS truck_home_terminal FROM fleetvision.trucks", null, [EnableFolding=false]),
				    #"Renamed Columns" = Table.RenameColumns(Result, {{"model_year", "truck_model_year"}, {"vin", "truck_vin"}, {"acquisition_date", "truck_acquisition_date"}, {"status", "truck_status"}, {"home_terminal", "truck_home_terminal"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"truck_id", type text}, {"unit_number", Int64.Type}, {"make", type text}, {"truck_model_year", Int64.Type}, {"truck_vin", type text}, {"truck_acquisition_date", type text}, {"acquisition_mileage", type number}, {"fuel_type", type text}, {"tank_capacity_gallons", type number}, {"truck_status", type text}, {"truck_home_terminal", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table