table 'Weather_Data'
    lineageTag: d6a62e56-e6fd-4a78-9ca6-db627652737c

    column 'City'
        dataType: string
        lineageTag: 2942b248-bd15-407a-ab4d-5c97ede29460
        summarizeBy: none
        sourceColumn: City

    column 'Date'
        sourceColumn: Date
        dataType: dateTime
        formatString: Long Date
        lineageTag: e27eb4ff-3c65-415a-a749-8e22fa4de913
        summarizeBy: none

        variation Variation
            isDefault
            relationship: befb3abd-a597-451f-838a-0a0e51b54dc4
            defaultHierarchy: LocalDateTable_3b00d9d0-4efd-469a-aa5d-f650c5cfee93.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Record_Type'
        dataType: string
        lineageTag: 0c33daf4-bb8d-44a5-9f72-c0f904e4f750
        summarizeBy: none
        sourceColumn: Record_Type

    column 'Temperature'
        dataType: double
        lineageTag: 5c5df39d-4e16-4bf2-84be-7956de8eef9e
        summarizeBy: none
        sourceColumn: Temperature

    column 'Temp_Min'
        dataType: double
        lineageTag: 54961e3c-2297-4f22-a854-f46e5aad1841
        summarizeBy: none
        sourceColumn: Temp_Min

    column 'Temp_Max'
        dataType: double
        lineageTag: 00dbe62a-e57a-4829-ba2a-66b1e0c50f68
        summarizeBy: none
        sourceColumn: Temp_Max

    column 'Precipitation'
        dataType: double
        lineageTag: 4a235275-9770-4f5a-95b2-28ad8346802a
        summarizeBy: none
        sourceColumn: Precipitation

    column 'Weather_Code'
        dataType: double
        lineageTag: 6fa8605e-24a9-488b-9ea9-04935f3b3670
        summarizeBy: none
        sourceColumn: Weather_Code

    column 'Latitude'
        dataType: double
        lineageTag: d3985ba8-10c8-462c-8f0c-fdae599029ed
        summarizeBy: none
        sourceColumn: Latitude

    column 'Longitude'
        dataType: double
        lineageTag: e5759a93-dc52-4aba-983c-02aaf5d2afc7
        summarizeBy: none
        sourceColumn: Longitude

    column 'Observation_Time'
        sourceColumn: Observation_Time
        dataType: dateTime
        formatString: General Date
        lineageTag: a074b9fc-3e0c-41ec-8645-69d178976931
        summarizeBy: none

        variation Variation
            isDefault
            relationship: e4cc2429-e64b-4848-b8a7-69d42d7eca77
            defaultHierarchy: LocalDateTable_6feb13e8-c793-4521-a0e6-3ddba3e22456.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    measure '30-Day High' =
        VAR _MaxDate = TODAY()
        VAR _MinDate = _MaxDate - 30
        RETURN CALCULATE(MAX('Weather_Data'[Temp_Max]), KEEPFILTERS('Weather_Data'[Date] >= _MinDate), KEEPFILTERS('Weather_Data'[Date] <= _MaxDate))


    measure '30-Day Low' =
        VAR _MaxDate = TODAY()
        VAR _MinDate = _MaxDate - 30
        RETURN CALCULATE(MIN('Weather_Data'[Temp_Min]), KEEPFILTERS('Weather_Data'[Date] >= _MinDate), KEEPFILTERS('Weather_Data'[Date] <= _MaxDate))


    measure '30-Day Avg' =
        VAR _MaxDate = TODAY()
        VAR _MinDate = _MaxDate - 30
        RETURN INT(
            CALCULATE(
                AVERAGE('Weather_Data'[Temperature]),
                KEEPFILTERS('Weather_Data'[Date] >= _MinDate),
                KEEPFILTERS('Weather_Data'[Date] <= _MaxDate)
            )
        )


    measure 'Change Percentage' =
        DIVIDE(AVERAGE('Weather_Data'[Temperature]) - AVERAGE('Weather_Data'[Temp_Min]), ABS(AVERAGE('Weather_Data'[Temp_Min])), 0) * 100


    measure 'AVG of Temperature' =
        AVERAGE('Weather_Data'[Temperature])


    measure 'SUM of Precipitation' =
        SUM('Weather_Data'[Precipitation])


    measure 'SUM of Highest Avg Temp' =
        SUM('Weather_Data'[Highest Avg Temp])


    measure 'Highest Avg Temp' =
        CALCULATE(AVERAGE('Weather_Data'[Temp_Max]), ALLEXCEPT('Weather_Data', 'Weather_Data'[City]))


    measure 'Lowest Avg Temp' =
        CALCULATE(AVERAGE('Weather_Data'[Temp_Min]), ALLEXCEPT('Weather_Data', 'Weather_Data'[City]))


    partition 'Weather_Data' = m
        mode: import
        source =
            let
                Source = GoogleBigQuery.Database([BillingProject = null, UseStorageApi = null, ConnectionTimeout = null, CommandTimeout = null, ProjectId = null]),
                #"Navigation 1" = Source{[Name = "ordinal-avatar-497006-v6"]}[Data],
                #"Navigation 2" = #"Navigation 1"{[Name = "Weather_001", Kind = "Schema"]}[Data],
                #"Navigation 3" = #"Navigation 2"{[Name = "Weather_Data", Kind = "Table"]}[Data],
                #"Changed Type" = Table.TransformColumnTypes(#"Navigation 3", {{"City", type text}, {"Date", type date}, {"Record_Type", type text}, {"Temperature", type number}, {"Temp_Min", type number}, {"Temp_Max", type number}, {"Precipitation", type number}, {"Weather_Code", type number}, {"Latitude", type number}, {"Longitude", type number}, {"Observation_Time", type datetime}})
            in
                #"Changed Type"
