table 'Weather_Data'
    lineageTag: 0f92f0a4-f24e-4c79-9955-4afb2f516a67

    column 'City'
        dataType: string
        lineageTag: a6928f65-9ddf-4329-873d-623d435cfa34
        summarizeBy: none
        sourceColumn: City

    column 'Date'
        sourceColumn: Date
        dataType: dateTime
        formatString: Long Date
        lineageTag: 1906219d-fc85-493a-be09-8a59277ac0ad
        summarizeBy: none

        variation Variation
            isDefault
            relationship: cc069cf0-224f-447f-970d-3dd10be9051a
            defaultHierarchy: LocalDateTable_caf9bef4-9936-4737-a79a-71f3b08fc364.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Record_Type'
        dataType: string
        lineageTag: 9b7b1037-bf83-4c73-9fc0-bb9f9c6d13a9
        summarizeBy: none
        sourceColumn: Record_Type

    column 'Temperature'
        dataType: double
        lineageTag: b46971e8-4f2e-47ec-b4f8-38a270310b20
        summarizeBy: none
        sourceColumn: Temperature

    column 'Temp_Min'
        dataType: double
        lineageTag: 44628475-730d-444d-97be-57a9e8f195bf
        summarizeBy: none
        sourceColumn: Temp_Min

    column 'Temp_Max'
        dataType: double
        lineageTag: 16ac2736-efe3-49c2-a20e-7f5ab34a2308
        summarizeBy: none
        sourceColumn: Temp_Max

    column 'Precipitation'
        dataType: double
        lineageTag: 53b3fc3f-962c-48ba-bb86-b65fa266e629
        summarizeBy: none
        sourceColumn: Precipitation

    column 'Weather_Code'
        dataType: double
        lineageTag: 13d75fc3-588e-48fd-b8eb-dae527d0c800
        summarizeBy: none
        sourceColumn: Weather_Code

    column 'Latitude'
        dataType: double
        lineageTag: 4b718e1b-96dd-4b12-8420-74dbedea7ba3
        summarizeBy: none
        sourceColumn: Latitude

    column 'Longitude'
        dataType: double
        lineageTag: 2f855db1-4a3a-4bb8-87e7-ae6f2bdf77eb
        summarizeBy: none
        sourceColumn: Longitude

    column 'Observation_Time'
        sourceColumn: Observation_Time
        dataType: dateTime
        formatString: General Date
        lineageTag: 4dbaad82-69d6-47da-92c1-39ccdcaa3368
        summarizeBy: none

        variation Variation
            isDefault
            relationship: c3f15805-54db-460d-879d-39718a974069
            defaultHierarchy: LocalDateTable_cc2a855f-8c4e-498f-b968-c5609c3c5f9c.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    measure '30-Day High' =
        VAR _MaxDate = TODAY()
        VAR _MinDate = _MaxDate - 30
        RETURN CALCULATE(MAX('Weather_Data'[Temp_Max]), KEEPFILTERS('Weather_Data'[Date] >= _MinDate), KEEPFILTERS('Weather_Data'[Date] <= _MaxDate))


    measure '30-Day Low' =
        VAR _MaxDate = TODAY()
        VAR _MinDate = _MaxDate - 30
        RETURN CALCULATE(MIN('Weather_Data'[Temp_Min]), KEEPFILTERS('Weather_Data'[Date] >= _MinDate), KEEPFILTERS('Weather_Data'[Date] <= _MaxDate))


    measure '30-Day Avg' =
        VAR _MaxDate = TODAY()
        VAR _MinDate = _MaxDate - 30
        RETURN INT(
            AVERAGEX(
                FILTER(
                    'Weather_Data',
                    'Weather_Data'[Date] >= _MinDate &&
                    'Weather_Data'[Date] <= _MaxDate
                ),
                'Weather_Data'[Temperature]
            )
        )


    measure 'Change Percentage' =
        DIVIDE(AVERAGE('Weather_Data'[Temperature]) - AVERAGE('Weather_Data'[Temp_Min]), ABS(AVERAGE('Weather_Data'[Temp_Min])), 0) * 100


    measure 'AVG of Temperature' =
        AVERAGE('Weather_Data'[Temperature])


    measure 'SUM of Precipitation' =
        SUM('Weather_Data'[Precipitation])


    measure 'SUM of Highest Avg Temp' =
        SUM('Weather_Data'[Highest Avg Temp])


    measure 'Highest Avg Temp' =
        CALCULATE(AVERAGE('Weather_Data'[Temp_Max]), ALLEXCEPT('Weather_Data', 'Weather_Data'[City]))


    measure 'Lowest Avg Temp' =
        CALCULATE(AVERAGE('Weather_Data'[Temp_Min]), ALLEXCEPT('Weather_Data', 'Weather_Data'[City]))


    partition 'Weather_Data' = m
        mode: import
        source =
            let
                Source = GoogleBigQuery.Database([BillingProject = null, UseStorageApi = null, ConnectionTimeout = null, CommandTimeout = null, ProjectId = null]),
                #"Navigation 1" = Source{[Name = "ordinal-avatar-497006-v6"]}[Data],
                #"Navigation 2" = #"Navigation 1"{[Name = "Weather_001", Kind = "Schema"]}[Data],
                #"Navigation 3" = #"Navigation 2"{[Name = "Weather_Data", Kind = "Table"]}[Data],
                #"Changed Type" = Table.TransformColumnTypes(#"Navigation 3", {{"City", type text}, {"Date", type date}, {"Record_Type", type text}, {"Temperature", type number}, {"Temp_Min", type number}, {"Temp_Max", type number}, {"Precipitation", type number}, {"Weather_Code", type number}, {"Latitude", type number}, {"Longitude", type number}, {"Observation_Time", type datetime}})
            in
                #"Changed Type"
