table 'payers'
    lineageTag: b7b27e0f-5d0d-46e0-86eb-c5c46085f1bf

    column 'Id (payers)'
        dataType: string
        lineageTag: bb25910e-9538-4a2f-9095-dd1b9b61f63b
        summarizeBy: none
        sourceColumn: Id (payers)

    column 'NAME (payers)'
        dataType: string
        lineageTag: 866e5c79-c3de-4ae9-bcdd-a2089d6cd7b0
        summarizeBy: none
        sourceColumn: NAME (payers)

    column 'ADDRESS (payers)'
        dataType: string
        lineageTag: 8e2122c7-f74f-40e1-8276-32f530a3237b
        summarizeBy: none
        sourceColumn: ADDRESS (payers)

    column 'CITY (payers)'
        dataType: string
        lineageTag: 5a5f275b-5117-4e3d-b593-4c0da9c6b615
        summarizeBy: none
        sourceColumn: CITY (payers)

    column 'State Headquartered'
        dataType: string
        lineageTag: d4e25ee3-a8df-4223-904a-1d558bff511f
        summarizeBy: none
        sourceColumn: State Headquartered

    column 'ZIP (payers)'
        dataType: double
        lineageTag: 8af8df2d-126e-44b7-ac2e-c5ad06b57293
        summarizeBy: none
        sourceColumn: ZIP (payers)

    column 'Phone'
        dataType: string
        lineageTag: fb5f9e42-8ef6-44ab-9260-08463730bdb1
        summarizeBy: none
        sourceColumn: Phone

    partition 'payers' = m
        mode: import
        source =
            let Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1NB9uAQnBa6RYGfm5addKbcToYUZJY_5OlBkWxVZRrbU"),
            #"Navigation 1" = Source{[name = "payers", ItemKind = "Table"]}[Data],
                            #"Final Renamed Columns" = Table.RenameColumns(#"Navigation 1", {{"Id", "Id (payers)"}, {"NAME", "NAME (payers)"}, {"ADDRESS", "ADDRESS (payers)"}, {"CITY", "CITY (payers)"}, {"STATE_HEADQUARTERED", "State Headquartered"}, {"ZIP", "ZIP (payers)"}, {"PHONE", "Phone"}}, MissingField.Ignore)
                        in
                            #"Final Renamed Columns"
