table 'organizations'
    lineageTag: d77b3114-b87a-41c2-8ee0-c0d3305e5607

    column 'Id (organizations)'
        dataType: string
        lineageTag: dedffd2a-8afd-4665-9653-b3e21d36cc20
        summarizeBy: none
        sourceColumn: Id (organizations)

    column 'Name'
        dataType: string
        lineageTag: 8756bc1f-6552-4154-9946-6839acd769d8
        summarizeBy: none
        sourceColumn: Name

    column 'ADDRESS (organizations)'
        dataType: string
        lineageTag: c6917d2a-f6c7-4aa0-9d93-8e41cee20b8f
        summarizeBy: none
        sourceColumn: ADDRESS (organizations)

    column 'CITY (organizations)'
        dataType: string
        lineageTag: 7ba8ac9d-a963-4a7b-9282-d1f7fb4bd4ee
        summarizeBy: none
        sourceColumn: CITY (organizations)

    column 'STATE (organizations)'
        dataType: string
        lineageTag: e7141354-d88d-47d7-8368-218ba82d9aca
        summarizeBy: none
        sourceColumn: STATE (organizations)

    column 'ZIP (organizations)'
        dataType: double
        lineageTag: 50a3982f-a67c-45a3-9bd3-590b2a2a70a8
        summarizeBy: none
        sourceColumn: ZIP (organizations)

    column 'LAT (organizations)'
        dataType: double
        lineageTag: 436bb1d3-53fc-4956-b9e5-f8acebc418f7
        summarizeBy: none
        sourceColumn: LAT (organizations)

    column 'LON (organizations)'
        dataType: double
        lineageTag: d00d9f93-6ded-4acd-a8c8-7650fb3727db
        summarizeBy: none
        sourceColumn: LON (organizations)

    column 'Username' = -- SKIPPED BY USER
        dataType: string

        summarizeBy: none

    measure 'RLS - Organization Access' =
        -- SKIPPED BY USER


    partition 'organizations' = m
        mode: import
        source =
            let Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1Gfqr930PI28eveUiJrS8ikSsyzDUbPE4pJy7nG9ZIUc"),
            #"Navigation 1" = Source{[name = "organizations", ItemKind = "Table"]}[Data],
                            #"Final Renamed Columns" = Table.RenameColumns(#"Navigation 1", {{"Id", "Id (organizations)"}, {"NAME", "Name"}, {"ADDRESS", "ADDRESS (organizations)"}, {"CITY", "CITY (organizations)"}, {"STATE", "STATE (organizations)"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}}, MissingField.Ignore)
                        in
                            #"Final Renamed Columns"
