table 'procedures'
    lineageTag: d654d25d-6b66-4a5b-8f1a-d1d8e31e2c7f

    column 'START (procedures)'
        dataType: string
        lineageTag: cc3e3159-1a67-4b47-853a-ec0b05eb5f9f
        summarizeBy: none
        sourceColumn: START (procedures)

    column 'STOP (procedures)'
        dataType: string
        lineageTag: 629aa314-41ff-4ac9-876c-f5498c5121cf
        summarizeBy: none
        sourceColumn: STOP (procedures)

    column 'PATIENT (procedures)'
        dataType: string
        lineageTag: 195d5041-1183-481d-a046-3557759ca472
        summarizeBy: none
        sourceColumn: PATIENT (procedures)

    column 'Encounter'
        dataType: string
        lineageTag: b8481987-9804-4b76-ab34-6ff59678bf13
        summarizeBy: none
        sourceColumn: Encounter

    column 'CODE (procedures)'
        dataType: double
        lineageTag: 683985cb-dd76-4c47-95d8-afbdd11e4309
        summarizeBy: none
        sourceColumn: CODE (procedures)

    column 'DESCRIPTION (procedures)'
        dataType: string
        lineageTag: db71c1be-0667-42cf-bcdd-3ab7abd29251
        summarizeBy: none
        sourceColumn: DESCRIPTION (procedures)

    column 'Base Cost'
        dataType: double
        lineageTag: 23c2b4b1-14cf-43bc-b6cb-4f2fa6ed5bd7
        summarizeBy: none
        sourceColumn: Base Cost

    column 'REASONCODE (procedures)'
        dataType: double
        lineageTag: 707012be-505f-462d-afb8-801f0165a178
        summarizeBy: none
        sourceColumn: REASONCODE (procedures)

    column 'REASONDESCRIPTION (procedures)'
        dataType: string
        lineageTag: e85637ca-4baf-45f3-aa30-45bb8067d5b2
        summarizeBy: none
        sourceColumn: REASONDESCRIPTION (procedures)

    column 'DESCRIPTION (procedures) Set' = -- SKIPPED
        dataType: string

        summarizeBy: none

    measure 'Procedure Rank(Top N Procedure Parameter)' =
        -- SKIPPED BY USER


    measure 'Top N Procedures Filter' =
        -- SKIPPED BY USER


    measure 'Selected Metric' =
        -- SKIPPED BY USER


    partition 'procedures' = m
        mode: import
        source =
            let Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/10X1xQHkGidpz_0qYh7o9mxmsRJsOHRB9bNnSKFnUNgo"),
            #"Navigation 1" = Source{[name = "procedures", ItemKind = "Table"]}[Data],
                            #"Final Renamed Columns" = Table.RenameColumns(#"Navigation 1", {{"START", "START (procedures)"}, {"STOP", "STOP (procedures)"}, {"PATIENT", "PATIENT (procedures)"}, {"ENCOUNTER", "Encounter"}, {"CODE", "CODE (procedures)"}, {"DESCRIPTION", "DESCRIPTION (procedures)"}, {"BASE_COST", "Base Cost"}, {"REASONCODE", "REASONCODE (procedures)"}, {"REASONDESCRIPTION", "REASONDESCRIPTION (procedures)"}}, MissingField.Ignore)
                        in
                            #"Final Renamed Columns"
