table 'patients'
    lineageTag: 5a5c76f0-3243-4d0a-85e0-eb63e122cdd0

    column 'Id (patients)'
        dataType: string
        lineageTag: 57e494ef-7a1c-4adb-aa8c-fafa0fafe8f4
        summarizeBy: none
        sourceColumn: Id (patients)

    column 'Birthdate'
        sourceColumn: Birthdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: 78d2ee63-15ec-466b-8d12-092da519c472
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 30d445dd-0481-4c21-8320-db3b7e5692b6
            defaultHierarchy: LocalDateTable_735a9355-dcb6-4063-a655-2a1844d9ed80.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Deathdate'
        sourceColumn: Deathdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: 560129ab-74d6-416a-a2c8-5976a8385a3e
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 2d4bc682-e8b1-43e7-9112-f34e9bb64f3d
            defaultHierarchy: LocalDateTable_6d27e5fa-9c8a-46ee-a617-2c4212a14e34.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Prefix'
        dataType: string
        lineageTag: 35de979f-7d56-4de2-8dc9-8e9d723ce4a2
        summarizeBy: none
        sourceColumn: Prefix

    column 'First'
        dataType: string
        lineageTag: d877ee1d-2c77-4766-89c0-6488051c2e11
        summarizeBy: none
        sourceColumn: First

    column 'Last'
        dataType: string
        lineageTag: cb521419-388b-486b-b68d-b482ce66271a
        summarizeBy: none
        sourceColumn: Last

    column 'Suffix'
        dataType: string
        lineageTag: 200a79a8-d798-404c-b4e4-691bd63706ee
        summarizeBy: none
        sourceColumn: Suffix

    column 'Maiden'
        dataType: string
        lineageTag: eafd5820-2e5a-446b-84a8-6766cfc63cac
        summarizeBy: none
        sourceColumn: Maiden

    column 'Marital'
        dataType: string
        lineageTag: 350a70f3-ca93-4653-af86-5928c0080d24
        summarizeBy: none
        sourceColumn: Marital

    column 'Race'
        dataType: string
        lineageTag: 2fbd2a87-5c82-43bf-8ded-9d421ca47926
        summarizeBy: none
        sourceColumn: Race

    column 'Ethnicity'
        dataType: string
        lineageTag: 04de18eb-80a4-4653-ae7a-17bb4eb41011
        summarizeBy: none
        sourceColumn: Ethnicity

    column 'Gender'
        dataType: string
        lineageTag: 4095d51d-48e3-4896-bf6c-61ae8d7d742d
        summarizeBy: none
        sourceColumn: Gender

    column 'Birthplace'
        dataType: string
        lineageTag: 4041a4de-7118-4a5a-b607-a2a8397185be
        summarizeBy: none
        sourceColumn: Birthplace

    column 'Address'
        dataType: string
        lineageTag: 50f8688d-1030-44b0-8296-6f22cd6b3e00
        summarizeBy: none
        sourceColumn: Address

    column 'City'
        dataType: string
        lineageTag: e42b2852-2114-4c49-858a-2518d871d520
        summarizeBy: none
        sourceColumn: City

    column 'State'
        dataType: string
        lineageTag: 8f86302d-a320-41e4-8044-6ffc5c7f59cd
        summarizeBy: none
        sourceColumn: State

    column 'County'
        dataType: string
        lineageTag: 1f5a9e37-6834-4733-b34c-1adecc89e65d
        summarizeBy: none
        sourceColumn: County

    column 'ZIP (organizations)'
        dataType: double
        lineageTag: 46b2768b-3437-4de4-a8da-dfa34a81a743
        summarizeBy: none
        sourceColumn: ZIP (organizations)

    column 'LAT (organizations)'
        dataType: double
        lineageTag: 868d82ad-ab31-4874-8482-88147838d6d0
        summarizeBy: none
        sourceColumn: LAT (organizations)

    column 'LON (organizations)'
        dataType: double
        lineageTag: ccea54f2-a09d-4355-b681-5d455135d979
        summarizeBy: none
        sourceColumn: LON (organizations)

    measure 'SUM of Avg Visits per Patient (patients)' =
        SUM('patients'[Avg Visits per Patient])


    measure 'SUM of Visits per Patient (patients)' =
        SUM('patients'[Visits per Patient])


    measure 'Total Patients (LOD)' =
        -- ERROR CONVERTING: LLM call failed after 6 retries. Last error: 404 Client Error: Not Found for url: https://api.groq.com/openai/v1/chat/completions


    measure 'Visits per Patient' =
        -- ERROR CONVERTING: LLM call failed after 6 retries. Last error: 404 Client Error: Not Found for url: https://api.groq.com/openai/v1/chat/completions


    measure 'Avg Visits per Patient' =
        -- ERROR CONVERTING: LLM call failed after 6 retries. Last error: 404 Client Error: Not Found for url: https://api.groq.com/openai/v1/chat/completions


    partition 'patients' = m
        mode: import
        source =
            let
                Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1Sd4bEK0Fm9q7yTVOwI4GdtixeeY8hPkKqpvnI4WdixA/edit"),
                #"Navigation 1" = Source{[name = "patients", ItemKind = "Table"]}[Data],
                #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
                #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Id", type text}, {"BIRTHDATE", type date}, {"DEATHDATE", type date}, {"PREFIX", type text}, {"FIRST", type text}, {"LAST", type text}, {"SUFFIX", type text}, {"MAIDEN", type text}, {"MARITAL", type text}, {"RACE", type text}, {"ETHNICITY", type text}, {"GENDER", type text}, {"BIRTHPLACE", type text}, {"ADDRESS", type text}, {"CITY", type text}, {"STATE", type text}, {"COUNTY", type text}, {"ZIP", type number}, {"LAT", type number}, {"LON", type number}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"Id", "Id (patients)"}, {"BIRTHDATE", "Birthdate"}, {"DEATHDATE", "Deathdate"}, {"PREFIX", "Prefix"}, {"FIRST", "First"}, {"LAST", "Last"}, {"SUFFIX", "Suffix"}, {"MAIDEN", "Maiden"}, {"MARITAL", "Marital"}, {"RACE", "Race"}, {"ETHNICITY", "Ethnicity"}, {"GENDER", "Gender"}, {"BIRTHPLACE", "Birthplace"}, {"ADDRESS", "Address"}, {"CITY", "City"}, {"STATE", "State"}, {"COUNTY", "County"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}})
            in
                #"Renamed Columns"
