table 'patients'
    lineageTag: 00ee0022-21bf-436b-984f-eada01a04a95

    column 'Id (patients)'
        dataType: string
        lineageTag: 3f623ce0-8ac6-400d-83c0-a38c8712360e
        summarizeBy: none
        sourceColumn: Id (patients)

    column 'Birthdate'
        sourceColumn: Birthdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: b212710e-7927-4473-8f6a-7398fabeda9c
        summarizeBy: none

        variation Variation
            isDefault
            relationship: a53cddde-5bf8-40a9-91aa-be1d802f4b6f
            defaultHierarchy: LocalDateTable_c2b41fdc-5f87-4833-830b-954cb6696023.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Deathdate'
        sourceColumn: Deathdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: 4180889c-b17d-4f89-8c90-51348c34ba40
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 83dcc815-21be-4b99-8797-99af9eb648e9
            defaultHierarchy: LocalDateTable_0256abe3-44b0-4c2e-bd97-2d2f27f29f70.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Prefix'
        dataType: string
        lineageTag: cb36f112-8579-47fb-b0ee-814bbe388b11
        summarizeBy: none
        sourceColumn: Prefix

    column 'First'
        dataType: string
        lineageTag: 286f28d1-aa84-4965-8ac3-f250dadd7ddb
        summarizeBy: none
        sourceColumn: First

    column 'Last'
        dataType: string
        lineageTag: 6cfcf5ef-22b6-43fc-987d-f2e5f14423a4
        summarizeBy: none
        sourceColumn: Last

    column 'Suffix'
        dataType: string
        lineageTag: aa333b77-a37b-4273-acf1-9db84dd74915
        summarizeBy: none
        sourceColumn: Suffix

    column 'Maiden'
        dataType: string
        lineageTag: d91bf85c-5a5a-4c67-9fa0-a071ab7edab5
        summarizeBy: none
        sourceColumn: Maiden

    column 'Marital'
        dataType: string
        lineageTag: e3970a28-66ba-4cb3-a0ca-506dc0d4d153
        summarizeBy: none
        sourceColumn: Marital

    column 'Race'
        dataType: string
        lineageTag: a9479d4c-5e51-4007-b11b-56d8581085e9
        summarizeBy: none
        sourceColumn: Race

    column 'Ethnicity'
        dataType: string
        lineageTag: 49431a2e-fc15-41d0-a4e2-5c829138c1e9
        summarizeBy: none
        sourceColumn: Ethnicity

    column 'Gender'
        dataType: string
        lineageTag: 4c79717b-7d85-4e76-b05f-1333f3d0aeda
        summarizeBy: none
        sourceColumn: Gender

    column 'Birthplace'
        dataType: string
        lineageTag: 6b1c6a3f-e04c-4aa7-9938-487f9575eda7
        summarizeBy: none
        sourceColumn: Birthplace

    column 'Address'
        dataType: string
        lineageTag: 0742ed60-8d22-4c8d-a0c1-d288038a9077
        summarizeBy: none
        sourceColumn: Address

    column 'City'
        dataType: string
        lineageTag: 091c20bb-f107-4738-8229-443385560f70
        summarizeBy: none
        sourceColumn: City

    column 'State'
        dataType: string
        lineageTag: e51d95d1-16e9-4262-a59b-5e3e46fcdc70
        summarizeBy: none
        sourceColumn: State

    column 'County'
        dataType: string
        lineageTag: 97f1de2b-eca9-4c2e-abc8-b3009b5f15a3
        summarizeBy: none
        sourceColumn: County

    column 'ZIP (organizations)'
        dataType: double
        lineageTag: f6524bb9-eb37-4837-a81b-af736a6e069b
        summarizeBy: none
        sourceColumn: ZIP (organizations)

    column 'LAT (organizations)'
        dataType: double
        lineageTag: 60f61522-38d9-40e9-a09a-eaf6f8679d35
        summarizeBy: none
        sourceColumn: LAT (organizations)

    column 'LON (organizations)'
        dataType: double
        lineageTag: 24afe9c5-1786-49f7-8e39-da58c84e264e
        summarizeBy: none
        sourceColumn: LON (organizations)

    measure 'SUM of Avg Visits per Patient (patients)' =
        SUM('patients'[Avg Visits per Patient])


    measure 'SUM of Visits per Patient (patients)' =
        SUM('patients'[Visits per Patient])


    measure 'Total Patients (LOD)' =
        -- SKIPPED BY USER


    measure 'Visits per Patient' =
        -- SKIPPED BY USER


    measure 'Avg Visits per Patient' =
        -- SKIPPED BY USER


    partition 'patients' = m
        mode: import
        source =
            let Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1Sd4bEK0Fm9q7yTVOwI4GdtixeeY8hPkKqpvnI4WdixA"),
            #"Navigation 1" = Source{[name="patients", ItemKind="Table"]}[Data],
            #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars=true]),
            #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Id", type text}, {"BIRTHDATE", type date}, {"DEATHDATE", type date}, {"PREFIX", type text}, {"FIRST", type text}, {"LAST", type text}, {"SUFFIX", type text}, {"MAIDEN", type text}, {"MARITAL", type text}, {"RACE", type text}, {"ETHNICITY", type text}, {"GENDER", type text}, {"BIRTHPLACE", type text}, {"ADDRESS", type text}, {"CITY", type text}, {"STATE", type text}, {"COUNTY", type text}, {"ZIP", type number}, {"LAT", type number}, {"LON", type number}}),
            #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"Id", "Id (patients)"}, {"BIRTHDATE", "Birthdate"}, {"DEATHDATE", "Deathdate"}, {"PREFIX", "Prefix"}, {"FIRST", "First"}, {"LAST", "Last"}, {"SUFFIX", "Suffix"}, {"MAIDEN", "Maiden"}, {"MARITAL", "Marital"}, {"RACE", "Race"}, {"ETHNICITY", "Ethnicity"}, {"GENDER", "Gender"}, {"BIRTHPLACE", "Birthplace"}, {"ADDRESS", "Address"}, {"CITY", "City"}, {"STATE", "State"}, {"COUNTY", "County"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}}),
                            #"Renamed Columns" = Table.RenameColumns(#"Renamed Columns", {{"Id", "Id (patients)"}, {"BIRTHDATE", "Birthdate"}, {"DEATHDATE", "Deathdate"}, {"PREFIX", "Prefix"}, {"FIRST", "First"}, {"LAST", "Last"}, {"SUFFIX", "Suffix"}, {"MAIDEN", "Maiden"}, {"MARITAL", "Marital"}, {"RACE", "Race"}, {"ETHNICITY", "Ethnicity"}, {"GENDER", "Gender"}, {"BIRTHPLACE", "Birthplace"}, {"ADDRESS", "Address"}, {"CITY", "City"}, {"STATE", "State"}, {"COUNTY", "County"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}})
                        in
                            #"Renamed Columns"
