table 'Weather_Data'
    lineageTag: 03b51d37-edc6-4e35-ac25-d8850c621b8f

    column 'City'
        dataType: string
        lineageTag: c842d2ed-9e3a-4d4c-912f-1b1375af3b4d
        summarizeBy: none
        sourceColumn: City

    column 'Date'
        sourceColumn: Date
        dataType: dateTime
        formatString: Long Date
        lineageTag: 51c77b81-6210-46bd-88d9-5fe1771ac754
        summarizeBy: none

        variation Variation
            isDefault
            relationship: f2a1b3fd-10d1-463f-85e5-d7d0e030691f
            defaultHierarchy: LocalDateTable_3391c51a-7454-4761-922c-4b380288e496.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Record_Type'
        dataType: string
        lineageTag: 1463a049-42af-447e-94df-57fd5ab5ba98
        summarizeBy: none
        sourceColumn: Record_Type

    column 'Temperature'
        dataType: double
        lineageTag: f03f8cc4-afd4-435f-83a4-9d5f44fd5c16
        summarizeBy: none
        sourceColumn: Temperature

    column 'Temp_Min'
        dataType: double
        lineageTag: f6b0a79a-d623-4fac-8f10-226f35e2e620
        summarizeBy: none
        sourceColumn: Temp_Min

    column 'Temp_Max'
        dataType: double
        lineageTag: 774d3516-e25c-43d7-8f71-01711ff8f594
        summarizeBy: none
        sourceColumn: Temp_Max

    column 'Precipitation'
        dataType: double
        lineageTag: 81d8942a-626f-4e7d-9c8d-961025f61900
        summarizeBy: none
        sourceColumn: Precipitation

    column 'Weather_Code'
        dataType: double
        lineageTag: 929f4aac-1cdc-4ce9-b417-97191697b2ca
        summarizeBy: none
        sourceColumn: Weather_Code

    column 'Latitude'
        dataType: double
        lineageTag: e2b3c28e-1ba0-44a1-86ea-c43f8fbee8d7
        summarizeBy: none
        sourceColumn: Latitude

    column 'Longitude'
        dataType: double
        lineageTag: a8b7e994-7bdc-4b05-ae04-b9f23629645a
        summarizeBy: none
        sourceColumn: Longitude

    column 'Observation_Time'
        sourceColumn: Observation_Time
        dataType: dateTime
        formatString: General Date
        lineageTag: 2fbd95d6-1c70-4723-8794-d0afe17c1400
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 4f214285-278b-41e4-976d-42e39bde8138
            defaultHierarchy: LocalDateTable_eab18d57-b53a-4d14-b577-3eaf08353af4.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    measure '30-Day High' =
        VAR _MaxDate = TODAY()
        VAR _MinDate = _MaxDate - 30
        RETURN CALCULATE(MAX('Weather_Data'[Temp_Max]), KEEPFILTERS('Weather_Data'[Date] >= _MinDate), KEEPFILTERS('Weather_Data'[Date] <= _MaxDate))


    measure '30-Day Low' =
        VAR _MaxDate = TODAY()
        VAR _MinDate = _MaxDate - 30
        RETURN CALCULATE(MIN('Weather_Data'[Temp_Min]), KEEPFILTERS('Weather_Data'[Date] >= _MinDate), KEEPFILTERS('Weather_Data'[Date] <= _MaxDate))


    measure '30-Day Avg' =
        VAR _MaxDate = TODAY()
        VAR _MinDate = _MaxDate - 30
        RETURN INT(
            AVERAGEX(
                FILTER(
                    'Weather_Data',
                    'Weather_Data'[Date] >= _MinDate &&
                    'Weather_Data'[Date] <= _MaxDate
                ),
                'Weather_Data'[Temperature]
            )
        )


    measure 'Change Percentage' =
        DIVIDE(AVERAGE('Weather_Data'[Temperature]) - AVERAGE('Weather_Data'[Temp_Min]), ABS(AVERAGE('Weather_Data'[Temp_Min])), 0) * 100


    measure 'AVG of Temperature' =
        AVERAGE('Weather_Data'[Temperature])


    measure 'SUM of Precipitation' =
        SUM('Weather_Data'[Precipitation])


    measure 'SUM of Highest Avg Temp' =
        SUM('Weather_Data'[Highest Avg Temp])


    measure 'Highest Avg Temp' =
        CALCULATE(AVERAGE('Weather_Data'[Temp_Max]), ALLEXCEPT('Weather_Data', 'Weather_Data'[City]))


    measure 'Lowest Avg Temp' =
        CALCULATE(AVERAGE('Weather_Data'[Temp_Min]), ALLEXCEPT('Weather_Data', 'Weather_Data'[City]))


    partition 'Weather_Data' = m
        mode: import
        source =
            let
                Source = GoogleBigQuery.Database([BillingProject = null, UseStorageApi = null, ConnectionTimeout = null, CommandTimeout = null, ProjectId = null]),
                #"Navigation 1" = Source{[Name = "ordinal-avatar-497006-v6"]}[Data],
                #"Navigation 2" = #"Navigation 1"{[Name = "Weather_001", Kind = "Schema"]}[Data],
                #"Navigation 3" = #"Navigation 2"{[Name = "Weather_Data", Kind = "Table"]}[Data],
                #"Changed Type" = Table.TransformColumnTypes(#"Navigation 3", {{"City", type text}, {"Date", type date}, {"Record_Type", type text}, {"Temperature", type number}, {"Temp_Min", type number}, {"Temp_Max", type number}, {"Precipitation", type number}, {"Weather_Code", type number}, {"Latitude", type number}, {"Longitude", type number}, {"Observation_Time", type datetime}})
            in
                #"Changed Type"
