table COURSES
	lineageTag: aef0d33b-71a4-5d33-acdb-9c8f236a6bb5

	measure 'Average Credits' = AVERAGE('COURSES'[CREDITS])
		formatString: "#,##0.00"
		lineageTag: 6423b155-78fd-5c68-816d-d2a029603e99

	measure 'Total Courses' = DISTINCTCOUNT('COURSES'[COURSE_ID])
		formatString: "#,##0.00"
		lineageTag: c3d88ac9-c95e-50d1-b772-ad5b195a12a3

	measure 'Avg(CREDITS)' = AVERAGE('COURSES'[CREDITS])
		formatString: "#,##0.00"
		lineageTag: 7fd6d62a-221d-5895-a5a1-2e92c7343017

	measure 'Avg(Pick(Match(GRADE,''A'',''B'',''C'',''D'',''F''),5,4,3,2,0))' = AVERAGEX('GRADES', SWITCH(SWITCH(TRUE(), 'GRADES'[GRADE] = 'A', 1, 'GRADES'[GRADE] = 'B', 2, 'GRADES'[GRADE] = 'C', 3, 'GRADES'[GRADE] = 'D', 4, 'GRADES'[GRADE] = 'F', 5, BLANK()), 1, 5, 2, 4, 3, 3, 4, 2, 5, 0, BLANK()))
		formatString: "#,##0.00"
		lineageTag: 9008cb4a-00fb-521e-83b5-0ee5299b1113

	measure 'COUNT(GRADE)' = COUNT('GRADES'[GRADE])
		formatString: "#,##0"
		lineageTag: d6f3c9e1-04e8-5ae0-8c34-e9543b61527a

	measure 'Count(DISTINCT COURSE_ID)' = DISTINCTCOUNT('COURSES'[COURSE_ID])
		formatString: "#,##0"
		lineageTag: 1608ff6c-5557-5085-b97d-a0f3b7f4c916

	measure 'Count(ENROLLMENT_ID)' = COUNT('GRADES'[ENROLLMENT_ID])
		formatString: "#,##0"
		lineageTag: ee1ddc97-eb6c-5d8e-84d5-94333efdb5d7

	measure 'Count(INSTRUCTOR_ID)' = COUNT('COURSE_INSTRUCTORS'[INSTRUCTOR_ID])
		formatString: "#,##0"
		lineageTag: 830ee78a-4682-54a7-8508-0057a3ee0a52

	measure 'Avg(Today() - [ASSIGNED_DATE])' = AVERAGE(Today() - 'COURSE_INSTRUCTORS'[ASSIGNED_DATE])
		formatString: "#,##0.00"
		lineageTag: 38118ab1-f895-56ca-8420-9b4ed5639bfa

	/// TODO (Qlik AGGR() has no direct DAX equivalent): Convert the Qlik expression to DAX manually.
	/// Original Qlik: // Decayed GPA Quality Index, 0–100 // - Uses last 180 days anchored to max 'GRADES'[GRADE] date // - Falls back to all-time GPA if the 180d window is empty 25 * (   // -------- helpers computed via AGGR (legal in Qlik) --------   // window row count   If(     SUMX(VALUES('GRADES'[GRADE_ID]), If(           FLOOR(GRADED_DATE_DATE, 1) >= FLOOR(MAX({1} TOTAL GRADED_DATE_DATE), 1) - 179           and FLOOR(GRADED_DATE_DATE, 1) <= FLOOR(MAX({1} TOTAL GRADED_DATE_DATE), 1),           1, 0         )) > 0,     // ---------- WINDOWED, DECAYED GPA (when window has rows) ----------     // numerator     SUMX(VALUES('GRADES'[GRADE_ID]), If(           FLOOR(GRADED_DATE_DATE, 1) >= FLOOR(MAX({1} TOTAL GRADED_DATE_DATE), 1) - 179           and FLOOR(GRADED_DATE_DATE, 1) <= FLOOR(MAX({1} TOTAL GRADED_DATE_DATE), 1),           // decay weight (half-life 30 days)           Exp(             -0.6931471805599453 *             ( FLOOR(MAX({1} TOTAL GRADED_DATE_DATE), 1) - FLOOR(GRADED_DATE_DATE, 1) ) / 30           )           *           // GPA mapping: numeric % OR letters           If(             IsNum('GRADES'[GRADE]),               RangeMax(0, RangeMin(4,                 If('GRADES'[GRADE]>=90, 4,                 If('GRADES'[GRADE]>=85, 3.7 + ('GRADES'[GRADE]-85)*0.06,                 If('GRADES'[GRADE]>=75, 3.0 + ('GRADES'[GRADE]-75)*0.07,                 If('GRADES'[GRADE]>=65, 2.0 + ('GRADES'[GRADE]-65)*0.10,                 If('GRADES'[GRADE]>=50, 1.0 + ('GRADES'[GRADE]-50)*0.0667, 0))))))),               SWITCH(SWITCH(TRUE(), Upper(Trim('GRADES'[GRADE])) = 'A+', 1, Upper(Trim('GRADES'[GRADE])) = 'A', 2, Upper(Trim('GRADES'[GRADE])) = 'A-', 3, Upper(Trim('GRADES'[GRADE])) = 'B+', 4, Upper(Trim('GRADES'[GRADE])) = 'B', 5, Upper(Trim('GRADES'[GRADE])) = 'B-', 6, Upper(Trim('GRADES'[GRADE])) = 'C+', 7, Upper(Trim('GRADES'[GRADE])) = 'C', 8, Upper(Trim('GRADES'[GRADE])) = 'C-', 9, Upper(Trim('GRADES'[GRADE])) = 'D+', 10, Upper(Trim('GRADES'[GRADE])) = 'D', 11, Upper(Trim('GRADES'[GRADE])) = 'D-', 12, Upper(Trim('GRADES'[GRADE])) = 'F', 13, Upper(Trim('GRADES'[GRADE])) = 'HD', 14, Upper(Trim('GRADES'[GRADE])) = 'DI', 15, Upper(Trim('GRADES'[GRADE])) = 'CR', 16, Upper(Trim('GRADES'[GRADE])) = 'P', 17, Upper(Trim('GRADES'[GRADE])) = 'N', 18, Upper(Trim('GRADES'[GRADE])) = 'PASS', 19, Upper(Trim('GRADES'[GRADE])) = 'FAIL', 20, BLANK()), 1, 4.0, 2, 4.0, 3, 3.7, 4, 3.3, 5, 3.0, 6, 2.7, 7, 2.3, 8, 2.0, 9, 1.7, 10, 1.3, 11, 1.0, 12, 0.7, 13, 0.0, 14, 4.0, 15, 3.7, 16, 2.5, 17, 1.0, 18, 0.0, 19, 1.0, 20, 0.0, BLANK())           ),           0         ))     /     // denominator (guarded)     MAX(       1e-9,       SUMX(VALUES('GRADES'[GRADE_ID]), If(             FLOOR(GRADED_DATE_DATE, 1) >= FLOOR(MAX({1} TOTAL GRADED_DATE_DATE), 1) - 179             and FLOOR(GRADED_DATE_DATE, 1) <= FLOOR(MAX({1} TOTAL GRADED_DATE_DATE), 1),             Exp(               -0.6931471805599453 *               ( FLOOR(MAX({1} TOTAL GRADED_DATE_DATE), 1) - FLOOR(GRADED_DATE_DATE, 1) ) / 30             ),             0           ))     ),     // ---------- FALLBACK: ALL-TIME GPA (no window rows) ----------     (       SUMX(VALUES('GRADES'[GRADE_ID]), If(           IsNum('GRADES'[GRADE]),             RangeMax(0, RangeMin(4,               If('GRADES'[GRADE]>=90, 4,               If('GRADES'[GRADE]>=85, 3.7 + ('GRADES'[GRADE]-85)*0.06,               If('GRADES'[GRADE]>=75, 3.0 + ('GRADES'[GRADE]-75)*0.07,               If('GRADES'[GRADE]>=65, 2.0 + ('GRADES'[GRADE]-65)*0.10,               If('GRADES'[GRADE]>=50, 1.0 + ('GRADES'[GRADE]-50)*0.0667, 0))))))),             SWITCH(SWITCH(TRUE(), Upper(Trim('GRADES'[GRADE])) = 'A+', 1, Upper(Trim('GRADES'[GRADE])) = 'A', 2, Upper(Trim('GRADES'[GRADE])) = 'A-', 3, Upper(Trim('GRADES'[GRADE])) = 'B+', 4, Upper(Trim('GRADES'[GRADE])) = 'B', 5, Upper(Trim('GRADES'[GRADE])) = 'B-', 6, Upper(Trim('GRADES'[GRADE])) = 'C+', 7, Upper(Trim('GRADES'[GRADE])) = 'C', 8, Upper(Trim('GRADES'[GRADE])) = 'C-', 9, Upper(Trim('GRADES'[GRADE])) = 'D+', 10, Upper(Trim('GRADES'[GRADE])) = 'D', 11, Upper(Trim('GRADES'[GRADE])) = 'D-', 12, Upper(Trim('GRADES'[GRADE])) = 'F', 13, Upper(Trim('GRADES'[GRADE])) = 'HD', 14, Upper(Trim('GRADES'[GRADE])) = 'DI', 15, Upper(Trim('GRADES'[GRADE])) = 'CR', 16, Upper(Trim('GRADES'[GRADE])) = 'P', 17, Upper(Trim('GRADES'[GRADE])) = 'N', 18, Upper(Trim('GRADES'[GRADE])) = 'PASS', 19, Upper(Trim('GRADES'[GRADE])) = 'FAIL', 20, BLANK()), 1, 4.0, 2, 4.0, 3, 3.7, 4, 3.3, 5, 3.0, 6, 2.7, 7, 2.3, 8, 2.0, 9, 1.7, 10, 1.3, 11, 1.0, 12, 0.7, 13, 0.0, 14, 4.0, 15, 3.7, 16, 2.5, 17, 1.0, 18, 0.0, 19, 1.0, 20, 0.0, BLANK())         ))        /       MAX(1, SUMX(VALUES('GRADES'[GRADE_ID]), 1))     )   ) )
	measure '// Decayed GPA Quality Index, 0–100 // - Uses last 180 days anchored to max grade date // - Falls back to all-time GPA if the 180d window is empty 25 * (   // -------- helpers computed via AGGR (legal in Qlik) --------   // window row count   If(     Sum(       Aggr(         If(           Floor(GRADED_DATE_DATE) >= Floor(Max({1} TOTAL GRADED_DATE_DATE)) - 179           and Floor(GRADED_DATE_DATE) <= Floor(Max({1} TOTAL GRADED_DATE_DATE)),           1, 0         ),         GRADE_ID       )     ) > 0,     // ---------- WINDOWED, DECAYED GPA (when window has rows) ----------     // numerator     Sum(       Aggr(         If(           Floor(GRADED_DATE_DATE) >= Floor(Max({1} TOTAL GRADED_DATE_DATE)) - 179           and Floor(GRADED_DATE_DATE) <= Floor(Max({1} TOTAL GRADED_DATE_DATE)),           // decay weight (half-life 30 days)           Exp(             -0.6931471805599453 *             ( Floor(Max({1} TOTAL GRADED_DATE_DATE)) - Floor(GRADED_DATE_DATE) ) / 30           )           *           // GPA mapping: numeric % OR letters           If(             IsNum(GRADE),               RangeMax(0, RangeMin(4,                 If(GRADE>=90, 4,                 If(GRADE>=85, 3.7 + (GRADE-85)*0.06,                 If(GRADE>=75, 3.0 + (GRADE-75)*0.07,                 If(GRADE>=65, 2.0 + (GRADE-65)*0.10,                 If(GRADE>=50, 1.0 + (GRADE-50)*0.0667, 0))))))),               Pick(                 Match(Upper(Trim(GRADE)),                   ''A+'',''A'',''A-'',''B+'',''B'',''B-'',''C+'',''C'',''C-'',''D+'',''D'',''D-'',''F'',                   ''HD'',''DI'',''CR'',''P'',''N'',''PASS'',''FAIL''                 ),                 4.0,4.0,3.7,3.3,3.0,2.7,2.3,2.0,1.7,1.3,1.0,0.7,0.0,                 4.0,3.7,2.5,1.0,0.0,1.0,0.0               )           ),           0         ),         GRADE_ID       )     )     /     // denominator (guarded)     Max(       1e-9,       Sum(         Aggr(           If(             Floor(GRADED_DATE_DATE) >= Floor(Max({1} TOTAL GRADED_DATE_DATE)) - 179             and Floor(GRADED_DATE_DATE) <= Floor(Max({1} TOTAL GRADED_DATE_DATE)),             Exp(               -0.6931471805599453 *               ( Floor(Max({1} TOTAL GRADED_DATE_DATE)) - Floor(GRADED_DATE_DATE) ) / 30             ),             0           ),           GRADE_ID         )       )     ),     // ---------- FALLBACK: ALL-TIME GPA (no window rows) ----------     (       Sum( Aggr(         If(           IsNum(GRADE),             RangeMax(0, RangeMin(4,               If(GRADE>=90, 4,               If(GRADE>=85, 3.7 + (GRADE-85)*0.06,               If(GRADE>=75, 3.0 + (GRADE-75)*0.07,               If(GRADE>=65, 2.0 + (GRADE-65)*0.10,               If(GRADE>=50, 1.0 + (GRADE-50)*0.0667, 0))))))),             Pick(               Match(Upper(Trim(GRADE)),                 ''A+'',''A'',''A-'',''B+'',''B'',''B-'',''C+'',''C'',''C-'',''D+'',''D'',''D-'',''F'',                 ''HD'',''DI'',''CR'',''P'',''N'',''PASS'',''FAIL''               ),               4.0,4.0,3.7,3.3,3.0,2.7,2.3,2.0,1.7,1.3,1.0,0.7,0.0,               4.0,3.7,2.5,1.0,0.0,1.0,0.0             )         ),         GRADE_ID       ))        /       Max(1, Sum( Aggr(1, GRADE_ID) ))     )   ) )' = BLANK()
		formatString: "#,##0"
		lineageTag: 9ebe8f30-4fc4-500d-9d10-0ea617c3acb3

	/// TODO (Qlik $() dollar expansion has no direct DAX equivalent): Convert the Qlik expression to DAX manually.
	/// Original Qlik: VAR __CalcVar_1 = AddMonths(MonthStart($(vMaxLoaded)),-11) VAR __CalcVar_2 = MonthEnd($(vMaxLoaded)) RETURN CALCULATE(COUNTROWS('COURSES'), [Date] >= __CalcVar_1<=__CalcVar_2, CALCULATE(Date=ASSIGNED_DATE_DATE))
	measure 'Sum({   <Date = {">=$(=AddMonths(MonthStart($(vMaxLoaded)),-11))<=$(=MonthEnd($(vMaxLoaded)))"},    Date = {"=Date=ASSIGNED_DATE_DATE"}> } 1)' = BLANK()
		formatString: "#,##0"
		lineageTag: 4f4a7d05-1f82-50a5-9452-bb38aa922cbb

	measure 'Count(STUDENT_ID)' = COUNT('STUDENT_COURSES'[STUDENT_ID])
		formatString: "#,##0"
		lineageTag: c8f23a9d-9b59-576e-b721-882ec4759c3c

	measure 'Avg(   Pick(     Match(Upper(Trim(GRADE)),''A+'',''A'',''A-'',''B+'',''B'',''B-'',''C+'',''C'',''C-'',''D+'',''D'',''D-'',''F''),     4.0,4.0,3.7,3.3,3.0,2.7,2.3,2.0,1.7,1.3,1.0,0.7,0.0   ) )' = AVERAGEX('GRADES', SWITCH(SWITCH(TRUE(), Upper(Trim('GRADES'[GRADE])) = 'A+', 1, Upper(Trim('GRADES'[GRADE])) = 'A', 2, Upper(Trim('GRADES'[GRADE])) = 'A-', 3, Upper(Trim('GRADES'[GRADE])) = 'B+', 4, Upper(Trim('GRADES'[GRADE])) = 'B', 5, Upper(Trim('GRADES'[GRADE])) = 'B-', 6, Upper(Trim('GRADES'[GRADE])) = 'C+', 7, Upper(Trim('GRADES'[GRADE])) = 'C', 8, Upper(Trim('GRADES'[GRADE])) = 'C-', 9, Upper(Trim('GRADES'[GRADE])) = 'D+', 10, Upper(Trim('GRADES'[GRADE])) = 'D', 11, Upper(Trim('GRADES'[GRADE])) = 'D-', 12, Upper(Trim('GRADES'[GRADE])) = 'F', 13, BLANK()), 1, 4.0, 2, 4.0, 3, 3.7, 4, 3.3, 5, 3.0, 6, 2.7, 7, 2.3, 8, 2.0, 9, 1.7, 10, 1.3, 11, 1.0, 12, 0.7, 13, 0.0, BLANK()))
		formatString: "#,##0.00"
		lineageTag: 5947325d-e200-5027-80e8-3310ae52a708

	column 'Course Category' = 'COURSES'[CREDITS]
		dataType: double
		lineageTag: 1c5ce9f4-58e9-5d7c-a1b1-7267dec4e135
		summarizeBy: none

	column COURSE_ID
		dataType: string
		lineageTag: b20ab871-1f63-54a3-968d-512304647cc6
		summarizeBy: none
		sourceColumn: COURSE_ID

		annotation SummarizationSetBy = Automatic

	column COURSE_NAME
		dataType: string
		lineageTag: 2a28884c-6ce7-5d88-bc97-72f8f44c511c
		summarizeBy: none
		sourceColumn: COURSE_NAME

		annotation SummarizationSetBy = Automatic

	column DEPARTMENT
		dataType: string
		lineageTag: fec604b5-389c-551e-9b9f-ad4f184d7d93
		summarizeBy: none
		sourceColumn: DEPARTMENT

		annotation SummarizationSetBy = Automatic

	column CREDITS
		dataType: double
		lineageTag: 55d744ab-d716-55db-bfe5-175c2d70b20c
		summarizeBy: sum
		sourceColumn: CREDITS
		formatString: General Number

		annotation SummarizationSetBy = Automatic

	partition COURSES = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("gq37595.ap-southeast-7.aws.snowflakecomputing.com", "COMPUTE_WH"),
				    Db = Source{[Name="LEARNING_ANALYTICS",Kind="Database"]}[Data],
				    Result = Value.NativeQuery(Db, "SELECT ""COURSE_ID"", ""COURSE_NAME"", ""DEPARTMENT"", ""CREDITS"" FROM ""LEARNING_ANALYTICS"".""PUBLIC"".""COURSES""", null, [EnableFolding=false]),
				    #"Changed Type" = Table.TransformColumnTypes(Result, {{"COURSE_ID", type text}, {"COURSE_NAME", type text}, {"DEPARTMENT", type text}, {"CREDITS", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table