table 'patients'
    lineageTag: 0d3a29df-4325-4efb-9f5a-dac50f272c3c

    column 'Id (patients)'
        dataType: string
        lineageTag: 41d8283f-ef41-486b-ad2f-f1c1e27cd628
        summarizeBy: none
        sourceColumn: Id (patients)

    column 'Birthdate'
        sourceColumn: Birthdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: a0697594-52ea-4de3-8f11-4c9f6b12e952
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 4b9f4d81-ce12-404b-ae67-a0588c9b5a8c
            defaultHierarchy: LocalDateTable_351f4dcc-a638-423f-a68b-4d6b3d89d0a3.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Deathdate'
        sourceColumn: Deathdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: 9dcc32e2-a729-4ed3-9094-7e0f3f6b60e4
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 3beb91cc-c353-4135-9b67-546399b606d5
            defaultHierarchy: LocalDateTable_05ac5375-b523-4385-9d0b-eceb3cf1c2df.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Prefix'
        dataType: string
        lineageTag: be212398-cd25-4be2-87ea-d04b1c32895e
        summarizeBy: none
        sourceColumn: Prefix

    column 'First'
        dataType: string
        lineageTag: d3831c12-7230-446b-80b5-7be28080cd81
        summarizeBy: none
        sourceColumn: First

    column 'Last'
        dataType: string
        lineageTag: 9708e511-00a8-44a9-a7bf-038487a10127
        summarizeBy: none
        sourceColumn: Last

    column 'Suffix'
        dataType: string
        lineageTag: bab7cd94-dd19-4029-a0b7-168132ed3890
        summarizeBy: none
        sourceColumn: Suffix

    column 'Maiden'
        dataType: string
        lineageTag: 6ec16b37-5e5b-4240-82ab-2daba98a0a32
        summarizeBy: none
        sourceColumn: Maiden

    column 'Marital'
        dataType: string
        lineageTag: c47f33c5-d9bc-4bb3-bb61-216ba1f0bb09
        summarizeBy: none
        sourceColumn: Marital

    column 'Race'
        dataType: string
        lineageTag: 0892f1b1-8967-4a96-84d0-c3b912415174
        summarizeBy: none
        sourceColumn: Race

    column 'Ethnicity'
        dataType: string
        lineageTag: 99e5292e-d0c7-4d5c-9bfe-10fecd892161
        summarizeBy: none
        sourceColumn: Ethnicity

    column 'Gender'
        dataType: string
        lineageTag: 3e192118-1dd1-48a8-ac94-0b9c0dbf6d09
        summarizeBy: none
        sourceColumn: Gender

    column 'Birthplace'
        dataType: string
        lineageTag: 617658d6-5968-476a-ae07-86b2b427263e
        summarizeBy: none
        sourceColumn: Birthplace

    column 'Address'
        dataType: string
        lineageTag: 97b05673-34c8-46ee-b08a-f2411ed2087a
        summarizeBy: none
        sourceColumn: Address

    column 'City'
        dataType: string
        lineageTag: dd74038b-f4a4-42fc-b2d9-2836db875778
        summarizeBy: none
        sourceColumn: City

    column 'State'
        dataType: string
        lineageTag: 1321bcef-21ea-4575-9798-9d854c9383f2
        summarizeBy: none
        sourceColumn: State

    column 'County'
        dataType: string
        lineageTag: 85e8750b-935e-4f2d-9197-a0eaceef934c
        summarizeBy: none
        sourceColumn: County

    column 'ZIP (organizations)'
        dataType: double
        lineageTag: be4d7d92-31c0-419b-80d3-f4aeb9b3773e
        summarizeBy: none
        sourceColumn: ZIP (organizations)

    column 'LAT (organizations)'
        dataType: double
        lineageTag: b281505b-0d89-4dfd-b01c-d68d2551ff04
        summarizeBy: none
        sourceColumn: LAT (organizations)

    column 'LON (organizations)'
        dataType: double
        lineageTag: d622d0d8-4bf3-4e87-9dec-fa9b9ce1e689
        summarizeBy: none
        sourceColumn: LON (organizations)

    measure 'SUM of Avg Visits per Patient (patients)' =
        SUM('patients'[Avg Visits per Patient])


    measure 'SUM of Visits per Patient (patients)' =
        SUM('patients'[Visits per Patient])


    measure 'Total Patients (LOD)' =
        -- SKIPPED BY USER


    measure 'Visits per Patient' =
        -- SKIPPED BY USER


    measure 'Avg Visits per Patient' =
        -- SKIPPED BY USER


    partition 'patients' = m
        mode: import
        source =
            let Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1Sd4bEK0Fm9q7yTVOwI4GdtixeeY8hPkKqpvnI4WdixA"),
            #"Navigation 1" = Source{[name = "patients", ItemKind = "Table"]}[Data],
                            #"Final Renamed Columns" = Table.RenameColumns(#"Navigation 1", {{"Id", "Id (patients)"}, {"BIRTHDATE", "Birthdate"}, {"DEATHDATE", "Deathdate"}, {"PREFIX", "Prefix"}, {"FIRST", "First"}, {"LAST", "Last"}, {"SUFFIX", "Suffix"}, {"MAIDEN", "Maiden"}, {"MARITAL", "Marital"}, {"RACE", "Race"}, {"ETHNICITY", "Ethnicity"}, {"GENDER", "Gender"}, {"BIRTHPLACE", "Birthplace"}, {"ADDRESS", "Address"}, {"CITY", "City"}, {"STATE", "State"}, {"COUNTY", "County"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}})
                        in
                            #"Final Renamed Columns"
