table 'payers'
    lineageTag: cb5316b3-daf1-4dd5-a98e-ff9deee940f0

    column 'Id (payers)'
        dataType: string
        lineageTag: 797c8f59-8583-4cc9-b891-2c4f9d6a3fed
        summarizeBy: none
        sourceColumn: Id (payers)

    column 'NAME (payers)'
        dataType: string
        lineageTag: c2a6dc37-f34a-4034-81a8-e2d73b883a03
        summarizeBy: none
        sourceColumn: NAME (payers)

    column 'ADDRESS (payers)'
        dataType: string
        lineageTag: fe3d475f-c775-4df9-9a4a-f01e11482b5e
        summarizeBy: none
        sourceColumn: ADDRESS (payers)

    column 'CITY (payers)'
        dataType: string
        lineageTag: 3cc9c332-bb6d-4902-8242-30f71861a719
        summarizeBy: none
        sourceColumn: CITY (payers)

    column 'State Headquartered'
        dataType: string
        lineageTag: d49d4114-4926-42f0-9305-731b4d872a4e
        summarizeBy: none
        sourceColumn: State Headquartered

    column 'ZIP (payers)'
        dataType: double
        lineageTag: 890c1b8d-0c60-4d5d-ab75-1411b050a59b
        summarizeBy: none
        sourceColumn: ZIP (payers)

    column 'Phone'
        dataType: string
        lineageTag: c3275c81-b791-4aeb-b48b-176b3bd770c6
        summarizeBy: none
        sourceColumn: Phone

    partition 'payers' = m
        mode: import
        source =
            let Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1NB9uAQnBa6RYGfm5addKbcToYUZJY_5OlBkWxVZRrbU"),
            #"Navigation 1" = Source{[name = "payers", ItemKind = "Table"]}[Data],
                            #"Final Renamed Columns" = Table.RenameColumns(#"Navigation 1", {{"Id", "Id (payers)"}, {"NAME", "NAME (payers)"}, {"ADDRESS", "ADDRESS (payers)"}, {"CITY", "CITY (payers)"}, {"STATE_HEADQUARTERED", "State Headquartered"}, {"ZIP", "ZIP (payers)"}, {"PHONE", "Phone"}})
                        in
                            #"Final Renamed Columns"
