table 'organizations'
    lineageTag: 5e518314-b494-42a4-b151-1f98aa84bd50

    column 'Id (organizations)'
        dataType: string
        lineageTag: 6ffcaf0b-462b-40c6-b274-20b7890a502e
        summarizeBy: none
        sourceColumn: Id (organizations)

    column 'Name'
        dataType: string
        lineageTag: 5c6ed9e7-a168-4938-a738-3dc58f1dbb7c
        summarizeBy: none
        sourceColumn: Name

    column 'ADDRESS (organizations)'
        dataType: string
        lineageTag: a3241120-2520-4d74-bd8e-a8f17b719fa2
        summarizeBy: none
        sourceColumn: ADDRESS (organizations)

    column 'CITY (organizations)'
        dataType: string
        lineageTag: f45f922a-c747-46af-8462-887dbd9261c1
        summarizeBy: none
        sourceColumn: CITY (organizations)

    column 'STATE (organizations)'
        dataType: string
        lineageTag: 31b63b9d-646a-46d5-b80b-04f7faf0648c
        summarizeBy: none
        sourceColumn: STATE (organizations)

    column 'ZIP (organizations)'
        dataType: double
        lineageTag: 7baa4ca9-46e3-4747-ac54-8eb6b5300635
        summarizeBy: none
        sourceColumn: ZIP (organizations)

    column 'LAT (organizations)'
        dataType: double
        lineageTag: 0925d66d-c325-4521-911e-d4ea02c567f3
        summarizeBy: none
        sourceColumn: LAT (organizations)

    column 'LON (organizations)'
        dataType: double
        lineageTag: f6896563-0570-48f9-8f3f-9ac8bebbc929
        summarizeBy: none
        sourceColumn: LON (organizations)

    column 'Username' = -- ERROR: LLM call failed after 6 retries. Last error: 404 Client Error: Not Found for url: https://api.groq.com/openai/v1/chat/completions
        dataType: string

        summarizeBy: none

    measure 'RLS - Organization Access' =
        -- ERROR: LLM call failed after 6 retries. Last error: 404 Client Error: Not Found for url: https://api.groq.com/openai/v1/chat/completions


    partition 'organizations' = m
        mode: import
        source =
            let Source = Sql.Database("", "Patients.xlsx"),
            #"Navigation 1" = Source{[Schema="[organizations$]",Item="organizations"]}[Data],
                            #"Renamed Columns" = Table.RenameColumns(#"Navigation 1", {{"Id", "Id (organizations)"}, {"NAME", "Name"}, {"ADDRESS", "ADDRESS (organizations)"}, {"CITY", "CITY (organizations)"}, {"STATE", "STATE (organizations)"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}})
                        in
                            #"Renamed Columns"
