table account
	lineageTag: 6b9f3a30-5bec-4103-9bef-dc7b32bdd835

	measure 'YEAR of Loan Date' = YEAR('account'[Loan Date])

	measure 'District Level Loan' = CALCULATE(SUM('loan'[Amount]), ALLEXCEPT('district', 'district'[District Id (District)]))

	column 'Account Id (Account)'
		dataType: double
		lineageTag: 98a5ebb3-d9e4-48e9-8b58-9afceb22c1ef
		summarizeBy: none
		sourceColumn: Account Id (Account)

	column 'District Id (Account)'
		dataType: double
		lineageTag: 3170eacb-febc-4fa3-83dc-620b9e35f559
		summarizeBy: none
		sourceColumn: District Id (Account)

	column Frequency
		dataType: string
		lineageTag: 85ebf30d-3aa6-4848-b2f7-549f14ba3758
		summarizeBy: none
		sourceColumn: Frequency

	column Date
		dataType: string
		lineageTag: 876de959-250d-448a-9402-e903575682c5
		summarizeBy: none
		sourceColumn: Date

	column 'Loan Date' = DATE( YEAR(MAXX(RELATEDTABLE('loan'), 'loan'[Date (Loan)])), MONTH(MAXX(RELATEDTABLE('loan'), 'loan'[Date (Loan)])), DAY(MAXX(RELATEDTABLE('loan'), 'loan'[Date (Loan)])) )
		dataType: dateTime
		formatString: Long Date
		lineageTag: af3f7cc0-fcd7-4f38-8dc5-170126667642
		summarizeBy: none

		variation Variation
			isDefault
			relationship: fc45ecd2-63e3-449b-b544-be7cd00a6368
			defaultHierarchy: LocalDateTable_aee59c61-5e57-43bb-9d14-658268f144e8.'Date Hierarchy'

		changedProperty = DataType

		annotation UnderlyingDateTimeDataType = Date

	partition account = m
		mode: import
		source =
				let
				    Source = AmazonRedshift.Database("financial-workgroup.164761934860.ap-southeast-2.redshift-serverless.amazonaws.com:5439", "dev", [ProviderName = null, BatchSize = null]),
				    #"Navigation 1" = Source{[Name = "public"]}[Data],
				    #"Navigation 2" = #"Navigation 1"{[Name = "account"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(#"Navigation 2", {{"account_id", type number}, {"district_id", type number}, {"frequency", type text}, {"date", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"account_id", "Account Id (Account)"}, {"district_id", "District Id (Account)"}, {"frequency", "Frequency"}, {"date", "Date"}})
				in
				    #"Renamed Columns"

