table card
	lineageTag: 0ae50d12-0019-467a-8077-9bf3ec0ece99

	column 'Card Id'
		dataType: double
		lineageTag: 04d97859-5212-412e-8cad-30fe9ea73fc8
		summarizeBy: none
		sourceColumn: Card Id

	column 'Disp Id (Card)'
		dataType: double
		lineageTag: ecaa1b04-e274-485b-a0b4-580cab06c382
		summarizeBy: none
		sourceColumn: Disp Id (Card)

	column 'Type (Card)'
		dataType: string
		lineageTag: 09055c97-5425-46f8-8120-ddd298fcd7a3
		summarizeBy: none
		sourceColumn: Type (Card)

	column Issued
		dataType: string
		lineageTag: 53b35d4a-65b1-4e2b-a5ac-c2d897bdd851
		summarizeBy: none
		sourceColumn: Issued

	partition card = m
		mode: import
		source =
				let
				    Source = AmazonRedshift.Database("financial-workgroup.164761934860.ap-southeast-2.redshift-serverless.amazonaws.com:5439", "dev", [ProviderName = null, BatchSize = null]),
				    #"Navigation 1" = Source{[Name = "public"]}[Data],
				    #"Navigation 2" = #"Navigation 1"{[Name = "card"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(#"Navigation 2", {{"card_id", type number}, {"disp_id", type number}, {"type", type text}, {"issued", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"card_id", "Card Id"}, {"disp_id", "Disp Id (Card)"}, {"type", "Type (Card)"}, {"issued", "Issued"}})
				in
				    #"Renamed Columns"

