table disp
	lineageTag: 1b35d5c7-7613-4652-845a-5a4bd3ef5096

	measure 'CNTD of Account Id (disp)' = DISTINCTCOUNT('disp'[Account Id])

	column 'Disp Id'
		dataType: double
		lineageTag: 209b9b6a-c422-421f-9a63-889b17c30f3b
		summarizeBy: none
		sourceColumn: Disp Id

	column 'Client Id (Disp)'
		dataType: double
		lineageTag: f30e6230-f6d9-4e3a-8562-19a9d748bc46
		summarizeBy: none
		sourceColumn: Client Id (Disp)

	column 'Account Id'
		dataType: double
		lineageTag: 3b91e852-6497-4406-b450-ea429e0275ab
		summarizeBy: none
		sourceColumn: Account Id

	column Type
		dataType: string
		lineageTag: 45133375-016b-48c0-8dfd-09366ef3ef5d
		summarizeBy: none
		sourceColumn: Type

	partition disp = m
		mode: import
		source =
				let
				    Source = AmazonRedshift.Database("financial-workgroup.164761934860.ap-southeast-2.redshift-serverless.amazonaws.com:5439", "dev", [ProviderName = null, BatchSize = null]),
				    #"Navigation 1" = Source{[Name = "public"]}[Data],
				    #"Navigation 2" = #"Navigation 1"{[Name = "disp"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(#"Navigation 2", {{"disp_id", type number}, {"client_id", type number}, {"account_id", type number}, {"type", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"disp_id", "Disp Id"}, {"client_id", "Client Id (Disp)"}, {"account_id", "Account Id"}, {"type", "Type"}})
				in
				    #"Renamed Columns"

