table district
	lineageTag: 0544e3a9-fbd3-4eb9-b5ec-9d60e2814002

	column 'District Id (District)'
		dataType: double
		lineageTag: 55eff572-cf04-4650-ab50-8d131e308205
		summarizeBy: none
		sourceColumn: District Id (District)

	column 'District Name'
		dataType: string
		lineageTag: b4f59c5e-b680-4034-95b5-4fb7e56292cc
		summarizeBy: none
		sourceColumn: District Name

	column Region
		dataType: string
		lineageTag: e49b693d-c929-40f1-955c-5ebc03e736a2
		summarizeBy: none
		sourceColumn: Region

	column Population
		dataType: double
		lineageTag: 6a397b7b-9578-4fce-9c1d-621b7c8eca77
		summarizeBy: none
		sourceColumn: Population

	column 'Number of municipalities (< 499 inhabitants)'
		dataType: double
		lineageTag: fba2b3ed-82c7-45e4-a9bc-244e26c9662d
		summarizeBy: none
		sourceColumn: Number of municipalities (< 499 inhabitants)

	column 'Number of municipalities (500–1999 inhabitants)'
		dataType: double
		lineageTag: 51c51296-2e77-43e3-9acb-214498628c44
		summarizeBy: none
		sourceColumn: Number of municipalities (500–1999 inhabitants)

	column 'Number of municipalities (2000–9999 inhabitants)'
		dataType: double
		lineageTag: bcb89a11-f9ae-45c7-9f1d-d6674dd0b9a8
		summarizeBy: none
		sourceColumn: Number of municipalities (2000–9999 inhabitants)

	column 'Number of municipalities (> 10000 inhabitants)'
		dataType: double
		lineageTag: be607457-6d36-4151-a966-cb84c09d04f0
		summarizeBy: none
		sourceColumn: Number of municipalities (> 10000 inhabitants)

	column 'Number of cities'
		dataType: double
		lineageTag: 31bbb511-ece6-4690-b3a5-7d8fb13b5b57
		summarizeBy: none
		sourceColumn: Number of cities

	column 'Urban population ratio'
		dataType: double
		lineageTag: 73b7465f-a673-4ed5-b27c-83591c8de63e
		summarizeBy: none
		sourceColumn: Urban population ratio

	column 'Average Salary'
		dataType: double
		lineageTag: afca6ab0-4b28-4732-90ac-e05b014a09d2
		summarizeBy: none
		sourceColumn: Average Salary

	column 'Unemployment rate (1995)'
		dataType: double
		lineageTag: 5f093aa2-38ad-4bc6-af7e-005c0244390e
		summarizeBy: none
		sourceColumn: Unemployment rate (1995)

	column 'Unemployment rate (1996)'
		dataType: double
		lineageTag: e39edf8f-c959-4472-8083-632a75323cd3
		summarizeBy: none
		sourceColumn: Unemployment rate (1996)

	column 'Number of entrepreneurs per 1000 inhabitants'
		dataType: double
		lineageTag: 12fab031-f92d-4ab0-b6b6-d17e060c172b
		summarizeBy: none
		sourceColumn: Number of entrepreneurs per 1000 inhabitants

	column 'Number of committed crimes (1995)'
		dataType: double
		lineageTag: 4ffa8b68-e9cf-4be3-8d25-c37a297bcf3a
		summarizeBy: none
		sourceColumn: Number of committed crimes (1995)

	column 'Number of committed crimes (1996)'
		dataType: double
		lineageTag: edb7a6ba-ba5f-46d6-aa09-fc758bc52d7e
		summarizeBy: none
		sourceColumn: Number of committed crimes (1996)

	partition district = m
		mode: import
		source =
				let
				    Source = AmazonRedshift.Database("financial-workgroup.164761934860.ap-southeast-2.redshift-serverless.amazonaws.com:5439", "dev", [ProviderName = null, BatchSize = null]),
				    #"Navigation 1" = Source{[Name = "public"]}[Data],
				    #"Navigation 2" = #"Navigation 1"{[Name = "district"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(#"Navigation 2", {{"district_id", type number}, {"a2", type text}, {"a3", type text}, {"a4", type number}, {"a5", type number}, {"a6", type number}, {"a7", type number}, {"a8", type number}, {"a9", type number}, {"a10", type number}, {"a11", type number}, {"a12", type number}, {"a13", type number}, {"a14", type number}, {"a15", type number}, {"a16", type number}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"district_id", "District Id (District)"}, {"a2", "District Name"}, {"a3", "Region"}, {"a4", "Population"}, {"a5", "Number of municipalities (< 499 inhabitants)"}, {"a6", "Number of municipalities (500–1999 inhabitants)"}, {"a7", "Number of municipalities (2000–9999 inhabitants)"}, {"a8", "Number of municipalities (> 10000 inhabitants)"}, {"a9", "Number of cities"}, {"a10", "Urban population ratio"}, {"a11", "Average Salary"}, {"a12", "Unemployment rate (1995)"}, {"a13", "Unemployment rate (1996)"}, {"a14", "Number of entrepreneurs per 1000 inhabitants"}, {"a15", "Number of committed crimes (1995)"}, {"a16", "Number of committed crimes (1996)"}})
				in
				    #"Renamed Columns"

