table 'payers'
    lineageTag: b3caa6a6-011b-4ee4-9520-68156fa7d3f1

    column 'Id (payers)'
        dataType: string
        lineageTag: dea0b05f-a13a-454e-aa6d-2acec7845324
        summarizeBy: none
        sourceColumn: Id (payers)

    column 'NAME (payers)'
        dataType: string
        lineageTag: ea274ee0-796f-449f-9d65-f29a0d1cab16
        summarizeBy: none
        sourceColumn: NAME (payers)

    column 'ADDRESS (payers)'
        dataType: string
        lineageTag: 783c10de-2b23-4a48-bec1-f17ca47c615f
        summarizeBy: none
        sourceColumn: ADDRESS (payers)

    column 'CITY (payers)'
        dataType: string
        lineageTag: 4ad07647-66e7-4547-8b2c-afd045a89b55
        summarizeBy: none
        sourceColumn: CITY (payers)

    column 'State Headquartered'
        dataType: string
        lineageTag: 44fead76-80d9-4967-a6cd-8357dd07b4a4
        summarizeBy: none
        sourceColumn: State Headquartered

    column 'ZIP (payers)'
        dataType: double
        lineageTag: 032e9591-88fb-4334-b0c1-9b1f85205d66
        summarizeBy: none
        sourceColumn: ZIP (payers)

    column 'Phone'
        dataType: string
        lineageTag: 3cc2242d-ccbb-4546-a73f-2be030309e52
        summarizeBy: none
        sourceColumn: Phone

    partition 'payers' = m
        mode: import
        source =
            let Source = Excel.Workbook(Web.Contents("https://www.googleapis.com/drive/v3/files/1Sd4bEK0Fm9q7yTVOwI4GdtixeeY8hPkKqpvnI4WdixA/export?mimeType=application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"), null, true),
            #"Navigation 1" = Source{[Item="payers",Kind="Sheet"]}[Data],
            #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars=true]),
            #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Id", type text}, {"NAME", type text}, {"ADDRESS", type text}, {"CITY", type text}, {"STATE_HEADQUARTERED", type text}, {"ZIP", type number}, {"PHONE", type text}}),
            #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"Id", "Id (payers)"}, {"NAME", "NAME (payers)"}, {"ADDRESS", "ADDRESS (payers)"}, {"CITY", "CITY (payers)"}, {"STATE_HEADQUARTERED", "State Headquartered"}, {"ZIP", "ZIP (payers)"}, {"PHONE", "Phone"}}),
                            #"Renamed Columns" = Table.RenameColumns(#"Renamed Columns", {{"Id", "Id (payers)"}, {"NAME", "NAME (payers)"}, {"ADDRESS", "ADDRESS (payers)"}, {"CITY", "CITY (payers)"}, {"STATE_HEADQUARTERED", "State Headquartered"}, {"ZIP", "ZIP (payers)"}, {"PHONE", "Phone"}})
                        in
                            #"Renamed Columns"
