table 'organizations'
    lineageTag: da1cde19-2f71-4de1-9274-f2b8f96752dc

    column 'Id (organizations)'
        dataType: string
        lineageTag: 48fe7017-91cb-4a31-8057-15301e89671a
        summarizeBy: none
        sourceColumn: Id (organizations)

    column 'Name'
        dataType: string
        lineageTag: 65d9dd22-4c22-4d3e-9e35-93c362926ade
        summarizeBy: none
        sourceColumn: Name

    column 'ADDRESS (organizations)'
        dataType: string
        lineageTag: 93544c14-2c30-47b2-acf6-b9954bcd5479
        summarizeBy: none
        sourceColumn: ADDRESS (organizations)

    column 'CITY (organizations)'
        dataType: string
        lineageTag: f7bc6c4c-d608-4ac3-9c59-6e9627419216
        summarizeBy: none
        sourceColumn: CITY (organizations)

    column 'STATE (organizations)'
        dataType: string
        lineageTag: b454c742-4a12-4cdd-b9a6-99c3dd17e67a
        summarizeBy: none
        sourceColumn: STATE (organizations)

    column 'ZIP (organizations)'
        dataType: double
        lineageTag: 3fe5984f-8180-4d16-a30c-ede50bd24900
        summarizeBy: none
        sourceColumn: ZIP (organizations)

    column 'LAT (organizations)'
        dataType: double
        lineageTag: 37f83924-5489-4764-ab82-45ec45724a39
        summarizeBy: none
        sourceColumn: LAT (organizations)

    column 'LON (organizations)'
        dataType: double
        lineageTag: 376f6ae4-745b-4d7e-b0c2-f18681f73444
        summarizeBy: none
        sourceColumn: LON (organizations)

    column 'Username' = -- SKIPPED BY USER
        dataType: string

        summarizeBy: none

    measure 'RLS - Organization Access' =
        -- SKIPPED BY USER


    partition 'organizations' = m
        mode: import
        source =
            let
                Source = GoogleSheets.Contents("None"),
                #"Navigation 1" = Source{[name = "organizations", ItemKind = "Table"]}[Data],
                #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
                #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Id", type text}, {"NAME", type text}, {"ADDRESS", type text}, {"CITY", type text}, {"STATE", type text}, {"ZIP", type number}, {"LAT", type number}, {"LON", type number}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"Id", "Id (organizations)"}, {"NAME", "Name"}, {"ADDRESS", "ADDRESS (organizations)"}, {"CITY", "CITY (organizations)"}, {"STATE", "STATE (organizations)"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}})
            in
                #"Renamed Columns"
