table 'patients'
    lineageTag: d84c0c1d-ea45-47be-874d-6cfdec932820

    column 'Id (patients)'
        dataType: string
        lineageTag: 010406e8-9799-43f7-a381-f81a7fd2aa46
        summarizeBy: none
        sourceColumn: Id (patients)

    column 'Birthdate'
        sourceColumn: Birthdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: db2bf62d-7939-464d-a790-99e28e59172f
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 82b8654e-99cd-4495-a57b-0b3fb25516d9
            defaultHierarchy: LocalDateTable_bed2e2b8-bf66-4e45-a1fd-b5bc50cf74c7.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Deathdate'
        sourceColumn: Deathdate
        dataType: dateTime
        formatString: Long Date
        lineageTag: 39544ef6-6dc5-4955-9b4d-0f2b7d48398d
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 608e7538-e0b8-45de-bce7-01d27eee397c
            defaultHierarchy: LocalDateTable_07c6e0cd-9b3b-4380-9222-8d5bace257b3.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Prefix'
        dataType: string
        lineageTag: 6fef2b82-5494-4829-8bb2-a9896291065f
        summarizeBy: none
        sourceColumn: Prefix

    column 'First'
        dataType: string
        lineageTag: 058ba628-d806-4555-9b2b-c2360d87c241
        summarizeBy: none
        sourceColumn: First

    column 'Last'
        dataType: string
        lineageTag: d235c2d7-6faf-4f86-ac95-eea447205b0a
        summarizeBy: none
        sourceColumn: Last

    column 'Suffix'
        dataType: string
        lineageTag: b679e2be-5fcb-4ab8-8c5c-8e740e268b33
        summarizeBy: none
        sourceColumn: Suffix

    column 'Maiden'
        dataType: string
        lineageTag: a41f184f-a40c-4116-9f39-fb598c852406
        summarizeBy: none
        sourceColumn: Maiden

    column 'Marital'
        dataType: string
        lineageTag: 645001e9-bd8f-46df-91d7-822f355c20df
        summarizeBy: none
        sourceColumn: Marital

    column 'Race'
        dataType: string
        lineageTag: 75b47e47-831b-44a0-8366-60a032cf8745
        summarizeBy: none
        sourceColumn: Race

    column 'Ethnicity'
        dataType: string
        lineageTag: 34a7c423-3664-4aa3-a330-f740b576fa82
        summarizeBy: none
        sourceColumn: Ethnicity

    column 'Gender'
        dataType: string
        lineageTag: 82ecc472-5d12-4ea3-83d9-a02692c99473
        summarizeBy: none
        sourceColumn: Gender

    column 'Birthplace'
        dataType: string
        lineageTag: 5453bc5b-857e-46f9-a2b1-0cfd3c64f812
        summarizeBy: none
        sourceColumn: Birthplace

    column 'Address'
        dataType: string
        lineageTag: 88bed795-2752-4f36-8965-525981a40798
        summarizeBy: none
        sourceColumn: Address

    column 'City'
        dataType: string
        lineageTag: 521dbb51-f02a-4050-b169-be63af750b63
        summarizeBy: none
        sourceColumn: City

    column 'State'
        dataType: string
        lineageTag: d6f54574-627e-4aa5-9b68-365e2ab1d68c
        summarizeBy: none
        sourceColumn: State

    column 'County'
        dataType: string
        lineageTag: 16c5a6f3-e497-4f38-84f6-9576bfb8f83c
        summarizeBy: none
        sourceColumn: County

    column 'ZIP (organizations)'
        dataType: double
        lineageTag: 2601da67-515a-4431-aebb-6fb4f0455839
        summarizeBy: none
        sourceColumn: ZIP (organizations)

    column 'LAT (organizations)'
        dataType: double
        lineageTag: a20b723d-c110-452e-93b5-68aaf6de1d81
        summarizeBy: none
        sourceColumn: LAT (organizations)

    column 'LON (organizations)'
        dataType: double
        lineageTag: 396be46a-efeb-4a05-86ca-63168e26cfd1
        summarizeBy: none
        sourceColumn: LON (organizations)

    measure 'SUM of Avg Visits per Patient (patients)' =
        SUM('patients'[Avg Visits per Patient])


    measure 'SUM of Visits per Patient (patients)' =
        SUM('patients'[Visits per Patient])


    measure 'Total Patients (LOD)' =
        -- SKIPPED BY USER


    measure 'Visits per Patient' =
        -- SKIPPED BY USER


    measure 'Avg Visits per Patient' =
        -- SKIPPED BY USER


    partition 'patients' = m
        mode: import
        source =
            let
                Source = GoogleSheets.Contents("None"),
                #"Navigation 1" = Source{[name = "patients", ItemKind = "Table"]}[Data],
                #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
                #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"Id", type text}, {"BIRTHDATE", type date}, {"DEATHDATE", type date}, {"PREFIX", type text}, {"FIRST", type text}, {"LAST", type text}, {"SUFFIX", type text}, {"MAIDEN", type text}, {"MARITAL", type text}, {"RACE", type text}, {"ETHNICITY", type text}, {"GENDER", type text}, {"BIRTHPLACE", type text}, {"ADDRESS", type text}, {"CITY", type text}, {"STATE", type text}, {"COUNTY", type text}, {"ZIP", type number}, {"LAT", type number}, {"LON", type number}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"Id", "Id (patients)"}, {"BIRTHDATE", "Birthdate"}, {"DEATHDATE", "Deathdate"}, {"PREFIX", "Prefix"}, {"FIRST", "First"}, {"LAST", "Last"}, {"SUFFIX", "Suffix"}, {"MAIDEN", "Maiden"}, {"MARITAL", "Marital"}, {"RACE", "Race"}, {"ETHNICITY", "Ethnicity"}, {"GENDER", "Gender"}, {"BIRTHPLACE", "Birthplace"}, {"ADDRESS", "Address"}, {"CITY", "City"}, {"STATE", "State"}, {"COUNTY", "County"}, {"ZIP", "ZIP (organizations)"}, {"LAT", "LAT (organizations)"}, {"LON", "LON (organizations)"}})
            in
                #"Renamed Columns"
