table 'APPOINTMENTS'
    lineageTag: eda5bf17-81a7-4cda-a1f7-cfc69add6f1c

    column 'Appointment Id'
        dataType: string
        lineageTag: a7c2b824-890f-4595-98cd-7d9a9f269846
        summarizeBy: none
        sourceColumn: Appointment Id

    column 'Patient Id'
        dataType: string
        lineageTag: 88525ff4-8cdd-4074-885a-bc13e9a8cff3
        summarizeBy: none
        sourceColumn: Patient Id

    column 'Doctor Id'
        dataType: string
        lineageTag: 82230941-1539-48f1-b2bd-7109b5307375
        summarizeBy: none
        sourceColumn: Doctor Id

    column 'Department'
        dataType: string
        lineageTag: 6b34fa28-1f22-4891-af28-cd47f087cbcc
        summarizeBy: none
        sourceColumn: Department

    column 'Appointment Date'
        sourceColumn: Appointment Date
        dataType: dateTime
        formatString: Long Date
        lineageTag: f805caf2-84f4-4636-9809-961b6ed131a2
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 8f7bc753-aec6-4092-a42d-aca0cb4be551
            defaultHierarchy: LocalDateTable_3a15ab11-cddb-4db5-8e98-47ebef89f6a5.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Appointment Time'
        sourceColumn: Appointment Time
        dataType: dateTime
        formatString: General Date
        lineageTag: 5f3d6313-39da-4b8a-9348-da7f8e113f17
        summarizeBy: none

        variation Variation
            isDefault
            relationship: e57a0801-a81a-4279-be8e-9baf79d4961f
            defaultHierarchy: LocalDateTable_50d0303d-52c2-448e-aff9-3da8c77b498f.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Visit Status'
        dataType: string
        lineageTag: a7c397e3-4e3e-4439-affc-a86b23bd8438
        summarizeBy: none
        sourceColumn: Visit Status

    column 'Reason For Visit'
        dataType: string
        lineageTag: 55dae1a4-690d-41ce-a77d-4e6a04fb4a38
        summarizeBy: none
        sourceColumn: Reason For Visit

    column 'Diagnosis Code'
        dataType: string
        lineageTag: 16a556f2-cf22-4db7-bb9d-5d3fa8048499
        summarizeBy: none
        sourceColumn: Diagnosis Code

    column 'Follow Up Required'
        dataType: boolean
        lineageTag: 304462ac-496c-44b9-a60a-4faa8b9b8a53
        summarizeBy: none
        sourceColumn: Follow Up Required

    column 'DEPARTMENT__Custom_SQL_Query__Set_Category' = IF('APPOINTMENTS'[Department] IN { }, "In", "Out")
        dataType: string

        summarizeBy: none

    column 'Doctor_Id_Set_Category' = IF('APPOINTMENTS'[Doctor Id] IN { }, "In", "Out")
        dataType: string

        summarizeBy: none

    measure 'Before Migration Count' =
        COUNT('APPOINTMENTS'[Doctor Id])


    measure 'Patients' =
        DISTINCTCOUNT('APPOINTMENTS'[Patient Id])


    measure 'Total Appointments' =
        COUNT('APPOINTMENTS'[Appointment Id])


    measure 'Doctor Contribution %' =
        DIVIDE([Doctor Revenue (LOD)], [Department Revenue (LOD)], 0)


    measure 'SUM of Doctor Contribution %' =
        SUM('APPOINTMENTS'[Doctor Contribution %])


    measure 'CNT of Appointment Id' =
        COUNT('APPOINTMENTS'[Appointment Id])


    measure 'SUM of Appointments per Doctor (LOD' =
        SUM('APPOINTMENTS'[Appointments per Doctor (LOD])


    measure 'Appointments per Patient (fixed)' =
        CALCULATE(COUNT('APPOINTMENTS'[Appointment Id]), ALLEXCEPT('APPOINTMENTS', 'APPOINTMENTS'[Patient Id]))


    measure 'Avg Consultation Fee per Patient(Include)' =
        CALCULATE(AVERAGEX(VALUES('APPOINTMENTS'[Patient Id]), CALCULATE(AVERAGE('DOCTORS'[Consultation Fee]))))


    measure 'Appointments per Doctor (LOD' =
        CALCULATE(COUNTX(VALUES('APPOINTMENTS'[Doctor Id]), CALCULATE(COUNT('APPOINTMENTS'[Appointment Id]))))


    measure 'Avg Doctor Bill Count by Specialization (Nested LOD)' =
        CALCULATE(AVERAGEX(VALUES('APPOINTMENTS'[Doctor Id]), [Doctor Bill Count (LOD)]), ALLEXCEPT('DOCTORS', 'DOCTORS'[Specialization]))


    measure 'Doctor Revenue (LOD)' =
        CALCULATE(SUM([COLLECTED_REVENUE]), ALLEXCEPT('APPOINTMENTS', 'APPOINTMENTS'[Department], 'APPOINTMENTS'[Doctor Id]))


    partition 'APPOINTMENTS' = m
        mode: import
        source =
            let
                Source = Snowflake.Databases("mmcuiwz-kl31490.snowflakecomputing.com", "COMPUTE_WH"),
                DB = Source{[Name="CITY_HOSPITAL"]}[Data],
                Schema = DB{[Name="PUBLIC"]}[Data],
                Table = Schema{[Name="APPOINTMENTS"]}[Data],
                #"Changed Type" = Table.TransformColumnTypes(Table, {{"APPOINTMENT_ID", type text}, {"PATIENT_ID", type text}, {"DOCTOR_ID", type text}, {"DEPARTMENT", type text}, {"APPOINTMENT_DATE", type date}, {"APPOINTMENT_TIME", type datetime}, {"VISIT_STATUS", type text}, {"REASON_FOR_VISIT", type text}, {"DIAGNOSIS_CODE", type text}, {"FOLLOW_UP_REQUIRED", type logical}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"APPOINTMENT_ID", "Appointment Id"}, {"PATIENT_ID", "Patient Id"}, {"DOCTOR_ID", "Doctor Id"}, {"DEPARTMENT", "Department"}, {"APPOINTMENT_DATE", "Appointment Date"}, {"APPOINTMENT_TIME", "Appointment Time"}, {"VISIT_STATUS", "Visit Status"}, {"REASON_FOR_VISIT", "Reason For Visit"}, {"DIAGNOSIS_CODE", "Diagnosis Code"}, {"FOLLOW_UP_REQUIRED", "Follow Up Required"}})
            in
                #"Renamed Columns"
