table 'BILLS'
    lineageTag: 4c0f7203-58c3-444e-9742-07824dd46eb6

    column 'Bill Id'
        dataType: string
        lineageTag: 4bf73ad9-cc69-48db-bd2f-685ebebb946c
        summarizeBy: none
        sourceColumn: Bill Id

    column 'Patient Id (Bills)'
        dataType: string
        lineageTag: 16d3e92e-5991-49fc-ab69-a3fe3b9fbed5
        summarizeBy: none
        sourceColumn: Patient Id (Bills)

    column 'Appointment Id (Bills)'
        dataType: string
        lineageTag: 05811df3-b6f8-4a05-ab11-c33f837b3199
        summarizeBy: none
        sourceColumn: Appointment Id (Bills)

    column 'Treatment Id'
        dataType: string
        lineageTag: 5ac9a22e-0394-4909-a083-2d8d4cc35366
        summarizeBy: none
        sourceColumn: Treatment Id

    column 'Billing Date'
        sourceColumn: Billing Date
        dataType: dateTime
        formatString: Long Date
        lineageTag: 0233ddf4-2dce-456a-90cc-f71d94dc4d86
        summarizeBy: none

        variation Variation
            isDefault
            relationship: b508f5a9-6eb8-423f-900a-147ad7be39d4
            defaultHierarchy: LocalDateTable_19f65e48-e79d-4644-8ce0-c4166435c9cd.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'Total Amount'
        dataType: double
        lineageTag: f6923f5d-9a0f-430a-8c9a-d556ea8f157e
        summarizeBy: none
        sourceColumn: Total Amount

    column 'Insurance Covered'
        dataType: double
        lineageTag: 03d5e1d1-d430-47d9-9f0b-f8a17f840133
        summarizeBy: none
        sourceColumn: Insurance Covered

    column 'Patient Payable'
        dataType: double
        lineageTag: bc3d0590-363a-42bd-9ab5-f7b253ac5126
        summarizeBy: none
        sourceColumn: Patient Payable

    column 'Payment Method'
        dataType: string
        lineageTag: 2aedbecf-98b6-44b8-aff0-6211a1684b11
        summarizeBy: none
        sourceColumn: Payment Method

    column 'Payment Status'
        dataType: string
        lineageTag: 030b07dc-fc10-4431-9feb-cab9a0842f85
        summarizeBy: none
        sourceColumn: Payment Status

    measure 'Insurance Coverage %' =
        DIVIDE(SUM('BILLS'[Insurance Covered]), SUM('BILLS'[Total Amount]), 0)


    measure 'Total Bill' =
        COUNT('BILLS'[Bill Id])


    measure 'Total billing Amount' =
        SUM('BILLS'[Total Amount])


    measure 'Total Revenue' =
        SUM('BILLS'[Total Amount])


    measure 'Unpaid Balance' =
        SUM('BILLS'[Total Amount]) - SUM('BILLS'[Insurance Covered])


    measure 'COLLECTED_REVENUE' =
        CALCULATE(SUM('BILLS'[Total Amount]), KEEPFILTERS('BILLS'[Payment Status] & "" = "Paid"))


    measure 'SUM of Total Amount (BILLS)' =
        SUM('BILLS'[Total Amount])


    measure 'Unpaid Balance per Specialization (Fixed)' =
        CALCULATE(SUM('BILLS'[Total Amount]) - SUM('BILLS'[Insurance Covered]), ALLEXCEPT('DOCTORS', 'DOCTORS'[Specialization]))


    measure 'Doctor Bill Count (LOD)' =
        CALCULATE(COUNT('BILLS'[Bill Id]), REMOVEFILTERS('BILLS'), ALLEXCEPT('DOCTORS', 'DOCTORS'[Doctor Id (Doctors)]))


    partition 'BILLS' = m
        mode: import
        source =
            let
                Source = Snowflake.Databases("mmcuiwz-kl31490.snowflakecomputing.com", "COMPUTE_WH"),
                DB = Source{[Name="CITY_HOSPITAL"]}[Data],
                Schema = DB{[Name="PUBLIC"]}[Data],
                Table = Schema{[Name="BILLS"]}[Data],
                #"Changed Type" = Table.TransformColumnTypes(Table, {{"BILL_ID", type text}, {"PATIENT_ID", type text}, {"APPOINTMENT_ID", type text}, {"TREATMENT_ID", type text}, {"BILLING_DATE", type date}, {"TOTAL_AMOUNT", type number}, {"INSURANCE_COVERED", type number}, {"PATIENT_PAYABLE", type number}, {"PAYMENT_METHOD", type text}, {"PAYMENT_STATUS", type text}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"BILL_ID", "Bill Id"}, {"PATIENT_ID", "Patient Id (Bills)"}, {"APPOINTMENT_ID", "Appointment Id (Bills)"}, {"TREATMENT_ID", "Treatment Id"}, {"BILLING_DATE", "Billing Date"}, {"TOTAL_AMOUNT", "Total Amount"}, {"INSURANCE_COVERED", "Insurance Covered"}, {"PATIENT_PAYABLE", "Patient Payable"}, {"PAYMENT_METHOD", "Payment Method"}, {"PAYMENT_STATUS", "Payment Status"}})
            in
                #"Renamed Columns"
