table 'custom table'
    lineageTag: e0bcf013-2f1e-4b7e-87a9-c5972663519c

    column 'APPOINTMENT_ID (Custom SQL Query)'
        dataType: string
        lineageTag: 7b41215b-3110-4aff-9988-f745456c03be
        summarizeBy: none
        sourceColumn: APPOINTMENT_ID (Custom SQL Query)

    column 'PATIENT_ID (Custom SQL Query)'
        dataType: string
        lineageTag: e06634f7-47db-4174-b709-f184977942b8
        summarizeBy: none
        sourceColumn: PATIENT_ID (Custom SQL Query)

    column 'DOCTOR_ID (Custom SQL Query)'
        dataType: string
        lineageTag: 085ae508-ec10-4e17-b187-2fc11aa9b836
        summarizeBy: none
        sourceColumn: DOCTOR_ID (Custom SQL Query)

    column 'DEPARTMENT (Custom SQL Query)'
        dataType: string
        lineageTag: e2bac1f2-406f-4ab8-8911-0d007ee2f16e
        summarizeBy: none
        sourceColumn: DEPARTMENT (Custom SQL Query)

    column 'APPOINTMENT_DATE (Custom SQL Query)'
        sourceColumn: APPOINTMENT_DATE (Custom SQL Query)
        dataType: dateTime
        formatString: Long Date
        lineageTag: 65aba703-16db-463a-9a1c-b1ef0eb0acc3
        summarizeBy: none

        variation Variation
            isDefault
            relationship: b96038a5-f4ce-4c77-938a-9d6397ec6c55
            defaultHierarchy: LocalDateTable_3457959d-89da-46c6-a0fb-f7afda26b8d1.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'APPOINTMENT_TIME (Custom SQL Query)'
        sourceColumn: APPOINTMENT_TIME (Custom SQL Query)
        dataType: dateTime
        formatString: General Date
        lineageTag: cf3109ec-7279-4620-8467-6f4c6e8a8d1d
        summarizeBy: none

        variation Variation
            isDefault
            relationship: 3b169057-389d-4bf7-8e57-73f2204bd59f
            defaultHierarchy: LocalDateTable_937abd76-28c0-4e74-90a4-40e059ffaa0a.'Date Hierarchy'

        changedProperty = DataType

        annotation UnderlyingDateTimeDataType = Date

    column 'VISIT_STATUS_CLEAN'
        dataType: string
        lineageTag: 7ff7e1b9-aa28-4e97-ac08-dda5c8f20ba8
        summarizeBy: none
        sourceColumn: VISIT_STATUS_CLEAN

    column 'REASON_FOR_VISIT (Custom SQL Query)'
        dataType: string
        lineageTag: 3ffb3e12-ba45-4e9a-a97b-47fdc823c2c9
        summarizeBy: none
        sourceColumn: REASON_FOR_VISIT (Custom SQL Query)

    column 'DIAGNOSIS_CODE (Custom SQL Query)'
        dataType: string
        lineageTag: c46906e5-78a2-449c-82f2-05b15d950b77
        summarizeBy: none
        sourceColumn: DIAGNOSIS_CODE (Custom SQL Query)

    column 'FOLLOW_UP_REQUIRED (Custom SQL Query)'
        dataType: boolean
        lineageTag: 2695b538-e899-411b-b746-e07e571db61a
        summarizeBy: none
        sourceColumn: FOLLOW_UP_REQUIRED (Custom SQL Query)

    column 'SPECIALIZATION (Custom SQL Query)'
        dataType: string
        lineageTag: 590266c7-e549-46b9-a59f-fdfbfc1e25a6
        summarizeBy: none
        sourceColumn: SPECIALIZATION (Custom SQL Query)

    column 'CONSULTATION_FEE (Custom SQL Query)'
        dataType: double
        lineageTag: c023705b-043d-425c-821f-23a3cf0ea0eb
        summarizeBy: none
        sourceColumn: CONSULTATION_FEE (Custom SQL Query)

    column 'TREATMENT_TYPE (Custom SQL Query)'
        dataType: string
        lineageTag: 2c9af6b7-fbeb-4279-b46c-b1c1a470dd3b
        summarizeBy: none
        sourceColumn: TREATMENT_TYPE (Custom SQL Query)

    column 'OUTCOME_STATUS (Custom SQL Query)'
        dataType: string
        lineageTag: 354bcbd9-6fe0-40bc-bb68-4a6361a90332
        summarizeBy: none
        sourceColumn: OUTCOME_STATUS (Custom SQL Query)

    column 'TREATMENT_COST (Custom SQL Query)'
        dataType: double
        lineageTag: 71c7b275-e527-4ba9-9dce-69e22c84f876
        summarizeBy: none
        sourceColumn: TREATMENT_COST (Custom SQL Query)

    column 'TOTAL_AMOUNT (Custom SQL Query)'
        dataType: double
        lineageTag: e5d82d1e-1d42-46c7-b004-c16744fcf6fd
        summarizeBy: none
        sourceColumn: TOTAL_AMOUNT (Custom SQL Query)

    column 'PAYMENT_STATUS (Custom SQL Query)'
        dataType: string
        lineageTag: e0c30324-99f9-4c10-8dcd-c8e85fba08ee
        summarizeBy: none
        sourceColumn: PAYMENT_STATUS (Custom SQL Query)

    column 'COLLECTED_REVENUE'
        dataType: double
        lineageTag: c0588330-5fe1-43da-90be-ed310564cad0
        summarizeBy: none
        sourceColumn: COLLECTED_REVENUE

    measure 'Revenue Filter' =
        SUMX('custom table', [COLLECTED_REVENUE]) >= SELECTEDVALUE('Revenue Threshold'[Value])


    measure 'SUM of COLLECTED_REVENUE (custom table)' =
        SUM('custom table'[COLLECTED_REVENUE])


    measure 'SUM of Completed Appointments per Department (custom table)' =
        SUM('custom table'[Completed Appointments per Department])


    measure 'Department Total Revenue (LOD)' =
        CALCULATE(SUM([COLLECTED_REVENUE]), ALLEXCEPT('custom table', 'custom table'[DEPARTMENT (Custom SQL Query)]))


    measure 'Completed Appointments per Department' =
        CALCULATE(SUMX('custom table', IF('custom table'[VISIT_STATUS_CLEAN] & "" = "Completed", 1, 0)), ALLEXCEPT('custom table', 'custom table'[DEPARTMENT (Custom SQL Query)]))


    measure 'Department Revenue (LOD)' =
        CALCULATE(SUM([COLLECTED_REVENUE]), ALLEXCEPT('custom table', 'custom table'[DEPARTMENT (Custom SQL Query)]))


    partition 'custom table' = m
        mode: import
        source =
            let Source = Snowflake.Databases("mmcuiwz-kl31490.snowflakecomputing.com", "COMPUTE_WH"),
            DB = Source{[Name="CITY_HOSPITAL"]}[Data],
            custom_table = Value.NativeQuery(DB, "SELECT a.APPOINTMENT_ID, a.PATIENT_ID, a.DOCTOR_ID, a.DEPARTMENT, a.APPOINTMENT_DATE, a.APPOINTMENT_TIME, CASE WHEN a.VISIT_STATUS IN ('No-Show', 'No Show') THEN 'No Show' WHEN a.VISIT_STATUS IN ('Cancelled', 'Canceled') THEN 'Cancelled' WHEN a.VISIT_STATUS = 'Completed' THEN 'Completed' ELSE 'Other' END AS VISIT_STATUS_CLEAN, a.REASON_FOR_VISIT, a.DIAGNOSIS_CODE, a.FOLLOW_UP_REQUIRED, d.SPECIALIZATION, d.CONSULTATION_FEE, t.TREATMENT_TYPE, t.OUTCOME_STATUS, t.TREATMENT_COST, b.TOTAL_AMOUNT, b.PAYMENT_STATUS, CASE WHEN b.PAYMENT_STATUS = 'Paid' THEN b.TOTAL_AMOUNT ELSE 0 END AS COLLECTED_REVENUE FROM SNOWFLAKE_LEARNING_DB.RAJANMORYA_LOAD_SAMPLE_DATA_FROM_S3.APPOINTMENTS a LEFT JOIN SNOWFLAKE_LEARNING_DB.RAJANMORYA_LOAD_SAMPLE_DATA_FROM_S3.DOCTORS d ON a.DOCTOR_ID = d.DOCTOR_ID LEFT JOIN SNOWFLAKE_LEARNING_DB.RAJANMORYA_LOAD_SAMPLE_DATA_FROM_S3.TREATMENTS t ON a.APPOINTMENT_ID = t.APPOINTMENT_ID LEFT JOIN SNOWFLAKE_LEARNING_DB.RAJANMORYA_LOAD_SAMPLE_DATA_FROM_S3.BILLS b ON a.APPOINTMENT_ID = b.APPOINTMENT_ID"),
                            #"Renamed Columns" = Table.RenameColumns(custom_table, {{"APPOINTMENT_ID", "APPOINTMENT_ID (Custom SQL Query)"}, {"PATIENT_ID", "PATIENT_ID (Custom SQL Query)"}, {"DOCTOR_ID", "DOCTOR_ID (Custom SQL Query)"}, {"DEPARTMENT", "DEPARTMENT (Custom SQL Query)"}, {"APPOINTMENT_DATE", "APPOINTMENT_DATE (Custom SQL Query)"}, {"APPOINTMENT_TIME", "APPOINTMENT_TIME (Custom SQL Query)"}, {"REASON_FOR_VISIT", "REASON_FOR_VISIT (Custom SQL Query)"}, {"DIAGNOSIS_CODE", "DIAGNOSIS_CODE (Custom SQL Query)"}, {"FOLLOW_UP_REQUIRED", "FOLLOW_UP_REQUIRED (Custom SQL Query)"}, {"SPECIALIZATION", "SPECIALIZATION (Custom SQL Query)"}, {"CONSULTATION_FEE", "CONSULTATION_FEE (Custom SQL Query)"}, {"TREATMENT_TYPE", "TREATMENT_TYPE (Custom SQL Query)"}, {"OUTCOME_STATUS", "OUTCOME_STATUS (Custom SQL Query)"}, {"TREATMENT_COST", "TREATMENT_COST (Custom SQL Query)"}, {"TOTAL_AMOUNT", "TOTAL_AMOUNT (Custom SQL Query)"}, {"PAYMENT_STATUS", "PAYMENT_STATUS (Custom SQL Query)"}})
                        in
                            #"Renamed Columns"
