table 'DOCTORS'
    lineageTag: f299b2b6-c37c-4776-96b6-b7bf00797756

    column 'Doctor Id (Doctors)'
        dataType: string
        lineageTag: 26811524-eda6-49d0-8cdf-b698c8e71861
        summarizeBy: none
        sourceColumn: Doctor Id (Doctors)

    column 'Full Name'
        dataType: string
        lineageTag: f44e9a48-0caf-4433-8f3c-951a097d9c35
        summarizeBy: none
        sourceColumn: Full Name

    column 'Specialization'
        dataType: string
        lineageTag: 8078ff28-0495-425d-b6a1-bedd43f89863
        summarizeBy: none
        sourceColumn: Specialization

    column 'Department (Doctors)'
        dataType: string
        lineageTag: 8bad36ae-e227-4564-b52a-48c492d4f76e
        summarizeBy: none
        sourceColumn: Department (Doctors)

    column 'Contact Number'
        dataType: string
        lineageTag: 695d448b-b4d1-4a54-95a1-3c2a4fb1f3a0
        summarizeBy: none
        sourceColumn: Contact Number

    column 'Email Address'
        dataType: string
        lineageTag: f89dbae2-164e-4665-b483-c518e7ccc69e
        summarizeBy: none
        sourceColumn: Email Address

    column 'Availability Days'
        dataType: string
        lineageTag: 60f3dda5-d530-491c-ac7b-c87b0c2250e2
        summarizeBy: none
        sourceColumn: Availability Days

    column 'Consultation Fee'
        dataType: double
        lineageTag: 65d249e5-955e-42a4-a161-3c888bee5287
        summarizeBy: none
        sourceColumn: Consultation Fee

    column 'Experience Years'
        dataType: double
        lineageTag: 855024e6-5d16-4fba-a439-c3ccf048efde
        summarizeBy: none
        sourceColumn: Experience Years

    column 'Registration Number'
        dataType: string
        lineageTag: 4b018c6a-a6a4-43ba-875f-240cd0e7292d
        summarizeBy: none
        sourceColumn: Registration Number

    column 'Experience Level_Cal' = SWITCH( TRUE(), 'DOCTORS'[Experience Years] < 5, "Junior", 'DOCTORS'[Experience Years] <= 10, "Mid-Level", "Senior" )
        dataType: string

        summarizeBy: none

    measure 'Average Consultation Fee' =
        AVERAGE('DOCTORS'[Consultation Fee])


    measure 'Average Doctor Experience (Years)1' =
        AVERAGE('DOCTORS'[Experience Years])


    measure 'Average by Specialization (NESTED)' =
        AVERAGEX(
            VALUES('DOCTORS'[Specialization]),
            AVERAGEX(
                VALUES('BILLS'[Appointment Id (Bills)]),
                CALCULATE(
                    SUM('BILLS'[Total Amount]) - SUM('BILLS'[Insurance Covered])
                )
            )
        )


    measure 'Doctor RLS Filter' =
        SELECTEDVALUE('DOCTORS'[Email Address]) = USERNAME()


    partition 'DOCTORS' = m
        mode: import
        source =
            let
                Source = Snowflake.Databases("mmcuiwz-kl31490.snowflakecomputing.com", "COMPUTE_WH"),
                DB = Source{[Name="CITY_HOSPITAL"]}[Data],
                Schema = DB{[Name="PUBLIC"]}[Data],
                Table = Schema{[Name="DOCTORS"]}[Data],
                #"Changed Type" = Table.TransformColumnTypes(Table, {{"DOCTOR_ID", type text}, {"FULL_NAME", type text}, {"SPECIALIZATION", type text}, {"DEPARTMENT", type text}, {"CONTACT_NUMBER", type text}, {"EMAIL_ADDRESS", type text}, {"AVAILABILITY_DAYS", type text}, {"CONSULTATION_FEE", type number}, {"EXPERIENCE_YEARS", type number}, {"REGISTRATION_NUMBER", type text}}),
                #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {{"DOCTOR_ID", "Doctor Id (Doctors)"}, {"FULL_NAME", "Full Name"}, {"SPECIALIZATION", "Specialization"}, {"DEPARTMENT", "Department (Doctors)"}, {"CONTACT_NUMBER", "Contact Number"}, {"EMAIL_ADDRESS", "Email Address"}, {"AVAILABILITY_DAYS", "Availability Days"}, {"CONSULTATION_FEE", "Consultation Fee"}, {"EXPERIENCE_YEARS", "Experience Years"}, {"REGISTRATION_NUMBER", "Registration Number"}})
            in
                #"Renamed Columns"
