table COURSE_INSTRUCTORS
	lineageTag: 041af670-a044-52d1-aa5e-3a7c03d2a5e5

	measure 'Assignment Duration' = AVERAGE(Today() - 'COURSE_INSTRUCTORS'[ASSIGNED_DATE])
		formatString: "#,##0.00"
		lineageTag: 22a4b98e-6311-5d9e-9001-8ee5cb903705

	/// TODO (Qlik $() dollar expansion has no direct DAX equivalent): Convert the Qlik expression to DAX manually.
	/// Original Qlik: VAR __CalcVar_1 = AddMonths(MonthStart($(vMaxLoaded)),-11) VAR __CalcVar_2 = MonthEnd($(vMaxLoaded)) RETURN CALCULATE(COUNTROWS('COURSES'), [Date] >= __CalcVar_1<=__CalcVar_2, CALCULATE(Date='COURSE_INSTRUCTORS'[ASSIGNED_DATE]))
	measure 'Rolling 12-month assignments' = BLANK()
		formatString: "#,##0.00"
		lineageTag: 088d1460-22c9-5ca7-94d3-dffceeafe409

	column COURSE_ID
		dataType: string
		lineageTag: 134eb7c3-a7c4-55ce-9612-c8ba2e0196e2
		summarizeBy: none
		sourceColumn: COURSE_ID

		annotation SummarizationSetBy = Automatic

	column INSTRUCTOR_ID
		dataType: string
		lineageTag: 52c3a779-396a-585e-acad-f852d49465a3
		summarizeBy: none
		sourceColumn: INSTRUCTOR_ID

		annotation SummarizationSetBy = Automatic

	column ASSIGNED_DATE
		dataType: dateTime
		lineageTag: f23691ee-c9a4-5c26-bea2-8c1fbf3a0e98
		summarizeBy: none
		sourceColumn: ASSIGNED_DATE
		formatString: M/D/YYYY

		annotation SummarizationSetBy = Automatic

	partition COURSE_INSTRUCTORS = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("gq37595.ap-southeast-7.aws.snowflakecomputing.com", "COMPUTE_WH"),
				    Db = Source{[Name="LEARNING_ANALYTICS",Kind="Database"]}[Data],
				    Result = Value.NativeQuery(Db, "SELECT ""COURSE_ID"", ""INSTRUCTOR_ID"", ""ASSIGNED_DATE"" FROM ""LEARNING_ANALYTICS"".""PUBLIC"".""COURSE_INSTRUCTORS""", null, [EnableFolding=false]),
				    #"Changed Type" = Table.TransformColumnTypes(Result, {{"COURSE_ID", type text}, {"INSTRUCTOR_ID", type text}, {"ASSIGNED_DATE", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table